### ISSUE TITLE
[BUG]: error: static assertion failed with "Type is not compatible with device shuffle" while compiling dropout_kernels

### ISSUE THREAD

**Issue by chaoji90** [hpcaitech/ColossalAI#1002]
### 🐛 Describe the bug

I ran "pip install ." and got an error while compling dropout_kernels.cu

`/usr/local/cuda/bin/nvcc -I/home/zhang90/project/nas/ColossalAI/colossalai/kernel/cuda_native/csrc/kernels/include -I/home/zhang90/virdir/torch11/lib/python3.9/site-packages/torch/include -I/home/zhang90/virdir/torch11/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/home/zhang90/virdir/torch11/lib/python3.9/site-packages/torch/include/TH -I/home/zhang90/virdir/torch11/lib/python3.9/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/zhang90/virdir/torch11/include -I/usr/local/python39/include/python3.9 -c colossalai/kernel/cuda_native/csrc/kernels/dropout_kernels.cu -o build/temp.linux-x86_64-3.9/colossalai/kernel/cuda_native/csrc/kernels/dropout_kernels.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -O3 --use_fast_math -DVERSION_GE_1_1 -DVERSION_GE_1_3 -DVERSION_GE_1_5 -std=c++14 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -DTHRUST_IGNORE_CUB_VERSION_CHECK -gencode arch=compute_60,code=sm_60 -gencode arch=compute_70,code=sm_70 -gencode arch=compute_75,code=sm_75 -gencode arch=compute_80,code=sm_80 -gencode arch=compute_86,code=sm_86 --threads 4 -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE="_gcc" -DPYBIND11_STDLIB="_libstdcpp" -DPYBIND11_BUILD_ABI="_cxxabi1011" -DTORCH_EXTENSION_NAME=colossal_multihead_attention -D_GLIBCXX_USE_CXX11_ABI=0`
             
      /usr/local/cuda/include/cooperative_groups/details/helpers.h(272): error: static assertion failed with "Type is not compatible with device shuffle"
                detected during:
                  instantiation of "TyElem cooperative_groups::__v1::details::tile::_intrinsic_compat_shuffle::_shfl_internal(TyElem, const TyShflFn &) [with TyElem=__half2, TyShflFn=lambda [](int)->int]"
      (295): here
                  instantiation of "TyRet cooperative_groups::__v1::details::tile::_intrinsic_compat_shuffle::shfl_down(TyElem &&, unsigned int, unsigned int, unsigned int) [with TyElem=__half2 &, TyRet=__half2]"
      /usr/local/cuda/include/cooperative_groups.h(1040): here
                  instantiation of "TyRet cooperative_groups::__v1::__static_size_thread_block_tile_base<Size>::shfl_down(TyElem &&, unsigned int) const [with Size=32U, TyElem=__half2 &, TyRet=__half2]"
      colossalai/kernel/cuda_native/csrc/kernels/dropout_kernels.cu(616): here

      1 error detected in the compilation of "colossalai/kernel/cuda_native/csrc/kernels/dropout_kernels.cu".
      error: command '/usr/local/cuda/bin/nvcc' failed with exit code 255

### Environment

cuda 11.6
cuDNN 8.3.3.40
python 3.9
pytroch 1.11.0

**Comment by chaoji90** [comment]
Is there anything I can do? Or need to test another version?

**Comment by FrankLeeeee** [comment]
> Is there anything I can do? Or need to test another version?

Hi, this has been fixed in the latest main branch.
