### ISSUE TITLE
[DOC]: Wrong information - AlexNet 2012

### ISSUE THREAD

**Issue by INF800** [hpcaitech/ColossalAI#1013]
### 📚 The doc issue

> Back in 2012, [AlexNet](https://arxiv.org/abs/1404.5997) won the champion of the ImageNet competition, and it was trained on **a single** GPU.

Two GTX 580 GPUs with 3GB.

Ref: https://www.colossalai.org/docs/concepts/distributed_training

**Comment by binmakeswell** [comment]
Hi @INF800  Thank you for pointing it out, we will fix it as soon as possible 🔥

**Comment by binmakeswell** [comment]
Fixed and will be updated to the website soon : )
