### ISSUE TITLE
[BUG]: Use Docker, import colossalai error

### ISSUE THREAD

**Issue by DarrenYing** [hpcaitech/ColossalAI#1014]
### 🐛 Describe the bug

I follow the instructions for Use Docker
```
git clone https://github.com/hpcaitech/ColossalAI.git
cd ColossalAI
docker build -t colossalai ./docker
docker run -ti --gpus all --rm --ipc=host colossalai bash
```
Then in the container, I execute 
```
colossalai check -i
```
Then I get this:
```
Colossalai should be built with cuda extension to use the FP16 optimizer
If you want to activate cuda mode for MoE, please install with cuda_ext!
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.8/site-packages/colossalai/__init__.py", line 1, in <module>
    from .initialize import (initialize, launch, launch_from_openmpi,
  File "/opt/conda/lib/python3.8/site-packages/colossalai/initialize.py", line 23, in <module>
    from colossalai.engine.schedule import NonPipelineSchedule, PipelineSchedule, InterleavedPipelineSchedule, get_tensor_shape
  File "/opt/conda/lib/python3.8/site-packages/colossalai/engine/__init__.py", line 1, in <module>
    from ._base_engine import Engine
  File "/opt/conda/lib/python3.8/site-packages/colossalai/engine/_base_engine.py", line 11, in <module>
    from colossalai.engine.schedule import BaseSchedule, NonPipelineSchedule, PipelineSchedule, InterleavedPipelineSchedule
  File "/opt/conda/lib/python3.8/site-packages/colossalai/engine/schedule/__init__.py", line 1, in <module>
    from ._base_schedule import BaseSchedule
  File "/opt/conda/lib/python3.8/site-packages/colossalai/engine/schedule/_base_schedule.py", line 10, in <module>
    from colossalai.utils import get_current_device
  File "/opt/conda/lib/python3.8/site-packages/colossalai/utils/__init__.py", line 15, in <module>
    from .model.colo_init_context import ColoInitContext
  File "/opt/conda/lib/python3.8/site-packages/colossalai/utils/model/colo_init_context.py", line 3, in <module>
    from colossalai.tensor import ColoTensor, ColoParameter
  File "/opt/conda/lib/python3.8/site-packages/colossalai/tensor/__init__.py", line 4, in <module>
    from .colo_tensor import ColoTensor
  File "/opt/conda/lib/python3.8/site-packages/colossalai/tensor/colo_tensor.py", line 9, in <module>
    from torch.overrides import get_default_nowrap_functions
ImportError: cannot import name 'get_default_nowrap_functions' from 'torch.overrides' (/opt/conda/lib/python3.8/site-packages/torch/overrides.py)
```
commands like 
```
import torch
print(torch.cuda.is_available())  //true
```
or ```nvidia smi``` is all right.

Do I miss some step?

**Comment by FrankLeeeee** [comment]
Hi Darren, thanks for spotting this problem. I will do some investigation. For now, I will build a docker image for you and put in Dockerhub so that you can pull. Will notify you when ready.

**Comment by FrankLeeeee** [comment]
Hi, I have uploaded a docker image with the latest main branch, you can check this out by 

```shell
docker pull hpcaitech/colossalai:nightly-cuda11.3-torch1.10
```

**Comment by DarrenYing** [comment]
> Hi, I have uploaded a docker image with the latest main branch, you can check this out by
> 
> ```shell
> docker pull hpcaitech/colossalai:nightly-cuda11.3-torch1.10
> ```

Thank you so much, I will try the docker image.

**Comment by FrankLeeeee** [comment]
Things are fine in this image, I will close this issue for now. Do let me know if you encounter further issues.
<img width="450" alt="Screenshot 2022-05-24 at 2 42 33 PM" src="https://user-images.githubusercontent.com/31818963/169965518-fe26ddf3-da7b-4103-901e-094f71046489.png">

**Comment by DarrenYing** [comment]
Thanks, I just finished pulling the image and things are fine in the container. Thanks again.

**Comment by MEllis-github** [comment]
@FrankLeeeee I see the Dockerfile now bases from an [hpcaitech image](https://github.com/hpcaitech/ColossalAI/blob/007ca0df925350c70ee8ff324599f8e156cec59a/docker/Dockerfile#L1) rather than an NVIDIA PyTorch image as previously done. Can you share the changes that were necessary to base from an NVIDIA Pytorch image e.g. specific version dependencies?

**Comment by FrankLeeeee** [comment]
> @FrankLeeeee I see the Dockerfile now bases from an [hpcaitech image](https://github.com/hpcaitech/ColossalAI/blob/007ca0df925350c70ee8ff324599f8e156cec59a/docker/Dockerfile#L1) rather than an NVIDIA PyTorch image as previously done. Can you share the changes that were necessary to base from an NVIDIA Pytorch image e.g. specific version dependencies?

Hi @MEllis-github , sorry for missing your question. We notice that the torch in the NGC containers sometimes do not have the same API as the official release thus we built our own onws. The hpcaitech image is built from CUDA image and installed pytorch from the official release. You can just change the base image if you wish to switch to NGC docker.
