### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Luciferbobo** [hpcaitech/ColossalAI#102]
Hi. I met an error when I tried to import colossalai. Seems it tries to import from its own layers but cannot: Is this means I need to change my encoding format? 

> Traceback (most recent call last):
>   File "main.py", line 8, in <module>
>     import colossalai
>   File "/usr/local/lib/python3.6/site-packages/colossalai/__init__.py", line 1, in <module>
>     from .initialize import (initialize, launch, launch_from_openmpi,
>   File "/usr/local/lib/python3.6/site-packages/colossalai/initialize.py", line 7, in <module>
>     from colossalai.nn.optimizer.colossalai_optimizer import ColossalaiOptimizer
>   File "/usr/local/lib/python3.6/site-packages/colossalai/nn/__init__.py", line 1, in <module>
>     from .layer import *
>   File "/usr/local/lib/python3.6/site-packages/colossalai/nn/layer/__init__.py", line 1, in <module>
>     from .colossalai_layer import *
>   File "/usr/local/lib/python3.6/site-packages/colossalai/nn/layer/colossalai_layer/__init__.py", line 2, in <module>
>     from .dropout import Dropout
>   File "/usr/local/lib/python3.6/site-packages/colossalai/nn/layer/colossalai_layer/dropout.py", line 1, in <module>
>     from contextlib import nullcontext
> ImportError: cannot import name 'nullcontext'

 - CUDA version: 11.0
 - Python version: 3.6.8
 - PyTorch version: 1.10.0

**Comment by FrankLeeeee** [comment]
Hi @Luciferbobo , I think this bug is due to python version being old. I suggest you to create a conda environment with python 3.8 and try it again. nullcontext seems to only support python 3.8 and above and we did not consider this version mismatch issue. We will remove this nullcontext dependency in the next pull request. Thanks for finding this!

**Comment by Luciferbobo** [comment]
Thanks! Error fixed :)
