### ISSUE TITLE
[FEATURE] how can I quickly test a huggingface transformer model

### ISSUE THREAD

**Issue by feifeibear** [hpcaitech/ColossalAI#103]
**Is your feature request related to a problem? Please describe.**
I'm frustrated when I try to apply this project on a huggingface transformer model, i.e. a bert model.

**Describe the solution you'd like**
I can not find a clear doc to direct me to port a huggingface model into the colossal-ai. Apparently, all of the examples are related to visual models, but most of the large model applications are on NLP scenarios. 

**Describe alternatives you've considered**
Provide an example to tell me how to simply move my training process to colossal-ai.

**Comment by binmakeswell** [comment]
Hi, feifeibear,

Thank you for your comments.
We are working NLP scenarios, such as BERT, GPT2, GPT3, and these examples and detailed documents will be updated very soon.

Sincerely,
Bin
