### ISSUE TITLE
[DOC]: Colab Tutorial Request

### ISSUE THREAD

**Issue by yuxuan-lou** [hpcaitech/ColossalAI#1039]
### 📚 The doc issue

Hi Colossal-AI developers,

Thank you for your amazing work! Would you consider creating a Colab tutorial page? I think it can allow users to experiment with Colossal-AI features easily.

**Comment by binmakeswell** [comment]
We have updated a lot. Colab is not suitable for large-scale parallelism.
This issue was closed due to inactivity. Thanks.
