### ISSUE TITLE
[BUG]: ZeRO not Working with SGD Optimizer

### ISSUE THREAD

**Issue by FrankLeeeee** [hpcaitech/ColossalAI#1057]
### 🐛 Describe the bug

ZeRO will keep throwing overflow if used together with momentum SGD in the [resnet example](https://github.com/hpcaitech/ColossalAI-Examples/tree/main/image/resnet). The code works fine with all kinds of amp.
<img width="1044" alt="Screenshot 2022-06-02 at 4 23 26 PM" src="https://user-images.githubusercontent.com/31818963/171587444-64b512b7-9e65-4bc7-89bc-a296acfbeb52.png">

**Comment by feifeibear** [comment]
ZeRO is used in the context of ADAM or 2nd order optimizer. Generally, a DNN using SGD does not have memory shortage issues. We can through an error if the user uses SGD for ZeRO.

**Comment by FrankLeeeee** [comment]
It is understood that ZeRO is not needed for SGD from the memory perspective, but this overflow might suggest a bug in the current implementation.

**Comment by feifeibear** [comment]
I see. We will check it later.

**Comment by binmakeswell** [comment]
We have updated a lot. This issue was closed due to inactivity. Thanks.
