### ISSUE TITLE
[FEATURE] How to prepare WebtextDataset?

### ISSUE THREAD

**Issue by feifeibear** [hpcaitech/ColossalAI#106]
**Is your feature request related to a problem? Please describe.**
I tried to run the gpt2 example. It uses the WebtextDataset. Is there any instruction on the data preparation?

**Comment by binmakeswell** [comment]
Hi, feifeibear,

Thank you for your comments.
Actually, the benchmark folder is used for internal testing, and we provide the example folder for users.
We will provide more details about gpt2 example and this dataset in a recent update.

Sincerely,
Bin

**Comment by kurisusnowdeng** [comment]
Hi. Sorry for missing this step. You can follow the steps described at [Megatron-LM/tools/openwebtext](https://github.com/NVIDIA/Megatron-LM/tree/main/tools/openwebtext) to prepare the dataset. We will also add an instruction for stable use in a later update.

**Comment by FrankLeeeee** [comment]
I have asked the intern to add steps to prepare webtext dataset in his GPT example PR in [#3](https://github.com/hpcaitech/ColossalAI-Examples/pull/3) and [#4](https://github.com/hpcaitech/ColossalAI-Examples/pull/4)

**Comment by FrankLeeeee** [comment]
We have provided a detail instruction to prepare webtext dataset. You can find it here.
https://github.com/hpcaitech/ColossalAI-Examples/tree/main/language/gpt_2
