### ISSUE TITLE
[BUG] The project is not compatible with torch v1.8.1

### ISSUE THREAD

**Issue by feifeibear** [hpcaitech/ColossalAI#107]
The PyTorch APIs have changed recently. I failed to run the Embedding layer using torch 1.8.1+cu111.
The APIs of Embedding and LayerNorm are different. Did you consider supporting different torch versions or locking it on a specific version? The latter is not a user-friendly choice, although I noticed your designate a torch version in requirements.txt.

https://pytorch.org/docs/1.8.1/generated/torch.nn.Embedding.html?highlight=embeddings
https://pytorch.org/docs/1.10.0/generated/torch.nn.Embedding.html?highlight=embeddings

**Comment by kurisusnowdeng** [comment]
Hi. Thanks for your suggestion. We do want to support as many versions of PyTorch as possible, and will fix issues of imcompatibility in a very recent update. For the issue you mentioned, we suggest that you can update PyTorch to 1.9.0 and above first. If there is any other imcompatibility issue, feel free to reach out to us and point it out.

**Comment by FrankLeeeee** [comment]
We are running thorough checks for version compatibility. @BoxiangW , can you update your results here as well?
