### ISSUE TITLE
[BUG]: RuntimeError of "RANK" when running train.py of ResNet example on a single GPU

### ISSUE THREAD

**Issue by songyuc** [hpcaitech/ColossalAI#1074]
### 🐛 Describe the bug

I met a problem today when running with `python train.py`, as below,
```bash 
/home/user/software/python/anaconda/anaconda3/envs/conda-general/bin/python /home/user/***/***
/ColossalAI-Examples/image/resnet/train.py
Traceback (most recent call last):
  File "/home/user/software/python/anaconda/anaconda3/envs/conda-general/lib/python3.10/site-packages/colossalai/initialize.py", line 210, in launch_from_torch
    rank = int(os.environ['RANK'])
  File "/home/user/software/python/anaconda/anaconda3/envs/conda-general/lib/python3.10/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'RANK'

During handling of the above exception, another exception occurred:

...

RuntimeError: Could not find 'RANK' in the torch environment, visit https://www.colossalai.org/ for more information on launching with torch
```
Is this error due to the absence of environment variable `RANK` in my Ubuntu?

### Environment

Python: 3.10

**Comment by feifeibear** [comment]
Did you run the script with torchrun?

**Comment by songyuc** [comment]
> Did you run the script with torchrun?

No, I run it with `python` interpreter.

**Comment by YuliangLiu0306** [comment]
You should use colossalai run or torchrun, they will set your environment internally.

**Comment by songyuc** [comment]
> You should use colossalai run or torchrun, they will set your environment internally.

As I want to debug it on PyCharm, so I need to use `python` interpreter.
So, is there a way to do this?

**Comment by YuliangLiu0306** [comment]
I highly recommend you using pdb to debug your program, then you don't have to care about how to trigger the pycharm debug mode.

**Comment by songyuc** [comment]
I am sorry to admit that I have never used `pdb`.
So, is there a equivalent way to use `python` instead of `torchrun` to run this script?

**Comment by FrankLeeeee** [comment]
`torchrun` is using `python` but in a distributed manner. Distributed training requires launching multiple processes together, therefore, we need something to spawn the processes and set the environment for inter-process communication. That is what `torchrun` or `colossalai run` does. If we simply run the script with `python train.py`, the distributed communication network cannot be initialized.

**Comment by songyuc** [comment]
> `torchrun` is using `python` but in a distributed manner. Distributed training requires launching multiple processes together, therefore, we need something to spawn the processes and set the environment for inter-process communication. That is what `torchrun` or `colossalai run` does. If we simply run the script with `python train.py`, the distributed communication network cannot be initialized.

Thanks sincerely for your guide. I might understand this architecture like a distributed system.

**Comment by FrankLeeeee** [comment]
Great, I think you might want to use the IDE debuggers for your code. However, for distributed code, it might be a bit tricky, a better way is to manually `import pdb` and insert break points.

**Comment by songyuc** [comment]
Hi, @FrankLeeeee,
By the way, I heard that processes spawning and environment setting are operations which can be done in python. So, it might not be a problem to transform the behavior of `torchrun` or `colossalai run` into a equivalent python script.

**Comment by songyuc** [comment]
> Great, I think you might want to use the IDE debuggers for your code. However, for distributed code, it might be a bit tricky, a better way is to manually `import pdb` and insert break points.

Yeah, I have experienced that the distributed codes might crash in PyCharm's debug.

**Comment by FrankLeeeee** [comment]
Yes, it can be done, but with some potential modifications to your code. A sample code is like below.

```python
import torch.multiprocessing as mp
import colossalai

def run_dist(rank, world_size):
    colossalai.launch(config='./config.py', rank=rank, world_size=world_size, host='localhost', port=29500, backend='nccl')
    
    run_your_code()

def main():
    world_size = 4
    run_func = partial(run_dist, world_size=world_size)
    mp.spawn(run_func, nprocs=world_size)

if __name__ == '__main__':
    main()
```

**Comment by songyuc** [comment]
> Yes, it can be done, but with some potential modifications to your code. A sample code is like below.
> 
> ```python
> import torch.multiprocessing as mp
> import colossalai
> 
> def run_dist(rank, world_size):
>     colossalai.launch(config='./config.py', rank=rank, world_size=world_size, host='localhost', port=29500, backend='nccl')
>     
>     run_your_code()
> 
> def main():
>     world_size = 4
>     run_func = partial(run_dist, world_size=world_size)
>     mp.spawn(run_func, nprocs=world_size)
> 
> if __name__ == '__main__':
>     main()
> ```

And it might be the last request: I would try exploring running the `python train.py` on PyCharm, if my following questions will be welcome to you. 
Or, I might have to give up continuing the exploring on it, as I should admit that adapting our model to the `colossalai` is beyond my current knowledge and ability.
So, would you offer more help which I seek for to adapt the codes on PyCharm?

**Comment by FrankLeeeee** [comment]
Sure, we welcome questions from the community.

**Comment by songyuc** [comment]
> Sure, we welcome questions from the community.

OK, I will update the information after further trials.

**Comment by songyuc** [comment]
> Sure, we welcome questions from the community.

Hi, @FrankLeeeee, if I want to run single-GPU training of [ResNet example ](https://github.com/hpcaitech/ColossalAI-Examples/tree/main/image/resnet#run-single-gpu-training), is `colossalai run` essential or directly `python train.py` is enough?

**Comment by yuxinyuan** [comment]
I'm not familiar with PyCharm debug. But it's totally possible to use vscode to run the code in debug mode. For single-GPU distributed training, it behaves almost the same as running a single process script with python interpreter (You can set breakpoints and use the debug console to interact with the script). Just use the following launch.json template in vscode:

------

```
{
  "name": "train",
  "type": "python",
  "request": "launch",
  "module": "torch.distributed.run",  // This invokes torchrun
  "args": [
    // Command line args goes here
    "train.py",
  ],
  "console": "integratedTerminal",
  // Environment variables goes here.
  // "env": {"CUDA_LAUNCH_BLOCKING": "1"}
}
```

**Comment by songyuc** [comment]
> I'm not familiar with PyCharm debug. But it's totally possible to use vscode to run the code in debug mode. For single-GPU distributed training, it behaves almost the same as running a single process script with python interpreter (You can set breakpoints and use the debug console to interact with the script). Just use the following launch.json template in vscode:
> 
> ```
> {
>   "name": "train",
>   "type": "python",
>   "request": "launch",
>   "module": "torch.distributed.run",  // This invokes torchrun
>   "args": [
>     // Command line args goes here
>     "train.py",
>   ],
>   "console": "integratedTerminal",
>   // Environment variables goes here.
>   // "env": {"CUDA_LAUNCH_BLOCKING": "1"}
> }
> ```

Hi, @yuxinyuan,
By the way, I heard `torch.distributed` is designed for running on a single device with multiple GPUs.
So, would invoking `torchrun` bring any benefits to the training on a single GPU?

**Comment by yuxinyuan** [comment]
@songyuc I guess you mean `torch.distributed.launch` ? They serve the same purpose and I guess there's not much difference, but `torch.distributed.launch` is being deprecated in latest pytorch versions. So if you are using recent versions of pytorch, you should use `torchrun`.

**Comment by FrankLeeeee** [comment]
Close due to inactivity.

**Comment by songyuc** [comment]
Hi, @FrankLeeeee , I am still working on this issue, so, please help reopen it.
By the way, my question is, in [ResNet example ](https://github.com/hpcaitech/ColossalAI-Examples/tree/main/image/resnet#run-single-gpu-training), `colossalai` launches as,
```python
colossalai.launch_from_torch(config='./config.py')
```
So, it different from,
> Yes, it can be done, but with some potential modifications to your code. A sample code is like below.
> 
> ```python
> import torch.multiprocessing as mp
> import colossalai
> 
> def run_dist(rank, world_size):
>     colossalai.launch(config='./config.py', rank=rank, world_size=world_size, host='localhost', port=29500, backend='nccl')
>     ......

**Comment by tongping** [comment]
> Great, I think you might want to use the IDE debuggers for your code. However, for distributed code, it might be a bit tricky, a better way is to manually `import pdb` and insert break points.

I tried to "import pdb;breakpoint()". However, then I will get the problem "self.quitting: raise BdbQuit bdb.BdbQuit". Do you have an idea how to solve such issue. BTW, I am using the container to run colossal ai.

**Comment by tongping** [comment]
> I highly recommend you using pdb to debug your program, then you don't have to care about how to trigger the pycharm debug mode.

I can't use pdb to debug the problem, which will have to BdbQuit issue as shown above. I wonder whether we could set up this environment that will allow me to step into "colossalai.launch_from_torch"??
