### ISSUE TITLE
can not open wechat link!

### ISSUE THREAD

**Issue by Arsmart123** [hpcaitech/ColossalAI#1079]
### 🐛 Describe the bug

I have used my VPN, so I can open this github page, but it can not load the picture, also can not load the wechat link! The lookings like below:
![QQ浏览器截图20220607221551](https://user-images.githubusercontent.com/65449458/172406264-697a770b-12c5-483a-9080-6c634883d9e6.png)
![QQ浏览器截图20220607221950](https://user-images.githubusercontent.com/65449458/172406285-72e39119-804a-43c7-9c90-e9049bfa5fbf.png)

**Comment by binmakeswell** [comment]
Hi @Arsmart123 This should be caused by your personal VPN's poor support for GitHub. 
Our global team has used many devices to access it from different network environments, and this problem has not yet occurred. 
I just tested it again, and the page displays fine.
