### ISSUE TITLE
[BUG]: NaiveAMPModel only handles single tensor or list/tuple of tensor output.

### ISSUE THREAD

**Issue by yuxinyuan** [hpcaitech/ColossalAI#1084]
### 🐛 Describe the bug

https://github.com/hpcaitech/ColossalAI/blob/65ee6dcc205abb703e09b0ef3ef6d3571d87cd14/colossalai/amp/naive_amp/naive_amp.py#L147

The NaiveAMPModel only converts single fp16 tensor or list/tuple of fp16 tensors back to fp32 tensors. This causes errors when the return type is a dict of tensors. I think NaiveAMPModel should at least handle primitive containers (e.g. tuple, list, dict) and nested containers.

### Environment

colossalai version: 0.1.5+torch1.11cu10.2

**Comment by FrankLeeeee** [comment]
Good proposal, we can support this in the next release or nightly build.

**Comment by FrankLeeeee** [comment]
Fixed in #1102 .
