### ISSUE TITLE
[BUG] Timer reset bug.

### ISSUE THREAD

**Issue by feifeibear** [hpcaitech/ColossalAI#109]
Could you please check the implementation of the timer reset? I believe it is buggy and not able to deal with exceptions. For example, what if the `name is not in `self._timers`?

colossalai - root - 2022-01-04 14:47:52,004 INFO: [Epoch 0 / Train]: Loss = nan | LR = 0.00015 | Throughput = 0
Traceback (most recent call last):
  File "/home/jiaruifang/codes/ColossalAI/examples/bert/run_bert_with_engine.py", line 106, in <module>
    train_gpt()
  File "/home/jiaruifang/codes/ColossalAI/examples/bert/run_bert_with_engine.py", line 102, in train_gpt
    trainer.fit(train_dataloader=train_dataloader, epochs=gpc.config.NUM_EPOCHS, hooks=hook_list, display_progress=True)
  File "/home/jiaruifang/codes/ColossalAI/colossalai/trainer/_trainer.py", line 312, in fit
    self._train_epoch(
  File "/home/jiaruifang/codes/ColossalAI/colossalai/trainer/_trainer.py", line 196, in _train_epoch
    self._call_timer(action='reset', item='Train-step')
  File "/home/jiaruifang/codes/ColossalAI/colossalai/trainer/_trainer.py", line 127, in _call_timer
    getattr(self._timer, action)(item, *args, **kwargs)
  File "/home/jiaruifang/codes/ColossalAI/colossalai/utils/timer.py", line 121, in reset
    self._timers[name].reset()
KeyError: 'Train-step'

**Comment by kurisusnowdeng** [comment]
Hi. The `timer` has to be manually initialized as below.
```
from colossalai.utils import MultiTimer
from colossalai.trainer import Trainer
timer = MultiTimer()
trainer = Trainer(..., timer=timer)
```
We will also add an example of using MultiTimer in trainer and hooks, and improve error messages very soon.

**Comment by feifeibear** [comment]
> Hi. The `timer` has to be manually initialized as below.
> 
> ```
> from colossalai.utils import MultiTimer
> from colossalai.trainer import Trainer
> timer = MultiTimer()
> trainer = Trainer(..., timer=timer)
> ```
> 
> We will also add an example of using MultiTimer in trainer and hooks, and improve error messages very soon.

Could you please review MR #114 ?

**Comment by kurisusnowdeng** [comment]
> > Hi. The `timer` has to be manually initialized as below.
> > ```
> > from colossalai.utils import MultiTimer
> > from colossalai.trainer import Trainer
> > timer = MultiTimer()
> > trainer = Trainer(..., timer=timer)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > We will also add an example of using MultiTimer in trainer and hooks, and improve error messages very soon.
> 
> Could you please review MR #114 ?

Approved. Thank you for contribution!
