### ISSUE TITLE
[FEATURE]: Basic Function of ColoTensors

### ISSUE THREAD

**Issue by feifeibear** [hpcaitech/ColossalAI#1149]
### Describe the feature

I found that ColoTensor lacks some basic functionalities.

- [x] initialized in shard mode from a torch tensor.
- [x] save and load in a distributed mode.
- [ ] support torch.einsum
- [ ] support conv2d
- [x] flexible assign process group for each tensor.
- [ ] inter-convert ColoTensor <-> torch.Tensor

**Comment by binmakeswell** [comment]
We have updated a lot. This issue was closed due to inactivity. Thanks.
