### ISSUE TITLE
[BUG]: program blocking when using pipeline parallelism training

### ISSUE THREAD

**Issue by VenAlone** [hpcaitech/ColossalAI#1180]
### 🐛 Describe the bug

on line 65 of p2p.py, if only using pipeline parallelism, send_split=False, object_send_list doesn't append anythings, process_object_to_send function will return a emtpy object_send_list, then p2p communication will blocking.Fix it just type as:
if send_list:
    object_send_list.append(split_tensor_into_1d_equal_chunks(tensor_send))
else:
    object_send_list.append(tensor_send)

**Comment by VenAlone** [comment]
I cloned colossalai from master branch just yesterday, the commit id is "dd0420".

**Comment by VenAlone** [comment]
> Hi, we have restructured our pipeline parallelism recently, could you provide your `colossalai` version as well?

I cloned colossalai from master branch just yesterday, the commit id is "dd0420".

**Comment by YuliangLiu0306** [comment]
Thank you for the feedback, I make the mistake in recent commit. I will fix the bug as you proposed.
