### ISSUE TITLE
[BUG]: stuck at initialization and no error message

### ISSUE THREAD

**Issue by binmakeswell** [hpcaitech/ColossalAI#1184]
### 🐛 Describe the bug

When parallel is set to pipeline=4 and tensor=dict(mode='2d', size=4), the program will get stuck on initialization and no error message will be output.

### Environment

2*8 A100

**Comment by binmakeswell** [comment]
Same bug at tp2pp4

**Comment by LinglingGreat** [comment]
same bug, looking forward a solution...

**Comment by FrankLeeeee** [comment]
which example is related to this bug?

**Comment by binmakeswell** [comment]
> which example is related to this bug?

gpt2 for the initial issue.

**Comment by binmakeswell** [comment]
We have updated a lot. This issue was closed due to inactivity. Thanks.
