### ISSUE TITLE
[BUG] Python 3.10 cannot install dependency by requirements.txt

### ISSUE THREAD

**Issue by swagshaw** [hpcaitech/ColossalAI#119]
**Describe the bug**

**To Reproduce**
Steps or code snippet to reproduce the behavior:
![image](https://user-images.githubusercontent.com/48468760/148194196-63a14005-6163-42a3-a5a5-ae9ca85c0e4a.png)
I use conda default python version which is 3.10 to follow this picture to install but raise an error.

**Expected behavior**
`pip install -r requirements/requirements.txt`, this command can not be used based on Python 3.10, the screenshots are as follow.

**Screenshots**
![image](https://user-images.githubusercontent.com/48468760/148193017-e4d59c21-10b0-4b5e-b752-9c636895a859.png)

**Environment (please complete the following information):**
 - CUDA version:
 - cuDNN version:
 - NCCL version:
 - Python version: 3.10
 - PyTorch version: 

**Additional context**
I found that `pip install -r requirements/requirements.txt` can be used at the latest version of python 3.8 and 3.9, so maybe we can set a note to let users do not use python 3.10 to install. Or recommend a python version.

**Comment by feifeibear** [comment]
I recommend this project provide a docker image. It will be helpful if you are also considering making it a cloud-native platform.

**Comment by FrankLeeeee** [comment]
As mentioned in this [issue](https://github.com/pytorch/pytorch/issues/67669), PyTorch seems to have no distribution for python 3.10, so downgrading to python 3.9 or below is required. A dockerfile is added in PR #126
