### ISSUE TITLE
Compatabilities to various batch formats[FEATURE]

### ISSUE THREAD

**Issue by ExtremeViscent** [hpcaitech/ColossalAI#120]
**Is your feature request related to a problem? Please describe.**
The implementation of ColossalAI seems only transfer tesors in batch (dict) values to device. However the organization of batch format can be various and highly customized (e.g. list-type batches, minibatch dict containing lists of tensors). In such cases the batchsize cannot be correctly determined and causing errors. 

**Describe the solution you'd like**
The `batch_size` in `BaseSchedule.load_batch()` should consider list-type batches and use `len()` instead of `size()`. The same applies for the `BaseSchedule._move_to_device()`, which should consider minibatches containing multiple tensors in a list.

**Comment by FrankLeeeee** [comment]
Hi @ExtremeViscent , sorry for my late reply. I think you are right, we currently uses dictionary to support complex inputs in pipeline parallelism. But for normal schedule, I think list/tuple should be supported as well.

**Comment by binmakeswell** [comment]
Work in process
