### ISSUE TITLE
[DOC] Document Issue in colossalai.utils.data_sampler.get_dataloader

### ISSUE THREAD

**Issue by swagshaw** [hpcaitech/ColossalAI#122]
Screen:
![image](https://user-images.githubusercontent.com/48468760/148356884-866faa1c-1ee2-440e-891b-a2fc9c85759d.png)
Url: 
https://www.colossalai.org/colossalai/colossalai.utils.data_sampler.html
Description:
The note of parameter dataset should be  `torch.utils.data.Dataset`.

**Comment by kurisusnowdeng** [comment]
Thank you for reminding us. We will fix this typo asap.

**Comment by FrankLeeeee** [comment]
Hi, @1SAA  , can you fix this doc issue in your PR as well?

**Comment by FrankLeeeee** [comment]
Fixed in #200
