### ISSUE TITLE
[FEATURE]: Expotential Moving Average (EMA)

### ISSUE THREAD

**Issue by taoisu** [hpcaitech/ColossalAI#1304]
### Describe the feature

The EMA is used to train many models, an example can be found here: https://github.com/CompVis/latent-diffusion/blob/main/ldm/modules/ema.py

But with model sharding it is unclear how to implement ema properly. It would be really nice to have a sample to showcase how to implement ema properly in Colossal AI.

**Comment by binmakeswell** [comment]
https://github.com/hpcaitech/ColossalAI/blob/main/examples/images/diffusion/ldm/models/autoencoder.py#L11
We have updated a lot. This issue was closed due to inactivity. Thanks.
