### ISSUE TITLE
[FEATURE]: Huggingface support

### ISSUE THREAD

**Issue by chuckhope** [hpcaitech/ColossalAI#1322]
### Describe the feature

Hi there, Colossal is a great work. I have seen you have made some huggingface transformers scripts in the test directory, I wonder when there will be a release of official usage with huggingface transformers. Thank you.

Regards,
Chuck

**Comment by binmakeswell** [comment]
Hi @chuckhope  Thanks for your comments, we have provided an OPT example with Huggingface:
https://github.com/hpcaitech/ColossalAI-Examples/tree/main/language/opt
Here is a related blog if you want to check it:
https://medium.com/@yangyou_berkeley/colossal-ai-seamlessly-accelerates-large-models-at-low-costs-with-hugging-face-4d1a887e500d
You are welcome to put forward expectations and needs.
