### ISSUE TITLE
[FEATURE]: PyTorch Lightning Integration 

### ISSUE THREAD

**Issue by tchaton** [hpcaitech/ColossalAI#1330]
### Describe the feature

Dear Collosal-ai Team, @FrankLeeeee @feifeibear.

My name is Thomas Chaton. I am part of PyTorch Lightning Team.

First of all, congrats on your latest results, those are impressive numbers !!!

We are thinking to integrate Collosal-ai into PyTorch Lightning to democratise its access to all our users in the same way as we did with DeepSpeed, FSDP or Bagua as there has been some demands from users: https://github.com/Lightning-AI/lightning/issues/12733

We wondered if anyone on your side would be interested in collaborating with one of us, so we can accelerate collosal-ai integration and its adoption within our community. Once finished, we will like to cross-promote the work done.

Reach out to me on PyTorch Lightning Slack, my username is tchaton. 

Best regards,
Thomas Chaton, Lightning Tech Lead.

**Comment by FrankLeeeee** [comment]
@tchaton Hey Thomas, glad to hear from you! Sure, we can work on the integration of ColossalAI and PyTorch Lightning. Let's chat on slack.

**Comment by binmakeswell** [comment]
We have done. Thanks.
