### ISSUE TITLE
How to initialize the linear2D?  Both TWO_DIMENSION_COL and TWO_DIMENSION_ROW must be initialized by the process group initializer

### ISSUE THREAD

**Issue by Arsmart123** [hpcaitech/ColossalAI#134]
### Describe the feature

#!/usr/bin/env python
# -*- encoding: utf-8 -*-

import os
import colossalai
import torch
import torchvision
from colossalai.builder import *
from colossalai.core import global_context as gpc
from colossalai.logging import get_dist_logger
from colossalai.nn import Accuracy, CrossEntropyLoss
from colossalai.nn.lr_scheduler import CosineAnnealingWarmupLR
from colossalai.trainer import Trainer
from colossalai.trainer.hooks import (AccuracyHook, LogMemoryByEpochHook,
                                      LogMetricByEpochHook,
                                      LogMetricByStepHook,
                                      LogTimingByEpochHook, LossHook,
                                      LRSchedulerHook, ThroughputHook)
from colossalai.utils import MultiTimer, get_dataloader
from model_zoo.vit import vit_lite_depth7_patch4_32
from torchvision import transforms
from colossalai.nn import Linear2D
import torch.nn as nn
from delete import trainset

os.environ['MASTER_ADDR'] = '127.0.0.1'
os.environ['MASTER_PORT'] = '8888'
os.environ['DATA'] = 'D:/trash_can'
os.environ['CONFIG_FILE'] = 'D:/trash_can/ColossalAI-main/benchmark/cifar/configs/vit_1d.py'
os.environ['LOCAL_RANK'] = '0'
os.environ['RANK'] = '0'
os.environ['WORLD_SIZE'] = '1'

DATASET_PATH = str(os.environ['DATA'])

def build_cifar(batch_size):
    train_dataset = trainset()
    test_dataset = trainset()
    train_dataloader = get_dataloader(dataset=train_dataset,
                                      shuffle=True,
                                      batch_size=batch_size,
                                      num_workers=0,
                                      pin_memory=True)
    test_dataloader = get_dataloader(dataset=test_dataset, batch_size=batch_size, num_workers=0, pin_memory=True)
    return train_dataloader, test_dataloader

class MLP_2D(nn.Module):

    def __init__(self):
        super().__init__()
        self.linear_1 = Linear2D(in_features=1024, out_features=16384)
        self.linear_2 = Linear2D(in_features=16384, out_features=1024)

    def forward(self, x):
        x = self.linear_1(x)
        x = self.linear_2(x)
        return x

def train_cifar():
    args = colossalai.get_default_parser().parse_args()  

    colossalai.launch_from_torch(config=args.config)

    logger = get_dist_logger()
    if hasattr(gpc.config, 'LOG_PATH'):
        if gpc.get_global_rank() == 0:
            log_path = gpc.config.LOG_PATH
            if not os.path.exists(log_path):
                os.mkdir(log_path)
            logger.log_to_file(log_path)

    model = MLP_2D()

    train_dataloader, test_dataloader = build_cifar(gpc.config.BATCH_SIZE // gpc.data_parallel_size)

    criterion = CrossEntropyLoss(label_smoothing=0.1)

    optimizer = torch.optim.AdamW(model.parameters(), lr=gpc.config.LEARNING_RATE, weight_decay=gpc.config.WEIGHT_DECAY)

    steps_per_epoch = len(train_dataloader)

    lr_scheduler = CosineAnnealingWarmupLR(optimizer=optimizer,
                                           total_steps=gpc.config.NUM_EPOCHS * steps_per_epoch,
                                           warmup_steps=gpc.config.WARMUP_EPOCHS * steps_per_epoch)

    engine, train_dataloader, test_dataloader, lr_scheduler = colossalai.initialize(model=model,
                                                                                    optimizer=optimizer,
                                                                                    criterion=criterion,
                                                                                    train_dataloader=train_dataloader,
                                                                                    test_dataloader=test_dataloader,
                                                                                    lr_scheduler=lr_scheduler)

    logger.info("Engine is built", ranks=[0])

    timer = MultiTimer()

    trainer = Trainer(engine=engine, logger=logger, timer=timer)
    logger.info("Trainer is built", ranks=[0])

    hooks = [
        LogMetricByEpochHook(logger=logger),
        LogMetricByStepHook(),
        # LogTimingByEpochHook(timer=timer, logger=logger),
        # LogMemoryByEpochHook(logger=logger),
        AccuracyHook(accuracy_func=Accuracy()),
        LossHook(),
        ThroughputHook(),
        LRSchedulerHook(lr_scheduler=lr_scheduler, by_epoch=False)
    ]

    logger.info("Train start", ranks=[0])
    trainer.fit(train_dataloader=train_dataloader,
                test_dataloader=test_dataloader,
                epochs=gpc.config.NUM_EPOCHS,
                hooks=hooks,
                display_progress=True,
                test_interval=1)

if __name__ == '__main__':
    train_cifar()

Traceback (most recent call last):
  File "D:/trash_can/ColossalAI-main/benchmark/cifar/train.py", line 161, in <module>
    train_cifar()
  File "D:/trash_can/ColossalAI-main/benchmark/cifar/train.py", line 112, in train_cifar
    model = MLP_2D()
  File "D:/trash_can/ColossalAI-main/benchmark/cifar/train.py", line 81, in __init__
    self.linear_1 = Linear2D(in_features=1024, out_features=16384)
  File "D:\trash_can\ColossalAI-main\colossalai\nn\layer\parallel_2d\layers.py", line 52, in __init__
    assert_summa_initialization()
  File "D:\trash_can\ColossalAI-main\colossalai\nn\layer\parallel_2d\_utils.py", line 23, in assert_summa_initialization
    'Both TWO_DIMENSION_COL and TWO_DIMENSION_ROW must be initialized by the process group initializer'
AssertionError: Both TWO_DIMENSION_COL and TWO_DIMENSION_ROW must be initialized by the process group initializer

**Comment by kurisusnowdeng** [comment]
Hi. Could please try `benchmark/cifar/configs/vit_2d.py`(instead of `vit_1d.py`) as the configuration to intialize a 2D tensor parallelism? If there is still problem, please reach out to us.

**Comment by Arsmart123** [comment]
> Hi. Could please try `benchmark/cifar/configs/vit_2d.py`(instead of `vit_1d.py`) as the configuration to intialize a 2D tensor parallelism? If there is still problem, please reach out to us.

Thank you! That works!!!
