### ISSUE TITLE
[BUG]: A conflict with pytorch1.8.1

### ISSUE THREAD

**Issue by Aziily** [hpcaitech/ColossalAI#1390]
### 🐛 Describe the bug

I am using the environment below to install colossalAI and it tell me that I am successfully install it
![image](https://user-images.githubusercontent.com/101855289/181875706-b45cd3ff-b4d2-4815-96c7-f34891b57597.png)

However, when I tried to use it, I got this error
![image](https://user-images.githubusercontent.com/101855289/181875729-5e23bc6e-4760-45b1-a8f0-5f30ea993249.png)

After searching the pytorch for help, I found that the Tensor.positive can only be used by pytorch 1.9.0 or latter. I think this is a bug and wonder how to solve it.

### Environment

colossalai-0.1.8
torch1.8cu10.1
python3.8

**Comment by ofey404** [comment]
Hi Azilly! Thank you for the feedback.

Currently Colossal-AI support pytorch 1.10, 1.11 and 1.12. [Supported Pytorch Version](https://colossalai.org/download).

Supporting pytorch 1.8 is not on our roadmap. Sorry for any inconvenience, but we recommend you to upgrade to pytorch 1.10+ and enjoy some new features ;)

**Comment by ofey404** [comment]
> Hi Azilly! Thank you for the feedback.
> 
> Currently Colossal-AI support pytorch 1.10, 1.11 and 1.12. [Supported Pytorch Version](https://colossalai.org/download).
> 
> Supporting pytorch 1.8 is not on our roadmap. Sorry for any inconvenience, but we recommend you to upgrade to pytorch 1.10+ and enjoy some new features ;)

Correcting a mistake: Pytorch 1.12 is not officially supported yet.

**Comment by binmakeswell** [comment]
We have updated a lot. This issue was closed due to inactivity. Thanks.
https://github.com/hpcaitech/ColossalAI#Installation
