### ISSUE TITLE
[DOC]:  What BATCHSIZE was used for megatron and Colossal-AI (different cards) respectively, in benchmark results of GPT-3?

### ISSUE THREAD

**Issue by zzqq2199** [hpcaitech/ColossalAI#1414]
### 📚 The doc issue

# Description
What's the **Batchsize** adopted in benchmark results shown in [figure](https://raw.githubusercontent.com/hpcaitech/public_assets/main/colossalai/img/GPT3-v5.png) ?

<p align="center">
<img src="https://raw.githubusercontent.com/hpcaitech/public_assets/main/colossalai/img/GPT3-v5.png" width=700/>
</p>

# Location
https://medium.com/@hpcaitech/train-18-billion-parameter-gpt-models-with-a-single-gpu-on-your-personal-computer-8793d08332dc

# Expectation
Show Batchsize adopted in Megatron-LM / Colossal-AI experiments

# Screenshots
None

# Suggestions
None

**Comment by zzqq2199** [comment]
**Batchsize** affects training throughput, especially when some optimizations whose overhead is constant regardless batchsize are adopted. I think this is important for showing benchmark results, and I'm personally very interested in how much BS was used, So I hope you can tell me!

**Comment by ver217** [comment]
Hi, the global batch size is 192.

**Comment by feifeibear** [comment]
@binmakeswell bin, can we add batch size setting in the tables?

**Comment by binmakeswell** [comment]
> @binmakeswell bin, can we add batch size setting in the tables?

Sure, it will be updated soon.

**Comment by binmakeswell** [comment]
Updated.
