### ISSUE TITLE
[BUG]: FreqCacheEmbeddingBag._weight.ProcessGroup is initialized before _weight initialized

### ISSUE THREAD

**Issue by zxgx** [hpcaitech/ColossalAI#1434]
### 🐛 Describe the bug

When I init a DLRM with ParallelFreqAwareEmbeddingBag, the bug is reported as the following:
![image](https://user-images.githubusercontent.com/34452939/184055340-c99579bf-c9df-43ed-8552-7c9ae7aadffb.png)

I believe that is because the [ParallelFreqAwareEmbeddingBag](https://github.com/hpcaitech/ColossalAI/blob/039b7ed3bc33173e36c5c4decd41f8d7b1ec0f45/colossalai/nn/_ops/cache_embedding/parallel_freq_aware_embedding.py#L60) init its `_weight.ProcessGroup` before the `_weight` is initialized.

After I swap above line with its next line, the traceback shows another error:
![image](https://user-images.githubusercontent.com/34452939/184055612-de402e67-ac19-4860-ac12-9622f88a6aca.png)

It looks like some api update issue.

**Comment by feifeibear** [comment]
Thanks for the feedback. I will have a look.
