### ISSUE TITLE
[FEATURE]: how to support codebases such as mmdetection as a distributed backend

### ISSUE THREAD

**Issue by ElephantGit** [hpcaitech/ColossalAI#1491]
### Describe the feature

Hi, I'm training my large detection model with mmdetection codebase, but it requires many GPUs and takes a very long time to train. So I'm wandering how to use this amazing distributed tools as a backend of mmdetection to accelerate my traing with only small number of GPUs.
Thanks!

**Comment by binmakeswell** [comment]
Thank you for your feedback, we will consider providing it first in future version updates.

**Comment by binmakeswell** [comment]
We have updated a lot. This issue was closed due to inactivity. Thanks.
