### ISSUE TITLE
How to specify the gpu of each server？

### ISSUE THREAD

**Issue by mandoxzhang** [hpcaitech/ColossalAI#1498]
for example, if each server has 8 GPUs, 0 to 7. I want to use 1, 3, 5, 7, not 0, 2, 4, 6
Thank you

**Comment by YuliangLiu0306** [comment]
You can use 'export CUDA_VISIBLE_DEVICES=1,3,5,7'  in linux terminal or os.environ["CUDA_VISIBLE_DEVICES"] = "1, 3, 5, 7" in your python code.

**Comment by mandoxzhang** [comment]
thx, I'll try

**Comment by binmakeswell** [comment]
This issue was closed due to inactivity. Thanks.
