### ISSUE TITLE
How to define a model with only one layer?

### ISSUE THREAD

**Issue by Arsmart123** [hpcaitech/ColossalAI#155]
### Describe the feature

#!/usr/bin/env python
# -*- encoding: utf-8 -*-

import os
import colossalai
import torchvision
from colossalai.builder import *
from colossalai.core import global_context as gpc
from colossalai.logging import get_dist_logger
from colossalai.nn import Accuracy, CrossEntropyLoss, MSELoss
from colossalai.nn.lr_scheduler import CosineAnnealingWarmupLR
from colossalai.trainer import Trainer
from colossalai.trainer.hooks import (AccuracyHook, LogMemoryByEpochHook,
                                      LogMetricByEpochHook,
                                      LogMetricByStepHook,
                                      LogTimingByEpochHook, LossHook,
                                      LRSchedulerHook, ThroughputHook)
from colossalai.utils import MultiTimer, get_dataloader
from model_zoo.vit import vit_lite_depth7_patch4_32
from torchvision import transforms
from colossalai.nn import Linear1D_Col, Linear1D, Linear1D_Row
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
import torch

DATASET_PATH = str(os.environ['DATA'])

class trainset(Dataset):
    def __init__(self):
        pass

    def __getitem__(self, index):
        target = torch.randint(5, (4,), dtype=torch.int64)
        data = torch.randn(1, 5)
        return data, target

    def __len__(self):
        return 512*1

def build_cifar(batch_size):
    train_dataset = trainset()
    test_dataset = trainset()
    train_dataloader = get_dataloader(dataset=train_dataset,
                                      shuffle=True,
                                      batch_size=batch_size,
                                      num_workers=0,
                                      pin_memory=True)
    test_dataloader = get_dataloader(dataset=test_dataset, batch_size=batch_size, num_workers=0, pin_memory=True)
    return train_dataloader, test_dataloader

class MLP_1D(nn.Module):

    def __init__(self):
        super().__init__()
        self.linear_1 = Linear1D_Col(in_features=5, out_features=4, gather_output=True)
        #self.linear_2 = Linear1D_Row(in_features=4, out_features=1)

    def forward(self, x):
        x = self.linear_1(x)
        #x = self.linear_2(x)
        x = torch.squeeze(x, 1)
        return x

def train_cifar():
    args = colossalai.get_default_parser().parse_args()
    # standard launch
    # colossalai.launch(config=args.config,
    #                   rank=args.rank,
    #                   world_size=args.world_size,
    #                   local_rank=args.local_rank,
    #                   host=args.host,
    #                   port=args.port)

    # launch from torchrun
    colossalai.launch_from_torch(config=args.config)

    logger = get_dist_logger()
    if hasattr(gpc.config, 'LOG_PATH'):
        if gpc.get_global_rank() == 0:
            log_path = gpc.config.LOG_PATH
            if not os.path.exists(log_path):
                os.mkdir(log_path)
            logger.log_to_file(log_path)

    # model = vit_lite_depth7_patch4_32()
    model = MLP_1D()

    train_dataloader, test_dataloader = build_cifar(gpc.config.BATCH_SIZE // gpc.data_parallel_size)
    
    
    criterion = CrossEntropyLoss(label_smoothing=0.1)

    optimizer = torch.optim.AdamW(model.parameters(), lr=gpc.config.LEARNING_RATE, weight_decay=gpc.config.WEIGHT_DECAY)

    steps_per_epoch = len(train_dataloader)

    lr_scheduler = CosineAnnealingWarmupLR(optimizer=optimizer,
                                           total_steps=gpc.config.NUM_EPOCHS * steps_per_epoch,
                                           warmup_steps=gpc.config.WARMUP_EPOCHS * steps_per_epoch)
    
    engine, train_dataloader, test_dataloader, lr_scheduler = colossalai.initialize(model=model,
                                                                                    optimizer=optimizer,
                                                                                    criterion=criterion,
                                                                                    train_dataloader=train_dataloader,
                                                                                    test_dataloader=test_dataloader,
                                                                                    lr_scheduler=lr_scheduler)

      
    logger.info("Engine is built", ranks=[0])

    timer = MultiTimer()

    trainer = Trainer(engine=engine, logger=logger, timer=timer)
    logger.info("Trainer is built", ranks=[0])

    hooks = [
        LogMetricByEpochHook(logger=logger),
        LogMetricByStepHook(),
        # LogTimingByEpochHook(timer=timer, logger=logger),
        # LogMemoryByEpochHook(logger=logger),
        AccuracyHook(accuracy_func=Accuracy()),
        LossHook(),
        ThroughputHook(),
        LRSchedulerHook(lr_scheduler=lr_scheduler, by_epoch=False)
    ]

    logger.info("Train start", ranks=[0])
    trainer.fit(train_dataloader=train_dataloader,
                test_dataloader=test_dataloader,
                epochs=gpc.config.NUM_EPOCHS,
                hooks=hooks,
                display_progress=True,
                test_interval=1)

if __name__ == '__main__':
    train_cifar()

This is my code and it reports: 
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
RuntimeError: Expected floating point type for target with class probabilities, got Long
I am not sure...How to define a single layer model?

**Comment by FrankLeeeee** [comment]
Hi @Arsmart123 , this looks like to dtype mismatch. Can you try cast your cifar10 label to float?

**Comment by Arsmart1** [comment]
> Hi @Arsmart123 , this looks like to dtype mismatch. Can you try cast your cifar10 label to float?

Thank you for your suggestion! Yes, the problem is my train and label set. After modifying the dtype, it works just fine.
