### ISSUE TITLE
[BUG]: Couldn't install cuda_ext

### ISSUE THREAD

**Issue by ShangWeiKuo** [hpcaitech/ColossalAI#1672]
### 🐛 Describe the bug

Excuse me. I installed ColossalAI following the ways you provided with.

After running the command "pip install colossalai==0.1.10+torch1.12cu11.3 -f https://release.colossalai.org", I got the message stated that "If you want to activate cuda mode for MoE, please install with cuda_ext!" and "CUDA_Extension = X".

How should I do to install the correct CUDA_Extension?

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/26018604/193171780-729b2be4-eadf-47ad-ae6d-78a05a4083d7.png)

### Environment

CUDA Version: 11.3
PyTorch Version: 1.12.0+cu113
CUDA Version in PyTorch Build: 11.3
PyTorch CUDA Version Match: Yes
CUDA Extension: No

**Comment by ranjan2829** [comment]
Ok, that is a little strange. If the --cuda-ext and --cpp_ext options are working as intended, you should have seen c++ and cuda files being built as part of the install (long gcc and nvcc command lines). Did you see these?

**Comment by binmakeswell** [comment]
We have updated a lot. This issue was closed due to inactivity. Thanks.
https://github.com/hpcaitech/ColossalAI#Installation
