### ISSUE TITLE
[BUG]: Unable to create Optimizer Using ZeroOptimizer

### ISSUE THREAD

**Issue by mayank-nference** [hpcaitech/ColossalAI#1693]
### 🐛 Describe the bug

 I am trying to create an optimizer to train an `opt-125m` model using `ZERO Chunk-based Memory Management`. I am getting the following assertion error. I am trying to replicate the following script - https://github.com/hpcaitech/ColossalAI-Examples/blob/main/language/opt/run_clm.py

getting following error

`---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
Cell In [24], line 3
      1 # optimizer
      2 optimizer = HybridAdam(optimizer_grouped_parameters, lr=1e-5)
----> 3 optimizer = ZeroOptimizer(model, optimizer, initial_scale=2**14)

File /opt/conda/lib/python3.9/site-packages/colossalai/zero/zero_optimizer.py:61, in ZeroOptimizer.__init__(self, optim, module, gpu_margin_mem_ratio, initial_scale, min_scale, growth_factor, backoff_factor, growth_interval, hysteresis, max_scale)
     49 def __init__(self,
     50              optim: Optimizer,
     51              module: ZeroDDP,
   (...)
     58              hysteresis: int = 2,
     59              max_scale: float = 2**32):
     60     super().__init__(optim)
---> 61     assert isinstance(module, ZeroDDP)
     62     self.module = module
     63     self.gemini_manager = module.gemini_manager

AssertionError: 
`

### Environment

I am using the following docker image - `docker pull hpcaitech/colossalai:0.1.8` reference of which is mentioned on the colossalAI [GitHub](https://github.com/hpcaitech/ColossalAI) repository - https://hub.docker.com/r/hpcaitech/colossalai

**Comment by binmakeswell** [comment]
https://github.com/hpcaitech/ColossalAI/tree/main/examples
You can try new examples. We have updated a lot. This issue was closed due to inactivity. Thanks.
