### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by Fazziekey** [hpcaitech/ColossalAI#1749]
### 🐛 Describe the bug

- Get cuda_emptyCache when use Pyrtorch lightning  ColossalAIStrategy(https://github.com/Lightning-AI/lightning/blob/master/src/pytorch_lightning/strategies/colossalai.py)
![4X0sMso74r](https://user-images.githubusercontent.com/55798671/196910162-78b7c977-5ad6-4f37-83f1-54b7d2380de2.jpg)

![image](https://user-images.githubusercontent.com/55798671/196910043-f11669f4-cb18-44bb-b7fd-2ee830068504.png)

**Comment by binmakeswell** [comment]
We have updated a lot. This issue was closed due to inactivity. Thanks.
