### ISSUE TITLE
Add hooks before and after operators

### ISSUE THREAD

**Issue by feifeibear** [hpcaitech/ColossalAI#175]
### Describe the feature

I noticed the project has a hook factory, which provides an easy way to add some extra business logic (like throughput metric) before and after a training iteration.
However, the name hook is a little bit misunderstanding since it is not the same as the hook of Pytorch.
The PyTorch hooks can add some operations before and after FWD and BWD of a submodule.
Currently, the project does not provide a function in the BaseHook for developers to do some operations before and after a PyTorch submodule (like Linear) execution.
For example, someone would like to depict the memory footprint during training by recording the memory usage before and after an operator execution.
I consider adding register_forward_hook and register_forward_pre_hook functions to HookBase. Just like the setup_zero_stage3_hooks. Does this make sense to you?

**Comment by FrankLeeeee** [comment]
Hi, the hooks currently only support the life cycle at the trainer level but not tensor level. Life cycle of trainer hook is like before train, before train iter, after train iteration and so on. If we want to track the memory footprint at the operation level, I think a new hook factory is required.
