### ISSUE TITLE
[BUG]: Cannot pull latest Docker image

### ISSUE THREAD

**Issue by groganz** [hpcaitech/ColossalAI#1756]
### 🐛 Describe the bug

Issuing `docker pull hpcaitech/colossalai` will result in this error:

`Error response from daemon: manifest for hpcaitech/colossalai:latest not found: manifest unknown: manifest unknown`

**Comment by FrankLeeeee** [comment]
I think you need to pull with a specific tag instead.

**Comment by groganz** [comment]
That's what I did. Just thought you might want to configure your deployment pipeline to also provide a latest image for the sake of convention and convenience.

**Comment by binmakeswell** [comment]
We have updated a lot. This issue was closed due to inactivity. Thanks.
https://github.com/hpcaitech/ColossalAI#use-docker
