### ISSUE TITLE
[BUG]: activation checkpoint function can't pass kwargs

### ISSUE THREAD

**Issue by Gy-Lu** [hpcaitech/ColossalAI#1761]
### 🐛 Describe the bug

See the [checkpoint function](https://github.com/hpcaitech/ColossalAI/blob/main/colossalai/utils/activation_checkpoint.py#L141) and how it used in [CheckpointModule](https://github.com/hpcaitech/ColossalAI/blob/main/colossalai/nn/layer/utils/common.py#L26).
Now **the only keyword arg** can be passed in `checkpoint` function is `use_reentrant`, and can't be passed into `_forward`.

the def of checkpoint function
```
def checkpoint(function, activation_offload, *args, use_reentrant: bool = True):
```

its usage in CheckpointModule
```
    def forward(self, *args, **kwargs):
        if self._use_checkpoint:
            return checkpoint(self._forward, self._offload, *args, **kwargs)
        else:
            return self._forward(*args, **kwargs)
```

**Comment by Gy-Lu** [comment]
Hmm, It seems that keyword args in `_forward` of CheckpointModule is not supported.

**Comment by super-dainiu** [comment]
cc @Cypher30

**Comment by binmakeswell** [comment]
We have updated a lot. This issue was closed due to inactivity. Thanks.
