### ISSUE TITLE
No module named 'colossal_C'

### ISSUE THREAD

**Issue by frankxyy** [hpcaitech/ColossalAI#1773]
After installing， i still meet error when trying to import colossal_C

**Comment by frankxyy** [comment]
Plus: I build from the source code as belows:

git clone https://github.com/hpcaitech/ColossalAI.git
cd ColossalAI

# install dependency
pip install -r requirements/requirements.txt

# install colossalai
pip install .

**Comment by kurisusnowdeng** [comment]
Hi, I guess our CUDA extensions are not correctly installed. Please make sure you are building colossalai with CUDA, and your CUDA version should be the same as the version of cudatoolkit of pytorch. You could run `nvcc -V` and `python -c "import torch; print(torch.version.cuda)"` to check the versions.

**Comment by frankxyy** [comment]
@kurisusnowdeng  it seems that in the setup.py file, the variable `CUDA_HOME` is not set. So the following code can not get the correct value of this variable.

**Comment by frankxyy** [comment]
Problem solved，the reason is the full version of cuda toolkit is not installed on the host machine.

**Comment by bestbzw** [comment]
@frankxyy 

I met the same problem, could you tell me how you install the full version of cuda toolkit.

**Comment by feifeibear** [comment]
@bestbzw I believe our dockerfile is a good reference.
https://github.com/hpcaitech/ColossalAI/blob/main/docker/Dockerfile#L4

**Comment by binmakeswell** [comment]
We have updated a lot. This issue was closed due to inactivity. Thanks.
https://github.com/hpcaitech/ColossalAI#Installation
