### ISSUE TITLE
[BUG]: stable diffusion example

### ISSUE THREAD

**Issue by AlvL1225** [hpcaitech/ColossalAI#1864]
### 🐛 Describe the bug

when installing stable diffusion environments, everything works fine until doing below:
**

> git clone https://github.com/Lightning-AI/lightning && cd lightning && git reset --hard b04a7aa
> pip install -r requirements.txt && pip install .

**

the requirements.txt in lightning will change lots of things(like changing torchmetrics==0.6.0 to torchmetrics>=0.7.0, <0.10.1)

**Comment by 1SAA** [comment]
Those specific versions of packages are required by Lightning. There may raise compatibility problem if you install a mismatched version.

**Comment by 1SAA** [comment]
Hi @yli1994 ,

Thanks for your issue. I've already updated `environment.yaml`.

**Comment by 1SAA** [comment]
Hi @yli1994,

could you show me more about your error and you environment.
you can use the scripts in pytorch issues to get your environment. just open an issue in pytorch and you should know how to get your environment.
