### ISSUE TITLE
GPU memory used for stable diffusion

### ISSUE THREAD

**Issue by cyysc1998** [hpcaitech/ColossalAI#1885]
I finetune the stable diffusion on one RTX3090 with config 
```
python main.py --logdir /tmp -t --postfix test -b configs/train_colossalai.yaml
```
The config for lighting is as follows:
![image](https://user-images.githubusercontent.com/35159700/201093881-70100c49-0cac-4165-9b0d-8a30e9f3a45d.png)

![image](https://user-images.githubusercontent.com/35159700/201093327-c521438c-9a36-4c9a-9c82-003ca60f1fb1.png)
The batch size is set to 1. However, it is still out of memory. 
Is this normal?
Thank you!

**Comment by DonStroganotti** [comment]
I can get it to start training by setting placement_policy to cpu or auto on my 2070 SUPER. But it crashes before it finishes training.

**Comment by cyysc1998** [comment]
@DonStroganotti Setting placement_policy to cpu works. But like you, is crashes after 5 epoches.

**Comment by feisan** [comment]
In addition to GPU memory, I'm curious about how much RAM memory is needed for training.

My device has 32GB of RAM and an RTX 3090 (24GB), but it runs out of memory after a few steps.

**Comment by Alfred-Duncan** [comment]
I have 4*3090, I'll try it next week

**Comment by binmakeswell** [comment]
We have updated a lot. This issue was closed due to inactivity. Thanks.
