### ISSUE TITLE
an error in stable diffusion[BUG]: 

### ISSUE THREAD

**Issue by kangxi1818** [hpcaitech/ColossalAI#1886]
### 🐛 Describe the bug

I run the code 
python main.py --logdir /tmp -t --postfix test -b configs/train_colossalai2.yaml
and I get an error 
![截屏2022-11-10 下午8 47 43](https://user-images.githubusercontent.com/117744200/201096084-a14222bc-4791-4673-b37a-7ee230dfa76c.png)
but where to download the file diffusion_pytorch_model.bin

**Comment by kangxi1818** [comment]
there are something wrong, the code is python main.py --logdir /tmp -t --postfix test -b configs/train_colossalai.yaml

**Comment by kangxi1818** [comment]
@jwliu-cc thank you for your reply, but in this website, there are all the .ckpt file, not the .bin file

**Comment by jwliu-cc** [comment]
You may check it again and I found the .bin files:
![image](https://user-images.githubusercontent.com/37931056/201527902-3870db05-9dda-467f-bd19-4c20076e5fbb.png)
