### ISSUE TITLE
[BUG]: memory not decrease

### ISSUE THREAD

**Issue by songjin321** [hpcaitech/ColossalAI#1887]
### 🐛 Describe the bug

<img width="571" alt="image" src="https://user-images.githubusercontent.com/15363101/201094615-fe48117e-b4fe-4a48-b0d3-a596bc8e88a8.png">

I use the train_pokemon.yaml file to train the model on my device with 3090ti gpu, then I got an OOM error. so I set the batch size to 1, but the gpu used is 18G, there are must some thing wrong....

**Comment by binmakeswell** [comment]
Hi @songjin321  Thank you for your feedback. We will try to reproduce your issue and fix it soon.

**Comment by Fazziekey** [comment]
you can try train_colossalai.yaml

**Comment by Fazziekey** [comment]
the train_pokemon.yaml is not completed
