### ISSUE TITLE
[BUG]: Version issues and Error on Start

### ISSUE THREAD

**Issue by arpowers** [hpcaitech/ColossalAI#1890]
### 🐛 Describe the bug

After spending roughly two hours trying to get this basic SD example working, I failed. 

There seems to be some issues around version compatibility and following the docs doesn't lead me to the promised land. 

Additionally, after (i think) i got version issues worked out, i ran it and got this error:

<img width="900" alt="Screenshot 2022-11-10 at 6 34 17 PM" src="https://user-images.githubusercontent.com/308134/201250336-5335f7c1-cd48-441d-82c1-edf7de027497.png">

### Environment

NVIDIA T4  cloud environment
All other packages i tried to upgrade to latest or recommended by repo

**Comment by 1SAA** [comment]
Hi @arpowers,

It seems like you do not install `pytorch-lightning` package or your `pytorch-lightning`'s version is lower than 1.8.0.
You can check [here](https://github.com/hpcaitech/ColossalAI/blob/main/examples/images/diffusion/environment.yaml)  for some requirements.

**Comment by binmakeswell** [comment]
We have updated a lot. This issue was closed due to inactivity. Thanks.
