### ISSUE TITLE
[BUG]: problem  to run the example of colossalai

### ISSUE THREAD

**Issue by lambda7xx** [hpcaitech/ColossalAI#1929]
### 🐛 Describe the bug

https://github.com/hpcaitech/ColossalAI-Examples/issues/196

https://github.com/hpcaitech/ColossalAI-Examples/issues/195

https://github.com/hpcaitech/ColossalAI-Examples/issues/193

**Comment by binmakeswell** [comment]
Hi @lambda7xx Thank you for your feedback. We will try to reproduce your issue and fix it soon.
By the way, we are restructuring the documents and examples, and the new version examples will be provided at the following link
https://github.com/hpcaitech/ColossalAI/tree/main/examples

**Comment by lambda7xx** [comment]
I try https://github.com/hpcaitech/ColossalAI/tree/main/examples and there are lots of problem.

BTW, I am working on a benchmark and try to implement gpt and swin transformer by using SP+PP of ColossalAI. I'm confused by the example code and document. So, could you help me implement gpt and swin transformer by using SP+PP of ColossalAI. You are more familiar  with the ColossalAI than me. I have struggled with the implementation  for half month.

**Comment by feifeibear** [comment]
Actually, I am not an expert on SP and PP. I can help you to contact the author of the SP paper. @FrankLeeeee can you help with this project?

**Comment by lambda7xx** [comment]
> Actually, I am not an expert on SP and PP. I can help you to contact the author of the SP paper. @FrankLeeeee can you help with this project?

thank you very much.

**Comment by binmakeswell** [comment]
We have updated a lot. This issue was closed due to inactivity. Thanks.
