### ISSUE TITLE
[BUG]: fine-tune with stable diffusion

### ISSUE THREAD

**Issue by ray0809** [hpcaitech/ColossalAI#1936]
### 🐛 Describe the bug

when I running the training example with cifar10, It broken with an error `RuntimeError: Expected is_sm80 to be true, but got false.`

As mentioned from [https://github.com/HazyResearch/flash-attention/issues/51](https://github.com/HazyResearch/flash-attention/issues/51), the author said the dim_head must be 128

but the input dim_head of SD‘s attention modules is lower 128

### Environment
GTX 3090
cuda 11.3
torch 1.12.1
colossalai 0.1.10+torch1.12cu11.3

### Screenshots
![image](https://user-images.githubusercontent.com/18100835/201587393-bc7893e9-8193-4a90-ac16-e122d1c75ee0.png)

By the way, the use_ema tag is false in training config, when I turned it on, it threw another error

English is not my native language, please excuse some of my grammar mistakes

**Comment by Fazziekey** [comment]
Flash attention is not a stable feature in ColossalAi, Flash attention is an approximation algorithm for attention， the dim size must be the second power of 2

**Comment by ray0809** [comment]
@Fazziekey thanks for your response
In the colossalai's stable diffusion example, the flash_attn's tag is disable, but the readme tells us that using flash could save much gpu memory.

**Comment by Fazziekey** [comment]
we fix the use_ema in https://github.com/hpcaitech/ColossalAI/pull/1986/files

**Comment by ray0809** [comment]
ok, Thank you~
