### ISSUE TITLE
Create a develop branch for dev

### ISSUE THREAD

**Issue by feifeibear** [hpcaitech/ColossalAI#195]
### Describe the feature

We can merge new features to develop branch instead of master.

https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow

**Comment by FrankLeeeee** [comment]
Thanks, I think this makes code practice more standard. I will create a develop branch later.

**Comment by FrankLeeeee** [comment]
Branch created. We will shift to this develop branch afterwards.
