### ISSUE TITLE
[BUG]: Cant Do Validation During Training

### ISSUE THREAD

**Issue by WuZifan** [hpcaitech/ColossalAI#1975]
### 🐛 Describe the bug

I try to do validation step on every n steps. the training step goes well, but got this error
<img width="1213" alt="image" src="https://user-images.githubusercontent.com/22706545/202389728-6895f411-edf3-4a62-9740-aac6fceb2eb8.png">

 here is my config:
<img width="911" alt="image" src="https://user-images.githubusercontent.com/22706545/202389834-5564787a-3cc5-47b7-b1aa-b6e6d913bc31.png">

### Environment

the env just as recommond

**Comment by Fazziekey** [comment]
Thanks for your issue, we will fix the bug as soon as we can

**Comment by binmakeswell** [comment]
We have updated a lot. This issue was closed due to inactivity. Thanks.
