### ISSUE TITLE
[FEATURE]: Support for train with diffusers

### ISSUE THREAD

**Issue by CrazyBoyM** [hpcaitech/ColossalAI#1976]
### Describe the feature

Is it possible to provide a version for training dreambooth and textual inversion with ColossalAI, and make a PR  to diffusers.

such as: 
https://github.com/huggingface/diffusers/tree/main/examples/dreambooth
https://github.com/huggingface/diffusers/tree/main/examples/textual_inversion

as there are many many people using the two script to finetune Stable diffusion.

**Comment by binmakeswell** [comment]
Hi @CrazyBoyM Thank you for your feedback.  
It’s pretty awesome. We will check it and consider providing it.

**Comment by Fazziekey** [comment]
we are Cooperation with huggingface, we will support huggingface diffuser an soon as we can
