### ISSUE TITLE
[FEATURE]: How to use multiple nodes for training examples/images/diffusion

### ISSUE THREAD

**Issue by summerwuxia** [hpcaitech/ColossalAI#1983]
### Describe the feature

How to use multiple nodes for training examples/images/diffusion

**Comment by Fazziekey** [comment]
https://pytorch-lightning.readthedocs.io/en/latest/api/pytorch_lightning.trainer.trainer.Trainer.html#pytorch_lightning.trainer.trainer.Trainer

**Comment by summerwuxia** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，夏武已经收到你的来信，祝你生活愉快

**Comment by Fazziekey** [comment]
![image](https://user-images.githubusercontent.com/55798671/203927601-0e7360f0-0982-481d-93e3-1ac527a9700f.png)

**Comment by Fazziekey** [comment]
![image](https://user-images.githubusercontent.com/55798671/203927659-651442cd-491e-43cd-bcb6-b3caf237620f.png)

**Comment by Fazziekey** [comment]
you can add `num_nodes` in your yaml

**Comment by Fazziekey** [comment]
![image](https://user-images.githubusercontent.com/55798671/203927793-6593c2c5-2b33-4ff2-88cd-aeff0c539b67.png)

**Comment by binmakeswell** [comment]
We have updated a lot. This issue was closed due to inactivity. Thanks.

**Comment by summerwuxia** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，夏武已经收到你的来信，祝你生活愉快
