### ISSUE TITLE
[BUG]: Nothing is available on the Download tab of the website

### ISSUE THREAD

**Issue by netw0rkf10w** [hpcaitech/ColossalAI#1991]
### 🐛 Describe the bug

Here you go:

<img width="1156" alt="Screen Shot 2022-11-18 at 15 18 00" src="https://user-images.githubusercontent.com/8569515/202725430-21ebe111-441a-4125-a6c9-dda2055e21dc.png">

**Comment by binmakeswell** [comment]
Hi @netw0rkf10w It looks like the website didn't load correctly, do you try to change your network or browser and still do so?
I checked the website and the download shows fine.
![image](https://user-images.githubusercontent.com/61670638/202825097-22dd453a-e651-4e7c-b058-5f610f7a85c5.png)

**Comment by FrankLeeeee** [comment]
Close due to inactivity, the download page should work fine at the moment.
