### ISSUE TITLE
KeyError: 'txt'

### ISSUE THREAD

**Issue by pokameng** [hpcaitech/ColossalAI#1992]
Hello
Thanks for your interesting works!
I want to use colossalAI to train a model on lsun bedroom dataset, and my config is as follow:
![image](https://user-images.githubusercontent.com/47957015/202922301-8a058268-fec5-44e9-b0bc-ca3578e8f08b.png)
When i run the train.sh, somethong was wrong with it:

Keyerror 'caption'

When i reoplace caption with txt , proplem is that keyerror 'txt'

![Uploading image.png…]()

@ryanrussell @xcnick @feifeibear @junxu @jimmieliu

**Comment by pokameng** [comment]
The bug is:
![image](https://user-images.githubusercontent.com/47957015/202922750-1b2c4263-3838-47de-800e-d96fd510eace.png)

**Comment by Fazziekey** [comment]
![image](https://user-images.githubusercontent.com/55798671/203892181-84aa1767-a8e3-4835-9e0e-ffb9cbccfc68.png)

**Comment by Fazziekey** [comment]
if you want to use your own datasets please refer to https://github.com/hpcaitech/ColossalAI/blob/main/examples/images/diffusion/ldm/data/base.py, the data format should be same as your yaml config

**Comment by Fazziekey** [comment]
![image](https://user-images.githubusercontent.com/55798671/203892417-7491aed9-644a-4870-ba2f-c9f01fbb9b1c.png)

**Comment by Fazziekey** [comment]
for example if the YAML file , `first_stage_key`: image, `cond_stage_key`: caption, your dataset should also return { caption,image}

**Comment by pokameng** [comment]
> if you want to use your own datasets please refer to https://github.com/hpcaitech/ColossalAI/blob/main/examples/images/diffusion/ldm/data/base.py, the data format should be same as your yaml config

I know, but the lsun.py you provide is suitable for lsun bedroom right? The config on `data` is shown as follow:
![image](https://user-images.githubusercontent.com/47957015/203893503-9e995cc4-57ea-4d7b-bad3-a8845e7b72c1.png)

Shuold I change the `target` : ldm.data.lsun.LSUNBedroomsTrain to ldm.data.lsun.LSUNBedroomsTrain?

But I  want to use ldm.data.lsun.LSUNBedroomsTrain to train lsun bedroom dataset.

**Comment by Fazziekey** [comment]
yes, the `target` in the yaml will create a python object with `params`, you should make it be a make it like a common torch data loadder

**Comment by pokameng** [comment]
> But I want to use ldm.data.lsun.LSUNBedroomsTrain to train lsun bedroom dataset.

But I want to use ldm.data.lsun.LSUNBedroomsTrain to train lsun bedroom dataset.
If i use ldm.data.lsun.LSUNBedroomsTrain, it has a wrong:
`text input must of type `str` (single example), `List[str]` (batch or single pretokenized example) or `List[List[str]]` (batch of pretokenized examples).`

The lsun.py is shown as follow:
![image](https://user-images.githubusercontent.com/47957015/203896443-134f3c36-8cc5-4c99-900f-6cf2607a8e1e.png)

**Comment by Fazziekey** [comment]
the lsun is an uncondition example, which means only an image without a text prompt, you should also change the model config in your train yaml. It was not recommend for training your own model

**Comment by Fazziekey** [comment]
![image](https://user-images.githubusercontent.com/55798671/203897407-28eeb7b4-d11c-4c23-84b9-75c6a0ab5a56.png)

**Comment by Fazziekey** [comment]
I think the base.py is an good example  to train image with text caption

**Comment by pokameng** [comment]
> I think the base.py is an good example to train image with text caption

Can you give me a example for text?
I want to kown the content in txt

**Comment by pokameng** [comment]
> I think the base.py is an good example to train image with text caption

you mean the cifar10 is the conditional example?

**Comment by Fazziekey** [comment]
you can try teyvat.py and the datasets are here https://huggingface.co/datasets/Fazzie/Teyvat

**Comment by Fazziekey** [comment]
![image](https://user-images.githubusercontent.com/55798671/203929382-75f8e21b-1d96-4a34-9af3-96f9c976347c.png)

**Comment by Fazziekey** [comment]
image with text is a right format

**Comment by binmakeswell** [comment]
We have updated a lot. This issue was closed due to inactivity. Thanks.
