### ISSUE TITLE
[BUG]: Bug in Stable-Diffusion Example, "Killed" when saving checkpoint

### ISSUE THREAD

**Issue by yxding95** [hpcaitech/ColossalAI#1993]
### 🐛 Describe the bug

I was trying to run the stable-diffusuin example, but found the program would be Killed at the saving process, Without any Error Message. Also found the config file "train_ddp.yaml" is OK. So maybe some bug in save_checkpoint, would you please fix this bug?

### Environment

I'm using the Docker Image you provide "hpcaitech/colossalai:0.1.10-torch1.11-cu11.3"

**Comment by Fazziekey** [comment]
Thanks for your issue, can you offer more detail such as the image?

**Comment by Thomas2419** [comment]
I also get this bug when trying to save this model. This was in a conda environment using the provided environment.yaml and on Ubuntu 20.04. I ran multiple tests to try and fix it and noted that, even with batch size of one the training went from virtual memory usage 22 to 46 to 68 and then the process was killed. I noticed that using save_weights_only: True enabled saving to work but with the weights only I am unable to do sampling, nor could I continue training.

**Comment by Comedian1926** [comment]
Hello, I also met the same problem. How did you solve it
![image](https://user-images.githubusercontent.com/46297043/206975420-d3cad254-e768-49d2-8668-078f4a3b8632.png)

**Comment by Fazziekey** [comment]
we have update the stable diffusion to v2 (https://github.com/hpcaitech/ColossalAI/pull/2120), Now there is no problem of kill

**Comment by yufengyao-lingoace** [comment]
@Fazziekey  But stable diffusion v2 has no pre-trained model, so is not useful. How to train with stable diffusion v1? I also met with this problem, the first epoch is normal , the second time to save checkpoints it is killed.

**Comment by binmakeswell** [comment]
We have updated a lot. This issue was closed due to inactivity. Thanks.
https://github.com/hpcaitech/ColossalAI/tree/main/examples/images/diffusion
