### ISSUE TITLE
[BUG]: Out of memory when training stable diffusion on RTX2070

### ISSUE THREAD

**Issue by basbaba** [hpcaitech/ColossalAI#1997]
### 🐛 Describe the bug

When training stable diffusion, crashed report: CUDA out of memory.

Is it possible to run on RTX2070?

Thanks!

### Environment

OS: Ubuntu 20.04
GPU: RTX2070 + 8GB RAM
Python: 3.8
pytorch: 1.11
cuda: 11.3
Colossalai: 0.1.10
Stable Diffusion pre-traind models downloaded from https://huggingface.co/CompVis/stable-diffusion-v1-4/tree/main
train_colossalai.yaml: only modified "data"->"file_path", there are 4 jpg files in size of 256*256 for testing

**Comment by DonStroganotti** [comment]
I don't think whoever wrote that article claiming that 8GB GPU's could easily be used for training has answered any questions about it yet. 

That includes their Reddit account they used for spam marketing this release, absolutely zero engagement with the community.

**Comment by Fazziekey** [comment]
what's your train.yaml, if you want to train on RTX2070, you must decrease your batch size from 64 to > 4.

**Comment by Fazziekey** [comment]
![image](https://user-images.githubusercontent.com/55798671/203893432-54e425cb-988b-4daa-88c7-654dfe914e48.png)

**Comment by Fazziekey** [comment]
![image](https://user-images.githubusercontent.com/55798671/203893511-4250d4f0-b6a4-4b8c-8136-383f47b844ef.png)
