### ISSUE TITLE
[BUG]: in stable-diffusion train appear Killed

### ISSUE THREAD

**Issue by ML-GCN** [hpcaitech/ColossalAI#2031]
### 🐛 Describe the bug

![image](https://user-images.githubusercontent.com/45411027/204083560-277f3eb2-7f68-4d62-8d1a-c418d11320fe.png)

in the train stage i set epoch 20 but after epoch 3 appear Killed the stop  but  The GPU is not released 
![image](https://user-images.githubusercontent.com/45411027/204083915-c52d219f-7056-45e9-a766-47b234ca497a.png)

AND save the checkpoint last.ckpt contains10G?
![image](https://user-images.githubusercontent.com/45411027/204083891-dcab1d83-56b1-43c7-9d29-5455df24f73e.png)

Could you tell me the reason for this thank you

### Environment

the environment is the same by you provide 
the yaml is train_colossalai.yaml

**Comment by FrankieDong** [comment]
我遇到了相同的情况。在docker环境中，finetune SD过程中，出现killed的情况。
colossalai：v0.1.10
cuda：12.0
nvcc：11.3
GPU型号：3090Ti 2块
