### ISSUE TITLE
Problem with stable diffusion training

### ISSUE THREAD

**Issue by pinxuezhao** [hpcaitech/ColossalAI#2054]
Hello! Thanks for your cool repo!
When I tried stable diffusion training with  
    python3 main.py --logdir /tmp -t --postfix test -b configs/train_colossalai_cifar10.yaml
I found it failed just after starting the training loop: 
![image](https://user-images.githubusercontent.com/106951017/204848892-b915385b-79af-447f-880e-e9f7e11ce511.png)
<img width="1593" alt="image" src="https://user-images.githubusercontent.com/106951017/204849162-f0a005fa-624b-43c0-b3f9-2df4d7f03a82.png">
![image](https://user-images.githubusercontent.com/106951017/204849270-a80e3aa3-6bbc-423e-95c1-c29bf70c1c5a.png)
I' m not sure if there are any details that I did wrong.
Any suggestions will be highly appreciated!

**Comment by JThh** [comment]
Try python3 main.py --logdir /tmp -t --postfix test -b configs/train_colossalai_cifar10.yaml --placement_policy 'cuda'

**Comment by binmakeswell** [comment]
We have updated a lot. This issue was closed due to inactivity. Thanks.
