### ISSUE TITLE
Can it support t5 or mt5 model training?

### ISSUE THREAD

**Issue by RyanYip-Kat** [hpcaitech/ColossalAI#2063]
### Describe the feature

If I want to train t5 or mt5 model with my dataset,whether it can be implemented using Colossal AI ?

**Comment by feifeibear** [comment]
https://github.com/hpcaitech/ColossalAI/blob/main/examples/language/gpt/README.md
Of course, ColossalAI is a general framework. You can refer the GPT example.

**Comment by theblackcat102** [comment]
I am currently trying to train a mt5-large model using colossalai but seems to have some issue with setstorage bug #2145. I would be happy to contribute a working example if this bug was sorted out.

**Comment by binmakeswell** [comment]
Welcome contributions from the community. 
 https://github.com/hpcaitech/ColossalAI/tree/main/examples/community#looking-for-examples
This issue was closed due to inactivity. Thanks.
