### ISSUE TITLE
Does the colossalAI support to train conditional model based on image condition rather than text?

### ISSUE THREAD

**Issue by pokameng** [hpcaitech/ColossalAI#2068]
Hello!
Does the colossalAI support to train conditional model based on image condition rather than text?
@Fazziekey 
The configs in colossalAI  are based on text to image, but i want to train a new model based on image.

**Comment by Fazziekey** [comment]
It‘s ok to train from image condition,  but you need to config the right model and input

**Comment by pokameng** [comment]
> It‘s ok to train from image condition, but you need to config the right model and input

Ok  can you share the  example config  with  me?

**Comment by pokameng** [comment]
> It‘s ok to train from image condition, but you need to config the right model and input

@Fazziekey

**Comment by Fazziekey** [comment]
> 

sorry, I don't have an example, but welcome to contribute a example for us
