### ISSUE TITLE
Masking is missing in triangle masked softmax kernel

### ISSUE THREAD

**Issue by kurisusnowdeng** [hpcaitech/ColossalAI#208]
### 🐛 Describe the bug

Hi, the triangle masked softmax cuda kernel ([`ScaledUpperTriangMaskedSoftmax.forward`](https://github.com/hpcaitech/ColossalAI/blob/main/colossalai/kernel/cuda_native/scaled_softmax.py#L24)) has only `inputs` and `scale` as its inputs. It cannot actually apply masking.

**Comment by binmakeswell** [comment]
We have updated a lot. This issue was closed due to inactivity. Thanks.
