### ISSUE TITLE
[BUG]: `_FORMAT` is not defined in `colossalai/logging/logger.py`

### ISSUE THREAD

**Issue by marsggbo** [hpcaitech/ColossalAI#2109]
### 🐛 Describe the bug

https://github.com/hpcaitech/ColossalAI/blob/61f31c3cf01a8db5084401e5f93f52a8f6bcb185/colossalai/logging/logger.py#L127

`_FORMAT` is not defined

**Comment by super-dainiu** [comment]
Thank u. I fixed this already.
