### ISSUE TITLE
[BUG]:  Is there anyway to use multi-gpus inference stable diffusion?

### ISSUE THREAD

**Issue by FrankieDong** [hpcaitech/ColossalAI#2185]
### 🐛 Describe the bug

Hello,
   We are now using the stable diffusion fork, but when I infer 1024*1024, cuda out of memory. However, we have 4 K80, only one used in inference, so is there anyway to use another cards in inference?

**Comment by FrankieDong** [comment]
I use the dataparallel, but it does not work.

**Comment by feifeibear** [comment]
why use data parallel? it is designed for training. We will release our quantized inference solution in the next week. It can save about 30% GPU memory. Maybe that is still not enough for your situation. Perhaps you need do pipelined or tensor parallel for inference. These optimizations are currently not supported.

**Comment by FrankieDong** [comment]
Thanks feifeibear, so we cannot infer 1024*1024 by two more gpus, right?

**Comment by FrankieDong** [comment]
> why use data parallel? it is designed for training. We will release our quantized inference solution in the next week. It can save about 30% GPU memory. Maybe that is still not enough for your situation. Perhaps you need do pipelined or tensor parallel for inference. These optimizations are currently not supported.

Thanks feifeibear, so we cannot infer 1024*1024 by two more gpus, right?

**Comment by feifeibear** [comment]
> > why use data parallel? it is designed for training. We will release our quantized inference solution in the next week. It can save about 30% GPU memory. Maybe that is still not enough for your situation. Perhaps you need do pipelined or tensor parallel for inference. These optimizations are currently not supported.
> 
> Thanks feifeibear, so we cannot infer 1024*1024 by two more gpus, right?

It depends on the spec of your hardware.
The fact is that we currently do not support parallel inference.

**Comment by FrankieDong** [comment]
> 

Thanks

**Comment by FrankieDong** [comment]
> > > why use data parallel? it is designed for training. We will release our quantized inference solution in the next week. It can save about 30% GPU memory. Maybe that is still not enough for your situation. Perhaps you need do pipelined or tensor parallel for inference. These optimizations are currently not supported.
> > 
> > 
> > Thanks feifeibear, so we cannot infer 1024*1024 by two more gpus, right?
> 
> It depends on the spec of your hardware. The fact is that we currently do not support parallel inference.



> > > why use data parallel? it is designed for training. We will release our quantized inference solution in the next week. It can save about 30% GPU memory. Maybe that is still not enough for your situation. Perhaps you need do pipelined or tensor parallel for inference. These optimizations are currently not supported.
> > 
> > 
> > Thanks feifeibear, so we cannot infer 1024*1024 by two more gpus, right?
> 
> It depends on the spec of your hardware. The fact is that we currently do not support parallel inference.

Thanks
