### ISSUE TITLE
[BUG]: after finetuning dreambooth, infer with trained model.

### ISSUE THREAD

**Issue by panshaohua** [hpcaitech/ColossalAI#2198]
### 🐛 Describe the bug

OSError: Unable to load weights from checkpoint file for 'output/unet/diffusion_pytorch_model.bin' at 'output/unet/diffusion_pytorch_model.bin'. If you tried to  load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True

### Environment

Package                  Version                Editable project location
------------------------ ---------------------- -------------------------
absl-py                  1.3.0
accelerate               0.15.0
attrs                    22.2.0
bcrypt                   4.0.1
cachetools               5.2.0
certifi                  2022.12.7
cffi                     1.15.1
cfgv                     3.3.1
charset-normalizer       2.1.1
click                    8.1.3
colossalai               0.1.13+torch1.12cu11.3 /data/shaohua/ColossalAI
commonmark               0.9.1
contexttimer             0.3.3
cryptography             38.0.4
diffusers                0.11.1
distlib                  0.3.6
exceptiongroup           1.1.0
fabric                   2.7.1
fbgemm-gpu               0.2.0
filelock                 3.8.2
ftfy                     6.1.1
google-auth              2.15.0
google-auth-oauthlib     0.4.6
grpcio                   1.51.1
huggingface-hub          0.11.1
identify                 2.5.11
idna                     3.4
importlib-metadata       5.2.0
iniconfig                1.1.1
invoke                   1.7.3
Jinja2                   3.1.2
Markdown                 3.4.1
MarkupSafe               2.1.1
modelcards               0.1.6
ninja                    1.11.1
nodeenv                  1.7.0
numpy                    1.24.0
nvidia-cublas-cu11       11.10.3.66
nvidia-cuda-nvrtc-cu11   11.7.99
nvidia-cuda-runtime-cu11 11.7.99
nvidia-cudnn-cu11        8.5.0.96
oauthlib                 3.2.2
packaging                22.0
paramiko                 2.12.0
pathlib2                 2.3.7.post1
Pillow                   9.3.0
pip                      22.3.1
platformdirs             2.6.0
pluggy                   1.0.0
pre-commit               2.21.0
protobuf                 3.20.3
psutil                   5.9.4
pyasn1                   0.4.8
pyasn1-modules           0.2.8
pycparser                2.21
Pygments                 2.13.0
PyNaCl                   1.5.0
pytest                   7.2.0
PyYAML                   6.0
regex                    2022.10.31
requests                 2.28.1
requests-oauthlib        1.3.1
rich                     12.6.0
rsa                      4.9
setuptools               65.5.0
six                      1.16.0
tensorboard              2.11.0
tensorboard-data-server  0.6.1
tensorboard-plugin-wit   1.8.1
tensornvme               0.1.0
tokenizers               0.13.2
tomli                    2.0.1
torch                    1.13.1
torchvision              0.14.1
tqdm                     4.64.1
transformers             4.25.1
typing_extensions        4.4.0
urllib3                  1.26.13
virtualenv               20.17.1
wcwidth                  0.2.5
Werkzeug                 2.2.2
wheel                    0.37.1
zipp                     3.11.0

**Comment by Sze-qq** [comment]
Hi, thanks for reaching out! We'll reproduce your bug and get back to you ASAP. :)

**Comment by feifeibear** [comment]
Thanks for using our new feature, this is a known bug and we are working on fixing it. I will reply you in this issue if it is fixed.

**Comment by binmakeswell** [comment]
We have updated a lot. This issue was closed due to inactivity. Thanks.

**Comment by wangxiaobo007** [comment]
same error
