### ISSUE TITLE
LAMB is not suited for tensor parallel

### ISSUE THREAD

**Issue by FrankLeeeee** [hpcaitech/ColossalAI#22]
The current LAMB optimizer implementation does not support tensor parallel as it needs to compute norm of the whole matrix. It is not compatible with tensor parallel as the tensor is split.

**Comment by FrankLeeeee** [comment]
@ver217 , i think we got to fix this bug these two days

**Comment by binmakeswell** [comment]
We have updated a lot. This issue was closed due to inactivity. Thanks.
