### ISSUE TITLE
[BUG]: AttributeError: _old_init is not found in the BertEmbeddings, please make sure that you have imported BertEmbeddings before entering the context

### ISSUE THREAD

**Issue by chexiangying** [hpcaitech/ColossalAI#2218]
### 🐛 Describe the bug

  File "/home/tiger/.local/lib/python3.7/site-packages/colossalai/utils/model/utils.py", line 92, in __exit__
    substitute_init_recursively(torch.nn.modules.module.Module, _disable_class, set())
  File "/home/tiger/.local/lib/python3.7/site-packages/colossalai/utils/model/utils.py", line 10, in substitute_init_recursively
    func(subcls)
  File "/home/tiger/.local/lib/python3.7/site-packages/colossalai/utils/model/utils.py", line 87, in _disable_class
    f"_old_init is not found in the {cls.__name__}, please make sure that you have imported {cls.__name__} before entering the context."
AttributeError: _old_init is not found in the BertEmbeddings, please make sure that you have imported BertEmbeddings before entering the context

**Comment by 1SAA** [comment]
Hi @chexiangying,

could you give more information to repeat your bug? accroding to the current information provided, I believe you should pay attentions to the submodules of your model. you should make sure that all modules are initialized under the context `ColoInitContext`.

**Comment by binmakeswell** [comment]
We have updated a lot. This issue was closed due to inactivity. Thanks.
