### ISSUE TITLE
[BUG]: Logger cannot print List[Tensor]

### ISSUE THREAD

**Issue by super-dainiu** [hpcaitech/ColossalAI#2230]
### 🐛 Describe the bug

A list of `torch.Tensor` on `device='meta'` cannot be printed by `DistributedLogger`
```python
logger = get_dist_logger()
logger.info(f"{[torch.tensor([1,2,3], device='meta')]}")
```

**Comment by binmakeswell** [comment]
We have updated a lot. This issue was closed due to inactivity. Thanks.
