### ISSUE TITLE
Lack of quick demo link about hybrid parallel in Documentation

### ISSUE THREAD

**Issue by binmakeswell** [hpcaitech/ColossalAI#225]
### 📚 The doc issue

In 'hybrid parallel' of 'Quick Demo', there is not an example link.  And 'You can follow the README.md for more details.' is also confusing.

Can we consider the hybrid ViT example in the following link?

https://github.com/hpcaitech/ColossalAI-Examples/tree/c3cf060d8346ce81d95704cf2b727c07fa35aa6c/image/vision_transformer/hybrid_parallel

**Comment by FrankLeeeee** [comment]
Hybrid ViT relies on ImageNet dataset which many users do no have. I will create a cifar10 version for this.
