### ISSUE TITLE
[BUG]: False warning

### ISSUE THREAD

**Issue by yhcc** [hpcaitech/ColossalAI#2250]
### 🐛 Describe the bug

The warning should be in the if condition?

https://github.com/hpcaitech/ColossalAI/blob/8897b8f753a7908db7b9ff4519ef79dd4708ef97/colossalai/initialize.py#L304-L306

**Comment by FrankLeeeee** [comment]
Ya, thanks, I will move it inside the if statement.

**Comment by binmakeswell** [comment]
We have updated a lot. This issue was closed due to inactivity. Thanks.
