### ISSUE TITLE
[FEATURE]: Integration to diffusers framework

### ISSUE THREAD

**Issue by haofanwang** [hpcaitech/ColossalAI#2331]
### Describe the feature

Diffusers has become a common framework for stable diffusion. It seems that you already have a [plan](https://github.com/huggingface/diffusers/issues/1212) to integrate to diffusers. What's the progress? I'm looking forward to using it.

**Comment by feifeibear** [comment]
Thanks for your attention to our project. Integration to diffuser is in our schedule. We are planning to add ColossalAI to dreambooth, then we will consider working on the other projects. We are also looking for warmhearted developers to help us on finish that roadmap.

**Comment by binmakeswell** [comment]
We have updated a lot. This issue was closed due to inactivity. Thanks.
https://github.com/hpcaitech/ColossalAI/tree/main/examples/images
