### ISSUE TITLE
Need a finetuning example

### ISSUE THREAD

**Issue by binmakeswell** [hpcaitech/ColossalAI#236]
### Describe the feature

Fewer users are able to train large models directly from scratch. We need to provide an example of fine-tuning.

For example, how to load pre-training parameters into model of colossal-AI and fine-tune them efficiently with other features in colossal-AI? Performance can be optimized incrementally with subsequent updates, but this feature is practical and important.

**Comment by fastalgo** [comment]
I agree

**Comment by feifeibear** [comment]
I believe the feature depends on #256

**Comment by feifeibear** [comment]
I believe the feature depends on #256

**Comment by binmakeswell** [comment]
You can refer to this https://github.com/hpcaitech/ColossalAI/tree/main/applications/Chat
