### ISSUE TITLE
[BUG]: diffusion docker problem

### ISSUE THREAD

**Issue by ziyuhuang123** [hpcaitech/ColossalAI#2362]
### 🐛 Describe the bug

Option 2: Use Docker
Mandatory, mount your prepared data to /data/scratch via -v <your-data-dir>:/data/scratch, where you need to replace <your-data-dir> with the actual data path on your machine.

Follow this instruction I replaced the <your-data-dir> with the /data/scratch/diffuser/laion_part0 and meet this bug:
~/data1/ColossalAI$ docker run --rm \
   -it --gpus all \
   -v $PWD:/workspace \
   -v </data/scratch/diffuser/laion_part0>:/data/scratch \
   -v <hf-cache-dir>:/root/.cache/huggingface \
   hpcaitech/diffusion:0.2.0 \
   /bin/bash
-bash: :/data/scratch: No such file or directory

**Comment by feifeibear** [comment]
</data/scratch/diffuser/laion_part0> `->` /data/scratch/diffuser/laion_part0

**Comment by ziyuhuang123** [comment]
oh, thanks!

**Comment by ziyuhuang123** [comment]
docker run --rm \
   -it --gpus all \
   -v $PWD:/workspace \
   -v /data/scratch/diffuser/laion_part0:/data/scratch \
   -v <hf-cache-dir>:/root/.cache/huggingface \
   hpcaitech/diffusion:0.2.0 \
   /bin/bash
-bash: hf-cache-dir: No such file or directory

So I think I can remove "   -v <hf-cache-dir>:/root/.cache/huggingface \" this line? (Seems it works)

**Comment by ziyuhuang123** [comment]
Download the model checkpoint from pretrained
stable-diffusion-v1-4
Our default model config use the weight from [CompVis/stable-diffusion-v1-4](https://huggingface.co/CompVis/stable-diffusion-v1-4?text=A+mecha+robot+in+a+favela+in+expressionist+style)

git lfs install

I am trying to install lfs. From the official webpage they told me "https://packagecloud.io/github/git-lfs/install#bash-deb", and use this "curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash", but I meet this:

bash: sudo: command not found
bash: curl: command not found

I think this is because I am do not have the privilege to use sudo. I am wondering, is it necessary to use this lfs?? Thanks!

**Comment by ziyuhuang123** [comment]
Well, never mind....Maybe I can use binary package like this.. https://github.com/git-lfs/git-lfs/issues/4134

**Comment by ziyuhuang123** [comment]
Actually, I find no way to install the binary package. I am wondering how the developer tested this diffusion... Is he/she a root user?
