### ISSUE TITLE
API on collective operations

### ISSUE THREAD

**Issue by ExtremeViscent** [hpcaitech/ColossalAI#237]
### Describe the feature

When I attempted to implement a partial tensor parallel model (i.e. only some layers are 2D/2.5D parallel), not a single rank can get a whole tensor. It would be best to provide a function to allow easier collective operations (all_reduce, broadcast, etc) at user level.

**Comment by FrankLeeeee** [comment]
Hi, you can call these operations from `torch.distributed`. You only need to get the group from `gpc`. Feel free to clarify if you do not mean this. :)

**Comment by feifeibear** [comment]
I think the replies solve the problem
