### ISSUE TITLE
[BUG]: Diffusion env problem

### ISSUE THREAD

**Issue by ziyuhuang123** [hpcaitech/ColossalAI#2376]
### 🐛 Describe the bug

I am using 

> conda env create -f environment.yaml
> conda activate ldm

and I meet this:

ModuleNotFoundError: No module named '_posixsubprocess'

**Comment by JThh** [comment]
It can be due to a conflicting version of 'subprocess32' installed via pip. Check this out.

`pip uninstall subprocess32
conda install -c conda-forge subprocess32 `

**Comment by binmakeswell** [comment]
We have updated a lot. This issue was closed due to inactivity. Thanks.
