### ISSUE TITLE
[DOC]: examples/images/dreambooth/README.md 多了一个 s ？

### ISSUE THREAD

**Issue by Degfy** [hpcaitech/ColossalAI#2377]
### 📚 The doc issue

![image](https://user-images.githubusercontent.com/15191087/210966313-4588cb0f-498e-4457-8b9e-3b67e2332037.png)

**Comment by feifeibear** [comment]
Many thanks for your attention to our project. I have fixed the typo!! Hope you can enjoy our dreambooth implementation.
