### ISSUE TITLE
[BUG]: FusedLayerNormAffineFunction need change import to Builder.load()

### ISSUE THREAD

**Issue by yhcc** [hpcaitech/ColossalAI#2388]
### 🐛 Describe the bug

The following import will raise import error after PR:https://github.com/hpcaitech/ColossalAI/pull/2374
https://github.com/hpcaitech/ColossalAI/blob/4e960396490759150ba50313bd89b07bfb2ee635/colossalai/kernel/cuda_native/layer_norm.py#L18-L21

**Comment by feifeibear** [comment]
Thanks, I will fix them ASAP.
