### ISSUE TITLE
[BUG]: backend for supporting distributed training

### ISSUE THREAD

**Issue by haofanwang** [hpcaitech/ColossalAI#2407]
### 🐛 Describe the bug

**Describe the bug**
I'm training with the [dreambooth example](https://github.com/hpcaitech/ColossalAI/tree/main/examples/images/dreambooth) with RDMA. But current backend (gloo) doesn't support it. It leads to following error.

```
RuntimeError: [../third_party/gloo/gloo/transport/tcp/pair.cc:799] connect 
[127.0.1.1]:29591: Connection refused
```

I check the corresponding function, and I guess [this line](https://github.com/hpcaitech/ColossalAI/blob/d3f5ce9efb35bf9e292aa041a3e98b737cbb68ee/colossalai/context/parallel_context.py#L378) is a typo?

old:
`cpu_group = dist.new_group(ranks, backend='gloo') if dist.get_backend() != 'gloo' else None
`
new:
`cpu_group = dist.new_group(ranks, backend='gloo') if dist.get_backend() == 'gloo' else None
`

**Comment by haofanwang** [comment]
I find that the typo above existed in many other files, will add another PR soon.

**Comment by FrankLeeeee** [comment]
Great, thanks!

**Comment by haofanwang** [comment]
@FrankLeeeee Could you re-check this [PR](https://github.com/hpcaitech/ColossalAI/pull/2415)?

**Comment by FrankLeeeee** [comment]
Okay sure.

**Comment by kurisusnowdeng** [comment]
The problem is mostly caused by the firewall since GLOO uses random ports to initialize groups

**Comment by binmakeswell** [comment]
We have updated a lot. This issue was closed due to inactivity. Thanks.
