### ISSUE TITLE
[BUG]: Do you have a wechat group for the debug

### ISSUE THREAD

**Issue by Tron1994** [hpcaitech/ColossalAI#2428]
### 🐛 Describe the bug

Encounter too many problems, hope to communicate in wechat group

**Comment by FrankLeeeee** [comment]
Take a look at the project README and You can join our WeChat group by click on the wechat icon.

**Comment by FrankLeeeee** [comment]
I will close this issue now. Please reopen if you still cannot join our wechat group.
