### ISSUE TITLE
[BUG]: bug in Stable-Diffusion, RuntimeError: expected scalar type Half but found Float

### ISSUE THREAD

**Issue by yufengyao-lingoace** [hpcaitech/ColossalAI#2450]
when i add a "callbacks", RuntimeError: expected scalar type Half but found Float

lightning:

  trainer:
    accelerator: 'gpu'
    devices: 1
    log_gpu_memory: all
    max_epochs: 5000
    precision: 16
    auto_select_gpus: False
    strategy:
      target: strategies.ColossalAIStrategy
      params:
        use_chunk: True
        enable_distributed_storage: True
        placement_policy: auto
        force_outputs_fp32: False

    log_every_n_steps: 2
    logger: True
    default_root_dir: "/tmp/diff_log/"
    profiler: pytorch
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 1
        max_images: 4
        increase_log_steps: False
        log_first_step: False
        #log_all_val: True
        log_images_kwargs:
          use_ema_scope: True
          inpaint: False
          plot_progressive_rows: False
          plot_diffusion_rows: False
          N: 4
          unconditional_guidance_scale: 3.0
          unconditional_guidance_label: [""]

**Comment by Fazziekey** [comment]
can you post which layer you counter precise problem

**Comment by yufengyao-lingoace** [comment]
there are so many layers, just like ddpm.py  line:1432

**Comment by yufengyao-lingoace** [comment]
@Fazziekey The worst problem is that when i use your code to train a model, the txt2img.py outputs a picture with random noise. Could you tell me what should I do?

**Comment by tungdq212** [comment]
@yufengyao-lingoace hello, did you fix this error?

**Comment by binmakeswell** [comment]
We have updated a lot. This issue was closed due to inactivity. Thanks.
