### ISSUE TITLE
[BUG]: Use Teyvat but produce blur grid pictures

### ISSUE THREAD

**Issue by FrankieDong** [hpcaitech/ColossalAI#2461]
### 🐛 Describe the bug

I am use the default teyvat.yaml to train a simple model, only modify the data->image_transform->size from 512 to 256 because of my gpu devices.  and set nums_workers 0.

**Comment by FrankieDong** [comment]
![4ea24c57430fadf14c5e684ccc1442d](https://user-images.githubusercontent.com/107011475/211970527-ccca77b1-a38c-418e-8599-d82b5533d645.jpg)

**Comment by feifeibear** [comment]
Hello, how long did you train the model. Epoches? Iterations? Considering that train a diffusion model from scratch is very slow to converge.

**Comment by FrankieDong** [comment]
> Hello, how long did you train the model. Epoches? Iterations? Considering that train a diffusion model from scratch is very slow to converge.

I set epoch 10, around 10 hours to produce the last.ckpt

**Comment by yufengyao-lingoace** [comment]
This is because the code is stable diffusion 2.0, and it has no pre-trained model. So after a small epoch, it produces a picture with random noise.

**Comment by binmakeswell** [comment]
We have updated a lot. This issue was closed due to inactivity. Thanks.
