### ISSUE TITLE
[BUG]: from colossalai._C import fused_optim ImportError 

### ISSUE THREAD

**Issue by yufengyao-lingoace** [hpcaitech/ColossalAI#2470]
### 🐛 Describe the bug

/examples/images/dreambooth/ runs error as follows:

Using /home/ubuntu/.cache/torch_extensions/py37_cu117 as PyTorch extensions root...
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/colossalai/kernel/__init__.py", line 4, in <module>
    from colossalai._C import fused_optim
ImportError: /home/ubuntu/anaconda3/lib/python3.7/site-packages/colossalai/_C/fused_optim.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops19empty_memory_format4callEN3c108ArrayRefIlEENS2_8optionalINS2_10ScalarTypeEEENS5_INS2_6LayoutEEENS5_INS2_6DeviceEEENS5_IbEENS5_INS2_12MemoryFormatEEE

**Comment by feifeibear** [comment]
Did you install it from our official website.
If install from source, please check if your CUDA tookit version matches your torch and colossalai version.

**Comment by yufengyao-lingoace** [comment]
Yes, I just folows your official document:
![WX20230113-134634@2x](https://user-images.githubusercontent.com/92853025/212246493-bdc38dc8-5159-4336-b534-1f415a3a80ec.png)

**Comment by yufengyao-lingoace** [comment]
my cuda is 11.4

**Comment by haofanwang** [comment]
You can try with cuda 11.3

**Comment by weiyuann1** [comment]
> my cuda is 11.4

I met the same question. Have you salved it by changing cuda version?

**Comment by gouchangjiang** [comment]
you may solve this problem if you use a higher version of gcc. I solved the same sort of problem using gcc 7.3.0.

**Comment by binmakeswell** [comment]
> you may solve this problem if you use a higher version of gcc. I solved the same sort of problem using gcc 7.3.0.

Thanks for the advice. 
We have updated a lot. This issue was closed due to inactivity. 
If you have similar bugs, please [open a new issue](https://github.com/hpcaitech/ColossalAI/issues/new/choose).
Thanks.
