### ISSUE TITLE
[BUG]: How can i save checkpoint trained by the way of GeminiDDP

### ISSUE THREAD

**Issue by upwindflys** [hpcaitech/ColossalAI#2478]
### 🐛 Describe the bug

when running the model OPT,but i have no idea how to save the checkpoint.
I tried the code 
```python
model = GeminiDDP(model, device=get_current_device(), placement_policy=PLACEMENT_POLICY, pin_memory=True)
model_to_save = model.module if hasattr(model, 'module') else model
model_to_save.save_pretrained(output_dir)
```
output_dir's file is so small,about 300k,but the model is 16G,in the mean while, it can't be loaded by transformers's api.

**Comment by haofanwang** [comment]
add `model = get_static_torch_model(model)` before saving.

**Comment by feifeibear** [comment]
@haofanwang correct! `get_static_torch_model ` will return a torch model, you can do whatever you want on it.

@1SAA @FrankLeeeee we should add a chapter in our document on model saving and loading.

**Comment by upwindflys** [comment]
Thank you for the reply.
But I'm not sure whether this method ```model_to_save = model.module if hasattr(model, 'module') else model```  is  a way of ```get_static_torch_model ```? this method's checkpoint is only 170k.

**Comment by JThh** [comment]
No. Import the one below
`from colossalai.nn.parallel.utils import get_static_torch_model`
And add `model = get_static_torch_model(model)` before saving.

**Comment by binmakeswell** [comment]
We have updated a lot. This issue was closed due to inactivity. Thanks.
