### ISSUE TITLE
[BUG]: RuntimeError: The tensor has a non-zero number of elements, but its data is not allocated yet. Caffe2 uses a lazy allocation, so you will need to call mutable_data() or raw_mutable_data() to actually allocate memory.

### ISSUE THREAD

**Issue by mandoxzhang** [hpcaitech/ColossalAI#2487]
### 🐛 Describe the bug

With ColossalAI 0.2.0 and a single A100 GPU, I use  PLACEMENT_POLICY = 'cpu' , ColoInitContext, GeminiDDP to decorate the model through the OPT from the example. However, ` loss.backward()` reports the following error.

`RuntimeError: The tensor has a non-zero number of elements, but its data is not allocated yet. Caffe2 uses a lazy allocation, so you will need to call mutable_data() or raw_mutable_data() to actually allocate memory.`

![2023-01-16_11-05](https://user-images.githubusercontent.com/111039218/212635246-aec0c362-b819-4ee3-abde-5a1055310784.png)

### Environment

Pytorch: 1.11
Cuda: 11.7
ColossalAI: 0.2.0

**Comment by mandoxzhang** [comment]
Solved.

**Comment by tungdq212** [comment]
@mandoxzhang hello, how did you fix that?

**Comment by lijiaqijane** [comment]
@mandoxzhang  hi, could you share how you solve the problem?

**Comment by mandoxzhang** [comment]
> 
It's my fault, not ColossalAI.

**Comment by mandoxzhang** [comment]
It's my fault, not ColossalAI.
