### ISSUE TITLE
[BUG]: Can't find the file /config/server.sh in EnergonAI docker

### ISSUE THREAD

**Issue by jouw** [hpcaitech/ColossalAI#2489]
### 🐛 Describe the bug

I built the docker with Dockerfile of EnergonAI, then I execute the launch.sh, it tells me /config/server.sh doesn't exist.
Dockerfile:
<img width="1275" alt="image" src="https://user-images.githubusercontent.com/1312493/212840310-b0f87c19-9cc8-4521-8bc1-2af34f453ee3.png">

(opt) [worker@bj3-136-162-18-s1 docker]$ ./launch.sh
bash: /config/server.sh: No such file or directory

### Environment

CUDA=11.4
python=3.10.8

**Comment by feifeibear** [comment]
you have to map your local directory to docker with `-v` to do column mapping. For docker volumn mapping usage please refer

https://www.geeksforgeeks.org/mounting-a-volume-inside-docker-container/

**Comment by binmakeswell** [comment]
We have updated a lot. This issue was closed due to inactivity. Thanks.
