### ISSUE TITLE
[BUG]: Several bugs in examples/language/gpt/titans

### ISSUE THREAD

**Issue by gouchangjiang** [hpcaitech/ColossalAI#2493]
### 🐛 Describe the bug

Several small bug in the examples provided in directory language/gpt/titans:

1. the default option of argument '--use_dummy_dataset' in function main of file train_gpt.py should be set to False, and 'store_false', otherwise even if I set the environment variable DATA, and run the train_gpt.py without the option '--use_dummy_dataset', the training will use dummy data.
2. Please add the py file webtext, otherwise the train_gpt.py will complain that 'WebtextDataset cannot be imported from dataset.webtext'.
3. The throughput is 0, Loss is nan from epoch 1 to epoch 8, then it stalls. The total epoch is 10. I am using the config 'gpt2_small_zero3_pp1d.py'. Nothing modified. 4 Nodes equipped with 8 A100 each are provided. ColossalAI is launched with Slurm. PyTorch is 1.12.1 and CUDA is of version 11.3.  Two screeshot of out are provided:
<img width="1054" alt="image" src="https://user-images.githubusercontent.com/7204483/213075947-66650695-1949-45ad-b8d4-1896c2a385f6.png">
<img width="1054" alt="image" src="https://user-images.githubusercontent.com/7204483/213075984-17c4533d-a40d-4bf1-8889-1eb979b9aa2d.png">
The full output logs are [here](https://drive.google.com/file/d/1dSAeIqXzZv-9FIMdFUVeNDz9vJapU1ip/view?usp=sharing)

### Environment

PyTorch is 1.12.1 and CUDA is of version 11.3. Colossal-AI is built from source without CUDA pre-compiled kernel.

**Comment by feifeibear** [comment]
Thanks, I have fixed some of the bugs. However, using dummy dataset seems still not ready. I will see it in detail.

**Comment by feifeibear** [comment]
I have fixed the bug. @gouchangjiang can you pull the latest code and try again?

**Comment by gouchangjiang** [comment]
Thanks. It get stalls when using configuration gpt3_zero3_pp1d and dummy dataset on 4 nodes 36 GPUS in totoal.

**Comment by feifeibear** [comment]
Running GPT3 is not easy. Can you start with a smaller model first? For example, a 10B model?

**Comment by feifeibear** [comment]
Can we close this issue (if you run the default config successfully?) and start another one titled **How to Run GPT3 using Titans**?

**Comment by gouchangjiang** [comment]
Oh, sorry, the configuration is gpt2_small_zero3_pp1d provided in the directory config.

**Comment by feifeibear** [comment]
Never mind. Can you run it successfully on 1 node?

**Comment by gouchangjiang** [comment]
Unfortunately. It report a problem 'AssertionError: Expected the world size 2 to be equal to data parallel size (0) * pipeline parallel size (4) * tensor parallel size (2)' if I run it simply on a node by bash run.sh

**Comment by gouchangjiang** [comment]
Let me use 8 GPUs.

**Comment by feifeibear** [comment]
I guess you only use 1 GPU.

**Comment by gouchangjiang** [comment]
I forget that I was on my develop branch. I siwtched back to main. And run it with 8 GPUs. The same phenomenon happens: load layernorm kernel many many times infinitely

**Comment by gouchangjiang** [comment]
<img width="1055" alt="image" src="https://user-images.githubusercontent.com/7204483/213106644-387feb77-8962-438b-8c3a-d0274001a1c2.png">
Not stall, but like a inbound for/while loop

**Comment by gouchangjiang** [comment]
Oh, it works. Thanks we can close it.
