### ISSUE TITLE
Any checkpoint saving/loading tutorial provided?

### ISSUE THREAD

**Issue by kurisusnowdeng** [hpcaitech/ColossalAI#256]
### 📚 The doc issue

So far is there any tutorial that shows how to save/load a model in checkpoint?

**Comment by FrankLeeeee** [comment]
Good point, was considering adding this tutorial as someone mentioned in the discussion post as well. I will write a tutorial to cover this next week.

**Comment by FrankLeeeee** [comment]
I have assigned this issue to myself, will close this issue next week upon completion.

**Comment by feifeibear** [comment]
We are planning to provide this feature this week (28th May).

**Comment by binmakeswell** [comment]
https://github.com/hpcaitech/ColossalAI/tree/main/applications/Chat#how-to-saveload-checkpoint
This issue was closed due to inactivity. Thanks.
