### ISSUE TITLE
Do we have activation CPU offloading?

### ISSUE THREAD

**Issue by feifeibear** [hpcaitech/ColossalAI#257]
### Describe the feature

Similar to the [CPU_checkpointing](https://www.deepspeed.ai/docs/config-json/#activation-checkpointing) in deepspeed.
Some reference [deepspeed implementation](https://github.com/microsoft/DeepSpeed/blob/e4cf40d6172199f304cb006d9d22f9581b900c3a/deepspeed/runtime/activation_checkpointing/checkpointing.py)

**Comment by FrankLeeeee** [comment]
No, we currently do not support this feature, but can add this feature after zero implementation.

**Comment by feifeibear** [comment]
OK, I can help on this enhencement
