### ISSUE TITLE
a bit mistake

### ISSUE THREAD

**Issue by fermionsy** [hpcaitech/ColossalAI#26]
![image](https://user-images.githubusercontent.com/22900982/142170093-1952a389-8af5-4f5e-be19-74e189a7e50d.png)
the right git clone code should be 
`git clone https://github.com/hpcaitech/ColossalAI.git`

**Comment by fermionsy** [comment]
because we are not the contributor, cannot use the ssh clone

**Comment by FrankLeeeee** [comment]
> because we are not the contributor, cannot use the ssh clone

Yes, thanks for highlighting that, we will update the git clone command. If you have ssh key registered with your github account, you should be able to do ssh clone too, but https is surely more common.
