### ISSUE TITLE
[RFC] Activation CPU Offloading

### ISSUE THREAD

**Issue by feifeibear** [hpcaitech/ColossalAI#262]
### Describe the feature

Now, colossal-ai has gradient checkpointing, which recomputes activations during backward to save GPU memory. We can further offload the remaining activations in GPU to CPU memory. See #65 

We can let users open the feature in the config file just like this.

"activation_checkpointing": {
      "enable": True,
      "cpu_checkpointing": True,
 },

**Comment by Gy-Lu** [comment]
Hi, we have done it.
See #331 
and the config now like this
```python
model = dict(
    type=model_name,
    checkpoint=True,
    offload=True,
)
```
