### ISSUE TITLE
[FEATURE]: More meta information patch for GPT auto-parallel runtime

### ISSUE THREAD

**Issue by Cypher30** [hpcaitech/ColossalAI#2628]
### Describe the feature

In #2582, I requested a meta information patch for `torch.matmul()`, and this issue was resolved by #2584.

Here is a checklist for operations that needed to be patched before we could combine our SPMD solver and auto activation checkpoint solver on GPT

- [x] #2629
- [x] #2630
- [x] #2631
- [x] #2632
- [x] #2735
- [x] #2779
- [x] #2780
- [x] #2782
- [x] #2783
- [x] #2784
- [x] #2785
- [x] #2633
- [x] #2786
- [x] #2787
- [x] #2788
- [x] #2814
- [x] #2799
- [x] #2800
- [x] #2815

**Comment by binmakeswell** [comment]
Thanks for awsome work. This issue was closed due to inactivity. Thanks.
