### ISSUE TITLE
[BUG]: AttributeError: 'NoneType' object has no attribute 'pop'

### ISSUE THREAD

**Issue by winktool** [hpcaitech/ColossalAI#2654]
### 🐛 Describe the bug

When I train the model myself and load it, I get an error: ```AttributeError: 'NoneType' object has no attribute 'pop'```

### Environment

Ubuntu 22.04
3 Tesla P100 GPU
use ```https://github.com/AUTOMATIC1111/stable-diffusion-webui``` to load models.

**Comment by JThh** [comment]
Hi, what are the ColossalAI-relevant contents you used and we can help with?
