### ISSUE TITLE
[FEATURE]: Looking forward to T5 example contributors!

### ISSUE THREAD

**Issue by binmakeswell** [hpcaitech/ColossalAI#2667]
### Describe the feature

We have received multiple requests for the [T5](https://github.com/google-research/text-to-text-transfer-transformer) example. 
We are looking forward to PR contributions from the community due to limited manpower. 
Thank you very much.

**Comment by CatherineZhou** [comment]
Looking for T5  example please

**Comment by binmakeswell** [comment]
https://github.com/hpcaitech/ColossalAI/tree/main/examples/community
Welcome to contribute T5 community example.
This issue was closed due to inactivity. Thanks.
