### ISSUE TITLE
[BUG]: Difference between OPT example code

### ISSUE THREAD

**Issue by waterhorse1** [hpcaitech/ColossalAI#2685]
### 🐛 Describe the bug

Hi guys, I am new to colossal-AI. Currently, I am trying the OPT-1.3B model with 8 RTX3090. I find two example codes, one in /tutorial/opt/opt and the other one in /language/opt. I can successfully run the finetuning on the code in /language/opt while I meet OOM when using the code in /tutorial/opt/opt.  Basically, I change nothing but the model size and keep other variables the same. Does anyone know why?

**Comment by binmakeswell** [comment]
Hi @waterhorse1 Please check the note at the beginning of tutorial path.
https://github.com/hpcaitech/ColossalAI/tree/main/examples/tutorial#colossal-ai-tutorial-hands-on
You should refer to the /language/opt example for your application.
This issue was closed due to inactivity. Thanks.
