### ISSUE TITLE
[BUG]: chatgpt issue: cannot import name 'FusedAdamBuilder' from 'deepspeed.ops.op_builder.builder_names'

### ISSUE THREAD

**Issue by jouw** [hpcaitech/ColossalAI#2733]
### 🐛 Describe the bug

<img width="1279" alt="image" src="https://user-images.githubusercontent.com/1312493/219006185-f7f7d82f-810b-4c4f-b3c2-716386a7c993.png">

### Environment

colossalai                0.2.5                    pypi_0    pypi
deepspeed                 0.8.0                    pypi_0    pypi
chatgpt                   0.1.0                    pypi_0    pypi
pytorch                   1.13.1          py3.10_cuda11.7_cudnn8.5.0_0    pytorch
pytorch-cuda              11.7                 h67b0de4_1    pytorch
accelerate                0.16.0                   pypi_0    pypi

_No response_

**Comment by Fazziekey** [comment]
I think this problem is not about colossalAI, it is about accelerate and deepspeed.

**Comment by jouw** [comment]
> I think this problem is not about colossalAI, it is about accelerate and deepspeed.

I just downgrade deepspeed's version from 0.8.0 to 0.7.7, it works now.

pip install deepspeed==0.7.7
