### ISSUE TITLE
[BUG]: No module named 'colossalai._C.cpu_adam'

### ISSUE THREAD

**Issue by Yiran-Zhu** [hpcaitech/ColossalAI#2743]
### 🐛 Describe the bug

When I run the command `torchrun --standalone --nproc_per_node=2 train_prompts.py prompts.csv --strategy colossalai_gemini` in the `ColossalAI/applications/ChatGPT/examples` directory, an error occurs. 
`ModuleNotFoundError: No module named 'colossalai._C.cpu_adam'`

### Environment

`  File "train_prompts.py", line 115, in <module>
    main(args)
  File "train_prompts.py", line 50, in main
    actor_optim = HybridAdam(actor.parameters(), lr=5e-6)
  File "/path/anaconda3/envs/colossalai/lib/python3.7/site-packages/colossalai/nn/optimizer/hybrid_adam.py", line 82, in __init__
    cpu_optim = CPUAdamBuilder().load()
  File "/path/anaconda3/envs/colossalai/lib/python3.7/site-packages/colossalai/kernel/op_builder/builder.py", line 164, in load
    verbose=verbose)
  File "/path/anaconda3/envs/colossalai/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1296, in load
    keep_intermediates=keep_intermediates)
  File "/path/anaconda3/envs/colossalai/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1534, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/path/anaconda3/envs/colossalai/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1936, in _import_module_from_library
    module = importlib.util.module_from_spec(spec)
  File "<frozen importlib._bootstrap>", line 583, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1043, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: /path/.cache/colossalai/torch_extensions/torch1.13_cu11.7/cpu_adam.so: cannot open shared object file: No such file or directory
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 128965 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 1 (pid: 128966) of binary: /path/anaconda3/envs/colossalai/bin/python3.7`

**Comment by JThh** [comment]
You have to install the Colossal CUDA extension.
`CUDA_EXT=1 pip install colossalai`

**Comment by JThh** [comment]
Also checkout this [issue](https://github.com/hpcaitech/ColossalAI/issues/2731) and install apex beforehand.

**Comment by lht947590837** [comment]
> You have to install the Colossal CUDA extension. `CUDA_EXT=1 pip install colossalai`
I tried this, but it still shows the same error. 
"ModuleNotFoundError: No module named 'colossalai._C.cpu_adam'".
It should be a problem with installing the colossalai package. But I can't open https://release.colossalai.org now.

**Comment by FrankLeeeee** [comment]
Hi, can you provide your colossalai version?

**Comment by lht947590837** [comment]
colossalai==0.2.5

**Comment by FrankLeeeee** [comment]
I see. The error seems to be implied by the line `ImportError: /path/.cache/colossalai/torch_extensions/torch1.13_cu11.7/cpu_adam.so: cannot open shared object file: No such file or directory`. There are a few things to check:
1. which operating system are you using?
2. it seems we cannot resolve the path `~` to be your home directory, can you try to provide the output of `os.path.expanduser('~')`?

**Comment by FrankLeeeee** [comment]
The error suggests that Python resolves the '~' directory to be `/path`, does this path actually exist?

**Comment by lht947590837** [comment]
At first time, I downloaded colossalai by “pip install colossalai==0.1.12+torch1.12cu11.3 -f https://release.colossalai.org”, and no error is displayed. I want to try this download method again, but the link is no longer open.

**Comment by sourasis** [comment]
Same issue with cpu_adam and “pip install colossalai==0.1.12+torch1.12cu11.3 -f https://release.colossalai.org” is a 404 now.

**Comment by FrankLeeeee** [comment]
> Same issue with cpu_adam and “pip install colossalai==0.1.12+torch1.12cu11.3 -f [https://release.colossalai.org”](https://release.colossalai.org%E2%80%9D) is a 404 now.

@sourasis you can try installing with `pip install colossalai` directly.

**Comment by FrankLeeeee** [comment]
> At first time, I downloaded colossalai by “pip install colossalai==0.1.12+torch1.12cu11.3 -f [https://release.colossalai.org”](https://release.colossalai.org%E2%80%9D), and no error is displayed. I want to try this download method again, but the link is no longer open.

@lht947590837 this release has been removed from our own private pip source, we have moved to pypi so that you can use `pip install colossalai` instead of `pip install colossalai==0.1.12+torch1.12cu11.3 -f https://release.colossalai.org`.

**Comment by sourasis** [comment]
> > Same issue with cpu_adam and “pip install colossalai==0.1.12+torch1.12cu11.3 -f [https://release.colossalai.org”](https://release.colossalai.org%E2%80%9D) is a 404 now.
> 
> @sourasis you can try installing with `pip install colossalai` directly.

Hi, yes I did that. That worked. Thanks. But the cpu_adam error persists when I try to run gemini in gpt example. Please suggest a solution for this

**Comment by FrankLeeeee** [comment]
> > > Same issue with cpu_adam and “pip install colossalai==0.1.12+torch1.12cu11.3 -f [https://release.colossalai.org”](https://release.colossalai.org%E2%80%9D) is a 404 now.
> > 
> > 
> > @sourasis you can try installing with `pip install colossalai` directly.
> 
> @FrankLeeeee Hi, yes I did that. That worked. Thanks. But the cpu_adam error persists when I try to run gemini in gpt example. Please suggest a solution for this


Hi @sourasis , several users have met the same issue, may I which operating system are your using? Suspect that this is a windows issue.

**Comment by joan126** [comment]
met same error:    colossalai : 0.2.5

**Comment by FrankLeeeee** [comment]
> 

Noted, I am looking into this issue. Can you provide more information like pytorch version, cuda version, operating system and version, python version

**Comment by sourasis** [comment]
> > > > Same issue with cpu_adam and “pip install colossalai==0.1.12+torch1.12cu11.3 -f [https://release.colossalai.org”](https://release.colossalai.org%E2%80%9D) is a 404 now.
> > > 
> > > 
> > > @sourasis you can try installing with `pip install colossalai` directly.
> > 
> > 
> > @FrankLeeeee Hi, yes I did that. That worked. Thanks. But the cpu_adam error persists when I try to run gemini in gpt example. Please suggest a solution for this
> 
> Hi @sourasis , several users have met the same issue, may I which operating system are your using? Suspect that this is a windows issue.

@FrankLeeeee I am on Ubuntu 22.04. Here is the list of issues I can see on the trace

In file included from /home/sourasis/anaconda3/envs/venv_name/lib/python3.10/site-packages/colossalai/kernel/cuda_native/csrc/cpu_adam.cpp:22:
/home/sourasis/anaconda3/envs/venv_name/lib/python3.10/site-packages/colossalai/kernel/cuda_native/csrc/cpu_adam.h:24:10: fatal error: cublas_v2.h: No such file or directory
   24 | #include <cublas_v2.h>
compilation terminated.
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/sourasis/anaconda3/envs/venv_name/lib/python3.10/site-packages/colossalai/kernel/op_builder/builder.py", line 135, in load
    op_module = self.import_op()
  File "/home/sourasis/anaconda3/envs/venv_name/lib/python3.10/site-packages/colossalai/kernel/op_builder/builder.py", line 118, in import_op
    return importlib.import_module(self.prebuilt_import_path)
  File "/home/sourasis/anaconda3/envs/venv_name/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'colossalai._C.cpu_adam'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sourasis/anaconda3/envs/venv_name/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1808, in _run_ninja_build
    subprocess.run(
  File "/home/sourasis/anaconda3/envs/venv_name/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sourasis/machinelearning/colossal/ColossalAI/examples/language/gpt/gemini/./train_gpt_demo.py", line 353, in <module>
    main()
  File "/home/sourasis/machinelearning/colossal/ColossalAI/examples/language/gpt/gemini/./train_gpt_demo.py", line 255, in main
    optimizer = HybridAdam(model.parameters(), lr=1e-3)
  File "/home/sourasis/anaconda3/envs/venv_name/lib/python3.10/site-packages/colossalai/nn/optimizer/hybrid_adam.py", line 82, in __init__
    cpu_optim = CPUAdamBuilder().load()
  File "/home/sourasis/anaconda3/envs/venv_name/lib/python3.10/site-packages/colossalai/kernel/op_builder/builder.py", line 157, in load
    op_module = load(name=self.name,
  File "/home/sourasis/anaconda3/envs/venv_name/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1202, in load
    return _jit_compile(
  File "/home/sourasis/anaconda3/envs/venv_name/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1425, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/home/sourasis/anaconda3/envs/venv_name/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1537, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "/home/sourasis/anaconda3/envs/venv_name/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1824, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'cpu_adam'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 3610) of binary: /home/sourasis/anaconda3/envs/venv_name/bin/python
Traceback (most recent call last):
  File "/home/sourasis/anaconda3/envs/venv_name/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==1.12.0', 'console_scripts', 'torchrun')())
  File "/home/sourasis/anaconda3/envs/venv_name/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/home/sourasis/anaconda3/envs/venv_name/lib/python3.10/site-packages/torch/distributed/run.py", line 761, in main
    run(args)
  File "/home/sourasis/anaconda3/envs/venv_name/lib/python3.10/site-packages/torch/distributed/run.py", line 752, in run
    elastic_launch(
  File "/home/sourasis/anaconda3/envs/venv_name/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/sourasis/anaconda3/envs/venv_name/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
./train_gpt_demo.py FAILED
------------------------------------------------------------

**Comment by joan126** [comment]
> 



> > 
> 
> Hi @joan126 noted, I am looking into this issue. Can you provide more information like pytorch version, cuda version, operating system and version, python version

pytorch : 1.12.1
cuda:11.3
os: Linux version 5.4.217-1-1.e17.elrepo.x86_64
python: 3.7.12

**Comment by FrankLeeeee** [comment]
@sourasis you problem is related to your CUDA environment as it cannot find cublas_v2.h. Can you check if your CUDA is available in your system and CUDA_HOME is set? Normally, you can find CUDA in `/usr/local`.

**Comment by sourasis** [comment]
> @sourasis you problem is related to your CUDA environment as it cannot find cublas_v2.h. Can you check if your CUDA is available in your system and CUDA_HOME is set? Normally, you can find CUDA in `/usr/local`.

I have installed cudatoolkit using conda. Since if I install it separately, it gets removed when I install nvidia-driver-525. My CUDA_HOME is set as /home/sourasis/anaconda3/pkgs/cuda-nvcc-11.3.58-h2467b9f_0

when I do find ~/ -name cublas_v2.h I get the following result : 
/home/sourasis/machinelearning/venv-new/lib/python3.10/site-packages/nvidia/cublas/include/cublas_v2.h
/home/sourasis/machinelearning/venv/lib/python3.10/site-packages/nvidia/cublas/include/cublas_v2.h

Should I add /home/sourasis/machinelearning/venv-new/lib/python3.10/site-packages/nvidia/ as well to my CUDA_HOME ?

**Comment by joan126** [comment]
upgrade gcc version from 4.8.5 to 9.5.0  fix this issue, but met another issue  " AttributeError : module 'math' has not attribute prod "

**Comment by FrankLeeeee** [comment]
> upgrade gcc version from 4.8.5 to 9.5.0 fix this issue, but met another issue " AttributeError : module 'math' has not attribute prod "

Great. The math issue is due to the Python version, try to use Python 3.8 instead with `conda create -n <env-name> python=3.8`

**Comment by joan126** [comment]
great...

**Comment by binmakeswell** [comment]
> > upgrade gcc version from 4.8.5 to 9.5.0 fix this issue, but met another issue " AttributeError : module 'math' has not attribute prod "
> 
> Great. The math issue is due to the Python version, try to use Python 3.8 instead with `conda create -n <env-name> python=3.8`

@joan126 #2837 has fixed the math issue. Thanks.

**Comment by yangjianxin1** [comment]
> upgrade gcc version from 4.8.5 to 9.5.0 fix this issue, but met another issue " AttributeError : module 'math' has not attribute prod "

My gcc version is 9.4.0,  i meet the same problem, do I have to update gcc to 9.5.0?

**Comment by secsilm** [comment]
> 

Could you please explain on this a bit more? Is there a big difference?

**Comment by secsilm** [comment]
> > upgrade gcc version from 4.8.5 to 9.5.0 fix this issue, but met another issue " AttributeError : module 'math' has not attribute prod "
> 
> Great. The math issue is due to the Python version, try to use Python 3.8 instead with `conda create -n <env-name> python=3.8`

Could you please explain on this a bit more? Is there a big difference?

**Comment by FrankLeeeee** [comment]
> > > upgrade gcc version from 4.8.5 to 9.5.0 fix this issue, but met another issue " AttributeError : module 'math' has not attribute prod "
> > 
> > 
> > Great. The math issue is due to the Python version, try to use Python 3.8 instead with `conda create -n <env-name> python=3.8`
> 
> Could you please explain on this a bit more? Is there a big difference?

You can check it out #2837 @secsilm

**Comment by secsilm** [comment]
> > > > upgrade gcc version from 4.8.5 to 9.5.0 fix this issue, but met another issue " AttributeError : module 'math' has not attribute prod "
> > > 
> > > 
> > > Great. The math issue is due to the Python version, try to use Python 3.8 instead with `conda create -n <env-name> python=3.8`
> > 
> > 
> > Could you please explain on this a bit more? Is there a big difference?
> 
> You can check it out #2837 @secsilm

Thanks for your quick reply. OK I got it.

**Comment by joan126** [comment]
when run examples/gpt/titans/run.sh  . I met a new error "no module named colossalai._C.layernorm error " with GCC 9.5.0 version.  could you help to see it?

**Comment by sourasis** [comment]
> @sourasis you problem is related to your CUDA environment as it cannot find cublas_v2.h. Can you check if your CUDA is available in your system and CUDA_HOME is set? Normally, you can find CUDA in `/usr/local`.

@FrankLeeeee Issue was when I tried to install nvidia driver 525 it removed cuda. So to counter that I used conda to install cuda. But this installation didnt bring Cublas along with it. My CUDA_HOME is set to this conda installation of Cuda. 

I have now installed nvidia-cublas-cu11 separately in conda environment and I can see that the cublas_v2.h is file there but inside a separate directory from the CUDA_HOME. if I can put this directory path as well as -isystem in "build.ninja" (/.cache/colossalai/torch_extensions/torch1.12_cu11.3/build.ninja) then it can work. But I can't find the file which creates build.ninja in runtime. 

Can you please tell me which file is creating build.ninja in runtime so that I can plug the cublas/inlcude directory to it as well?

**Comment by yangjianxin1** [comment]
> 
I have the same problem there is no cublas_v2.h file in mny cuda diretory, I copy the file to my cuda directory, and It works.

**Comment by siriluo2012** [comment]
I have the same problem. Following is my conda list:

_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
bcrypt                    4.0.1                    pypi_0    pypi
binutils_impl_linux-64    2.40                 hf600244_0    conda-forge
blas                      1.0                         mkl
brotlipy                  0.7.0           py310h7f8727e_1002
bzip2                     1.0.8                h7b6447c_0
ca-certificates           2023.01.10           h06a4308_0
certifi                   2022.12.7       py310h06a4308_0
cffi                      1.15.1          py310h5eee18b_3
cfgv                      3.3.1                    pypi_0    pypi
charset-normalizer        2.0.4              pyhd3eb1b0_0
click                     8.1.3                    pypi_0    pypi
colossalai                0.2.8                    pypi_0    pypi
contexttimer              0.3.3                    pypi_0    pypi
cryptography              39.0.1          py310h9ce1e76_0
cuda-cccl                 12.1.55                       0    nvidia
cuda-command-line-tools   11.8.0                        0    nvidia
cuda-compiler             12.1.0                        0    nvidia
cuda-cudart               11.8.89                       0    nvidia
cuda-cuobjdump            12.1.55                       0    nvidia
cuda-cupti                11.8.87                       0    nvidia
cuda-cuxxfilt             12.1.55                       0    nvidia
cuda-documentation        12.1.55                       0    nvidia
cuda-driver-dev           12.1.55                       0    nvidia
cuda-gdb                  12.1.55                       0    nvidia
cuda-libraries            11.8.0                        0    nvidia
cuda-libraries-dev        11.3.0               h3b286be_0    nvidia
cuda-memcheck             11.8.86                       0    nvidia
cuda-nsight               12.1.55                       0    nvidia
cuda-nsight-compute       12.1.0                        0    nvidia
cuda-nvcc                 12.1.66                       0    nvidia
cuda-nvdisasm             12.1.55                       0    nvidia
cuda-nvml-dev             12.1.55                       0    nvidia
cuda-nvprof               12.1.55                       0    nvidia
cuda-nvprune              12.1.55                       0    nvidia
cuda-nvrtc                11.8.89                       0    nvidia
cuda-nvtx                 11.8.86                       0    nvidia
cuda-nvvp                 12.1.55                       0    nvidia
cuda-opencl               12.1.56                       0    nvidia
cuda-opencl-dev           12.1.56                       0    nvidia
cuda-profiler-api         12.1.55                       0    nvidia
cuda-runtime              11.8.0                        0    nvidia
cuda-samples              11.6.101             h8efea70_0    nvidia
cuda-sanitizer-api        12.1.55                       0    nvidia
cuda-thrust               11.4.43              h00096a5_0    nvidia
cuda-toolkit              11.3.0               h3b286be_0    nvidia
cuda-tools                11.3.0               h3b286be_0    nvidia
cuda-visual-tools         11.3.0               h3b286be_0    nvidia
distlib                   0.3.6                    pypi_0    pypi
fabric                    3.0.0                    pypi_0    pypi
ffmpeg                    4.3                  hf484d3e_0    pytorch
filelock                  3.9.0           py310h06a4308_0
flit-core                 3.8.0           py310h06a4308_0
freetype                  2.12.1               h4a9f257_0
gcc                       12.2.0              h26027b1_12    conda-forge
gcc_impl_linux-64         12.2.0              hcc96c02_19    conda-forge
gds-tools                 1.6.0.25                      0    nvidia
giflib                    5.2.1                h5eee18b_3
gmp                       6.2.1                h295c915_3
gmpy2                     2.1.2           py310heeb90bb_0
gnutls                    3.6.15               he1e5248_0
huggingface-hub           0.13.4                   pypi_0    pypi
identify                  2.5.22                   pypi_0    pypi
idna                      3.4             py310h06a4308_0
intel-openmp              2021.4.0          h06a4308_3561
invoke                    2.0.0                    pypi_0    pypi
jinja2                    3.1.2           py310h06a4308_0
jpeg                      9e                   h5eee18b_1
kernel-headers_linux-64   2.6.32              he073ed8_15    conda-forge
lame                      3.100                h7b6447c_0
lcms2                     2.12                 h3be6417_0
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
lerc                      3.0                  h295c915_0
libcublas                 11.11.3.6                     0    nvidia
libcufft                  10.9.0.58                     0    nvidia
libcufile                 1.6.0.25                      0    nvidia
libcufile-dev             1.6.0.25                      0    nvidia
libcufile-static          1.6.0.25                      0    nvidia
libcurand                 10.3.2.56                     0    nvidia
libcurand-dev             10.3.2.56                     0    nvidia
libcurand-static          10.3.2.56                     0    nvidia
libcusolver               11.4.1.48                     0    nvidia
libcusparse               11.7.5.86                     0    nvidia
libdeflate                1.17                 h5eee18b_0
libffi                    3.4.2                h6a678d5_6
libgcc-devel_linux-64     12.2.0              h3b97bd3_19    conda-forge
libgcc-ng                 12.2.0              h65d4601_19    conda-forge
libgomp                   12.2.0              h65d4601_19    conda-forge
libiconv                  1.16                 h7f8727e_2
libidn2                   2.3.2                h7f8727e_0
libnpp                    11.8.0.86                     0    nvidia
libnvjitlink              12.1.55                       0    nvidia
libnvjitlink-dev          12.1.55                       0    nvidia
libnvjpeg                 11.9.0.86                     0    nvidia
libnvvm-samples           12.1.55                       0    nvidia
libpng                    1.6.39               h5eee18b_0
libsanitizer              12.2.0              h46fd767_19    conda-forge
libstdcxx-ng              12.2.0              h46fd767_19    conda-forge
libtasn1                  4.19.0               h5eee18b_0
libtiff                   4.5.0                h6a678d5_2
libunistring              0.9.10               h27cfd23_0
libuuid                   1.41.5               h5eee18b_0
libwebp                   1.2.4                h11a3e52_1
libwebp-base              1.2.4                h5eee18b_1
lz4-c                     1.9.4                h6a678d5_0
markdown-it-py            2.2.0                    pypi_0    pypi
markupsafe                2.1.1           py310h7f8727e_0
mdurl                     0.1.2                    pypi_0    pypi
mkl                       2021.4.0           h06a4308_640
mkl-service               2.4.0           py310h7f8727e_0
mkl_fft                   1.3.1           py310hd6ae3a3_0
mkl_random                1.2.2           py310h00e6091_0
mpc                       1.1.0                h10f8cd9_1
mpfr                      4.0.2                hb69a4c5_1
mpmath                    1.2.1                    pypi_0    pypi
ncurses                   6.4                  h6a678d5_0
nettle                    3.7.3                hbbd107a_1
networkx                  2.8.4           py310h06a4308_1
ninja                     1.11.1                   pypi_0    pypi
nodeenv                   1.7.0                    pypi_0    pypi
nsight-compute            2023.1.0.15                   0    nvidia
numpy                     1.23.5          py310hd5efca6_0
numpy-base                1.23.5          py310h8e6c178_0
openh264                  2.1.1                h4ff587b_0
openssl                   1.1.1t               h7f8727e_0
packaging                 23.0                     pypi_0    pypi
paramiko                  3.1.0                    pypi_0    pypi
pillow                    9.4.0           py310h6a678d5_0
pip                       23.0.1          py310h06a4308_0
platformdirs              3.2.0                    pypi_0    pypi
pre-commit                3.2.2                    pypi_0    pypi
psutil                    5.9.4                    pypi_0    pypi
pycparser                 2.21               pyhd3eb1b0_0
pygments                  2.14.0                   pypi_0    pypi
pynacl                    1.5.0                    pypi_0    pypi
pyopenssl                 23.0.0          py310h06a4308_0
pysocks                   1.7.1           py310h06a4308_0
python                    3.10.10              h7a1cb2a_2
pytorch                   2.0.0           py3.10_cuda11.8_cudnn8.7.0_0    pytorch
pytorch-cuda              11.8                 h7e8668a_3    pytorch
pytorch-mutex             1.0                        cuda    pytorch
pyyaml                    6.0                      pypi_0    pypi
readline                  8.2                  h5eee18b_0
regex                     2023.3.23                pypi_0    pypi
requests                  2.28.1          py310h06a4308_1
rich                      13.3.3                   pypi_0    pypi
safetensors               0.3.0                    pypi_0    pypi
setuptools                65.6.3          py310h06a4308_0
six                       1.16.0             pyhd3eb1b0_1
sqlite                    3.41.1               h5eee18b_0
sympy                     1.11.1          py310h06a4308_0
sysroot_linux-64          2.12                he073ed8_15    conda-forge
tk                        8.6.12               h1ccaba5_0
tokenizers                0.13.3                   pypi_0    pypi
torchaudio                2.0.0               py310_cu118    pytorch
torchtriton               2.0.0                     py310    pytorch
torchvision               0.15.0              py310_cu118    pytorch
tqdm                      4.65.0                   pypi_0    pypi
transformers              4.27.4                   pypi_0    pypi
typing_extensions         4.4.0           py310h06a4308_0
tzdata                    2023c                h04d1e81_0
urllib3                   1.26.15         py310h06a4308_0
virtualenv                20.21.0                  pypi_0    pypi
wheel                     0.38.4          py310h06a4308_0
xz                        5.2.10               h5eee18b_1
zlib                      1.2.13               h5eee18b_0
zstd                      1.5.4                hc292b87_0

**Comment by binmakeswell** [comment]
Hi @Yiran-Zhu @lht947590837 @sourasis @joan126 @secsilm @yangjianxin1 @secsilm  The possible reason is GCC version is too low, or env is not compatible.
Please check https://github.com/hpcaitech/ColossalAI#installation We have updated a lot. Thanks.
