### ISSUE TITLE
<img width="1268" alt="c56c4ea7-c449-40ba-8b53-84d6cb9e647c" src="https://user-images.githubusercontent.com/61670638/218991858-16733817-9236-4534-b994-7f63aed2dcf7.png">

### ISSUE THREAD

**Issue by genius0182** [hpcaitech/ColossalAI#2745]
<img width="1268" alt="c56c4ea7-c449-40ba-8b53-84d6cb9e647c" src="https://user-images.githubusercontent.com/61670638/218991858-16733817-9236-4534-b994-7f63aed2dcf7.png">
Clear error message or doc to remind user 'pip install .'
_Originally posted by @binmakeswell in https://github.com/hpcaitech/ColossalAI/issues/2722#issuecomment-1431030534_

```
   cd applications/Chatgpt
   pip install .
```

**Comment by FrankLeeeee** [comment]
Awesome, will update soon.
