### ISSUE TITLE
Training model save problem

### ISSUE THREAD

**Issue by xcxhy** [hpcaitech/ColossalAI#2746]
### Describe the feature

Hello, I use the ChatGPT/examples/train_dummpy.py to train GPT2, and the training is successful, but the trained model cannot be found. Can you write a document to explain the problems of saving the model and using the training model?

**Comment by terminator123** [comment]
i met the same problem too

**Comment by ht-zhou** [comment]
Thanks for your feedback, but I have to remind you that train_dummy.py using random input, and you may not find any improvement after training.
Anyway,  we'll add some guidance and demo to help save and inference the model.

**Comment by NLP-ZY** [comment]
@ht-zhou I have read source code, maybe train_prompts.py also not save the checkpoint. please add more demo help us to run it.

**Comment by xcxhy** [comment]
> 

Agree.  I notice is that neither train_dummy nor ptrain_prompts save checkpoint.

**Comment by xcxhy** [comment]
@NLP-ZY Agree. I notice is that neither train_dumm.py nor train_prompts.py save the checkpoint.

**Comment by YeHaijia** [comment]
same

**Comment by lajiyuan** [comment]
same

**Comment by Syno8** [comment]
I mkdir first as follows and will save the model correctly.
`os.makedirs(os.path.dirname(args.save_path), exist_ok=True)`

**Comment by A-biao96** [comment]
> i met the same problem too

Hello, did you solve the problem?

**Comment by A-biao96** [comment]
> ### Describe the feature
> Hello, I use the ChatGPT/examples/train_dummpy.py to train GPT2, and the training is successful, but the trained model cannot be found. Can you write a document to explain the problems of saving the model and using the training model?

Hello, did you solve the problem?

**Comment by FrankLeeeee** [comment]
This issue shall be fixed in #2846 once it is merged.

**Comment by A-biao96** [comment]
> > i met the same problem too
> 
> Hello, did you solve the problem?
> This issue shall be fixed in #2846 once it is merged.

Thanks, I got it.
