### ISSUE TITLE
[BUG]: torch.distributed.elastic.rendezvous.dynamic_rendezvous

### ISSUE THREAD

**Issue by hujunchao** [hpcaitech/ColossalAI#2748]
### 🐛 Describe the bug

When i use 2 nodes(16gpus) to do roberta/pretraining，i meet this error, can you help me?

### Environment

cuda 11.6
python 3.10
pytorch 1.12.1

**Comment by hujunchao** [comment]
WARNING:torch.distributed.elastic.rendezvous.dynamic_rendezvous:The node 'xxxxxx' has failed to send a keep-alive heartbeat to the rendezvous 'colossalai-default-job' due to an error of type RendezvousConnectionError.

**Comment by xyease** [comment]
i got the same problem, have you solved it now?

> WARNING:torch.distributed.elastic.rendezvous.dynamic_rendezvous:The node 'xxxxxx' has failed to send a keep-alive heartbeat to the rendezvous 'colossalai-default-job' due to an error of type RendezvousConnectionError.

**Comment by JThh** [comment]
Hi @xyease , what was your command?
