### ISSUE TITLE
[BUG]: No matching distribution found for transformers>=4.20.1 (from chatgpt==0.1.0)

### ISSUE THREAD

**Issue by clm971910** [hpcaitech/ColossalAI#2752]
### 🐛 Describe the bug

 https://pypi.org/simple

Could not find a version that satisfies the requirement transformers>=4.20.1 (from chatgpt==0.1.0) (from versions: 0.1, 2.0.0, 2.1.0, 2.1.1, 2.2.0, 2.2.1, 2.2.2, 2.3.0, 2.4.0, 2.4.1, 2.5.0, 2.5.1, 2.6.0, 2.7.0, 2.8.0, 2.9.0, 2.9.1, 2.10.0, 2.11.0, 3.0.0, 3.0.1, 3.0.2, 3.1.0, 3.2.0, 3.3.0, 3.3.1, 3.4.0, 3.5.0, 3.5.1, 4.0.0rc1, 4.0.0, 4.0.1, 4.1.0, 4.1.1, 4.2.0, 4.2.1, 4.2.2, 4.3.0rc1, 4.3.0, 4.3.1, 4.3.2, 4.3.3, 4.4.0, 4.4.1, 4.4.2, 4.5.0, 4.5.1, 4.6.0, 4.6.1, 4.7.0, 4.8.0, 4.8.1, 4.8.2, 4.9.0, 4.9.1, 4.9.2, 4.10.0, 4.10.1, 4.10.2, 4.10.3, 4.11.0, 4.11.1, 4.11.2, 4.11.3, 4.12.0, 4.12.1, 4.12.2, 4.12.3, 4.12.4, 4.12.5, 4.13.0, 4.14.0, 4.14.1, 4.15.0, 4.16.0, 4.16.1, 4.16.2, 4.17.0, 4.18.0)

**Comment by ht-zhou** [comment]
suggest to use
```
pip install transformers --upgrade
```
to update your transformers

**Comment by FrankLeeeee** [comment]
Can you give your Python version, pip version and your operating system?

**Comment by clm971910** [comment]
Python 3.7.3
pip 22.3.1 from /home/yewang/miniconda3/envs/chatgpt/lib/python3.7/site-packages/pip (python 3.7)
 4.9.168-016.ali3000.alios7.x86_64 #1 SMP Fri Jun 21 22:41:58 CST 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by binmakeswell** [comment]
Hi @clm971910 Could you manually install the transformers?
https://github.com/huggingface/transformers#installation
This should be caused by your basic environment, not by Colossal-AI.
Perhaps you can try docker https://github.com/hpcaitech/ColossalAI#Use-Docker
