### ISSUE TITLE
How to control the number of sequences returned by Colossal generation api? 

### ISSUE THREAD

**Issue by ma787639046** [hpcaitech/ColossalAI#2753]
I'm deploying Colossal for the generation with a GPT-like model. I'm using curl to get the returned generation results. I notice that Colossal only returns one sequence by default. How can I control the number of return sequences?
For example, I can use `num_return_sequences` to control the returned numbers in Huggingface API. I'm wondering if Colossal has a similar parameter.
Thanks a lot.

**Comment by Camille7777** [comment]
hi, @ma787639046 could you please provide more information about how you deploying Colossal for your generation? 
If you are implementing language model like Colossal Chat, you can refer to [here](https://github.com/hpcaitech/ColossalAI/tree/main/applications/Chat/inference) for our latest inference method.

**Comment by Camille7777** [comment]
Hi, @ma787639046  I'll close this issue for now.
If you have further questions/suggestions, welcome to keep track with our latest project and open a new issue!
Thanks!
