### ISSUE TITLE
[FEATURE]: Is Chatgpt support Tensor Parallelism or Pipeline Parallelism

### ISSUE THREAD

**Issue by nicknign** [hpcaitech/ColossalAI#2756]
### Describe the feature

Hello, great work for reproduced the PPO training! I found the code is not support Tensor Parallelism or Pipeline Parallelism yet, is there any plan to add these parallelism features ?

**Comment by binmakeswell** [comment]
Hi @nicknign Yes, they are on our TODO list. Current ZeRO and Gemini is a convenient way because you needn't change model and enough for most cases. For complicated parallelism with extremely large scale models, we will release the solution later. 
This issue was closed due to inactivity. Thanks.
