### ISSUE TITLE
[BUG]: site-packages/transformers/models/gpt2/modeling_gpt2.py", line 181, in _attn     attn_weights = torch.matmul(query, key.transpose(-1, -2)) RuntimeError: CUDA error: CUBLAS_STATUS_NOT_SUPPORTED when calling `cublasSgemmStridedBatched( handle, opa, opb, m, n, k, &alpha, a, lda, stridea, b, ldb, strideb, &beta, c, ldc, stridec, num_batches)`

### ISSUE THREAD

**Issue by sxk000** [hpcaitech/ColossalAI#2759]
### 🐛 Describe the bug

when i run  ChatGPT  ： python train_prompts.py prompts.csv --strategy naive
get ：
site-packages/transformers/models/gpt2/modeling_gpt2.py", line 181, in _attn
    attn_weights = torch.matmul(query, key.transpose(-1, -2))
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_SUPPORTED when calling `cublasSgemmStridedBatched( handle, opa, opb, m, n, k, &alpha, a, lda, stridea, b, ldb, strideb, &beta, c, ldc, stridec, num_batches)`

### Environment

python=3.10.9
torch=1.13.1

aiohttp                  3.8.4
aiosignal                1.3.1
async-timeout            4.0.2
attrs                    22.2.0
bcrypt                   4.0.1
certifi                  2022.12.7
cffi                     1.15.1
cfgv                     3.3.1
charset-normalizer       3.0.1
chatgpt                  0.1.0
click                    8.1.3
colossalai               0.2.5
contexttimer             0.3.3
cryptography             39.0.1
datasets                 2.9.0
dill                     0.3.6
distlib                  0.3.6
fabric                   3.0.0
filelock                 3.9.0
frozenlist               1.3.3
fsspec                   2023.1.0
huggingface-hub          0.12.0
identify                 2.5.18
idna                     3.4
invoke                   2.0.0
loralib                  0.1.1
markdown-it-py           2.1.0
mdurl                    0.1.2
multidict                6.0.4
multiprocess             0.70.14
ninja                    1.11.1
nodeenv                  1.7.0
numpy                    1.24.2
nvidia-cublas-cu11       11.10.3.66
nvidia-cuda-nvrtc-cu11   11.7.99
nvidia-cuda-runtime-cu11 11.7.99
nvidia-cudnn-cu11        8.5.0.96
packaging                23.0
pandas                   1.5.3
paramiko                 3.0.0
pip                      22.3.1
platformdirs             3.0.0
pre-commit               3.0.4
psutil                   5.9.4
pyarrow                  11.0.0
pycparser                2.21
Pygments                 2.14.0
PyNaCl                   1.5.0
python-dateutil          2.8.2
pytz                     2022.7.1
PyYAML                   6.0
regex                    2022.10.31
requests                 2.28.2
responses                0.18.0
rich                     13.3.1
setuptools               65.6.3
six                      1.16.0
tokenizers               0.13.2
torch                    1.13.1
tqdm                     4.64.1
transformers             4.26.1
typing_extensions        4.5.0
urllib3                  1.26.14
virtualenv               20.19.0
wheel                    0.37.1
xxhash                   3.2.0
yarl                     1.8.2

**Comment by FrankLeeeee** [comment]
Can you provide your system information? e.g. CUDA/CUDNN/OS

**Comment by sxk000** [comment]
conda 4.14.0

cudnn
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Fri_Dec_17_18:16:03_PST_2021
Cuda compilation tools, release 11.6, V11.6.55
Build cuda_11.6.r11.6/compiler.30794723_0

os
Linux version 3.10.0-693.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-16) (GCC) ) #1 SMP Tue Aug 22 21:09:27 UTC 2017

**Comment by FrankLeeeee** [comment]
Can you provide the output?

```python
import torch
print(torch.version.cuda)
```

**Comment by sxk000** [comment]
11.7

**Comment by FrankLeeeee** [comment]
Ok, that's why. This line `Cuda compilation tools, release 11.6, V11.6.55` means that your CUDA version is 11.6, but the CUDA version required by torch is 11.7 as given by `torch.version.cuda`. Try to install PyTorch with the correct version. 
<img width="850" alt="torch" src="https://user-images.githubusercontent.com/31818963/219332926-6a7b7a48-83af-42f1-b68a-54656d48b34e.png">

**Comment by sxk000** [comment]
ok ,thanks very much

**Comment by FrankLeeeee** [comment]
I  will close this issue now, please create another one if you encounter any more issues.
