### ISSUE TITLE
[BUG]: Couldn't install colossalai

### ISSUE THREAD

**Issue by natureXD** [hpcaitech/ColossalAI#2761]
### 🐛 Describe the bug

Command：install colossalai==0.2.0+torch1.12cu11.3 -f https://release.colossalai.org

Traceback Infos：

Traceback (most recent call last):
  File "D:\Projects\DiffusionAlg\ColossalAI-main-diffusion\prepare_env.py", line 90, in <module>
    prepare_environment()
  File "D:\Projects\DiffusionAlg\ColossalAI-main-diffusion\prepare_env.py", line 86, in prepare_environment
    run_pip(f"install colossalai==0.2.0+torch1.12cu11.3 -f https://release.colossalai.org", "colossalai")
  File "D:\Projects\DiffusionAlg\ColossalAI-main-diffusion\prepare_env.py", line 48, in run_pip
    return run(f'"{python}" -m pip {args} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}")
  File "D:\Projects\DiffusionAlg\ColossalAI-main-diffusion\prepare_env.py", line 41, in run
    raise RuntimeError(message)
RuntimeError: Couldn't install colossalai.
                        Command: "D:\Projects\DiffusionAlg\ColossalAI-main-diffusion\venv\Scripts\python.exe" -m pip install colossalai==0.2.0+torch1.12cu11.3 -f https://release.colossalai.org --prefer-binary
                        Error code: 1
                        stdout: Looking in links: https://release.colossalai.org
Could not fetch URL https://release.colossalai.org: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='release.colossalai.org', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)'))) - skipping

### Environment

torch==1.13.1+cu117
python: 3.10.10

**Comment by FrankLeeeee** [comment]
Please use `pip install colossalai` directly. We will update our README accordingly as we have removed our own pip source.

**Comment by natureXD** [comment]
> Please use `pip install colossalai` directly. We will update our README accordingly as we have removed our own pip source.

OK, it works, thank you very much.
