### ISSUE TITLE
[BUG]: I can not run this project on Windows11

### ISSUE THREAD

**Issue by shendl1978** [hpcaitech/ColossalAI#2763]
### 🐛 Describe the bug

Hi,
    I can not run this project on Windows11.
    How do you run this project?

    Does this project only support Linux?

### Environment

Colossal-AI version: 0.2.5
PyTorch version: 1.12.0
CUDA version: 12.0
CUDA version required by PyTorch: 11.3

**Comment by FrankLeeeee** [comment]
Hi, you can try WSL on windows. This project is only supported on Linux for now.

**Comment by FrankLeeeee** [comment]
I will close this issue for now. Don't hesitate to let us know if there is any more issue.
