### ISSUE TITLE
[BUG]: I can not run  the demo of auto_parallel  on Windows11

### ISSUE THREAD

**Issue by shendl1978** [hpcaitech/ColossalAI#2765]
### 🐛 Describe the bug

Hi,
     I can not run  the demo of auto_parallel  on Windows11.
     The following is the output of my Computer.
   The reason seems to be because of the use of shell instructions in the code.
But Windows does not support shell instructions.

ColossalAI\examples\tutorial\auto_parallel> colossalai run --nproc_per_node 1 auto_parallel_with_resnet.py
'export' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
Error: failed to run torchrun --nproc_per_node=1 --nnodes=1 --node_rank=0 --rdzv_backend=c10d --rdzv_endpoint=127.0.0.1:29500 --rdzv_id=colossalai-default-job auto_parallel_with_resnet.py
 on 127.0.0.1, is localhost: True, exception: Encountered a bad command exit code!

Command: 'cd C:\\5workspace\\5gitWorkspace\\ColossalAI\\examples\\tutorial\\auto_parallel && export __INTELLIJ_COMMAND_HISTFILE__="C:\\Users\\sdlwo\\AppData\\Local\\JetBrains\\PyCharmCE20
21.2\\terminal\\history\\ColossalAI-history1" PROCESSOR_IDENTIFIER="Intel64 Family 6 Model 165 Stepping 2, GenuineIntel" COMMONPROGRAMFILES="C:\\Program Files\\Common Files" APPDATA="C:\\
Users\\sdlwo\\AppData\\Roaming" LOCALAPPDATA="C:\\Users\\sdlwo\\AppData\\Local" COMMONPROGRAMFILES(X86)="C:\\Program Files (x86)\\Common Files" PROGRAMDATA="C:\\ProgramData" CUDA_PATH="C:
\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.0" COMPUTERNAME="SDLWORKERU" ONEDRIVECONSUMER="C:\\Users\\sdlwo\\OneDrive" SYSTEMDRIVE="C:" USERDOMAIN="SDLWORKERU" CUDA_PATH_V12_
0="C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.0" ONEDRIVE="C:\\Users\\sdlwo\\OneDrive" TMP="C:\\Users\\sdlwo\\AppData\\Local\\Temp" SYSTEMROOT="C:\\WINDOWS" HOMEPATH="\\Us
ers\\sdlwo" TEMP="C:\\Users\\sdlwo\\AppData\\Local\\Temp" TERMINAL_EMULATOR="JetBrains-JediTerm" WINDIR="C:\\WINDOWS" LOGONSERVER="\\\\SDLWORKERU" SESSIONNAME="Console" PROGRAMFILES="C:\\
Program Files" HOMEDRIVE="C:" DRIVERDATA="C:\\Windows\\System32\\Drivers\\DriverData" PUBLIC="C:\\Users\\Public" USERDOMAIN_ROAMINGPROFILE="SDLWORKERU" PYCHARM COMMUNITY EDITION="C:\\Prog
ram Files\\JetBrains\\PyCharm Community Edition 2021.2.3\\bin;" PATH="C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.0\\bin;C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CU
DA\\v12.0\\libnvvp;C:\\Program Files\\Microsoft\\jdk-11.0.12.7-hotspot\\bin;C:\\Program Files\\Common Files\\Oracle\\Java\\javapath;C:\\ProgramData\\Anaconda3;C:\\ProgramData\\Anaconda3\\
Library\\mingw-w64\\bin;C:\\ProgramData\\Anaconda3\\Library\\usr\\bin;C:\\ProgramData\\Anaconda3\\Library\\bin;C:\\ProgramData\\Anaconda3\\Scripts;C:\\Windows\\system32;C:\\Windows;C:\\Wi
ndows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Program Files\\NVIDI
A Corporation\\NVIDIA NvDLISR;C:\\Program Files\\dotnet\\;C:\\Program Files\\Git\\cmd;C:\\Program Files\\Docker\\Docker\\resources\\bin;C:\\ProgramData\\DockerDesktop\\version-bin;C:\\Pro
grams\\apache-maven-3.8.6\\bin;C:\\Program Files\\Go\\bin;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\Syste
m32\\OpenSSH\\;C:\\Program Files\\NVIDIA Corporation\\Nsight Compute 2022.4.1\\;C:\\Users\\sdlwo\\.cargo\\bin;C:\\Users\\sdlwo\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Programs\\Micros
oft VS Code\\bin;C:\\Program Files\\JetBrains\\PyCharm Community Edition 2021.2.3\\bin;;C:\\Users\\sdlwo\\AppData\\Local\\GitHubDesktop\\bin;C:\\Users\\sdlwo\\go\\bin;C:\\Users\\sdlwo\\.d
otnet\\tools;C:\\ProgramData\\sdlwo\\GitHubDesktop\\bin;" PROCESSOR_LEVEL="6" COMSPEC="C:\\WINDOWS\\system32\\cmd.exe" NUMBER_OF_PROCESSORS="16" IDEA_INITIAL_DIRECTORY="C:\\Users\\sdlwo\\
Desktop" PROCESSOR_ARCHITECTURE="AMD64" PROCESSOR_REVISION="a502" OS="Windows_NT" USERPROFILE="C:\\Users\\sdlwo" ASL.LOG="Destination=file" ALLUSERSPROFILE="C:\\ProgramData" USERNAME="sdl
wo" GOPATH="C:\\Users\\sdlwo\\go" PROGRAMW6432="C:\\Program Files" COMMONPROGRAMW6432="C:\\Program Files\\Common Files" TERM_SESSION_ID="90f7a8a2-3632-4b11-82ed-e83b1a8826a4" PROGRAMFILES
(X86)="C:\\Program Files (x86)" PSMODULEPATH="C:\\Users\\sdlwo\\Documents\\WindowsPowerShell\\Modules;C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShel
l\\v1.0\\Modules" PATHEXT=".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL" && torchrun --nproc_per_node=1 --nnodes=1 --node_rank=0 --rdzv_backend=c10d --rdzv_endpoint=127.0.0.
1:29500 --rdzv_id=colossalai-default-job auto_parallel_with_resnet.py'

Exit code: 1

Stdout: already printed

Stderr: already printed

====== Training on All Nodes =====
127.0.0.1: failure

====== Stopping All Nodes =====
127.0.0.1: finish

### Environment

------------ Environment ------------
Colossal-AI version: 0.2.5
PyTorch version: 1.12.0
CUDA version: 12.0
CUDA version required by PyTorch: 11.3

**Comment by FrankLeeeee** [comment]
Hi, we do not support Windows shell now. We recommend you to use `WSL` on windows. Ideally, a linux environment should work for you.

**Comment by FrankLeeeee** [comment]
I will close this issue for now. Don't hesitate to let us know if there is any more issue.
