### ISSUE TITLE
[BUG]: No module named 'colossalai.kernel.op_builder'

### ISSUE THREAD

**Issue by zscwind** [hpcaitech/ColossalAI#2771]
### 🐛 Describe the bug

 `from colossalai.kernel.op_builder.layernorm import LayerNormBuilder
ModuleNotFoundError: No module named 'colossalai.kernel.op_builder'`

### Environment
pyhton 3.8.0
CUDA 11.6
torch 1.13.0+cu116

**Comment by JThh** [comment]
Please build Colossalai with cuda extension and try again. Refer to this [file](https://github.com/hpcaitech/ColossalAI/blob/main/docker/Dockerfile) for relevant details.

**Comment by FrankLeeeee** [comment]
Did you install from pypi or from source?

**Comment by zscwind** [comment]
> Did you install from pypi or from source?

from source

**Comment by zscwind** [comment]
> 

The given file's env: `pytorch==1.12.1 torchvision==0.13.1 torchaudio==0.12.1 cudatoolkit=11.3 -c pytorch`
but mine is: `pyhton 3.8.0 CUDA 11.6torch 1.13.0+cu116`
I did as the file's command, but the error still exists: `No module named 'colossalai.kernel.op_builder'`

**Comment by FrankLeeeee** [comment]
This is likely that you are importing colossalai in the repository root directory, which means you current directory is `Colossal-AI` as given below. If this is the case, that means Python is importing from the `colossalai` folder instead of the installed package.

```
- Colossal-AI
   - colossalai
   - setup.py
   - examples
   - ...

```

**Comment by zscwind** [comment]
> This is likely that you are importing colossalai in the repository root directory, which means you current directory is `Colossal-AI` as given below. If this is the case, that means Python is importing from the `colossalai` folder instead of the installed package.
> 
> ```
> - Colossal-AI
>    - colossalai
>    - setup.py
>    - examples
>    - ...
> ```

So, I should install from pypi?

**Comment by FrankLeeeee** [comment]
You can give it a try and do not execute your code from the root directory.

**Comment by zscwind** [comment]
> You can give it a try and do not execute your code from the root directory.

It works, thank you, Frank!

**Comment by FrankLeeeee** [comment]
No problem! I will close this issue for now.

**Comment by chensimian** [comment]
> 请使用 cuda 扩展构建 Colossalai，然后重试。相关详细信息请参阅此[文件。](https://github.com/hpcaitech/ColossalAI/blob/main/docker/Dockerfile)

your answers are not helpful.
