### ISSUE TITLE
[BUG]: A100 24G，加载opt6.7b爆内存

### ISSUE THREAD

**Issue by iMountTai** [hpcaitech/ColossalAI#2772]
oomkilled
![image](https://user-images.githubusercontent.com/35353688/219367782-55fc3c31-d553-4a41-b649-95e349244907.png)

默认的脚本
`set -x
export BS=${BS:-16}
export MEMCAP=${MEMCAP:-0}
export GPUNUM=${GPUNUM:-1}

export MODLE_PATH="facebook/opt-${MODEL}"
model_name_or_path=./opt6.7b

\# HF_DATASETS_OFFLINE=1 TRANSFORMERS_OFFLINE=1
torchrun \
  --nproc_per_node ${GPUNUM} \
  --master_port 19198 \
  train_gemini_opt.py \
  --mem_cap ${MEMCAP} \
  --model_name_or_path ${model_name_or_path} \
  --batch_size ${BS} `

### Environment

版本：torch1.12+cu113
deepspeed:0.7.7
内存：80G

**Comment by JThh** [comment]
Can you reveal more about your environment settings (number of gpus) and the complete error message? Thanks

**Comment by iMountTai** [comment]
![image](https://user-images.githubusercontent.com/35353688/220101359-084a1c94-7391-4edd-be68-647132babdf0.png)
ColossalAI通过源码安装后，运行后一直卡在这儿，

**Comment by JThh** [comment]
Please install apex before making the trial again. Follow the instruction [here](https://github.com/hpcaitech/ColossalAI/blob/main/docker/Dockerfile).

**Comment by FrankLeeeee** [comment]
@JThh this is not about apex. I can take this over.

**Comment by FrankLeeeee** [comment]
@iMountTai  mostly that your cuda environment is not matching the one required by PyTorch. You can check this by 

1. check your system cuda version
```bash
nvcc -v
```

2. check your pytorch's cuda version
```python
import torch
print(torch.version.cuda)
```

Compilation will only run successfully if they match.

**Comment by iMountTai** [comment]
升级环境为torch1.13cu117后，解决了该问题，虽然不知道为什么:joy:

**Comment by FrankLeeeee** [comment]
> 升级环境为torch1.13cu117后，解决了该问题，虽然不知道为什么😂

可能是你的系统CUDA是1.17 :)

**Comment by iMountTai** [comment]
请问为什么每次运行时都要重构算子呢，之前的缓存不能直接加载吗？

**Comment by FrankLeeeee** [comment]
> 请问为什么每次运行时都要重构算子呢，之前的缓存不能直接加载吗？

第一次编译之后都是重载。

**Comment by iMountTai** [comment]
谢谢回复如此及时。torch1.12cu113仍然存在该问题
![image](https://user-images.githubusercontent.com/35353688/220297253-25d7c2cd-a20a-47df-bb02-ed90618eb177.png)


> > 升级环境为torch1.13cu117后，解决了该问题，虽然不知道为什么😂
> 
> 可能是你的系统CUDA是1.17 :)

**Comment by binmakeswell** [comment]
Glad to hear it was resolved. Thanks.
