### ISSUE TITLE
[BUG]: ChatGPT Reward Model Eval Distance No Accumulated?

### ISSUE THREAD

**Issue by Dcyx** [hpcaitech/ColossalAI#2795]
### 🐛 Describe the bug

<img width="406" alt="image" src="https://user-images.githubusercontent.com/12059721/219571182-d752489a-fb99-4048-81f5-1b448a156da5.png">

**Comment by ht-zhou** [comment]
> @ver217 , should the `dist=0` be outside the loop?

yep, I will fix soon.

**Comment by yangtailu** [comment]
怎么用呢？
