### ISSUE TITLE
[BUG]: colossalai check -i failed after installation both from PyPl and source

### ISSUE THREAD

**Issue by MDLS-Delores** [hpcaitech/ColossalAI#2802]
### 🐛 Describe the bug

I encounter this bug using "colossalai check -i" right after the installation.
File "../anaconda3/envs/base/lib/python3.8/site-packages/torch/_ops.py", line 485, in __getattr__
    raise AttributeError(
AttributeError: The underlying op of 'aten.upsample_nearest2d_backward' has no overload name 'vec'

And this can be traced to file 'anaconda3/envs/base/lib/python3.8/site-packages/colossalai/fx/profiler/opcount.py' at line 273, aten.upsample_nearest2d_backward.vec: elementwise_flop_counter(0, 1).

### Environment

CUDA 12.0/PyTorch 2.0.0/Pytorch-cuda 11.8/python 3.8.16/colossalai 0.2.5

**Comment by MDLS-Delores** [comment]
It seems to be solved by changing line 273 in file 'anaconda3/envs/base/lib/python3.8/site-packages/colossalai/fx/profiler/opcount.py' from "aten.upsample_nearest2d_backward.vec: elementwise_flop_counter(0, 1)," to "aten.upsample_nearest2d_backward.default: elementwise_flop_counter(0, 1),".
It seems that in my environment, the torch.ops.aten.upsample_nearst2d_backward class does not have vec attribute.

**Comment by JThh** [comment]
torch 2.0. is not supported by CAI yet. Please try downgrading it into 1.x

**Comment by MDLS-Delores** [comment]
ok. thanks for your guidance.

**Comment by gfiameni** [comment]
Hi all, 
I am experiencing the same issue with this environment: CUDA 12.0/PyTorch 1.14/Python 3.8.0/CUDA Python 12.1.0/colossalai 0.2.5

Wondering if CUDA 12.0/ColossalAI is the root cause.

Thanks!

**Comment by liyanhui607** [comment]
> It seems to be solved by changing line 273 in file 'anaconda3/envs/base/lib/python3.8/site-packages/colossalai/fx/profiler/opcount.py' from "aten.upsample_nearest2d_backward.vec: elementwise_flop_counter(0, 1)," to "aten.upsample_nearest2d_backward.default: elementwise_flop_counter(0, 1),". It seems that in my environment, the torch.ops.aten.upsample_nearst2d_backward class does not have vec attribute.

this suggestion can work

**Comment by Camille7777** [comment]
> Hi all, I am experiencing the same issue with this environment: CUDA 12.0/PyTorch 1.14/Python 3.8.0/CUDA Python 12.1.0/colossalai 0.2.5
> 
> Wondering if CUDA 12.0/ColossalAI is the root cause.
> 
> Thanks!

torch==1.13.1 can work

**Comment by XuJing1022** [comment]
When can ColossalAI support Pytorch2.0? T T
