### ISSUE TITLE
[BUG]: No module named 'chatgpt.nn'

### ISSUE THREAD

**Issue by shendl1978** [hpcaitech/ColossalAI#2810]
### 🐛 Describe the bug

Hi,
    I can not run demo of ColossalAI.
The following is the output.

/ColossalAI/dev_test/benchmark_gpt_dummy.py", line 1, in <module>
    from chatgpt.nn import GPTActor, GPTCritic, RewardModel
ModuleNotFoundError: No module named 'chatgpt.nn'

**Comment by JThh** [comment]
Please what's instructed in this [file](https://github.com/hpcaitech/ColossalAI/tree/main/applications/ChatGPT) (most importantly, `pip install .` in the `applications/ChatGPT` folder.

**Comment by chaos2024** [comment]
got the same error, and i already pip install . under the chatgpt folder.  I can import chatgpt from python environment, the error comes out with the torchrun command

**Comment by A-biao96** [comment]
chatgpt.nn is in this path "ColossalAI/applications/ChatGPT/chatgpt/nn", put trian_XX.py with the folder chatgpt, in the same path.

**Comment by A-biao96** [comment]
> 得到同样的错误，我已经 pip install .在 chatgpt 文件夹下。我可以从python环境中导入chatgpt，torchrun命令出现错误

You did not successfully install pytorch，please test it with the following code：
import torch
print(torch.cuda.is_available())

**Comment by chaos2024** [comment]
> > 得到同样的错误，我已经 pip install .在 chatgpt 文件夹下。我可以从python环境中导入chatgpt，torchrun命令出现错误
> 
> You did not successfully install pytorch，please test it with the following code： import torch print(torch.cuda.is_available())

thanks 

moving file to chatgpt/nn didn't work,  the error became no module named transformers while it's been installed. 

and torch.cuda.is_available()) is True

**Comment by wqw547243068** [comment]
Warning:
- `chatgpt.nn` has been modified as `chatgpt.models`
- The overall arch diagram is ...

![image](https://user-images.githubusercontent.com/3257257/224962901-f6dffc13-459f-475d-b471-42a7c5f87a9a.png)

If this error (No module named 'chatgpt.nn') still pops up, remember to git pull in order to update the code

**Comment by binmakeswell** [comment]
> Warning:
> 
> * `chatgpt.nn` has been modified as `chatgpt.models`
> * The overall arch diagram is ...
> 
> ![image](https://user-images.githubusercontent.com/3257257/224962901-f6dffc13-459f-475d-b471-42a7c5f87a9a.png)
> 
> If this error (No module named 'chatgpt.nn') still pops up, remember to `git pull` in order to update the code

Thanks for such a clear summary!

**Comment by binmakeswell** [comment]
We have updated a lot.
Please check the latest instructions
https://github.com/hpcaitech/ColossalAI/tree/main/applications/Chat#install
This issue was closed due to inactivity. Thanks.
