### ISSUE TITLE
when Train the reward model, Get error

### ISSUE THREAD

**Issue by zhangsanfeng86** [hpcaitech/ColossalAI#2818]
when Train the reward model, Get error:

<img width="856" alt="image" src="https://user-images.githubusercontent.com/73547638/219875434-2696725a-c19a-4e03-8e3e-7e26e326ad54.png">

**Comment by ht-zhou** [comment]
Thanks for your feedback, but we can't reproduce your bug.
Please show more detail about your bug.
By the way, we suggest to use our train_rm.sh to train.
Thanks.
<img width="764" alt="image" src="https://user-images.githubusercontent.com/70618399/220241839-3ce20034-368b-4880-a8b7-4dd2062ff4c9.png">
