### ISSUE TITLE
[FEATURE]: Optimization

### ISSUE THREAD

**Issue by programmin1** [hpcaitech/ColossalAI#2827]
### Describe the feature

You mention CUDA optimization which is "needed" but why do you not have support for Movidius compute stick or a Pine64 Quartz64 Neural Network Acceleration Engine? Is there a cpu strong enough at working this that it can be done without Nvidia-CUDA?
Can that be supported as well or does it provide enough power?

**Comment by FrankLeeeee** [comment]
Interesting feature, however our primary target is the training process which occurs mostly on GPU platform. However, edges devices can be an important scenario for inference, we probably will look into this feature in the future.

**Comment by programmin1** [comment]
In other words it will not train OR run without CUDA?

**Comment by binmakeswell** [comment]
Hi @programmin1 Yes, you can check the detailed requirements.
https://github.com/hpcaitech/ColossalAI#Installation
This issue was closed due to inactivity. Thanks.
