### ISSUE TITLE
[BUG]: 使用 gemini，必须是2的幂的卡数，不然出现 assert chunk_size % self.pg_size == 0

### ISSUE THREAD

**Issue by 1024er** [hpcaitech/ColossalAI#2836]
### 🐛 Describe the bug

使用 gemini，必须是2的幂的卡数，不然出现 assert chunk_size % self.pg_size == 0

打印 chunk_size 是 40MB

### Environment

多台 8x80G A100，使用最新的code

**Comment by FrankLeeeee** [comment]
@ver217  and @1SAA , can you take a look at this issue. I thought Gemini has implemented padding for chunks, so that 8 elements over 3 devices will be divided as (3, 3, 2) where 2 will be padded to 3.

**Comment by 1SAA** [comment]
I'll fix this soon.
