### ISSUE TITLE
[BUG]: ChatGPT: why total reward is reward = r - kl_coef * kl, not total_reward=r + gamma * critic(next_states)?

### ISSUE THREAD

**Issue by liukaiyueyuo** [hpcaitech/ColossalAI#2839]
### 🐛 Describe the bug

ChatGPT: why total reward is reward = r - kl_coef * kl, not total_reward=r + gamma * critic(next_states)?
![image](https://user-images.githubusercontent.com/11996971/220237581-94ddb213-576f-431a-a5da-671285992a58.png)

**Comment by ht-zhou** [comment]
Because as we think, the rl training process here is a one-step process, which means there isn't a next_state.

**Comment by ht-zhou** [comment]
I'll close this issue now, please reopen the issue if you have further questions.
