### ISSUE TITLE
ModelZoo

### ISSUE THREAD

**Issue by bobo0810** [hpcaitech/ColossalAI#2844]
### Discussed in https://github.com/hpcaitech/ColossalAI/discussions/2843

<div type='discussions-op-text'>

<sup>Originally posted by **bobo0810** February 21, 2023</sup>
是否计划提供官方模型库，以便直接启用Tensor、流水线等并行策略。

</div>

**Comment by FrankLeeeee** [comment]
thank you for your attention. We usually separate discussion and issue. I will close this issue now and any related discussion will occur in #2843 .
