### ISSUE TITLE
[DOC]: a readme typo in "Run GPT With Colossal-AI"

### ISSUE THREAD

**Issue by ErenChan** [hpcaitech/ColossalAI#2851]
### 📚 The doc issue

https://github.com/hpcaitech/ColossalAI/blob/main/examples/language/gpt/titans/README.md#29
there are two different cmds and they have the same comments.
# run on multiple nodes with slurm
I think the first may be #  run on multiple nodes with pytorch

**Comment by binmakeswell** [comment]
Hi @ErenChan You are right, the "with slurm" in #29 is redundant. Thank you for your careful inspection. 
Can you submit a PR to fix it?  Contributors from the open source community are very welcome! Thanks.
