### ISSUE TITLE
[BUG]: AttributeError: 'ColossalAIStrategy' object has no attribute 'prepare'

### ISSUE THREAD

**Issue by xiaocainiao** [hpcaitech/ColossalAI#2855]
### 🐛 Describe the bug

上周我跑过单机的benchmark_gpt_dummy.py都是正常的，今天同步了最近的更新后，跑benchmark_gpt_dummy.py或者train_prompts.py都会报object has no attribute 'prepare'这个错误

**Comment by ht-zhou** [comment]
Thanks for your feedback .
Suggest you to do 'pip instal . ' in Chatgpt file , after you update the code.

**Comment by ht-zhou** [comment]
I'm going to close this issue, if you have any problems about this issue ,please reopen it. Thanks.
