### ISSUE TITLE
[DOC]: Step3 in Basic Usage for Build an online OPT service using Colossal-AI in 5 minutes is not clear

### ISSUE THREAD

**Issue by grantchenhuarong** [hpcaitech/ColossalAI#2856]
### 📚 The doc issue

Just like the issue title,when I read it ,I can not figure out how to implement it through the guide. Lack of files such as server.sh and opt_config.py, which was mentioned about.

Need some clear helps to deploy this inference，pls help and thank you.

**Comment by JThh** [comment]
Sorry for any confusion caused. Please take a look at this [instruction](https://github.com/hpcaitech/EnergonAI/tree/main/examples/opt) and follow along. It would probably work.

**Comment by binmakeswell** [comment]
Thanks for your feedback. Sorry for this issue, we are a small team and have to focus on development currently. Maybe we will update the doc maybe next month. 
This issue was closed due to inactivity. Thanks.
