### ISSUE TITLE
[DOC]:  Hope to get your answer!    

### ISSUE THREAD

**Issue by NLPxiaoxu** [hpcaitech/ColossalAI#2862]
### 📚 The doc issue

two options:
1.  8*24G A40900  
2.  8*48G A6000 .   

I have LLM 11B, RewardModel 1B.  
which option can  run PPO model?

**Comment by NLPxiaoxu** [comment]
8*24G 4090
sorry!

**Comment by binmakeswell** [comment]
Larger memory is more possible. You can try memory optimizations like zero, gemini, offload, etc. if encounter OOM.

**Comment by binmakeswell** [comment]
We have updated a lot. This issue was closed due to inactivity. Thanks.
