### ISSUE TITLE
[DOC]: 公式乱码

### ISSUE THREAD

**Issue by bobo0810** [hpcaitech/ColossalAI#2864]
### 📚 The doc issue

当前官方最新文档的公式乱码、格式混乱。对阅读造成很大的困扰，期待修复~
![image](https://user-images.githubusercontent.com/26057879/220508956-e5e6b004-4829-44e2-a7ee-96e2e576c1b9.png)

**Comment by binmakeswell** [comment]
感谢反馈，将会在近期修复

**Comment by jiangmingyan** [comment]
已修复
