### ISSUE TITLE
[DOC]: how to infer by chatgpt models

### ISSUE THREAD

**Issue by Muzzypepper** [hpcaitech/ColossalAI#2868]
### 📚 The doc issue

Hello, authors and developers，I have a problem with chatgpt. I train my model with single GPU, I want to know how to infer or predict the chatgpt model trained based on scripts such as examples/train_prompt.py, without related scripts or some dependencies。Thanks for your reply.

**Comment by hurun** [comment]
meet the same issue. 
anyone can write a doc or any blog to show how to use colossalai to infer

**Comment by binmakeswell** [comment]
Hi @Muzzypepper and @hurun Thanks for the feedback, we will provide it soon.

**Comment by LeiJiang1** [comment]
Please let me know if a doc is published. Thanks
