### ISSUE TITLE
[BUG]: Conflict with Deepspeed and colossalAI for fused  adam

### ISSUE THREAD

**Issue by Fazziekey** [hpcaitech/ColossalAI#2874]
### 🐛 Describe the bug

when the anaconda env has both deepspeed and colossalAI, and we use zero optimizer for deepspeed, I will get error to load Fused Adam, because both of the  deepspeed and colossalAI will put their kernel in `.conda/envs/chat/lib/python3.9/site-packages/op_builder` and get conflict
![image](https://user-images.githubusercontent.com/55798671/220552160-4a61800f-396c-4921-aab3-6c799be195ac.png)

>
related issue in deepspeed: https://github.com/microsoft/DeepSpeed/issues/2874

**Comment by ver217** [comment]
How did you install colossalai? There is no `op_builder/` folder in my `site-packages/` folder.
![image](https://user-images.githubusercontent.com/23111350/220556227-4644edd4-7c42-4374-acb2-010b5350a03e.png)

**Comment by jeffra** [comment]
@FrankLeeeee and @ver217 I just finished debugging an issue on the DeepSpeed side that seems very related to this issue.

I can confirm that `op_builder` is being installed in site-packages. One way you can see this is when you try and uninstall colossalai:

<img width="591" alt="image" src="https://user-images.githubusercontent.com/645595/223578371-99f6ab73-fdf1-4df9-a6c1-fe1b8f5e2e01.png">

Please also see this issue: https://github.com/microsoft/DeepSpeed/issues/2904 and my related PR: https://github.com/microsoft/DeepSpeed/pull/2963 where I am trying to workaround this issue.

I should note that we've had similar issues in the past where we accidently installed packages into site-packages (https://github.com/microsoft/DeepSpeed/issues/2690). They can usually be resolved by adding an explicit exclude for folders like `op_builder` in your setup.py here: 

https://github.com/hpcaitech/ColossalAI/blob/ea0b52c12ee7598fe126ed0d8b0557f7e8a0e999/setup.py#L154-L164
