### ISSUE TITLE
[BUG]: train_gpt_demo.py cannot load parameters from model file

### ISSUE THREAD

**Issue by zhanghaoie** [hpcaitech/ColossalAI#2879]
### 🐛 Describe the bug

I  want to load model parameters from a pretrained model after use tp, but use train_gpt_demo.py after zero_model_wrapper also made tensor shape mismatch error

**Comment by binmakeswell** [comment]
Hi @zhanghaoie maybe you can refer to this example https://github.com/hpcaitech/ColossalAI/tree/main/applications/ChatGPT#how-to-saveload-checkpoint

**Comment by binmakeswell** [comment]
We have updated a lot. This issue was closed due to inactivity. Thanks.
