### ISSUE TITLE
why GPTActor is not to load pretained parameters  in chatgpt examples

### ISSUE THREAD

**Issue by alphanlp** [hpcaitech/ColossalAI#2890]
### 🐛 Describe the bug

 with strategy.model_init_context():
        if args.model == 'gpt2':
            actor = GPTActor().cuda()
            critic = GPTCritic().cuda()

**Comment by ver217** [comment]
As it just shows training process, we just use randomly initialized model for simplicity. You can use a pretrained model easily by `GPTActor(pretrained='gpt2')`.

**Comment by binmakeswell** [comment]
https://github.com/hpcaitech/ColossalAI/tree/main/applications/Chat
We have updated a lot. This issue was closed due to inactivity. Thanks.
