### ISSUE TITLE
[DOC]: How should I start from pre-training and train a text-generated gpt2 or gpt3? Can I produce a document tutorial

### ISSUE THREAD

**Issue by Dark1Forest** [hpcaitech/ColossalAI#2893]
### 📚 The doc issue

I only see how to prepare the dataset in the gpt training document, and I don't know how to train a text-generated gpt model

**Comment by binmakeswell** [comment]
Hi @Dark1Forest You can refer to the GPT example https://github.com/hpcaitech/ColossalAI/tree/main/examples/language/gpt

**Comment by binmakeswell** [comment]
This issue was closed due to inactivity. Thanks.
