### ISSUE TITLE
[DOC]: Setup guide for smooth-brain noob dummies from base installation of ubuntu to working inference

### ISSUE THREAD

**Issue by iculverr** [hpcaitech/ColossalAI#2898]
### 📚 The doc issue

**Description:** I am running on Ubuntu (the latest distro available from Feb 24 2023) with an RTX3090. I want to load up for example GPT-2 or GPT-3 for simple text generation to get things running so that I can then start experimenting and learning. There is no better way to start than to have a working product that you can modify to figure out what the functions do. The current "quick demo" does not provide a clear explanation from beginning to end for beginners on what commands to input and why, where to input them, how to get the output, and what the expected output would look like. 

What I have done so far is FIRST git clone the ColossalAI repository and I also installed the ColossalAI with pip install colossalai. 

THEN I input colossalai run --nproc_per_node 1 train.py and it points to /home/dev/ and cannot find a train.py, I imagine I need to run the command within the specific directory of resnet or the examples, but nowhere does it say this. Now that I look at the repository it says that it is deprecated and archived. So why does the "quick demo" point to it? How do I quickly demo? 

**Location:** When I test out the "quick demo" from https://colossalai.org/docs/get_started/run_demo and the information at: https://github.com/hpcaitech/ColossalAI-Examples/tree/main/image/resnet

The README.md within /ColossalAI/examples/tutorial tells me to use a conda virtual environment but it does not say this on the main ColossalAI installation page nor on the [colossalai.org](http://colossalai.org/) website

After digging through the files I found the README.md file in /home/dev/ColossalAI/examples/tutorial/auto_parallel
and the README.md file in /home/dev/ColossalAI/examples/tutorial/opt/opt that contains something more like what I am looking for. But WHY is it not on the front page of the github??? Why is it not in the "quick demo" website?

https://github.com/hpcaitech/ColossalAI#Installation

**Expectations:**
What I am looking for is a step by step full page commands that I can input into the Linux terminal sequentially from base installation to running my first model and getting an output for text generation. The exact model doesn't matter too much, anything GPT-like or BERT-like or BLOOM-like will do. 
Areas of future guidance would also be helpful after this first demo works. For example, if I GPT-2 or GPT-3 is successfully loaded and I wanted to branch into making a Chat GPT replica or something with more persistent memory **describe conceptually the actions I would need to take** in terms of scripting, directory tinkering, and commands of interest. 
I expect that the tutorial contains a list of all the installation requirements necessary to load and run the model, the front page says something about NOT install transformers or pytorch at the beginning which is also confusing because it is suggested that these (or the CUDA files) are loaded when colossal ai is loaded??

**Screenshots:**
![image](https://user-images.githubusercontent.com/71106045/221119596-0abe3a25-8169-4087-aeaf-a36128b50cc9.png)

![image](https://user-images.githubusercontent.com/71106045/221120700-1783336a-5bbe-4169-88eb-c2443aa7430c.png)

![image](https://user-images.githubusercontent.com/71106045/221121325-7997bf80-1b1f-48b4-a004-f92fbdb4b30a.png)

![image](https://user-images.githubusercontent.com/71106045/221121448-104c8501-1134-4a30-8357-d21e73805886.png)

What is the purpose of the Docker? Do I need it to run inference? It is not mentioned anywhere in the tutorial!

**Suggestions:**

What I am looking for is a step by step full page commands that I can input into the Linux terminal sequentially from base installation to running my first model and getting an output that is explained like I am five years old and smooth brained.

**Comment by binmakeswell** [comment]
Hi @iculverr Thank you for such a detailed suggestion. Our documentation does have deficiencies at the moment, which are being fixed over time. I have added notes to the documentation under the tutorial path to avoid misunderstandings. You can refer to https://github.com/hpcaitech/ColossalAI/tree/main/examples/language

@FrankLeeeee and @ver217 , @iculverr provide a good idea about our new documents. Thanks.

**Comment by binmakeswell** [comment]
https://colossalai.org/
We have updated a lot. This issue was closed due to inactivity. Thanks.
