### ISSUE TITLE
[DOC]: 文档这么少，几乎没法用

### ISSUE THREAD

**Issue by BeyonderXX** [hpcaitech/ColossalAI#2903]
### 📚 The doc issue

文档属于有一点，但不是很多的状态。
官方的教程文档非常简略，甚至给出样例的很多方法和类都不会说明用途，我意思是系统和全面的说明。
教程写的不行，那去看代码注释吧，没想到也是几乎没有的状态，对于类和接口的使用场景，输入输出样例，一点都没有提供。
难不成要我们一行一行读代码，给整个框架读懂了，做自己的山寨Colossal-AI？
真搞不懂，这些必要的东西没做好，就开始大规模宣传噱头干什么？
还是让我用deepspeed吧，慢死我。

**Comment by Chtholly1** [comment]
同感，关键是我跑里面的很多example都跑不起来...浪费了好多时间 排了好多坑 还是用不顺手...

**Comment by JThh** [comment]
Which examples are you referring to? Would you please point them out and let us enhance the documentation accordingly?

**Comment by binmakeswell** [comment]
感谢反馈，作为新生项目，目前确实还有很多不足，已经提升文档问题的处理优先级。
您可以具体描述下是具体哪些文档/例子对您造成困扰，后续会尽快提供针对性修复，感谢。

**Comment by binmakeswell** [comment]
This issue was closed due to inactivity. We have updated a lot. You can open a new issue if you have specific questions. Thanks.
