### ISSUE TITLE
train_reward_model loss is random

### ISSUE THREAD

**Issue by ipackhu** [hpcaitech/ColossalAI#2905]
use default rm_static dataset,
set train_data to 75000
batch_size 4
machine: 8 A100 80g
after 13hours train 
loss is random change
the training seems no problem

base model: opt-iml-max-1.3b
![image](https://user-images.githubusercontent.com/15916781/221324803-ddef53ce-b21a-447c-9e76-e856039b6757.png)
![image](https://user-images.githubusercontent.com/15916781/221324831-c66529b0-3f9c-4eee-8806-6821273bc658.png)
![image](https://user-images.githubusercontent.com/15916781/221324862-6b0b5b65-b3ee-4e30-ab83-91ebfcb62b0c.png)

why?

**Comment by binmakeswell** [comment]
We have updated a lot. This issue was closed due to inactivity. Thanks.
