### ISSUE TITLE
[BUG]: AttributeError: module 'torch.distributed' has no attribute '_all_gather_base'

### ISSUE THREAD

**Issue by zp2459** [hpcaitech/ColossalAI#2916]
### 🐛 Describe the bug

when I follow the README.md to configure my environment in **../ColossalAI/applications/ChatGPT/examples/README.md**,the AttributeError happenned. 

### Environment

Package                  Version
------------------------ ----------
aiohttp                  3.8.4
aiosignal                1.3.1
async-timeout            4.0.2
attrs                    22.2.0
bcrypt                   4.0.1
certifi                  2022.12.7
cffi                     1.15.1
cfgv                     3.3.1
charset-normalizer       3.0.1
chatgpt                  0.1.0
click                    8.1.3
colossalai               0.2.5
contexttimer             0.3.3
cryptography             39.0.1
datasets                 2.10.0
dill                     0.3.6
distlib                  0.3.6
exceptiongroup           1.1.0
fabric                   3.0.0
filelock                 3.9.0
frozenlist               1.3.3
fsspec                   2023.1.0
huggingface-hub          0.12.1
identify                 2.5.18
idna                     3.4
iniconfig                2.0.0
invoke                   2.0.0
loralib                  0.1.1
markdown-it-py           2.2.0
mdurl                    0.1.2
multidict                6.0.4
multiprocess             0.70.14
ninja                    1.11.1
nodeenv                  1.7.0
numpy                    1.24.2
nvidia-cublas-cu11       11.10.3.66
nvidia-cuda-nvrtc-cu11   11.7.99
nvidia-cuda-runtime-cu11 11.7.99
nvidia-cudnn-cu11        8.5.0.96
packaging                23.0
pandas                   1.5.3
paramiko                 3.0.0
pip                      22.3.1
platformdirs             3.0.0
pluggy                   1.0.0
pre-commit               3.1.0
psutil                   5.9.4
pyarrow                  11.0.0
pycparser                2.21
Pygments                 2.14.0
PyNaCl                   1.5.0
pytest                   7.2.1
python-dateutil          2.8.2
pytz                     2022.7.1
PyYAML                   6.0
regex                    2022.10.31
requests                 2.28.2
responses                0.18.0
rich                     13.3.1
setuptools               65.6.3
six                      1.16.0
tls-client               0.1.8
tokenizers               0.13.2
tomli                    2.0.1
torch                    1.8.1
tqdm                     4.64.1
transformers             4.26.1
typing_extensions        4.5.0
urllib3                  1.26.14
virtualenv               20.19.0
wheel                    0.38.4
xxhash                   3.2.0
yarl                     1.8.2

**Comment by binmakeswell** [comment]
Hi @zp2459 Could you please provide more details about your issue? It's hard for us to follow/reproduce/fix it. Thanks.

**Comment by zp2459** [comment]
这个问题已经解决，我出现此bug应该是torch版本或者cuda版本过低引起的，谢谢

**Comment by binmakeswell** [comment]
Glad to hear it was resolved. Thanks.
