### ISSUE TITLE
[BUG]: How to infer gpt2

### ISSUE THREAD

**Issue by YuchengWang** [hpcaitech/ColossalAI#2926]
### 🐛 Describe the bug

I can't find any docs to describe how to infer.

I had to find something from https://github.com/YuchengWang/EnergonAI/tree/main/examples/gpt but can't run.

I report the bug https://github.com/hpcaitech/EnergonAI/issues/196

Wait for response.

**Comment by binmakeswell** [comment]
Responded in the linked issue. This issue was closed due to inactivity. Thanks.

**Comment by yehx1** [comment]
How to solve it?
