### ISSUE TITLE
[BUG]: Anybody run through ColossalAI/examples/language/gpt/gemini? 或者有人跑通任何一个language example了吗？

### ISSUE THREAD

**Issue by nameless0704** [hpcaitech/ColossalAI#2941]
### 🐛 Describe the bug

I've been trying to fit this project into my computer & GPU and fixing all kinds of hardware/software/torch version/MSVC environment variables...problems, but more bugs were coming up and I cannot see the end of this. So I'd like to know if anyone has run through this example and is willing to share one's configurations including all the above & more. 
其实只是想问究竟有没有人跑通…想问一下大家跑通之后所使用的各个版本、配置是什么

### Environment

I'm currently using 4 V100, python37, CUDA116, and torch 1.13+cu117 (I heard 1.8.0 is better but the requirements said >=1.8.1?)

**Comment by binmakeswell** [comment]
Hi @nameless0704 What specific problems did you encounter?
You can check the env we tested at https://github.com/hpcaitech/ColossalAI#Installation

**Comment by nameless0704** [comment]
@binmakeswell I know how spoiled it may sound, but I'm going to list all the problems I ran into... First, is there an external argument/parameter to identify which torch backend to use? It has defaulted to NCCL, but windows cannot run NCCL, so I manually changed the defaults into GLOO in site-packages codes which are pretty dangerous(I'm that stupid). I tried environmental variables, but it didn't work.↓
```os.environ["PL_TORCH_DISTRIBUTED_BACKEND] = "gloo" ```

**Comment by binmakeswell** [comment]
Our development is based on Linux as I updated and did not test it on GLOO or Windows, sorry about that. Developing with windows can bring many other potential problems, perhaps you can try Linux from now. Thanks.

**Comment by nameless0704** [comment]
@binmakeswell Thank you!

**Comment by kurisusnowdeng** [comment]
> @binmakeswell I know how spoiled it may sound, but I'm going to list all the problems I ran into... First, is there an external argument/parameter to identify which torch backend to use? It has defaulted to NCCL, but windows cannot run NCCL, so I manually changed the defaults into GLOO in site-packages codes which are pretty dangerous(I'm that stupid). I tried environmental variables, but it didn't work.↓ `os.environ["PL_TORCH_DISTRIBUTED_BACKEND] = "gloo" `

Hi @nameless0704, hope the followings can anwser your questions:

1. We mainly do support Linux runtime environment, and recommend you to use nvidia dockers on Windows;
2. To use GLOO, we provide an `backend` option for every single way to launch colossalai. How about have a try.
