### ISSUE TITLE
[BUG]: type object 'LRUCache' has no attribute '_gorg'

### ISSUE THREAD

**Issue by pilipala818** [hpcaitech/ColossalAI#2945]
### 🐛 Describe the bug

Prompt the error when running the resNet demon

### Environment

python3.6
colossalai 0.2.5
torch 1.10.1

**Comment by binmakeswell** [comment]
Hi @pilipala818 Could you please provide more details about your issue? It's hard for us to follow/reproduce/fix it now. Thanks.

**Comment by binmakeswell** [comment]
We have updated a lot. Please check the latest code. This issue was closed due to inactivity. Thanks.
