### ISSUE TITLE
Why is the API document removed from the official website page

### ISSUE THREAD

**Issue by bobo0810** [hpcaitech/ColossalAI#2947]
### Discussed in https://github.com/hpcaitech/ColossalAI/discussions/2937

<div type='discussions-op-text'>

<sup>Originally posted by **bobo0810** February 28, 2023</sup>
Why is the API document removed from the official website page？</div>

**Comment by binmakeswell** [comment]
Hi @bobo0810 We have replied it at #2937 Thanks.

**Comment by binmakeswell** [comment]
This issue was closed due to inactivity. Thanks.
