### ISSUE TITLE
[BUG]: nvmeoffload

### ISSUE THREAD

**Issue by LYMDLUT** [hpcaitech/ColossalAI#2949]
### 🐛 Describe the bug

![image](https://user-images.githubusercontent.com/70597027/221857439-b611b4ab-27df-4eb4-bd77-b1d0815c283f.png)
![8c1afe573f597c2ef5105adb811c76b](https://user-images.githubusercontent.com/70597027/221857484-1a6eda68-68a2-4a92-9579-9de3f46bd3a0.png)
![QQ截图20230228204631](https://user-images.githubusercontent.com/70597027/221858141-f2bbda1b-f111-4b68-a2ae-6ca84e2908a0.png)
![QQ截图20230228204728](https://user-images.githubusercontent.com/70597027/221858327-8447d35f-a880-411b-b2c5-4544c57f5735.png)

### Environment

需要有其它改变吗，非常想使用该项功能

**Comment by ver217** [comment]
Hi, it only offload optimizer states to disk. It seems your error is not related to optimizer.

**Comment by ver217** [comment]
Can you provide more info?

**Comment by binmakeswell** [comment]
We have updated a lot. Please check the latest code. This issue was closed due to inactivity. Thanks.
