### ISSUE TITLE
[BUG]: colossalai多机多卡训练，机器间通讯不了，或服务

### ISSUE THREAD

**Issue by Cloopen-ReLiNK** [hpcaitech/ColossalAI#2958]
### 🐛 Describe the bug

![image](https://user-images.githubusercontent.com/107677991/222091175-29daa2c0-ba14-40e4-b3b9-d338caf2dc99.png)

### Environment

CUDA = 10.2
Python = 3.8.13
PyTorch = 1.12.1

**Comment by JingxinLee** [comment]
train_multi_node.py?

**Comment by Cloopen-ReLiNK** [comment]
不报这个错了，，但是还是无法运行

**Comment by joan126** [comment]
怎么配置的？

**Comment by joan126** [comment]
> 不报这个错了，，但是还是无法运行

socket 问题怎么解决的？我也遇到了

**Comment by YuliangLiu0306** [comment]
你们可以使用colossalai run来替代torch run，colossalai run同时支持单机和多机的训练启动。

**Comment by JingxinLee** [comment]
我也遇到了 之前有人说配置/etc/hosts

**Comment by joan126** [comment]
> 

配置后，起作用了吗？我配置了也不行，不管是用torchrun还是colossalai run都不行

**Comment by joan126** [comment]
> 我也遇到了 之前有人说配置/etc/hosts

配置后，起作用了吗？我配置了也不行，不管是用torchrun还是colossalai run都不行

**Comment by JingxinLee** [comment]
> > 我也遇到了 之前有人说配置/etc/hosts
> 
> 配置后，起作用了吗？我配置了也不行，不管是用torchrun还是colossalai run都不行

我配置了下可以。
1. 代码中backend="nccl"。所以保证机器/node的nccl版本一样。
2. master机器的/etc/hosts文件里 加入 IP 和 对应机器的hostname，如 1.2.3.4  dell-Tower-1

前两步先试试，不行的话再加上下面
export NCCL_DEBUG=INFO
export NCCL_SOCKET_IFNAME='en0' 注意 en0改成你机器ifconfig后对应的那个，我的就是enp0s31f6

**Comment by fearless1007** [comment]
用完上述方法后错误还没有变化，还有别的方法可以解决吗

**Comment by binmakeswell** [comment]
> 用完上述方法后错误还没有变化，还有别的方法可以解决吗

Hi @fearless1007 If you have further questions, please [open another new issue](https://github.com/hpcaitech/ColossalAI/issues/new/choose) and provide details. Because everyone's issue details may be different. Thanks.
