### ISSUE TITLE
[BUG]: the speed of chinese data for chatgpt is very slow

### ISSUE THREAD

**Issue by tnickMoxuan** [hpcaitech/ColossalAI#2960]
### 🐛 Describe the bug

![image](https://user-images.githubusercontent.com/120445480/222135625-8720e041-aca4-4a4b-a383-8edfb310d764.png)
the num of data is 10000
by debugging， i find the main reason is the line highlighted in red，but i do not konw why
![image](https://user-images.githubusercontent.com/120445480/222136545-5c7e1cdd-8d22-412a-9f79-647878262ca7.png)

**Comment by ht-zhou** [comment]
Thank you for your feedback. It's slow here in fact, and it's one of our points to optimize soon.

**Comment by binmakeswell** [comment]
Hi @tnickMoxuan We have updated a lot. Please check the latest code. This issue was closed due to inactivity. Thanks.
