### ISSUE TITLE
数据并行数 ×  epoch数 =  真实的epoch数?

### ISSUE THREAD

**Issue by bobo0810** [hpcaitech/ColossalAI#2962]
### Discussed in https://github.com/hpcaitech/ColossalAI/discussions/2961

<div type='discussions-op-text'>

<sup>Originally posted by **bobo0810** March  1, 2023</sup>
每个gpu上的dataloader都是完整的数据集，未做拆分。 即epoch=3  gpu=2时仅数据并行，模型实际上过了6遍数据集。
```
engine, train_dataloader, val_dataloader, _ = colossalai.initialize(
        model,
        optimizer,
        criterion,
        train_dataloader,
        val_dataloader,
    )
```

</div>

**Comment by binmakeswell** [comment]
Hi @bobo0810 I have replied to you in the discussion. Thanks.

**Comment by bobo0810** [comment]
Hi @binmakeswell
> Hi @bobo0810 如果是PyTorch正常dataloader提供给Colossal，会被自动转成DistributedSampler。每个GPU各自处理一部分数据，共同完成整个数据集的epoch。epoch=3是3遍数据集。

Hi @binmakeswell 
数据并行=2  epoch=3,理论上每张图片只出现3次，但从日志上看 每轮epoch出现2次，共出现6次。

启动命令`colossalai run --nproc_per_node 2 train.py --epochs 3`

代码
![image](https://user-images.githubusercontent.com/26057879/222613864-cf2bd32c-6d09-4700-9b8b-0c97bf6c198b.png)

日志
![image](https://user-images.githubusercontent.com/26057879/222613711-9dbca871-a9f9-4d12-8940-140b22815101.png)

**Comment by terrifyzhao** [comment]
遇到了一样的问题，同问

**Comment by terrifyzhao** [comment]
> 

并不会自动做DistributedSampler，需要手动处理下
