### ISSUE TITLE
problem of GPU memory usage 

### ISSUE THREAD

**Issue by laozhanghahaha** [hpcaitech/ColossalAI#2965]
Hey

I try to do training using this example https://github.com/hpcaitech/ColossalAI/tree/main/examples/language/opt

I tried to set PLACEMENT_POLICY to different value,  'cpu' ,'auto' and 'cuda'
https://github.com/hpcaitech/ColossalAI/blob/b0a8766381910921af60db5fcc03e57e349e1442/examples/language/opt/train_gemini_opt.py#L181

 When I set PLACEMENT_POLICY to 'cuda' the GPU memory usage would decrease with the increasing GPU number. But when I set the PLACEMENT_POLICY to 'cpu' or 'auto' , the GPU memory usage almost the same with the increasing GPU number.

here is an example when PLACEMENT_POLICY = 'auto'

GPU_NUM=1
![image](https://user-images.githubusercontent.com/12216214/222348043-59042793-8ee5-4b7c-847b-a38fe6ee6e6c.png)
GPU_NUM=4
![image](https://user-images.githubusercontent.com/12216214/222347994-f9af4bb0-5445-42c7-94b3-846c8de76585.png)

Is it normal?  Why does the used GPU memory keep the same with various number of GPU?

**Comment by kurisusnowdeng** [comment]
Hi @laozhanghahaha, the results from `nvidia-smi` maybe not accurate due to pytorch reservation mechanism. Could you please provide some results of actual real-time memory usage with `torch.cuda.memory_allocated` and `torch.cuda.max_memory_allocated`? Thank you so much!

**Comment by 1SAA** [comment]
Hi @laozhanghahaha 

It's normal, since 'cpu' policy makes you use the minimum CUDA memory to run your code and 'auto' policy automatically use your full CUDA memory.

**Comment by laozhanghahaha** [comment]
> Hi @laozhanghahaha
> 
> It's normal, since 'cpu' policy makes you use the minimum CUDA memory to run your code and 'auto' policy automatically use your full CUDA memory.


It is weird if the CUDA memory stay the same with different GPU numbers, since there is no sense to use multi GPU traning.

**Comment by laozhanghahaha** [comment]
@kurisusnowdeng
I try to train the opt1.3 B model , with this example https://github.com/hpcaitech/ColossalAI/tree/main/examples/language/opt
train command: `sh ./run_gemini.sh`

here is the results:
1.  `PLACEMENT_POLICY ='cuda'`
4 GPUs
`torch.cuda.memory_allocated`: 4588.43310546875 M
`torch.cuda.max_memory_allocated`: 7299.23828125 M
single GPU
`torch.cuda.memory_allocated`: 17834.14404296875 M
`torch.cuda.max_memory_allocated`: 18668.61328125 M
2.  `PLACEMENT_POLICY ='cpu'`
4 GPUs
`torch.cuda.memory_allocated`: 98.20654296875 M
`torch.cuda.max_memory_allocated`: 1060.705078125 M
single GPU
`torch.cuda.memory_allocated`: 98.20654296875 M
`torch.cuda.max_memory_allocated`: 1060.75390625 M
3.  `PLACEMENT_POLICY ='auto'`
4 GPUs
`torch.cuda.memory_allocated`: 98.20654296875 M
`torch.cuda.max_memory_allocated`: 3434.45703125 M
single GPU
`torch.cuda.memory_allocated`: 98.20654296875 M
`torch.cuda.max_memory_allocated`: 3434.408203125 M

**Comment by kurisusnowdeng** [comment]
> @kurisusnowdeng I try to train the opt1.3 B model , with this example https://github.com/hpcaitech/ColossalAI/tree/main/examples/language/opt train command: `sh ./run_gemini.sh`
> 
> here is the results:
> 
> 1. `PLACEMENT_POLICY ='cuda'`
>    4 GPUs
>    `torch.cuda.memory_allocated`: 4588.43310546875 M
>    `torch.cuda.max_memory_allocated`: 7299.23828125 M
>    single GPU
>    `torch.cuda.memory_allocated`: 17834.14404296875 M
>    `torch.cuda.max_memory_allocated`: 18668.61328125 M
> 2. `PLACEMENT_POLICY ='cpu'`
>    4 GPUs
>    `torch.cuda.memory_allocated`: 98.20654296875 M
>    `torch.cuda.max_memory_allocated`: 1060.705078125 M
>    single GPU
>    `torch.cuda.memory_allocated`: 98.20654296875 M
>    `torch.cuda.max_memory_allocated`: 1060.75390625 M
> 3. `PLACEMENT_POLICY ='auto'`
>    4 GPUs
>    `torch.cuda.memory_allocated`: 98.20654296875 M
>    `torch.cuda.max_memory_allocated`: 3434.45703125 M
>    single GPU
>    `torch.cuda.memory_allocated`: 98.20654296875 M
>    `torch.cuda.max_memory_allocated`: 3434.408203125 M

They look normal, since the strategies `auto` and `cpu` successfully offload most of the memory to CPU. In the meantime they use much smaller memory than no offloading.

**Comment by laozhanghahaha** [comment]
thanks for your explanation, may I ask what is left on GPU, non-model data or something else?

**Comment by kurisusnowdeng** [comment]
> @kurisusnowdeng thanks for your explanation, may I ask what is left on GPU, non-model data or something else?

@laozhanghahaha it is supposed to be non model data, such as input data pinned in memory, or some buffers.

**Comment by laozhanghahaha** [comment]
> > @kurisusnowdeng thanks for your explanation, may I ask what is left on GPU, non-model data or something else?
> 
> @laozhanghahaha it is supposed to be non model data, such as input data pinned in memory, or some buffers.

thanks, I'll close the issue
