### ISSUE TITLE
[BUG]: failed to run ..ColossalAI/examples/language/gpt/gemini

### ISSUE THREAD

**Issue by zp2459** [hpcaitech/ColossalAI#2973]
### 🐛 Describe the bug

根据README.md文档安装环境，但是跑不起来。报错如下：
=========================================================================================
No pre-built kernel is found, build and load the cpu_adam kernel during runtime now
=========================================================================================
Traceback (most recent call last):
  File "/home/panz/anaconda3/envs/chatgpt/lib/python3.8/site-packages/colossalai/kernel/op_builder/builder.py", line 135, in load
    op_module = self.import_op()
  File "/home/panz/anaconda3/envs/chatgpt/lib/python3.8/site-packages/colossalai/kernel/op_builder/builder.py", line 118, in import_op
    return importlib.import_module(self.prebuilt_import_path)
  File "/home/panz/anaconda3/envs/chatgpt/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'colossalai._C.cpu_adam'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./train_bert_demo.py", line 332, in <module>
    main()
  File "./train_bert_demo.py", line 231, in main
    optimizer = HybridAdam(model.parameters(), lr=1e-3)
  File "/home/panz/anaconda3/envs/chatgpt/lib/python3.8/site-packages/colossalai/nn/optimizer/hybrid_adam.py", line 82, in __init__
    cpu_optim = CPUAdamBuilder().load()
  File "/home/panz/anaconda3/envs/chatgpt/lib/python3.8/site-packages/colossalai/kernel/op_builder/builder.py", line 159, in load
    extra_include_paths=self.strip_empty_entries(self.include_dirs()),
  File "/home/panz/anaconda3/envs/chatgpt/lib/python3.8/site-packages/colossalai/kernel/op_builder/cpu_adam.py", line 25, in include_dirs
    self.get_cuda_home_include()
  File "/home/panz/anaconda3/envs/chatgpt/lib/python3.8/site-packages/colossalai/kernel/op_builder/builder.py", line 71, in get_cuda_home_include
    raise RuntimeError("CUDA_HOME is None, please set CUDA_HOME to compile C++/CUDA kernels in ColossalAI.")
RuntimeError: CUDA_HOME is None, please set CUDA_HOME to compile C++/CUDA kernels in ColossalAI.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 37184) of binary: /home/panz/anaconda3/envs/chatgpt/bin/python
Traceback (most recent call last):
  File "/home/panz/anaconda3/envs/chatgpt/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/panz/anaconda3/envs/chatgpt/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/panz/anaconda3/envs/chatgpt/lib/python3.8/site-packages/torch/distributed/run.py", line 762, in main
    run(args)
  File "/home/panz/anaconda3/envs/chatgpt/lib/python3.8/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/home/panz/anaconda3/envs/chatgpt/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/panz/anaconda3/envs/chatgpt/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
./train_bert_demo.py FAILED
./train_bert_demo.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------

### Environment

torch1.13.1 
transformers4.26.1 
colossalai0.2.5

**Comment by pilipala818** [comment]
运行chatGPT项目时，一直停留在  No pre-built kernel is found, build and load the cpu_adam kernel during runtime now
显存显示已经载入模型，但没有任何进展。请问是否与内网无法连接网络有关？

**Comment by FrankLeeeee** [comment]
> 运行chatGPT项目时，一直停留在 No pre-built kernel is found, build and load the cpu_adam kernel during runtime now 显存显示已经载入模型，但没有任何进展。请问是否与内网无法连接网络有关？

能看一下`colossalai check -i`吗？

**Comment by zp2459** [comment]
> > 运行chatGPT项目时，一直停留在 No pre-built kernel is found, build and load the cpu_adam kernel during runtime now 显存显示已经载入模型，但没有任何进展。请问是否与内网无法连接网络有关？
> 
> 能看一下`colossalai check -i`吗？

#### Installation Report ####

------------ Environment ------------
Colossal-AI version: 0.2.5
PyTorch version: 1.12.0
CUDA version: N/A
CUDA version required by PyTorch: 11.3

Note:
1. The table above checks the versions of the libraries/tools in the current environment
2. If the CUDA version is N/A, you can set the CUDA_HOME environment variable to locate it

------------ CUDA Extensions AOT Compilation ------------
Found AOT CUDA Extension: x
PyTorch version used for AOT compilation: N/A
CUDA version used for AOT compilation: N/A

Note:
1. AOT (ahead-of-time) compilation of the CUDA kernels occurs during installation when the environment varialbe CUDA_EXT=1 is set
2. If AOT compilation is not enabled, stay calm as the CUDA kernels can still be built during runtime

------------ Compatibility ------------
PyTorch version match: N/A
System and PyTorch CUDA version match: N/A
System and Colossal-AI CUDA version match: N/A

Note:
1. The table above checks the version compatibility of the libraries/tools in the current environment
   - PyTorch version mistach: whether the PyTorch version in the current environment is compatible with the PyTorch version used for AOT compilation
   - System and PyTorch CUDA version match: whether the CUDA version in the current environment is compatible with the CUDA version required by PyTorch
   - System and Colossal-AI CUDA version match: whether the CUDA version in the current environment is compatible with the CUDA version used for AOT compilation

**Comment by pilipala818** [comment]
Colossal-AI version: 0.2.5
PyTorch version: 1.13.1
CUDA version: 10.1
CUDA version required by PyTorch: 11.7
请问是CUDA与torch版本匹配的问题吗？

**Comment by pilipala818** [comment]
Colossal-AI version: 0.2.5
PyTorch version: **1.13.1**
CUDA version: **10.1**
CUDA version required by PyTorch: **11.7**

Note:

The table above checks the versions of the libraries/tools in the current environment
If the CUDA version is N/A, you can set the CUDA_HOME environment variable to locate it
------------ CUDA Extensions AOT Compilation ------------
Found AOT CUDA Extension: x
PyTorch version used for AOT compilation: N/A
CUDA version used for AOT compilation: N/A

Note:

AOT (ahead-of-time) compilation of the CUDA kernels occurs during installation when the environment varialbe CUDA_EXT=1 is set
If AOT compilation is not enabled, stay calm as the CUDA kernels can still be built during runtime
------------ Compatibility ------------
PyTorch version match: N/A
System and PyTorch CUDA version match: **×**
System and Colossal-AI CUDA version match: N/A

Note:

The table above checks the version compatibility of the libraries/tools in the current environment
PyTorch version mistach: whether the PyTorch version in the current environment is compatible with the PyTorch version used for AOT compilation
System and PyTorch CUDA version match: whether the CUDA version in the current environment is compatible with the CUDA version required by PyTorch
System and Colossal-AI CUDA version match: whether the CUDA version in the current environment is compatible with the CUDA version used for AOT compilation

**Comment by pilipala818** [comment]
cuda 10.1
torch 1.10.0
torchvision 0.11.1
It works

**Comment by zp2459** [comment]
> cuda 10.1 torch 1.10.0 torchvision 0.11.1 It works

你是解决了吗？我能添加一个你的联系方式吗，我第一次接触这类项目，有些问题问您

**Comment by joan126** [comment]
看下gcc版本，提升一下gcc版本

**Comment by zp2459** [comment]
gcc版本7.5.0

**Comment by joan126** [comment]
colossalai用源码安装一下呢

**Comment by Cloopen-ReLiNK** [comment]
没有下文了吗？？？这个

**Comment by Cloopen-ReLiNK** [comment]
遇到同样的问题

**Comment by wenzezhang** [comment]
这个解决了吗？

**Comment by JThh** [comment]
Hi, sorry for getting to this late.

Would this issue https://github.com/hpcaitech/ColossalAI/issues/3496 be any helpful?

**Comment by binmakeswell** [comment]
We have updated a lot. Please check the latest code. This issue was closed due to inactivity. Thanks.
