### ISSUE TITLE
[BUG]:chatgpt inference still ERROR after fix

### ISSUE THREAD

**Issue by wac81** [hpcaitech/ColossalAI#2978]
### 🐛 Describe the bug

still error：

size mismatch for transformer.ln_f.weight: copying a param with shape torch.Size([768]) from checkpoint, the shape in current model is torch.Size([64]).
size mismatch for transformer.ln_f.bias: copying a param with shape torch.Size([768]) from checkpoint, the shape in current model is torch.Size([64]).
size mismatch for lm_head.weight: copying a param with shape torch.Size([50257, 768]) from checkpoint, the shape in current model is torch.Size([250880, 64]).

params：
parser.add_argument('--model', default='bloom', choices=['gpt2', 'bloom', 'opt'])
parser.add_argument('--pretrain', type=str, default='./actor_checkpoint_prompts.pt')

**Comment by wac81** [comment]
File "inference.py", line 56, in <module>
    eval(args)
  File "inference.py", line 21, in eval
    actor.model.load_state_dict(state_dict)
  File "/home/rst/ColossalAI/env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1671, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(

**Comment by ht-zhou** [comment]
Thanks for your feedback, can you show your command line code please？

**Comment by wac81** [comment]
python inference.py --pretrain ./actor_checkpoint_prompts.pt --model bloom

**Comment by wac81** [comment]
if i use gpt2 to train , i get right results, bloom is not right any way.
