### ISSUE TITLE
[DOC]:  How to do the  supervised fine-tuning (SFT) (Stage 1 of chatGPT) ？   

### ISSUE THREAD

**Issue by yaleimeng** [hpcaitech/ColossalAI#2980]
### 📚 The doc issue

We only see stage 2 and 3 in the chatpgt/example/readme file.
Will you please  show us how to finetune the gpt/blooom/opt model with an example dataset ?

**Comment by chingfeng2021** [comment]
确实不知道，这个第一步怎么弄

**Comment by wqw547243068** [comment]
This  [issue](https://github.com/hpcaitech/ColossalAI/issues/2793) says stage 1 is too simple to implement ... 😭

**Comment by yaleimeng** [comment]
Simple or not, the absence of the first stage makes the entire demo incomplete. The finetuing for different models maybe very different. Many beginners feel  confused about it. 
If the authors hasnot finish stage 1 themselves, how can they say easy? If the first step is done, is there any difficulty in sharing relevant resources?

**Comment by wqw547243068** [comment]
I’ve spent some time drawing a diagram to illustrate the calling process, share with you all

<div class="mxgraph" style="max-width:100%;border:1px solid transparent;" data-mxgraph="{&quot;highlight&quot;:&quot;#0000ff&quot;,&quot;nav&quot;:true,&quot;resize&quot;:true,&quot;toolbar&quot;:&quot;zoom layers tags lightbox&quot;,&quot;edit&quot;:&quot;_blank&quot;,&quot;xml&quot;:&quot;&lt;mxfile host=\&quot;app.diagrams.net\&quot; modified=\&quot;2023-03-06T08:57:54.490Z\&quot; agent=\&quot;5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36\&quot; etag=\&quot;JAikWntVZPGOyydFXDpQ\&quot; version=\&quot;21.0.2\&quot;&gt;&lt;diagram id=\&quot;xdYpP7w1t2VaaceZiyqw\&quot; name=\&quot;第 1 页\&quot;&gt;7V1Zc6O4Fv4t94GqmYdQElqAR+Ml3XWn76Qmmb7dTynFxjbTGDyAO8n8+pFYbEBy7CRAvDlT00Yb0jnfkY4+LdZQf/F0HbHl/Es4cX3NAJMnDQ00w4AGNvg/IuQ5CzFtkgXMIm+SJ9oE3Hr/uHkgyENX3sSNKwmTMPQTb1kNHIdB4I6TShiLovCxmmwa+tW3LtnMlQJux8yXQ//vTZJ5FmoZ5ib8k+vN5sWbIbWzmAUrEuctiedsEj6WgtBQQ/0oDJPs2+Kp7/pCeIVcsnyjLbHrikVukOyT4fH6uzPteX5yh+fXwc1fUdRbXFlZKT+Zv8ob3A/9MI6ZyNn7zP/Xn7Pk+uZOG1LNHmoOzb9YOG9V8lyIKnGfeEWcebLweQDkX+MkCn+4osSIhwRhwFM6U8/3a0HM92YBfxzzprg83PnpRonHldDLIxbeZCJe4zzOvcS9XbKxeOcjhxwPi8JVMHFFK4EoPgySHEbQTmMTlnhhkEdnVSpUiXiILMdctKIS7lMpKJfrtRsu3CR65knyWANB3chx/VzF7+MGNIaB9TzRvAQZlKdkOVJn6+I3yuRfcn2qdftfHP9N0N3X+f2M3SWzR/gNDK8MSbeSyjaig1uEW9JmWXGagaZE/OUSL4VnH0n7PIamn7XIJfkqtLBV5NggumVURI6JLHNoGbqpEPpaP41LHUlSTyLmBfeT1WLxrMfzRnUAHxh0DZWsAaDD3kjEFN0OrBmHWTI8350msian6achfWFZX1ShL6TWV2tGgreoaxmFi2USXxRWUhgBCoXhjhVG5F5tSDQbaFx4/IvV03qWNrTEAGX30sGqr/X6BzpY+ezB9R02/jFLw+svrym/pm0wEn/NaJuYlk7MiraRJWvbBh1qmm4xzWhxzlZp6nbV0yBYYZXA0EGXVmmesq8BoVE3DpWvwWc7yq4Qmm1JXfbey77G8rlRHUyIa03wto7yNfbRhEqQrJJDcCfsHe7EmenkIDyGwtWXBxL3kUWT+4UgLU5cM1ivKUY1aJimbpldKgZKipF04E5m7m3+GEbJPJyFAfOHm9CaR7VJ81sYLnMJ/+UmyXMuYrZKwqrmxqvo51rLVX5A6RNYQPzxGC796PlbnjF9+C5qoZPicfCU1yp7ei6enrzkW+l7KRd/2mQSD0WeEkjsNSiEcF6GBJdluIrG7gtayCesCYtmbrJrsJEhFrk+S7yf1XqooJJnvQk9XsM1NBGfx6PavLCgUopSsibkGcsMV60sjGm9LERr4M2aKZWV4nfdqndAeg/S5QLptiGN94S03QqkMZFgiK03QtowZfOol9U2pGVG67ggfVDQpO1AjgrIgc2nOkXE9hvhh6AEP0I6hp/M0GlDU1A6/L8h1pyeZvUFz9MbaD1eNfDHl/TJ0nowZYaGmuVIgJXpn/1pnciNvX/YQ1qUAMtSND0VBnE0MhBlcfTGuUf3CmZpB9+zRnQDHiHBe5AIuEu2B6qIvbKeLc2yK3r+7dPootfdPB5W8HjQ6FS125g8DY2apvLWTNF2RugdVN6ab2pAVRhbEsFePJcpV6hDq0tlKai8uh2Csh3eju4uHe4eHS7YqWpIOrVKmT28vvlTLJ30hpozFEp3BuJ7o+Y5nRrjsco8J/SBkteaZxNmyHtMm2x1nVSrICbtdh1f5q+O0wFfO93fyz73Pg74elpamol+10qz1C3T0gYd91zmO+eUsB2eBBNL8sTpW716mXORymrZqzdk6i8Jo/E8WgUnMXSIz6ihtVkVRWZ/8Nps0QVV+iTqCz3xFzAeM56zKM4thf69ErvcnFUyFTRi8VhRcxEoBHmVKaTHE0Bj+ZQm3WSis/zf9HXxkgXbC5qyhec/Z0X1Ik9sa+MN5lKhbCFGqjztF28chXE4FUbynX1yvXqCPNvQ1hxHs2HqCA00GxXhRAyU3O2phscsiK9iN/Ky1V+wrW15RNYEEROE0YLXdRP3k/HK8385vlmyisSOyBfTjdlyW5LHHB8iEoOslwQ+7/rd6IoLc+wFMzlnGC3nvDFZhJGFCbu8yk2xl5aRj8lZjMeHmyB/DygamsZw5z+Ip7z04j2pRWVoTjdsll7yGEaTarXWZfGWPPzweHGizMxur3J7qKR7WO+vuBpnFiqio9nDL3xulClq84WgX0s1nbjjMEq3D14lc2/8I3DjvHpe4CVeIZ162pImX0xXqk4l3dQPWVIXzsSLlz57LpL7Ho8wwH+8xZIP5ixIlFbCLfA+uPddFif3q9id3Pf/HPTuv36+/ez8NrwfDL9+7g9vC1PiPUFmTYWFqTviXR5fqWc0VD2jbac9o6JTbcKdg5ZebMFdryco1uoJVe8LbK3DVLGor+8wT6fvo5e+79L3tdr3pbQFByQVX2wi2AqxQXCk8am32BdINAekADY0iz8aOZgtS7MHKarNFNUytZFuNOSliZLTHYcOVCWrlcyto6/ZVpqln+e1bZFLWQf+KKbivLaD7SlVDeSNsmCaF2liqaiWJZ3e81xieu9oFloX/svNze93gpZzo1+lXLbYTMlFl+2ndHr5fhZF1XkjLVASn/Q+hVxGhcQHqYB4xqFohqiZeJk2HKXFWiopOy9KtumBrTSQ2emntYEMmbpBK+MYRfI4hkxLB1Qex+rL3s2NY/JyzJ2YuDXKErlobIHNaY3XbJ6p75FNPw1ppMrgIcUWQKvTOZi8YnJXjC5uFJ+BRqCBdLJTKRCgLrUiL3YUR6hOXyGKg1AHoBF5RaN2yO3k9YKQtNZ0AHqRFyAkVRw0r/1GUroBPnzC4vm6zuLhhok5TJCG8MnVGjWNUN+5/eykvjPfoJX9VKC+pv2O/VS7ymqb+pb3iF9gf9SwJ63A3jBsCap1t35f2FugXhSyQaeoR8e+iHlBvcrPbR71SEZ9/fzUvqi3JdRj0DHqT+WEwwX15blE86jHMuqtN6IeAhn29dsO2oa9vDrcGyccXU3OtKaAIcBU8HUGZjZz+qjpllldgFofAC1NtSju9hAcktef+pGXeONz0Qkk1uEpRSZT//hyLgoxita/pBBrTSd1oxCZvLuM14c4XuPiLrBdAzZqh5OAmOrFwahtg+z+nIShwxpranTtqO5xgcMF+EcFfNSOpwpBHfjorcBHclkG6Rj3Fw761HBvtIN7Q8Z9fbPY/vuvZdx3fE4dySS044fhgheWrlSOflesVx7jRuwmz/BAaErXPKrOTXZ6jAfLxGq+i0fS34lOJJC9uVDmgOYSWOb+Avlww7t0wiYmkw9T7bPW3IQ1UFzbfGEolpQJ7Pg+R5l6Stowhw8VPbKpXj7tDw5QD8d+a8TGscLQqrhW+mE4V+k7b9zI4woTY2/TB94KS9rpcWGgBut7bwbio60FX/aS9va4bFsqq2NOHCvusThSg3jrTMMuWcMV0EF6kr5Rk+DZW7SIYmvfbotoZw6CQUMTb2xW14cMirq1BcVdH2dmC2abI8OhmMEWL+a9ZtDUPBxbNTMwOzYDebWBY44l7sxzm92+vcVd5TEPmBKAO/BZCSDS5FkxS7M6XoLDZ058w3I/9Lpb0TomAPd2R9vZmLS+SfK9viiurXsasONeR6a8B4Ob26zjafYSXN7t2BPlZUzM5b240UG3gy1bR+ZmplydBKiuxoLd3u6CZSb2f4zD9FQVgijWy9QFoIemESIzqsV5kd7nU1ULhRKJqlIFhV0q4kx3T37sOLu3d9/ORUeE2lsXWV471FKM6mXZ3Q62RKajLxDeOml9LWn6IbBv59JoCqruJXzrlb20cJSLgjq+r5ecDvF/QXzJH2oe8bA2oQJvRTypIb7ju+yIzOyHy8RbcDBETbuJH83iUGrqgNqbT1XyB0DokGPnlo+NmCl4kN39SDtbcQ3QEDFjmNUTAl2vEBKZDk77kS76kI42LmCsQ6PUe9iHt3GBnDkhfDQ7QoubiHb3Oy0RwrV+R/qpob37nXoH1vHRbHLse6C7227zBrtqEvH7nlKl7XjsGME6R4jq/fC+oCdWDfT1Q94tg57KJO9J7c4kpH411iEMrlRmdL1g6vJGjd1z+wVGFb0OiN7lDUxUZicTN07ux753zj+xLN2VRRU3CEPQ8Q+zUAWxNqSaQ4prNkeaTfLf1TGd9CeANaNfXNRpDiR1nvtxjvpvYKm0vFbnO1XMH6NQ3E67GcO4xcy/iJ+e5YH/Ag==&lt;/diagram&gt;&lt;/mxfile&gt;&quot;}"></div>
<script type="text/javascript" src="https://viewer.diagrams.net/js/viewer-static.min.js"></script>

**Comment by ht-zhou** [comment]
> I’ve spent some time drawing a diagram to illustrate the calling process, share with you all
> 
> ![image](https://user-images.githubusercontent.com/3257257/223063906-5f929737-ac49-4d35-9a88-42feff9d1cbf.png)
> 
> Here is the code to fine-tune the Bloom model, [petals](https://github.com/bigscience-workshop/petals)
> 
> ```python
> from petals import DistributedBloomForCausalLM
> 
> model = DistributedBloomForCausalLM.from_pretrained("bigscience/bloom-petals", tuning_mode="ptune", pre_seq_len=16)
> # Embeddings & prompts are on your device, BLOOM blocks are distributed across the Internet
> 
> inputs = tokenizer("A cat sat", return_tensors="pt")["input_ids"]
> outputs = model.generate(inputs, max_new_tokens=5)
> print(tokenizer.decode(outputs[0]))  # A cat sat on a mat...
> 
> # Fine-tuning (updates only prompts or adapters hosted locally)
> optimizer = torch.optim.AdamW(model.parameters())
> for input_ids, labels in data_loader:
>     outputs = model.forward(input_ids)
>     loss = cross_entropy(outputs.logits, labels)
>     optimizer.zero_grad()
>     loss.backward()
>     optimizer.step()
> ```


Awesome! Thank you so much. Fantastic work, it is amazing.
We are considering to restructure the code, your pic will be a good reference.

**Comment by ht-zhou** [comment]
> Simple or not, the absence of the first stage makes the entire demo incomplete. The finetuing for different models maybe very different. Many beginners feel confused about it. If the authors hasnot finished stage 1 themselves, how can they say easy? If the first step has been done, is there any difficulty in sharing relevant resources?

We do not have the plan to implement stage1 soon, you can refer to https://github.com/hpcaitech/ColossalAI-Examples/tree/main/language to implement the code.
We hope that more people can participate in our open source projects and contribute to us. Thanks a lot ！！

**Comment by Fazziekey** [comment]
Stage 1 is a simple supervised learning process, and we have plans to add a wiki page for this project in the future, so that newcomers who do not understand the field can get started quickly.

**Comment by yaleimeng** [comment]
thanks for answering。That's very helpful.
