### ISSUE TITLE
有什么训练策略是可以直接在单机单显卡运行的吗？[DOC]: 

### ISSUE THREAD

**Issue by chingfeng2021** [hpcaitech/ColossalAI#2985]
### 📚 The doc issue

有相关的文档说明吗

**Comment by JThh** [comment]
Try this one out: https://github.com/hpcaitech/ColossalAI/tree/main/examples/language/gpt/gemini

**Comment by chingfeng2021** [comment]
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./train_gpt_demo.py", line 353, in <module>
    main()
  File "./train_gpt_demo.py", line 267, in main
    model = zero_model_wrapper(model, zero_stage, gemini_config)
  File "/opt/conda/lib/python3.8/site-packages/colossalai/nn/parallel/zero_wrapper.py", line 43, in zero_model_wrapper
    wrapped_model = GeminiDDP(model, **gemini_config)
  File "/opt/conda/lib/python3.8/site-packages/colossalai/nn/parallel/gemini_parallel.py", line 63, in __init__
    super().__init__(module, gemini_manager, pin_memory, force_outputs_fp32, strict_ddp_mode)
  File "/opt/conda/lib/python3.8/site-packages/colossalai/nn/parallel/data_parallel.py", line 242, in __init__
    self._init_chunks(param_order=param_order,
  File "/opt/conda/lib/python3.8/site-packages/colossalai/nn/parallel/data_parallel.py", line 670, in _init_chunks
    self.chunk_manager.register_tensor(tensor=fp32_p,
  File "/opt/conda/lib/python3.8/site-packages/colossalai/gemini/chunk/manager.py", line 71, in register_tensor
    self.__close_one_chunk(chunk_group[-1])
  File "/opt/conda/lib/python3.8/site-packages/colossalai/gemini/chunk/manager.py", line 228, in __close_one_chunk
    chunk.close_chunk()
  File "/opt/conda/lib/python3.8/site-packages/colossalai/gemini/chunk/chunk.py", line 302, in close_chunk
    self.cpu_shard = torch.empty(self.shard_size, dtype=self.dtype, pin_memory=self.pin_memory)
RuntimeError: CUDA error: out of memor

**Comment by chingfeng2021** [comment]
这个需要什么配置才能跑起来呢 @JThh

**Comment by JThh** [comment]
Can I know what's your current configuration? 你目前的配置是怎样的呢？

**Comment by chingfeng2021** [comment]
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 530.30.02              Driver Version: 531.18       CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                  Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce GTX 1070         On | 00000000:01:00.0 Off |                  N/A |
| 45%   47C    P8                8W / 150W|      0MiB /  8192MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce RTX 3080         On | 00000000:03:00.0  On |                  N/A |
|  0%   46C    P8               21W / 340W|   1126MiB / 10240MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+

**Comment by chingfeng2021** [comment]
@JThh  这是我目前的配置 2张显卡 ，3080 + 1070

**Comment by chingfeng2021** [comment]
我把batchsize都调的很小，还是说内存不够
export PLACEMENT=${PLACEMENT:-"cput"}   ----> 这个参数是不是应该设置为cuda

**Comment by pecanjk** [comment]
> 我把batchsize都调的很小，还是说内存不够 export PLACEMENT=${PLACEMENT:-"cput"} ----> 这个参数是不是应该设置为cuda

你跑多大的gpt2，报错的

**Comment by JThh** [comment]
Take a look at [this](https://github.com/hpcaitech/ColossalAI/tree/main/applications/Chat#faq).

**Comment by binmakeswell** [comment]
We have updated a lot. Please check the latest code. This issue was closed due to inactivity. Thanks.
