### ISSUE TITLE
[BUG]: [DIFFUSION]: While marked as closed issue #2204 still persists, 

### ISSUE THREAD

**Issue by Thomas2419** [hpcaitech/ColossalAI#2991]
### 🐛 Describe the bug

Issue #2204 while the main issue was solved the other that cropped up and was marked closed by pull request #2356 seemed to be a solution that was implemented onto the Dreambooth area, and not the main diffusion one, is this get static torch model a solution that we should be manually implementing into the Diffusion one and it will fix it or was the fix simply for the same type of problem but affecting dreambooth, as still finetuning diffusion does not produce discernable results and only makes random noise.

**Comment by binmakeswell** [comment]
We have updated a lot. Please check the latest code. This issue was closed due to inactivity. 
If you have further questions, please [open another new issue](https://github.com/hpcaitech/ColossalAI/issues/new/choose) and provide details. Because everyone's issue details may be different. Thanks.
