### ISSUE TITLE
The rm model which ppo train step3 requires ，but I can not find where to input this param in example ! pls help me out 

### ISSUE THREAD

**Issue by taishiciR** [hpcaitech/ColossalAI#3009]
https://github.com/hpcaitech/ColossalAI/blob/82503a96f20c2e61016af78445f9d1697ac07dd5/applications/ChatGPT/examples/train_prompts.py#L115

**Comment by binmakeswell** [comment]
Hi @taishiciR you can use --pretrain <your pretrain model name/path>
https://github.com/hpcaitech/ColossalAI/tree/main/applications/ChatGPT/examples#inference-exampleafter-stage3
