### ISSUE TITLE
What does the parameter 'max_length=96' mean here?

### ISSUE THREAD

**Issue by taishiciR** [hpcaitech/ColossalAI#3045]
https://github.com/hpcaitech/ColossalAI/blob/ea0b52c12ee7598fe126ed0d8b0557f7e8a0e999/applications/ChatGPT/examples/train_prompts.py#L72

What does the parameter 'max_length=96' mean here? Can it be changed to 256 or something？

**Comment by JThh** [comment]
Check out https://huggingface.co/docs/transformers/main_classes/tokenizer#transformers.PreTrainedTokenizer.__call__.max_length. And I believe it can be adjusted as you wish (but be mindful about model input lengths as well).

**Comment by taishiciR** [comment]
thx~
