### ISSUE TITLE
Shouldn't the output of the critic be generated for each individual time step, rather than averaged over the entire sequence?

### ISSUE THREAD

**Issue by zhangyipin** [hpcaitech/ColossalAI#3047]
https://github.com/hpcaitech/ColossalAI/blob/29386a54e66d7e5ca40cabf1686839fba9aac71d/applications/ChatGPT/chatgpt/models/base/critic.py#L46

**Comment by binmakeswell** [comment]
This issue was closed due to inactivity. Thanks.
