### ISSUE TITLE
[BUG]: diffusion train question

### ISSUE THREAD

**Issue by Chenhuaqi6** [hpcaitech/ColossalAI#3048]
### 🐛 Describe the bug

/home/chenhq/anaconda3/envs/ldm/lib/python3.9/site-packages/lightning-1.9.0-py3.9.egg/lightning/pytorch/loggers/tensorboard.py:188: UserWarning: Could not log computational graph to TensorBoard: The `model.example_input_array` attribute is not set or `input_array` was not given.
  rank_zero_warn(
/home/chenhq/anaconda3/envs/ldm/lib/python3.9/site-packages/lightning-1.9.0-py3.9.egg/lightning/pytorch/strategies/ddp.py:437: UserWarning: Error handling mechanism for deadlock detection is uninitialized. Skipping check.
  rank_zero_warn("Error handling mechanism for deadlock detection is uninitialized. Skipping check.")
Summoning checkpoint.

run python main.py --logdir ./tmp/ --train --base configs/Teyvat/train_colossalai_teyvat.yaml --ckpt 512-base-ema.ckpt , No output but gpu 100%, Can you help me what the problem is?

### Environment

cuda11.2 
python3.9
pytorch 1.10.0

**Comment by JThh** [comment]
Hi, what does it mean by no output? Can you show me the full execution message log? Thanks

**Comment by Chenhuaqi6** [comment]
[logs.txt](https://github.com/hpcaitech/ColossalAI/files/10919313/logs.txt)
Wait here, wait for an hour or so, no more output

**Comment by JThh** [comment]
@Fazziekey , can you take a look at this issue? Thanks

**Comment by Fazziekey** [comment]
> @Fazziekey , can you take a look at this issue? Thanks

ok

**Comment by Chenhuaqi6** [comment]
@Fazziekey @JThh sorry, my dataset is error,  is runing now.   I will close this issue, Thanks

**Comment by Fazziekey** [comment]
> @Fazziekey @JThh sorry, my dataset is error, is runing now. I will close this issue, Thanks

Thanks
