### ISSUE TITLE
[test] add test set for mainstream model zoos

### ISSUE THREAD

**Issue by FrankLeeeee** [hpcaitech/ColossalAI#3049]
# Overview

We should regularly test on a set of mainstream models as a coverage test. This could help to ensure that our features work reliably on the most models that users use. This test set should include timm, torchvision, torchaudio, huggingface transformers, diffusers, and etc.

**Comment by super-dainiu** [comment]
I am doing some related work recently. can discuss later if necessary

**Comment by FrankLeeeee** [comment]
@super-dainiu  We have set up some test model zoo . Do you wanna join?

**Comment by super-dainiu** [comment]
omg I feel this model zoo is good enough haha

**Comment by super-dainiu** [comment]
https://github.com/huggingface/transformers/blob/1c4a9acc7319221643555c0e8ff1fda2f758c400/src/transformers/utils/fx.py#L103

but there are more transformers here.

**Comment by FrankLeeeee** [comment]
@super-dainiu welcome to contribute to the test model zoo if you like :)

**Comment by FrankLeeeee** [comment]
I will close this issue for now as the planned models are included by #3129 , #3132 , #3135 , #3136, #3139  and #3138 .
