### ISSUE TITLE
In this code line -  trainer.fit(dataset, ...), What is the dataset need to be considered. 

### ISSUE THREAD

**Issue by Pradeep-Vanapalli** [hpcaitech/ColossalAI#3059]
### 🐛 Describe the bug

I am running the code in the NaiveStrategy and trying to train by giving the dataset path as  "ChatGPT/chatgpt/dataset/". But it is throwing the error as "Ellipsis object cannot be interpreted as an integer". 

When I am trying to pass as follows, 
trainer.fit('ChatGPT/chatgpt/dataset/', 5)
It is throwing error as "unsupported type <class list>" And the value for the inputs taking is ['a', 'o', 't', 'd', 'c', '/', 't', '/'].

Please suggest if it is related dataset need to be take or any other thing.

**Comment by Fazziekey** [comment]
you can refer the datasets we use to build your own datasets:https://huggingface.co/datasets/Anthropic/hh-rlhf

**Comment by Pradeep-Vanapalli** [comment]
Thank You Fazziekey for the prompt response...!!!

I used the same dataset but still facing below error.
TypeError: 'ellipsis' object cannot be interpreted as an integer

In the code line  trainer.fit(dataset, ...), What is the meaning of  "..."

**Comment by binmakeswell** [comment]
Hi @Pradeep-Vanapalli We have updated a lot. Please check the latest code. This issue was closed due to inactivity. Thanks.
