### ISSUE TITLE
[BUG]: 单机单卡和单机八卡训练时间一样

### ISSUE THREAD

**Issue by Vvvvvvsysy** [hpcaitech/ColossalAI#3077]
### 🐛 Describe the bug

为什么我用单机单卡、单机四卡（TP--2D）和单机八卡（TP--3D）三种训练方式，显卡显存占用和训练时间都是一样的？并没有感觉到colossal在对我的训练进行加速！！ 
如何才能知道自己的模型有没有在做并行计算呢？

**Comment by pilipala818** [comment]
你好，我也遇到相同的问题。
基于https://github.com/hpcaitech/ColossalAI-Examples/tree/main/features/tensor_parallel项目进行测试，
例如，单卡消耗1707m显存，倘若四卡张量并行，每张卡应消耗430m左右，但实际测试是每张卡消耗1723m。
仅修改关键参数（nproc per node），其余不变。请问是我理解或操作有误嘛？请指正，谢谢

**Comment by Vvvvvvsysy** [comment]
> 你好，我也遇到相同的问题。 基于https://github.com/hpcaitech/ColossalAI-Examples/tree/main/features/tensor_parallel 项目进行测试， 例如，单卡消耗1707m显存，倘若四卡张量并行，每张卡应消耗430m左右，但实际测试是每张卡消耗1723m。 仅修改关键参数（nproc per node），其余不变。请问是我理解或操作有误嘛？请指正，谢谢

你用官方的代码也是这样吗？这个问题困扰我们很久了，我们在单机单卡和单机八卡这两种设置下，显存消耗和时间消耗都是一样的，像是一种假并行。假如你能解决这个问题，请务必回复我，非常感谢！！

**Comment by pilipala818** [comment]
> > 你好，我也遇到相同的问题。 基于https://github.com/hpcaitech/ColossalAI-Examples/tree/main/features/tensor_parallel 项目进行测试， 例如，单卡消耗1707m显存，倘若四卡张量并行，每张卡应消耗430m左右，但实际测试是每张卡消耗1723m。 仅修改关键参数（nproc per node），其余不变。请问是我理解或操作有误嘛？请指正，谢谢
> 
> 你用官方的代码也是这样吗？这个问题困扰我们很久了，我们在单机单卡和单机八卡这两种设置下，显存消耗和时间消耗都是一样的，像是一种假并行。假如你能解决这个问题，请务必回复我，非常感谢！！

暂未解决该问题，本人实验并未记录时间消耗。
在验证官方代码时，张量的切分是正常的，但显存占用对不上。
例如，四卡情况下，在1d切分时，输入256*1024，张量切分为256*256
                                 在2d切分时，输入256*1024，张量切分为128*512

**Comment by Vvvvvvsysy** [comment]
> > > 你好，我也遇到相同的问题。 基于https://github.com/hpcaitech/ColossalAI-Examples/tree/main/features/tensor_parallel 项目进行测试， 例如，单卡消耗1707m显存，倘若四卡张量并行，每张卡应消耗430m左右，但实际测试是每张卡消耗1723m。 仅修改关键参数（nproc per node），其余不变。请问是我理解或操作有误嘛？请指正，谢谢
> > 
> > 
> > 你用官方的代码也是这样吗？这个问题困扰我们很久了，我们在单机单卡和单机八卡这两种设置下，显存消耗和时间消耗都是一样的，像是一种假并行。假如你能解决这个问题，请务必回复我，非常感谢！！
> 
> 暂未解决该问题，本人实验并未记录时间消耗。 在验证官方代码时，张量的切分是正常的，但显存占用对不上。 例如，四卡情况下，在1d切分时，输入256_1024，张量切分为256_256 在2d切分时，输入256_1024，张量切分为128_512

**Comment by Vvvvvvsysy** [comment]
> 

来我主页，我们邮箱交流一下把！

**Comment by laozhanghahaha** [comment]
@Vvvvvvsysy 你好，请问你解决这个问题了么，我也出现了同样的情况。在训练https://github.com/hpcaitech/ColossalAI/tree/main/examples/language/opt 时 ，单卡，八卡，四卡，gpu memory usage几乎是一样的

**Comment by kurisusnowdeng** [comment]
Hi @pilipala818 @Vvvvvvsysy ，用[`torch.cuda.memory_allocated`](https://pytorch.org/docs/stable/generated/torch.cuda.memory_allocated.html#torch.cuda.memory_allocated)和[`torch.cuda.max_memory_allocated`](https://pytorch.org/docs/stable/generated/torch.cuda.max_memory_allocated.html#torch.cuda.max_memory_allocated)来测显存占用会比较精确。测时间的时候需要注意加上[`torch.cuda.synchronize`](https://pytorch.org/docs/stable/generated/torch.cuda.synchronize.html#torch.cuda.synchronize)

**Comment by zhangyuanscall** [comment]
> 

运行GPT2 gemini的examples时候，我用nvidia-smi命令，观察单卡和多卡占用的显存都是一样的，batch=16时候单卡15935Mi，但是在日志中观察发现：
`[03/27/23 17:24:22] INFO     colossalai - colossalai - INFO: ./train_gpt2.py:366 train_step
                    INFO     colossalai - colossalai - INFO: [1/20] Forward GPU memory usage: 2034.80 MB, CPU memory usage: 15982.80 MB
[03/27/23 17:24:33] INFO     colossalai - colossalai - INFO: ./train_gpt2.py:377 train_step
                    INFO     colossalai - colossalai - INFO: [1/20] Backward GPU memory usage: 486.07 MB, CPU memory usage: 15982.81 MB`

NVidai-smi显示的显存数值和日志里面的CPU Memory的数值是一样？

**Comment by kurisusnowdeng** [comment]
> > 
> 
> 运行GPT2 gemini的examples时候，我用nvidia-smi命令，观察单卡和多卡占用的显存都是一样的，batch=16时候单卡15935Mi，但是在日志中观察发现： `[03/27/23 17:24:22] INFO colossalai - colossalai - INFO: ./train_gpt2.py:366 train_step INFO colossalai - colossalai - INFO: [1/20] Forward GPU memory usage: 2034.80 MB, CPU memory usage: 15982.80 MB [03/27/23 17:24:33] INFO colossalai - colossalai - INFO: ./train_gpt2.py:377 train_step INFO colossalai - colossalai - INFO: [1/20] Backward GPU memory usage: 486.07 MB, CPU memory usage: 15982.81 MB`
> 
> NVidai-smi显示的显存数值和日志里面的CPU Memory的数值是一样？

`nvidia-smi`的结果并不准确因为还包含pytorch的reserved memory，不过从你的结果也能侧面证明大部分显存开销已经被offload到RAM上了

**Comment by binmakeswell** [comment]
This issue was closed due to inactivity. If you have further questions, please [open another new issue](https://github.com/hpcaitech/ColossalAI/issues/new/choose) and provide details. Thanks.
