### ISSUE TITLE
[chatgpt]: the policy loss and value loss of PPO may be incorrect

### ISSUE THREAD

**Issue by wenjunyang** [hpcaitech/ColossalAI#3078]
In training_step of PPOTrainer, the `advantage` and `penalty` are computed by the old Actor during making experience. while the ValueLoss  computed with clamp. i think they are incorrect.here is the reason:
1. penalty should be recomputed by the current Actor.
2. Critic is indepentant with action, and no matter the experence is collected by the old Actor or the current Actor, the distribution of state(prompts) are the same. so the ValueLoss should be the same as A2C without PPO.

Below is my conclusion about the policy loss and the value loss:
![image](https://user-images.githubusercontent.com/2840667/224193915-adb56a35-857a-4f01-82e6-bdc710c324b0.png)

Red part in below should be collected by the old Actor during making experience:
![image](https://user-images.githubusercontent.com/2840667/224194095-2d9d14cc-862e-4cdd-a2e6-f4ddc3d32d36.png)

Green part in below should be computed by the current Actor and Critic:
![image](https://user-images.githubusercontent.com/2840667/224071977-60a9a93a-37d4-4caa-8aac-88c26c051b4e.png)

So, please consider the above questions, I will submit a PR, you can compare the difference by code.

**Comment by wenjunyang** [comment]
more details: [https://openreview.net/forum?id=chDrutUTs0K](https://openreview.net/forum?id=chDrutUTs0K))
![image](https://user-images.githubusercontent.com/2840667/224195054-682b6b30-7c7b-4217-bc7c-a7aaef4e70c4.png)
![image](https://user-images.githubusercontent.com/2840667/224195093-0d70970b-eebf-4176-b9fc-b01c260065b4.png)
![image](https://user-images.githubusercontent.com/2840667/224195255-c9c2b96f-b8bd-4dd8-a396-1ee752716035.png)
![image](https://user-images.githubusercontent.com/2840667/224194939-6d84312e-0d52-43f5-a803-67cd6f52ee44.png)

**Comment by ht-zhou** [comment]
Thanks for your feedback.
1\ the change in value_loss computation is reasonable because of the change of the input of critic from sentence to prompt;
2\I have think about your last pr again.And I think we can use action-value function here (which Openai only menentioned as value funciton)

**Comment by ht-zhou** [comment]
Because RM's input is sequence, so it will be more reasonable here to use (state + action)as input.
We will set a bool flag here to offer different choice.

**Comment by ht-zhou** [comment]
As for this problem, what you wanna to do is to change the calculation of ADV from Experience-maker to PPO-trainer, I have to think more about the details here.
You can notice that we compute KL_div between action_log and base_log and the base_model is never changed, so the whole algo has many difference to classic PPO, we have to consider more about it.

**Comment by wenjunyang** [comment]
here are two my points: 
1. ADV can calculated in Experience-maker, but the KL penalty between Actor and base should be calculated in training step using current Actor, instead of using old Actor.
2. Critic is indenpent with action, so value loss should not care about change of action distribution. through Critic and RM are the same model structure, their input are not same.  Critic take prompt as input. RM take (prompt, action) or only action as input, i think thw two all all ok, because action prob already info about prompt,  i may prefer (prompt, action) as input.

**Comment by ehion** [comment]
> 

totally agree。
instruct-gpt use tuned language model as Pi_actor and sft is the what we wanna optimize，but in colossalai example Pi_actor and Pi_sft is the same model when initialized and the only difference is copy.deepcopy。i think Pi_actor and Pi_sft have the same model structure with the different parameters。
