### ISSUE TITLE
[BUG]: ChatGPT - There is a possibility that the generation is not working properly.

### ISSUE THREAD

**Issue by brcps12** [hpcaitech/ColossalAI#3088]
### 🐛 Describe the bug

`generate_kwargs` is not properly passed to `PPOTrainer`. So, generating sentences might be incorrect. (At leat in my case)

https://github.com/hpcaitech/ColossalAI/blob/5d5f475d758347b5e61dbb4b0ccb6108821e3e93/applications/ChatGPT/chatgpt/trainer/ppo.py#L64-L76

Like Huggingface GPT2 Model, `prepare_inputs_fn` and `update_model_kwargs_fn` should be passed to generate. But in that code, these functions are not applied because `_set_default_generate_kwargs()` is called after `super().__init__()`

So, I think the order of call should be changed.

**Comment by ver217** [comment]
Hi, `_set_default_generate_kwargs()` will modify `generate_kwargs` inplace, so this is OK. But I agree the order is bad and we will update this. 

Thanks for your suggestion!

**Comment by ver217** [comment]
Can you create a PR to solve this problem? All contribution is welcome.
