### ISSUE TITLE
[PROPOSAL]: A significant improvement in user-friendliness

### ISSUE THREAD

**Issue by nemoramo** [hpcaitech/ColossalAI#3095]
### Proposal

The load_checkpoint method in "colossalai.utils.checkpoint" cannot scatter large model state dict parameters since the gather operations will first fill the gpu memory and cause OOM problems. The proposal is to gather parameters step by step.

### Self-service

- [X] I'd be willing to do some initial work on this proposal myself.

**Comment by FrankLeeeee** [comment]
Hi, @nemoramo , we are currently working on that. Are you interested to be part of the development?

**Comment by nemoramo** [comment]
sure

**Comment by nemoramo** [comment]
> sure



> Hi, @nemoramo , we are currently working on that. Are you interested to be part of the development?

sure

**Comment by FrankLeeeee** [comment]
> > Hi, @nemoramo , we are currently working on that. Are you interested to be part of the development?
> 
> sure

You can join our development channel via 
https://colossalaiworkspace.slack.com/archives/C04S86SEFCP

There is developer guide for your reference 
https://github.com/hpcaitech/ColossalAI/wiki/2.-Developer-Guideline

**Comment by binmakeswell** [comment]
We have updated a lot. Please check the latest code. This issue was closed due to inactivity. Thanks.
