### ISSUE TITLE
[BUG]: cannot meta info prop unet on cpu

### ISSUE THREAD

**Issue by oahzxl** [hpcaitech/ColossalAI#3096]
### 🐛 Describe the bug

Cannot meta info prop unet (from diffusers import UNet2DModel) on cpu.
I can run unet on cpu and cuda, and meta info prop it on cuda but not on cpu.
The error message is
<img width="1186" alt="image" src="https://user-images.githubusercontent.com/43881818/224244365-0819ecaf-4583-44fb-adf3-1126389bed05.png">
It seems that groupnorm caused this problem and there is a view in groupnorm kernel. So I check its cpp code, and I find some lines of code maybe related with view.
<img width="587" alt="image" src="https://user-images.githubusercontent.com/43881818/224244878-eccac23a-6bc1-4432-a87a-b88b08f5db35.png">
So I guess for cpu, there is problem for suggest_memory_format() for some unknown reasons, maybe due to meta. Then I change the code by simply contiguous every tensor and solved this problem. But its very ugly.
<img width="664" alt="image" src="https://user-images.githubusercontent.com/43881818/224245104-4d582653-ce77-4cf5-a196-550d2e9817ae.png">

### Environment

torch 1.12.1, cuda 11.3, diffusers 0.10.2

**Comment by super-dainiu** [comment]
It's okay for now I guess.
I am not seriously considering the real tensor layout.
so if this hack works it will be fine

**Comment by oahzxl** [comment]
Great, thanks.
