### ISSUE TITLE
[BUG]: chatGPT-OOM of opt-6b7

### ISSUE THREAD

**Issue by alisyzhu** [hpcaitech/ColossalAI#3100]
### 🐛 Describe the bug

i want to run train_reward_model.py with opt-6b7, but failed. 

parameters:
--strategy colossalai_gemini
<img width="1228" alt="image" src="https://user-images.githubusercontent.com/127492258/224286499-325d6402-77a1-4c96-9db4-0a4e69088c10.png">

### Environment

v100 * 4

**Comment by JThh** [comment]
You might be interested to change [line](https://github.com/hpcaitech/ColossalAI/blob/c9dd036592ee97e73faa9934831d2f8f7184e9b7/applications/ChatGPT/examples/train_reward_model.py#L27) to use 'cpu' placement strategy and see if the issue persists!

**Comment by alisyzhu** [comment]
> You might be interested to change [line](https://github.com/hpcaitech/ColossalAI/blob/c9dd036592ee97e73faa9934831d2f8f7184e9b7/applications/ChatGPT/examples/train_reward_model.py#L27) to use 'cpu' placement strategy and see if the issue persists!

i set placement_strategy='cpu', but not work ...
<img width="1229" alt="image" src="https://user-images.githubusercontent.com/127492258/224302382-f5b6b9fb-7439-47b1-ba8d-d2a14bcd898c.png">

**Comment by JThh** [comment]
Are you using the default batch size? Can you make it smaller to be `1`?

**Comment by binmakeswell** [comment]
Hi @alisyzhu We have updated a lot. Please check the latest code. This issue was closed due to inactivity. Thanks.
