### ISSUE TITLE
[DOC]: 请问该如何准备数据集？或者哪里有开源的数据集下载

### ISSUE THREAD

**Issue by Rex-LK** [hpcaitech/ColossalAI#3112]
### 📚 The doc issue

如题，请问该如何准备数据集？或者哪里有开源的数据集下载？

**Comment by twwch** [comment]
> ### 📚 The doc issue
> 如题，请问该如何准备数据集？或者哪里有开源的数据集下载？

请问你找到处理数据集的方法了么？
