### ISSUE TITLE
[BUG]: inference.py

### ISSUE THREAD

**Issue by JingxinLee** [hpcaitech/ColossalAI#3123]
### 🐛 Describe the bug

```python
python inference.py --model_path ./actor_checkpoint_prompts.pt --pretrain bloom-560m --model bloom 
```

```bash
 size mismatch for transformer.ln_f.weight: copying a param with shape torch.Size([768]) from checkpoint, the shape in current model is torch.Size([1024]).
 size mismatch for transformer.ln_f.bias: copying a param with shape torch.Size([768]) from checkpoint, the shape in current model is torch.Size([1024]).
 size mismatch for lm_head.weight: copying a param with shape torch.Size([50257, 768]) from checkpoint, the shape in current model is torch.Size([250880, 1024]).
```

**Comment by ht-zhou** [comment]
Thanks for your feedback, please update your code to our newest pr, this problem has been solved.

**Comment by JingxinLee** [comment]
> Thanks for your feedback, please update your code to our newest pr, this problem has been solved.

I am sure I used the latest code. Problem still exists.

**Comment by ht-zhou** [comment]
There may be some problems with the old ckpt.
I suggest you to train a new one for few epochs to test.

**Comment by 1a2cjitenfei** [comment]
> There may be some problems with the old ckpt. I suggest you to train a new one for few epochs to test.
How to realize stage1 of chatGPT training? Can you explain it in detail

**Comment by 1a2cjitenfei** [comment]
> There may be some problems with the old ckpt. I suggest you to train a new one for few epochs to test.
How to realize stage1 of chatGPT training? Can you explain it in detail

**Comment by 1a2cjitenfei** [comment]
> There may be some problems with the old ckpt. I suggest you to train a new one for few epochs to test.

How to realize stage1 of chatGPT training? Can you explain it in detail

**Comment by ht-zhou** [comment]
> ? Can you explain it in detail

You can use a human-writing dataset to fine tune a pretrained language model like Bloom/Lamma.

**Comment by JingxinLee** [comment]
> There may be some problems with the old ckpt. I suggest you to train a new one for few epochs to test.

I trained new one. And this problem still exist.

**Comment by 1a2cjitenfei** [comment]
> > ? Can you explain it in detail
> 
> You can use a human-writing dataset to fine tune a pretrained language model like Bloom/Lamma.

How to operate it? Using the hugging face? However, the GPU video memory that can be supported by using the hugging face is ColossalAI 1/10. This problem will come back. It is recommended to add stage1

**Comment by ht-zhou** [comment]
> > There may be some problems with the old ckpt. I suggest you to train a new one for few epochs to test.
> 
> I trained new one. And this problem still exist.
You can refer to our test_ci in https://github.com/hpcaitech/ColossalAI/blob/main/applications/ChatGPT/examples/test_ci.sh
 to try. We have already completed the ci process of this application, so it may not have this problem because the code has passed this ci.

**Comment by ht-zhou** [comment]
> 

Ok, we will add stage 1 soon.

**Comment by ht-zhou** [comment]
> > > ? Can you explain it in detail
> > 
> > 
> > You can use a human-writing dataset to fine tune a pretrained language model like Bloom/Lamma.
> 
> How to operate it? Using the hugging face? However, the GPU video memory that can be supported by using the hugging face is ColossalAI 1/10. This problem will come back. It is recommended to add stage1

Ok, we will support stage1 in our example soon.
