### ISSUE TITLE
[lazyinit] add correctness verification

### ISSUE THREAD

**Issue by ver217** [hpcaitech/ColossalAI#3134]
## Overview

Current implementation is not tested on many models. We have to add large scale correctness verification.

Wanna track the development progress? Take a look at

proposal: https://github.com/hpcaitech/ColossalAI/discussions/3124
kanban: https://github.com/orgs/hpcaitech/projects/20

## Goal

Pass the most models in torchvision, timm, transformers, torchrec, torchaudio and diffusers.

**Comment by super-dainiu** [comment]
I think it might be hard to satisfy torch.all_close condition.
checking the norm of weights might be an alternative.
