### ISSUE TITLE
Need an integrated configuration tutorial for users to customize their applications

### ISSUE THREAD

**Issue by kurisusnowdeng** [hpcaitech/ColossalAI#314]
### 📚 The doc issue

Just like what deepspeed has https://www.deepspeed.ai/docs/config-json/ .

**Comment by feifeibear** [comment]
Did we have the doc?

**Comment by FrankLeeeee** [comment]
> Did we have the doc?

The current doc has the configuration for each feature.

**Comment by binmakeswell** [comment]
We have updated a lot. This issue was closed due to inactivity. Thanks.
For example https://github.com/hpcaitech/ColossalAI/tree/main/applications/Chat/examples
