### ISSUE TITLE
[BUG]: Module version incompatibility found when training the stable diffusion model in /examples/images/difffusion

### ISSUE THREAD

**Issue by NatalieC323** [hpcaitech/ColossalAI#3169]
### 🐛 Describe the bug

I met an error when I was trying to start the environment by downloading the requirements.txt. The error says it can not find a compatible version of 'opencv-python', and 'torchmetrics' is not compatible with the existing environment. Similarly, it runs with various incompatibilities since the torch has released a new version and some default module version will support torch 1.13.1 instead of torch 1.12.1. 

cd Colossal AI/examples/images/diffusion
pip install -r requirements

### Environment

CUDA ==11.8
Python=3.9

**Comment by JThh** [comment]
Can you try creating a docker environment with this [file](https://github.com/hpcaitech/ColossalAI/blob/main/examples/images/diffusion/docker/Dockerfile)?
