### ISSUE TITLE
terminate called after throwing an instance of 'c10::CUDAError'    

### ISSUE THREAD

**Issue by Arsmart123** [hpcaitech/ColossalAI#318]
### 🐛 Describe the bug

![image](https://user-images.githubusercontent.com/65449458/156759648-dcf967b0-a727-42d9-b1d9-76531c38364f.png)
This error often happens, well, mostly after the training, but not sure whether related to colossalai (maybe not?) I searched this error on google, but other people also do not provide some useful suggestion. I am just wondering does any other user also meet this error when using colossalai? 

Thank you!!

**Comment by FrankLeeeee** [comment]
Hi, did you use `torchrun` to execute this?

**Comment by Arsmart123** [comment]
> Hi, did you use `torchrun` to execute this?

oh! I did not! Let me try it. Thanks!

**Comment by FrankLeeeee** [comment]
In general, this issue is due to improper process termination by the launcher. Don't worry about it if you can get the results you want.
