### ISSUE TITLE
[PROPOSAL]: [chatgpt] add code for  fine-tuning supervised model 

### ISSUE THREAD

**Issue by pgzhang** [hpcaitech/ColossalAI#3182]
### Proposal

Based on the instructions by InstructGPT, training the model involves three steps. ColossalAI has already implemented steps 2 and 3. Although there is code available for pretraining large language models (such as GPT) in this project, it does not fit well with ChatGPT. Therefore, I have written the code for step 1, which involves fine-tuning the model using supervised learning.

### Self-service

- [X] I'd be willing to do some initial work on this proposal myself.

**Comment by ht-zhou** [comment]
Fantastic work !! Thanks for your contribution !! 
We will check your pr soon, and add ci about it.
