### ISSUE TITLE
please add reward model eval scripts

### ISSUE THREAD

**Issue by akk-123** [hpcaitech/ColossalAI#3189]
### Describe the feature

@ht-zhou  I notice RM training and [training result](https://github.com/hpcaitech/ColossalAI/blob/main/applications/ChatGPT/examples/README.md#experiment-result)  is updated,  can you share the eval data and scripts?
what' more, I think you cite the wrong paper, It should be https://arxiv.org/pdf/2204.05862.pdf

**Comment by Camille7777** [comment]
hi, @akk-123, thanks for your suggestion, and the paper link has been updated.
