### ISSUE TITLE
Maybe to "cpu"?

### ISSUE THREAD

**Issue by gongel** [hpcaitech/ColossalAI#3196]
https://github.com/hpcaitech/ColossalAI/blob/e7f3bed2d36c5406e9a9ab92438be46a5f9258d7/applications/ChatGPT/chatgpt/replay_buffer/naive.py#L46

**Comment by JThh** [comment]
No, it should not be. The final output should be on target device, and it was initially on cpu if `cpu_offload` is enabled!

**Comment by gongel** [comment]
ok. thx
