### ISSUE TITLE
[BUG]: ModuleNotFoundError: No module named 'chatgpt.models'

### ISSUE THREAD

**Issue by Aadedd** [hpcaitech/ColossalAI#3201]
### 🐛 Describe the bug

when i do [Inference example(After Stage3)]

Traceback (most recent call last):
  File "inference.py", line 5, in <module>
    from chatgpt.models.gpt import GPTActor
ModuleNotFoundError: No module named 'chatgpt.models'
pip3 list -> chatgpt   0.1.0
How can I solve this problem

**Comment by Camille7777** [comment]
hii, @Aadedd can you try with `pip install .` under the directory `~/ColossalAI/applications/ChatGPT`?

**Comment by Aadedd** [comment]
<img width="1081" alt="image" src="https://user-images.githubusercontent.com/31611061/227418924-83039e8a-7ef6-4bfa-990d-ed732ad0e00e.png">

**Comment by Aadedd** [comment]
@Camille7777 I've done that, but it still doesn't work

**Comment by Camille7777** [comment]
> <img alt="image" width="1081" src="https://user-images.githubusercontent.com/31611061/227418924-83039e8a-7ef6-4bfa-990d-ed732ad0e00e.png">

it seems like an enviroment problem. Can you share the packages in your env `python37` using `conda list`, and also use `which python3` to ensure you are running the script in correct env?

**Comment by Camille7777** [comment]
> > <img alt="image" width="1081" src="https://user-images.githubusercontent.com/31611061/227418924-83039e8a-7ef6-4bfa-990d-ed732ad0e00e.png">
> 
> Hiii @Aadedd it seems like an enviroment problem. Can you share the packages in your env `python37` using `conda list`, and also use `which python3` to ensure you are running the script in correct env?

**Comment by Aadedd** [comment]
@Camille7777 Python 3.7.16 (default, Jan 17 2023, 22:20:44) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import chatgpt
>>> from chatgpt.models.gpt import GPTActor
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'chatgpt.models'

**Comment by Aadedd** [comment]
@Camille7777 
<img width="670" alt="image" src="https://user-images.githubusercontent.com/31611061/227430602-8d9b6ec2-c6ad-4607-9ccd-b38c35e95005.png">

**Comment by Aadedd** [comment]
@Camille7777 
<img width="635" alt="image" src="https://user-images.githubusercontent.com/31611061/227430902-64f6b90b-7fa0-40f0-835c-02d83559a922.png">

**Comment by Camille7777** [comment]
> @Camille7777 <img alt="image" width="635" src="https://user-images.githubusercontent.com/31611061/227430902-64f6b90b-7fa0-40f0-835c-02d83559a922.png">

Can you check the `which python3`? 
![image](https://user-images.githubusercontent.com/44392324/227434904-834f515f-99b3-4a7e-8dc5-ac33ffc108e3.png)


From my view, the problem is caused by the environment settings, you may need to ensure your `pip` and `python3` operations are all used the ones in your env called `python37`. For example, if you pip the installation in your `python37` env, but your `python3` are directed to other env, then it cannot work. If still not work, try to create a clean env to test whether this problem still there. Hope these can help :)

**Comment by Aadedd** [comment]
@Camille7777 /root/anaconda3/envs/python37/bin/python3

**Comment by Aadedd** [comment]
@Camille7777 thank you for your help, i will try to create a clean env to test.

**Comment by Aadedd** [comment]
@Camille7777 I pulled up the latest version of the code and installed it. the problem is solved. but another problem arises.**NVIDIA GeForce RTX 4090 with CUDA capability sm_89 is not compatible with the current PyTorch installation.**😔

**Comment by Aadedd** [comment]
@Camille7777 i have to upgrade my cuda version?

**Comment by Camille7777** [comment]
> @Camille7777 I pulled up the latest version of the code and installed it. the problem is solved. but another problem arises.**NVIDIA GeForce RTX 4090 with CUDA capability sm_89 is not compatible with the current PyTorch installation.**😔

@Aadedd Hiii, based on the error message you may have installed PyTorch binaries with CUDA 10.x, which is incompatible with your 4090. Try upgrade your CUDA to the latest or nightly release with CUDA 11.7 or 11.8.
