### ISSUE TITLE
AssertionError: Unsupported optimizer <class 'colossalai.nn.optimizer.fused_sgd.FusedSGD'>[BUG]: 

### ISSUE THREAD

**Issue by withyou1771** [hpcaitech/ColossalAI#3202]
### 🐛 Describe the bug

When I replaced HybridAdam with FusedSGD, I met the problem:

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ applications/ChatGP │
│ T/examples/train_prompts.py:237 in <module>                                                      │
│                                                                                                  │
│   234 │   args = parser.parse_args()                                                             │
│   235 │                                                                                          │
│   236 │                                                                                          │
│ ❱ 237 │   main(args)                                                                             │
│   238                                                                                            │
│                                                                                                  │
│ applications/ChatGP │
│ T/examples/train_prompts.py:147 in main                                                          │
│                                                                                                  │
│   144 │   #(actor, actor_optim), (critic, critic_optim), reward_model, initial_model = strateg   │
│   145 │   #    (actor, actor_optim), (critic, critic_optim), reward_model, initial_model)        │
│   146 │   print(f"TIACC - prepare actor critic reward_model! RANK {RANK}")                       │
│ ❱ 147 │   (actor, actor_optim), (critic, critic_optim), reward_model = strategy.prepare(         │
│   148 │   │   (actor, actor_optim), (critic, critic_optim), reward_model)                        │
│   149 │                                                                                          │
│   150 │   print(f"TIACC - create initial_model! RANK {RANK}")                                    │
│                                                                                                  │
│ ChatGPT/chatgpt/trainer/strategies/base.py:83 in prepare                                               │
│                                                                                                  │
│    80 │   │   │   │   assert len(arg) == 2, f'Expect (model, optimizer) pair, got a tuple with   │
│    81 │   │   │   │   model, optimizer = arg                                                     │
│    82 │   │   │   │   model = prepare_model(model)                                               │
│ ❱  83 │   │   │   │   optimizer = self.setup_optimizer(optimizer, self._unwrap_model(model))     │
│    84 │   │   │   │   rets.append((model, optimizer))                                            │
│    85 │   │   │   elif isinstance(arg, nn.Module):                                               │
│    86 │   │   │   │   rets.append(prepare_model(arg))                                            │
│                                                                                                  │
│ ChatGPT/chatgpt/trainer/strategies/colossalai.py:128 in setup_optimizer                                │
│                                                                                                  │
│   125 │   │   return zero_model_wrapper(model, zero_stage=self.stage, gemini_config=self.gemin   │
│   126 │                                                                                          │
│   127 │   def setup_optimizer(self, optimizer: optim.Optimizer, model: nn.Module) -> optim.Opt   │
│ ❱ 128 │   │   assert isinstance(optimizer, (CPUAdam, HybridAdam)), f'Unsupported optimizer {ty   │
│   129 │   │   return zero_optim_wrapper(model, optimizer, optim_config=self.zero_optim_config,   │
│   130 │                                                                                          │
│   131 │   def backward(self, loss: torch.Tensor, model: nn.Module, optimizer: optim.Optimizer,   │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AssertionError: Unsupported optimizer <class 'colossalai.nn.optimizer.fused_sgd.FusedSGD'>

**Comment by JThh** [comment]
From my inspection of the codes, `FusedSGD` is unfortunately not yet compatible with ZeRO mechanism yet.
