### ISSUE TITLE
[BUG]: oom and process killed when saving ckpt

### ISSUE THREAD

**Issue by laozhanghahaha** [hpcaitech/ColossalAI#3212]
### 🐛 Describe the bug

Hey I try to run opt6.7B with batchsize=1 using this example https://github.com/hpcaitech/ColossalAI/blob/main/examples/tutorial/opt/opt/run_clm.py

**Describe the bug:**
memory leak

**To Reproduce**
It works fine if I use small dataset or if the training process is not too long. But when I use some bigger dataset and the training process takes long time, the error will occur.

I run 6.7B size on customdataset which contain 100w examples and the program was kill at the second expoch. The log showed `ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -9)`

I guess there should be memory leakage which caused this oom error.

### Environment

cuda version: release 11.3, V11.3.109
python 3.8
torch    1.11.0+cu113

**Comment by JThh** [comment]
Can you try setting `preprocessing_num_workers` to larger values?
