### ISSUE TITLE
[BUG]: OOM occurs while training BLOOM-7B model in the PPO stage.

### ISSUE THREAD

**Issue by tonylin52** [hpcaitech/ColossalAI#3228]
### 🐛 Describe the bug

[BUG]: OOM occurs while training BLOOM-7B model in the PPO stage.

### Environment
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.106.00   Driver Version: 460.106.00   CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  A100 80GB PCIe      On   | 00000000:17:00.0 Off |                    0 |
| N/A   29C    P0    65W / 300W |   3MiB / 81251MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   1  A100 80GB PCIe      On   | 00000000:CA:00.0 Off |                    0 |
| N/A   30C    P0    61W / 300W |      3MiB / 81251MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+

_No response_

**Comment by tonylin52** [comment]
torchrun --standalone --nproc_per_node=2 train_prompts.py prompts.csv --pretrain 'bigscience/bloom-7b1' --model 'bloom' --strategy colossalai_zero2

**Comment by tonylin52** [comment]
Hi,

I tried examples of 'opt-350M' etc. They are all good.
But when I tried larger model like bloom-7B with following command in the train_prompt.sh 
"torchrun --standalone --nproc_per_node=2 train_prompts.py prompts.csv --pretrain 'bigscience/bloom-7b1' --model 'bloom' --strategy colossalai_zero2(and gemini as well)", OOM ocurred.

I also try to change the "placement_policy" to "cpu" and get 
"ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -9) local_rank: 0"

Is there some params that I missed causing these problems?

Thanks

**Comment by JThh** [comment]
Would you please try smaller batch sizes or enlarging your allocated CPU memory?

**Comment by tonylin52** [comment]
> allocated CPU

Thanks a lot! Batch size as 1 still causes OOM. I would take a deep look at allocated CPU memory.

Another question is that the size of bloom-7B is 13G. The models for PPO training phase contains actor(13G, train), critic(13G, train) and rm(13G, eval). I implemented zero2 with 'cuda' placement_policy and LORA(rank=8) strategies in the 2x80G A100 GPU environment, where 39G<<160G, and still got OOM. Is there any possible that I do not setup these strategies parameters properly, so that they are not fully used?

**Comment by JThh** [comment]
I cannot tell exactly why given the current information. Would you please try using `torch.profiler` to profile your run and analyze cuda memory usage?

**Comment by tonylin52** [comment]
> I cannot tell exactly why given the current information. Would you please try using `torch.profiler` to profile your run and analyze cuda memory usage?

Sure! Thanks very much :)
