### ISSUE TITLE
[BUG]: AttributeError: 'DistributedDataParallel' object has no attribute 'model'

### ISSUE THREAD

**Issue by XuJing1022** [hpcaitech/ColossalAI#3234]
### 🐛 Describe the bug

When I run the train_rm.py in the strategy mode _ddp_, there is an error like "AttributeError: 'DistributedDataParallel' object has no attribute 'model'". 

Maybe, Line 38 in the chatgpt/trainer/strategies/ddp.py should be **model = model.module** instead of **model = model.model.module**.

The following command could reproduce the error in the screenshot.
`torchrun --nproc_per_node 1 train_reward_model.py --pretrain 'facebook/opt-125m' 
                             --model 'opt' 
                             --strategy ddp 
                             --loss_fn 'log_exp'
                             --save_path 'rmstatic.pt' 
                             --test True 
                             --dataset '/ossfs/workspace/data/rm-static/data'`
![image](https://user-images.githubusercontent.com/14179401/227455516-4a528e58-ceb2-4da1-b4ad-c6a3f8968576.png)

Of course! If there are no issues with the code but my problem, please let me know, thanks.

### Environment

python=3.8
torch=1.13.1

**Comment by JThh** [comment]
Thanks. I think this is a bug in our codes. We will seek to solve it quite soon!

**Comment by akk-123** [comment]
@JThh do you fix it, I get same error

**Comment by CWHer** [comment]
`DDPStrategy` has been updated.

Please reopen this issue if the error persists.
