### ISSUE TITLE
[RFC] Provide Communication Profiler as a Context Manager

### ISSUE THREAD

**Issue by FrankLeeeee** [hpcaitech/ColossalAI#326]
The current communication profiler works in a global scope as we need to initialize the profiler before training. Can we provide a context manager to profile only certain parts of the program so as to support finer granularity.

An example code will be:
```python
from colossalai.utils.profiler import profile_communication

...

class Net(nn.Module):

    ...

    def forward(self, x):
          with profile_communication():
                 self.layer_1(x)
          x = self.layer_2(x)
          return x
```

**Comment by FrankLeeeee** [comment]
Hi, @1SAA what do you think?

**Comment by feifeibear** [comment]
A good feature, however, the implementation is not straightforward from my point of view. You need to insert profiler logic to forward and backward routines for layer_1. @FrankLeeeee do you have any idea?

**Comment by binmakeswell** [comment]
@1SAA will update the sloving status.

**Comment by 1SAA** [comment]
We now have a context manager which can be used as a python context.
More details can be found [here](https://github.com/hpcaitech/ColossalAI/blob/main/colossalai/utils/profiler/prof_utils.py).
And useful tensorboard tools will be added soon @raejaf .

**Comment by feifeibear** [comment]
We close the RFC because the functionality has been developed. Although being used in the other manner.
