### ISSUE TITLE
[BUG]: [coati]: llama sft training not fit with other LMs

### ISSUE THREAD

**Issue by pgzhang** [hpcaitech/ColossalAI#3314]
### 🐛 Describe the bug

when I run `train_sft.sh` with `gpt2` model , I encountered these errors, and the PR is linked
```
Traceback (most recent call last):
  File "ColossalAI/applications/Chat/examples/train_sft.py", line 184, in <module>
    train(args)
  File "/ColossalAI/applications/Chat/examples/train_sft.py", line 113, in train
    train_sampler = DistributedSampler(train_dataset,
  File "/opt/conda/lib/python3.9/site-packages/torch/utils/data/distributed.py", line 83, in __init__
    if self.drop_last and len(self.dataset) % self.num_replicas != 0:  # type: ignore[arg-type]
  File "ColossalAI/applications/Chat/coati/dataset/sft_dataset.py", line 72, in __len__
    length = len(self.prompts)
AttributeError: 'SFTDataset' object has no attribute 'prompts'
```

```
Traceback (most recent call last):
  File "ColossalAI/applications/Chat/examples/train_sft.py", line 184, in <module>
    train(args)
  File "ColossalAI/applications/Chat/examples/train_sft.py", line 134, in train
    collate_fn=data_collator,
UnboundLocalError: local variable 'data_collator' referenced before assignment

```

```
 File "ColossalAI/applications/Chat/examples/train_sft.py", line 185, in <module>
    train(args)
  File "ColossalAI/applications/Chat/examples/train_sft.py", line 156, in train
    trainer.fit(logger=logger, log_interval=args.log_interval)
  File "ColossalAI/applications/Chat/coati/trainer/sft.py", line 88, in fit
    p_mask = batch["attention_mask"].to(torch.cuda.current_device())
KeyError: 'attention_mask'
```

### Environment

pytorch== 1.12

**Comment by scarydemon2** [comment]
same error

**Comment by scarydemon2** [comment]
change SFTDataset intoclass SFTDataset(Dataset):
    """
    Dataset for sft model

    Args:
        dataset: dataset for supervised model
        tokenizer: tokenizer for supervised model
        max_length: max length of input
    """

    def __init__(self, dataset, tokenizer: Callable, max_length: int = 512) -> None:
        super().__init__()
        # self.prompts = []
        self.input_ids = []

        for data in tqdm(dataset, disable=not is_rank_0()):
            prompt = data['prompt'] + data['completion'] + "<|endoftext|>"
            prompt_token = tokenizer(prompt,
                                     max_length=max_length,
                                     padding="max_length",
                                     truncation=True,
                                     return_tensors="pt")

            # self.prompts.append(prompt_token)s
            self.input_ids.append(prompt_token['input_ids'])

            self.labels = copy.deepcopy(self.input_ids)

    def __len__(self):
        length = len(self.input_ids)
        return length

    def __getitem__(self, idx):
        # dict(input_ids=self.input_ids[i], labels=self.labels[i])
        return dict(input_ids=self.input_ids[idx], labels=self.labels[idx],attention_mask=self.input_ids[idx].ne(self.tokenizer.pad_token_id),)
        # return dict(self.prompts[idx], self.prompts[idx])

**Comment by CWHer** [comment]
We have updated our code. Please try out the new code and reopen the issue if the problem persists.
