### ISSUE TITLE
[coati]: stage1, what's the exact arguments for [pretrain, save_path, dataset], especialy for [pretrain]？

### ISSUE THREAD

**Issue by iGuaZi** [hpcaitech/ColossalAI#3321]
torchrun --standalone --nproc_per_node=4 train_sft.py \
    --pretrain "/path/to/LLaMa-7B/" \
    --model 'llama' \
    --strategy colossalai_zero2 \
    --log_interval 10 \
    --save_path  /path/to/Coati-7B \
    --dataset /path/to/data.json \
    --batch_size 4 \
    --accimulation_steps 8 \
    --lr 2e-5 \
    --max_datasets_size 512 \
    --max_epochs 1 \

what's the exact arguments for [pretrain, save_path, dataset], especialy for [pretrain]？

**Comment by JThh** [comment]
For `pretrain', it directs to your downloaded model weights either locally or to be downloaded on the fly. `save_path` and `dataset` should be self-explanatory which mean path to save trained model weights as well as the path to dataset config.

**Comment by mingyangan** [comment]
So where can we get the LLaMa model? Will it be affect the final effect of Coati?
