### ISSUE TITLE
Train Data about the three-stage training of ColossalChat

### ISSUE THREAD

**Issue by Vincent131499** [hpcaitech/ColossalAI#3325]
### Describe the feature

Can you give an example of the corresponding json training data in the three-stage training of ColossalChat? 
This makes it easier for beginners to get started.

**Comment by fingertap** [comment]
Did they release the data?

**Comment by binmakeswell** [comment]
@Vincent131499 @fingertap 
https://github.com/hpcaitech/ColossalAI/tree/main/applications/Chat#supervised-datasets-collection
