### ISSUE TITLE
[BUG]: ValueError: Tokenizer class LLaMATokenizer does not exist or is not currently imported.

### ISSUE THREAD

**Issue by bittteerr** [hpcaitech/ColossalAI#3334]
### 🐛 Describe the bug

ValueError: Tokenizer class LLaMATokenizer does not exist or is not currently imported.

**Comment by StarsTesla** [comment]
@binmakeswel l  also meet the same bug while I trying to run the code follow the README.
![1680162614140](https://user-images.githubusercontent.com/45264423/228767764-f3ff149e-241a-4b05-9f3e-06837ca6c07a.png)

**Comment by StarsTesla** [comment]
for sup：I used the pretrain form hugguingface of decapoda-research/llama-7b-hf, and the dataset is follow the README.

**Comment by scutcyr** [comment]
> LlamaTokenizer
@StarsTesla
I modified all the name of "LlamaTokenizer" to "LLaMATokenizer" in the forked repo transfomers "https://github.com/hpcaitech/transformers", and rebuild the code, the problem solved.
这个办法确实能解决，这里补充一下细节：
```bash
git clone https://github.com/hpcaitech/transformers
cd transformers
```
分别需要修改```./transformers/src/transformers/__init__.py```、```./transformers/src/transformers/models/llama/__init__.py```、```./transformers/src/transformers/models/llama/tokenization_llama.py```这三个文件，把所有"LlamaTokenizer"替换为"LLaMATokenizer"
然后运行：
```bash
pip install .
```
即可成功使用https://huggingface.co/decapoda-research/llama-7b-hf版本

**Comment by bingoko** [comment]
> 
Problem solved!

**Comment by binmakeswell** [comment]
Hi @StarsTesla @scutcyr Thank you for feedback. We will fix this issue as soon as possible.

**Comment by binmakeswell** [comment]
> 我放弃了兄弟们，文档太不完善了，待处理bug太多了，这代码中间训练出bug会把东西卡在GPU里出不来，reboot后直接连不上docker了，指定4个，会占我8个，其中4个会没有显存占用但依然会升瓦数上去，等代码维护稳定后再来吧唉

抱歉，请问“指定4个，会占我8个”可以开个issue提供下具体详情供复现和修复吗？

**Comment by StarsTesla** [comment]
> > 我放弃了兄弟们，文档太不完善了，待处理bug太多了，这代码中间训练出bug会把东西卡在GPU里出不来，reboot后直接连不上docker了，指定4个，会占我8个，其中4个会没有显存占用但依然会升瓦数上去，等代码维护稳定后再来吧唉
> 
> 抱歉，请问“指定4个，会占我8个”可以开个issue提供下具体详情供复现和修复吗？感谢

抱歉，上周我用A100跑stage 2依然OOM后就交给我的同事他们去负责了，我只能说，可能依然还是显存不够导致各种问题吧

**Comment by 610lyn** [comment]
> > 
> 
> Is there any progress? I am facing same issue when training stage 2 using A100. I am worry about how to fix it.
> 
> 请问后续有什么进展吗？我用A100运行stage2遇到了同样的问题，请问应该怎样解决？

update: I fix this issue by set placement='cpu', but it is extremely slow.
