### ISSUE TITLE
[BUG]: LlamaCritic use CausalLM but the other Critic use Model

### ISSUE THREAD

**Issue by baibaiw5** [hpcaitech/ColossalAI#3341]
### 🐛 Describe the bug

BLOOMCritic->BloomModel
GPTCritic->GPT2Model
OPTCritic->OPTModel
The source code of LlamaCritic use LlamaForCausalLM which dose not provide outputs['last_hidden_state']
https://github.com/hpcaitech/ColossalAI/blob/main/applications/Chat/coati/models/llama/llama_critic.py
It seem that there is a LlamaModel.
https://huggingface.co/docs/transformers/main/model_doc/llama#transformers.LlamaModel

**Comment by JThh** [comment]
You are right! And a similar issue is #3428

**Comment by binmakeswell** [comment]
Hi @baibaiw5 Could you please fix it with a PR? We welcome contributions from the community. Thanks.
