### ISSUE TITLE
[BUG]: CololssalChat is really weird.

### ISSUE THREAD

**Issue by hyunwoongko** [hpcaitech/ColossalAI#3345]
### 🐛 Describe the bug

![image](https://user-images.githubusercontent.com/38183241/228759067-f60edf38-fdd4-429d-a82b-6e60229660cd.png)

![image](https://user-images.githubusercontent.com/38183241/228759091-65af5785-3193-4f90-b054-90c580446711.png)

What's the 'appropriate content'...?

**Comment by FrankLeeeee** [comment]
We have collected a list of words which are offensive and check if the content contains these words as a simple safety checker. This occurs perhaps because the some words are accidentally hit.

This has been stated in the banner section at the bottom of the page as well.

**Comment by FrankLeeeee** [comment]
I guess it might be because that `damn` is included as part of the chat history. Every query contains the word `damn` and thus rejected by the service.

**Comment by JThh** [comment]
You may try asking some more involved things
<img width="1439" alt="Screenshot 2023-03-30 at 3 40 43 PM" src="https://user-images.githubusercontent.com/59948448/228765070-97329d22-cb72-4124-afd1-49600ffaf733.png">
<img width="1434" alt="Screenshot 2023-03-30 at 3 40 52 PM" src="https://user-images.githubusercontent.com/59948448/228765087-04811eb1-5349-4b66-aefe-2df9b480fbec.png">
 like below. It responded quite well.

**Comment by hyunwoongko** [comment]
My first question is 'who is the tallest person in the world'. I don't understand why this is inappropriate.

**Comment by FrankLeeeee** [comment]
@hyunwoongko We would appreciate a lot if you have some better suggestions to handle harmful input and output :)

**Comment by hyunwoongko** [comment]
I've checked https://github.com/hpcaitech/ColossalAI/blob/main/applications/Chat/inference/server.py this file, and there is a parameter named 'profanity_file'. could you share this file?

**Comment by FrankLeeeee** [comment]
I think my answers should resolve this issue and thus I will close this issue for now. Do re-open it if you feel there is more to discuss and we'd love to exchange ideas to better improve our system. 😺

**Comment by hyunwoongko** [comment]
@FrankLeeeee

**Comment by hyunwoongko** [comment]
Yeah. OpenAI API seems great for this case. Thanks!

**Comment by FrankLeeeee** [comment]
Thanks for your feedback as well!
