### ISSUE TITLE
[BUG]: ChatColossalAI training stucked at No pre-built kernel is found, build and load the cpu_adam kernel during runtime now

### ISSUE THREAD

**Issue by alibabadoufu** [hpcaitech/ColossalAI#3359]
### 🐛 Describe the bug

Is it normal to stuck at this stage for more than 15 mins?

Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:20<00:00, 10.18s/it]Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:25<00:00, 12.51s/it]
=========================================================================================
No pre-built kernel is found, build and load the cpu_adam kernel during runtime now
=========================================================================================

**Comment by evi-Genius** [comment]
same error

**Comment by FrankLeeeee** [comment]
Hi, can you check the output for `colossalai check -i`?

**Comment by FrankLeeeee** [comment]
You may retry with `rm -rf ~/.cache/colossalai`

**Comment by alibabadoufu** [comment]
Worked for me. THanks @FrankLeeeee !
