### ISSUE TITLE
[FEATURE]: dataset for train prompt stage

### ISSUE THREAD

**Issue by boundles** [hpcaitech/ColossalAI#3360]
### Describe the feature

torchrun --standalone --nproc_per_node=4 train_prompts.py \
         --pretrain "/path/to/LLaMa-7B/" \
         --model 'llama' \
         --strategy colossalai_zero2 \
         --prompt_path /path/to/your/prompt_dataset \
         --pretrain_dataset /path/to/your/pretrain_dataset \
         --rm_pretrain /your/pretrain/rm/defination \
         --rm_path /your/rm/model/path

这一步的后面四个训练数据是怎么获取的呢，有现成的吗以方便快速复现。

**Comment by raihan0824** [comment]
Asking the same question, is there any UI/interface to reproduce the dataset?

**Comment by lfxuyufei** [comment]
Asking the same question

**Comment by MrRace** [comment]
The same question! How to reproduce the dataset?
```
```

**Comment by TBBTfans** [comment]
请教一下，预训练模型LLaMa-7B在哪里可以获取呢？

**Comment by Fazziekey** [comment]
从Facebook官方的repo获取, LLaMa暂时不能商用,所以我们暂时不能开源权重

**Comment by MrRace** [comment]
Anything more detail about prompt_dataset，pretrain_dataset and  rm_pretrain model？

**Comment by jamesunnc** [comment]
Hi, I can't figure out whether train_rm.sh will save checkpoint. But I got something don't like checkpoint.

**Comment by gg22mm** [comment]
也不知道哪来的这么多星星，训练数据集格式都没有 。谁在测？

**Comment by CWHer** [comment]
Refer to #3415.
