### ISSUE TITLE
[BUG]: No pretrained model found https://github.com/hpcaitech/ColossalAI/tree/main/applications/Chat/inference

### ISSUE THREAD

**Issue by feiliya333** [hpcaitech/ColossalAI#3385]
### 🐛 Describe the bug

I found no pretrained model weight, is it possible to release a model weight to enable quick local demo deployment?

**Comment by binmakeswell** [comment]
Hi @feiliya333 The original LLaMA restricts weight sharing, and we need to inherit that rule. We j will try to share it in an indirect form in a subsequent version.
