### ISSUE TITLE
[BUG]: Chat hung answering a question 

### ISSUE THREAD

**Issue by lcn2** [hpcaitech/ColossalAI#3387]
### 🐛 Describe the bug

I asked:

“Another conjecture I enjoy thinking about is the Goldbach conjecture. Do you know that conjecture?”

It responded:

“Yes, I do. The Goldbach Conjecture states that every even number greater than two can be expressed as the sum of two primes. It is also widely believed to be true although again there has been no definitive proof as yet.”

which is correct, BTW. So then I asked:

“What is the best evidence that the Goldbach conjecture is true?”

The chat hung. Even waiting a good number of mini minutes, no replay came back. 

### Environment

Using iPhone safari browser running the latest iOS 16.4 via the URL:

https://chat.colossalai.org/

**Comment by Ankitprajapati51** [comment]
Don't worry

**Comment by lcn2** [comment]
Opening up a new session and repeating the last question, it was able to respond with a reasonable answer.

**Comment by lcn2** [comment]
Here is an example:

![image](https://user-images.githubusercontent.com/10429707/229263131-6d980113-a696-4df8-b25d-4047a119d4bd.png)
