### ISSUE TITLE
[BUG]: where can i find the dataset used in stage 3 of chatgpt

### ISSUE THREAD

**Issue by zhhao1** [hpcaitech/ColossalAI#3396]
### 🐛 Describe the bug

Thanks for your great work. prompt_dataset and pretrain_dataset were used in stage3. Is there a download link here?

**Comment by patelshu89** [comment]
pretrain_dataset_provider = NvidiaBertDatasetProvider(args)

NvidiaBertDatasetProvider is likely a custom class that provides pre-training datasets for Nvidia's implementation of BERT (Bidirectional Encoder Representations from Transformers), which is a popular neural network architecture for natural language processing (NLP) tasks such as language modeling, text classification, and question answering.

The args argument passed to the NvidiaBertDatasetProvider constructor likely contains configuration options for the dataset provider, such as the location of the pre-training data and the size of the batches used for training.

By creating an instance of the NvidiaBertDatasetProvider class, the code is able to use the pre-training datasets provided by this class for training the BERT model. The resulting instance of the NvidiaBertDatasetProvider class is assigned to the pretrain_dataset_provider variable, which can be used to access the pre-training datasets and their associated configuration options.


Please correct me if I am wrong

**Comment by zhhao1** [comment]
> pretrain_dataset_provider = NvidiaBertDatasetProvider(args)
> 
> NvidiaBertDatasetProvider is likely a custom class that provides pre-training datasets for Nvidia's implementation of BERT (Bidirectional Encoder Representations from Transformers), which is a popular neural network architecture for natural language processing (NLP) tasks such as language modeling, text classification, and question answering.
> 
> The args argument passed to the NvidiaBertDatasetProvider constructor likely contains configuration options for the dataset provider, such as the location of the pre-training data and the size of the batches used for training.
> 
> By creating an instance of the NvidiaBertDatasetProvider class, the code is able to use the pre-training datasets provided by this class for training the BERT model. The resulting instance of the NvidiaBertDatasetProvider class is assigned to the pretrain_dataset_provider variable, which can be used to access the pre-training datasets and their associated configuration options.
> 
> Please correct me if I am wrong

maybe there have some understanding.
the pretrain_dataset just is a json file. You can see the load code:
train_prompts.py, line 140
Chat/coati/dataset/sft_dataset.py, line 119

**Comment by patelshu89** [comment]
data_path (string): the path to the JSON file .
Yes you are right.

**Comment by MrRace** [comment]
Therefore how to get them？

**Comment by HaixHan** [comment]
So, how to get prompt dataset?

**Comment by HaixHan** [comment]
> So, how to get prompt dataset?
hi, do you know how to get prompt dataset?

**Comment by MrRace** [comment]
No official reply, Sad the closed issue

**Comment by binmakeswell** [comment]
Hi @MrRace @HaixHan @zhhao1 @patelshu89 We have provide the prompt dataset example in stage 3 doc. Thanks.
https://github.com/hpcaitech/ColossalAI/tree/main/applications/Chat/examples#stage3---training-model-using-prompts-with-rl

**Comment by CWHer** [comment]
Relevant docs are added in 6d41c3f2aa7c859fe2b87889e6b02b4febbfa4f6. Sorry for not pointing it out here explicitly.
