### ISSUE TITLE
[BUG]: Stuck at the stage 1 training for Chat application

### ISSUE THREAD

**Issue by alibabadoufu** [hpcaitech/ColossalAI#3407]
### 🐛 Describe the bug

When I train the model using the train_sft.sh

> torchrun --standalone --nproc_per_node=2 train_sft.py \
>     --pretrain "llama-path" \
>     --model 'llama' \
>     --strategy colossalai_zero2 \
>     --log_interval 10 \
>     --save_path  output_save_path \
>     --dataset data_path \
>     --batch_size 4 \
>     --accimulation_steps 8 \
>     --lr 2e-5 \
>     --max_datasets_size 256 \
>     --max_epochs 1 \

I was stuck at this stage for a few hours. When I ran this training script, I have already remove the cache using `rm ~/.cache/colossalai`

```
wandb: Enter your choice: 3
wandb: Enter your choice: 3
wandb: Enter your choice: 3
wandb: WARNING Invalid choice
wandb: Enter your choice: 3
wandb: You chose "Don't visualize my results"
wandb: Tracking run with wandb version 0.13.10
wandb: W&B syncing is set to `offline` in this directory.  
wandb: Run `wandb online` or set WANDB_MODE=online to enable cloud syncing.
`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`...
```

**Comment by mynewstart** [comment]
same question

**Comment by mynewstart** [comment]
"wandb disabled" works for me

**Comment by chengeharrison** [comment]
It seems that when you are prompted to give your choice, you only enter your choice once. You should key in your choice multiple times.



> ### 🐛 Describe the bug
> When I train the model using the train_sft.sh
> 
> > torchrun --standalone --nproc_per_node=2 train_sft.py 
> > --pretrain "llama-path" 
> > --model 'llama' 
> > --strategy colossalai_zero2 
> > --log_interval 10 
> > --save_path  output_save_path 
> > --dataset data_path 
> > --batch_size 4 
> > --accimulation_steps 8 
> > --lr 2e-5 
> > --max_datasets_size 256 
> > --max_epochs 1 \
> 
> I was stuck at this stage for a few hours. When I ran this training script, I have already remove the cache using `rm ~/.cache/colossalai`
> 
> ```
> wandb: Enter your choice: 3
> wandb: Enter your choice: 3
> wandb: Enter your choice: 3
> wandb: WARNING Invalid choice
> wandb: Enter your choice: 3
> wandb: You chose "Don't visualize my results"
> wandb: Tracking run with wandb version 0.13.10
> wandb: W&B syncing is set to `offline` in this directory.  
> wandb: Run `wandb online` or set WANDB_MODE=online to enable cloud syncing.
> `use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`...
> ```
> 
> ### Environment
> _No response_

It seems that when you are prompted to give your choice, you only enter your choice once. You should key in your choice multiple times.

In your case, I think you only key in the choice once because wandb respond once. You may key in 3 again.
