### ISSUE TITLE
[BUG]: bug in training rm with ddp strategy with single machine multi-GPUs!

### ISSUE THREAD

**Issue by xHansonx** [hpcaitech/ColossalAI#3421]
### 🐛 Describe the bug

Code:
------------------------------------------------------------
 torchrun --standalone --nproc_per_node=1 train_reward_model.py --dataset Dahoas/rm-static               --subset ../../../datasets/Dahoas_rm-static               --max_len 512  --model gpt2                --pretrain ../../../gpt2/gpt2-small                --lora_rank 0  --max_epochs 1                  --batch_size 1                  --loss_fn log_sig                  --test True                  --need_optim_ckpt True                  --strategy ddp                  --save_path rm_ckpt.pt 

Error: 
------------------------------------------------------------
![image](https://user-images.githubusercontent.com/37849338/229699763-6b16a770-d841-4416-884d-ebc43068e315.png)
![image](https://user-images.githubusercontent.com/37849338/229699888-be8915cd-ae7d-4e99-aac0-3faf1251bfb9.png)

**Comment by JThh** [comment]
Can I know your environment settings such as your machine type as well as torch, Python versions?

**Comment by xHansonx** [comment]
> Can I know your environment settings such as your machine type as well as torch, Python versions?


------------ Environment ------------
Colossal-AI version: 0.2.8
PyTorch version: 1.12.1
System CUDA version: 11.3
CUDA version required by PyTorch: 11.3

**Comment by JThh** [comment]
Sorry for getting to your questions late. May I know why you are setting `nproc_per_node=1` when you have multiple nodes on the machine and set the strategy to be `ddp`?

**Comment by CWHer** [comment]
Thanks for reporting. #4023 Contains this now.
