### ISSUE TITLE
maybe LlamaModel？

### ISSUE THREAD

**Issue by gongel** [hpcaitech/ColossalAI#3428]
https://github.com/hpcaitech/ColossalAI/blob/b09adff724c2bbded1c71cc51a707f736a0e2899/applications/Chat/coati/models/llama/llama_critic.py#L31

**Comment by JThh** [comment]
You are absolutely right! Thank you for spotting this error and we will get to fix it soon!

**Comment by binmakeswell** [comment]
Hi @gongel Could you please fix it with a PR? We welcome contributions from the community. Thanks.

**Comment by gongel** [comment]
Ok. And about this issue ？#3415

**Comment by binmakeswell** [comment]
> Ok. And about this issue ？#3415

Replied.
