### ISSUE TITLE
[BUG]: "OverflowError: int too big to convert" during SFT training using Bloom model

### ISSUE THREAD

**Issue by chengeharrison** [hpcaitech/ColossalAI#3438]
### 🐛 Describe the bug

```
torchrun --standalone --nproc_per_node=2 train_sft.py \
    --pretrain "bigscience/bloom-560m" \
    --model 'bloom' \
    --strategy ddp \
    --log_interval 10 \
    --save_path  "./output/" \
    --dataset "/data/users/lcxyc/instinwild_ch.json" \
    --batch_size 2 \
    --accimulation_steps 8 \
    --lr 2e-5 \
    --max_datasets_size 512 \
    --max_epochs 1 \
```

When building the SFT dataset, the error occurs.

**Comment by GXKIM** [comment]
I also get an error when running this file, and I can't import the package after downloading the transformers

**Comment by GXKIM** [comment]
train_sft.py => from coati.models.llama import LlamaLM line11

**Comment by chengeharrison** [comment]
> train_sft.py => from coati.models.llama import LlamaLM line11

It's so weird because your ```from coati.models.bloom import BLOOMLM``` can pass but for llama couldn't. Maybe you should check your coati module and reinstall it.
