### ISSUE TITLE
[BUG]: Is it normal to have loss nan after the Stage 1 - Supervised Finetuning?

### ISSUE THREAD

**Issue by alibabadoufu** [hpcaitech/ColossalAI#3439]
### 🐛 Describe the bug

```
wandb: Synced 6 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Waiting for W&B process to finish... (success).
wandb: - 0.010 MB of 0.010 MB uploaded (0.000 MB deduped)
wandb: Run history:
wandb: batch_id ▁▁▂▂▃▃▄▄▅▅▆▆▇▇██
wandb:    epoch ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:     loss ▁               
wandb:       lr ███▇▇▆▆▅▄▃▃▂▂▁▁▁
wandb: 
wandb: Run summary:
wandb: batch_id 127
wandb:    epoch 0
wandb:     loss nan
wandb:       lr 0.0
wandb: 
wandb: Synced 6 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
```

Is it normal to have nan loss?

**Comment by JThh** [comment]
Can you try to print some forward outputs maybe [here](https://github.com/hpcaitech/ColossalAI/blob/46c009dba462800b4f7bd54b4558a37e6326726d/applications/Chat/coati/trainer/sft.py#L94) and ensure they are not nan?

**Comment by JThh** [comment]
Also, can you inspect the loss before and after this [line](https://github.com/hpcaitech/ColossalAI/blob/46c009dba462800b4f7bd54b4558a37e6326726d/applications/Chat/coati/trainer/sft.py#L102)?

**Comment by emigmo** [comment]
Here are some variable value in sft.py.
![image](https://user-images.githubusercontent.com/10398640/230266357-643845cb-5d19-4ab1-b7de-3bbac1e5ff2d.png)
batch_size: 1
strategy: ddp
accimulation_steps: 8
lr: 2e-5

**Comment by GeraldWu23** [comment]
same logs are seen here

**Comment by JThh** [comment]
Do you mean when disabling `grad_accumulation` it will work correctly? How about when set to colossalai_gemini?

**Comment by allendred** [comment]
This seems to have nothing to do with the accumulation of gradients. In the first few steps, the loss is normal, and then it starts to become nan

**Comment by puyuanOT** [comment]
same logs are seen here

**Comment by zhhao1** [comment]
enlarge the lr may work

**Comment by Yunnglin** [comment]
This issue seems related to the quantization of fp16:
```python
# in train_sft.py
model = LlamaLM(pretrained=args.pretrain, 
                            lora_rank=args.lora_rank,
                            checkpoint=True).to(torch.float16).to(torch.cuda.current_device())
```

I removed the `to(torch.float16)`, and try to load in 8-bit (remember to install the official `transformes` library), the loss is normal now.

```python
# in llama_lm.py
# try to load in 8-bit
model = LlamaForCausalLM.from_pretrained(pretrained, 
                                                 load_in_8bit=load_in_8bit,
                                                 device_map='auto')
```
In this way, the model is quantized into 8-bit, but still don't know why the quantization of fp16 results in NaN loss.

**Comment by puyuanOT** [comment]
@Yunnglin It looks like the optimizer won't work as long as the LoRA parameter is fp16. I hacked into the code and kept themodel parameters to fp16 but changed LoRA parameters fp32, then it started to work.

**Comment by puyuanOT** [comment]
@JThh Looking forward for a fix regarding this! I suspect something is wrong during the lora parameter optimization.

**Comment by mforgithub** [comment]
Here is my solution：
In sft.py changed my code like the pic blow: 
![图片](https://user-images.githubusercontent.com/29246850/232206619-f7e4dd8b-4bb7-4bec-8be6-36c561f42696.png)
Then my loss got normal

**Comment by Yunnglin** [comment]
> Here is my solution： In sft.py changed my code like the pic blow: ![图片](https://user-images.githubusercontent.com/29246850/232206619-f7e4dd8b-4bb7-4bec-8be6-36c561f42696.png) Then my loss got normal

The code may be buggy, `loss_copy` is detached from the computation graph, so LoRA parameters won't update.

**Comment by binmakeswell** [comment]
Thanks for the feedback, we are fixing it.

**Comment by shawnxiaolongyang** [comment]
+1
Encounters the same issue, loss became 0 after one step.
https://api.wandb.ai/links/yangshawnlong/52wvbbnw

**Comment by shawnxiaolongyang** [comment]
> This issue seems related to the quantization of fp16:
> 
> ```python
> # in train_sft.py
> model = LlamaLM(pretrained=args.pretrain, 
>                             lora_rank=args.lora_rank,
>                             checkpoint=True).to(torch.float16).to(torch.cuda.current_device())
> ```
> 
> I removed the `to(torch.float16)`, and try to load in 8-bit (remember to install the official `transformes` library), the loss is normal now.
> 
> ```python
> # in llama_lm.py
> # try to load in 8-bit
> model = LlamaForCausalLM.from_pretrained(pretrained, 
>                                                  load_in_8bit=True,
>                                                  device_map='auto')
> ```
> 
> In this way, the model is quantized into 8-bit, but still don't know why the quantization of fp16 results in NaN loss.

Follow the comment and change the loss rate to 8-bit, now I have loss but it never decrease.
https://api.wandb.ai/links/yangshawnlong/07idgc0i

**Comment by Camille7777** [comment]
> naive

Hi, @shawnxiaolongyang have you tried with other strategy like ddp?

**Comment by GeraldWu23** [comment]
> This issue seems related to the quantization of fp16:
> 
> ```python
> # in train_sft.py
> model = LlamaLM(pretrained=args.pretrain, 
>                             lora_rank=args.lora_rank,
>                             checkpoint=True).to(torch.float16).to(torch.cuda.current_device())
> ```
> 
> I removed the `to(torch.float16)`, and try to load in 8-bit (remember to install the official `transformes` library), the loss is normal now.
> 
> ```python
> # in llama_lm.py
> # try to load in 8-bit
> model = LlamaForCausalLM.from_pretrained(pretrained, 
>                                                  load_in_8bit=True,
>                                                  device_map='auto')
> ```
> 
> In this way, the model is quantized into 8-bit, but still don't know why the quantization of fp16 results in NaN loss.

I remove to.(torch.float16) and set load_in_8bit=True as you do, but I run into this new issue:
RuntimeError: Only Tensors of floating point and complex dtype can require gradients

**Comment by zhhao1** [comment]
My experience:
model.half() adam(eps=1e-8)   loss:nan
model.half() sgd                       loss:normal, however, non convergence
model.half() adam(eps=1-4)    loss:normal, however, non convergence
model.half() fp16                     loss:normal, however, non convergence
model adam(eps=1e-8)          loss:normal, convergence
Remove .half() can work. I hope this information is useful.

**Comment by Yahuicai** [comment]
Encounters the same issue

**Comment by Yahuicai** [comment]
> My experience: model.half() adam(eps=1e-8) loss:nan model.half() sgd loss:normal, however, non convergence model.half() adam(eps=1-4) loss:normal, however, non convergence model.half() fp16 loss:normal, however, non convergence model adam(eps=1e-8) loss:normal, convergence Remove .half() can work. I hope this information is useful.

I try this , but is OOM, my GPU MEM is 24G*1 。

**Comment by zhhao1** [comment]
> > My experience: model.half() adam(eps=1e-8) loss:nan model.half() sgd loss:normal, however, non convergence model.half() adam(eps=1-4) loss:normal, however, non convergence model.half() fp16 loss:normal, however, non convergence model adam(eps=1e-8) loss:normal, convergence Remove .half() can work. I hope this information is useful.
> 
> I try this , but is OOM, my GPU MEM is 24G*1 。

V100 32G*4 can work for 7B when batch is 1 and open the activate checkpoint. suggest lora.
