### ISSUE TITLE
[BUG]: ImportError: cannot import name 'ColoInitContext' from 'colossalai.zero'

### ISSUE THREAD

**Issue by Luoyang144** [hpcaitech/ColossalAI#3447]
### 🐛 Describe the bug

I have install colossal with `CUDA_EXT=1 pip install colossalai`, and get following error:
`ImportError: cannot import name 'ColoInitContext' from 'colossalai.zero' (/xxx/xxxx/anaconda3/envs/colossai/lib/python3.9/site-packages/colossalai/zero/__init__.py)
`
Command are same as [here](https://github.com/hpcaitech/ColossalAI/blob/main/applications/Chat/examples/train_prompts.sh), how can I solve this problem?

### Environment

Install with [requirements.txt](https://github.com/hpcaitech/ColossalAI/blob/main/applications/Chat/requirements.txt)

**Comment by chengeharrison** [comment]
My solution is:

```
git clone https://github.com/hpcaitech/ColossalAI.git
cd ColossalAI
pip install .
```

It seems that the version pip install colossalai is installing doesn't include this change #3424 (Maybe this pr).

**Comment by Luoyang144** [comment]
@chengeharrison Thank you, it works!
