### ISSUE TITLE
[FEATURE]: Huggingface Peft model supports

### ISSUE THREAD

**Issue by yynil** [hpcaitech/ColossalAI#3454]
### Describe the feature

Currently the models adopts liblora to implement LoRa when training huge models. But the original one is not easy to train and distribute since the artifacts are huge. 

Huggingface peft is a better Lora/prompt tuning library that can be easily trained and distributed because the additional parameters are stored separately and one massive model can be loaded with different peft parameters to serve different purposes. 

So adding peft support will make Chat more production ready.

**Comment by taishiciR** [comment]
@yynil hi~,Any update about Peft way to train sft? I find it buggy with ZERO3 strategy where training not only the lora params but  all params is trainable

**Comment by yynil** [comment]
> @yynil hi~,Any update about Peft way to train sft? I find it buggy with ZERO3 strategy where training not only the lora params but all params is trainable

I'm working on ZERO2+ChatGLM6B+Peft+(SFT,RM,PPO training) in one 3090ti graphic card now. Currently I almost finish all codes and dry_run training.  After I reorganized codes, I'll put them to my fork and ask for a PR.
I don't recommend ZERO3 since I encountered a lot problems. For now , ZERO2 is much better and more stable.

**Comment by taishiciR** [comment]
thanks a lot for your advice
