### ISSUE TITLE
[BUG]: How to run the code on AWS Sagemaker Single GPU

### ISSUE THREAD

**Issue by samarthsarin** [hpcaitech/ColossalAI#3455]
### 🐛 Describe the bug

Hi
I am looking to fine tune the model on my data by running the code on AWS sagemaker. There I only have 1 GPU machine.
Can someone please guide me how to run the code on single GPU machine as I keep getting an error undefined host, master address, master port etc. How do I find these values or turn it off whilw running it on a single GPU machine

Thank you

**Comment by JThh** [comment]
Have you created a docker environment to run the example? e.g. `docker pull hpcaitech/colossalai:0.2.7`

**Comment by samarthsarin** [comment]
No,
I am directlt running the train_sft.py file in my Sagemaker notebook where
I have just cloned the git repo of ColossalAI.

**Comment by binmakeswell** [comment]
https://aws.amazon.com/cn/blogs/china/run-colossal-ai-based-distributed-finetune-tasks-on-sagemaker/
@samarthsarin May be you can refer to this blog for AWS sagemaker with Colossal-AI.

**Comment by binmakeswell** [comment]
This issue was closed due to inactivity. Thanks.
