### ISSUE TITLE
[BUG]: ImportError: cannot import name 'register_meta' from 'torch._meta_registrations' 

### ISSUE THREAD

**Issue by ZhangMaoTai** [hpcaitech/ColossalAI#3466]
### 🐛 Describe the bug

When I run https://github.com/hpcaitech/ColossalAI/blob/main/applications/Chat/examples/train_rm.sh, I encounter this import error. 

File "/XXX/ColossalAI/colossalai/fx/_meta_regist_13.py", line 2, in <module>
    from torch._meta_registrations import register_meta
ImportError: cannot import name 'register_meta' from 'torch._meta_registrations' (/opt/conda/lib/python3.8/site-packages/torch/_meta_registrations.py)

### Environment

The same as https://github.com/hpcaitech/ColossalAI/blob/main/applications/Chat/requirements.txt

**Comment by ZhangMaoTai** [comment]
This bug occurs directly after I solve this bug [https://github.com/hpcaitech/ColossalAI/issues/3447](url) using his methos

**Comment by Camille7777** [comment]
hiii @ZhangMaoTai could you please pull the latest ColossalAI and try `pip install -e .`, and also ensure that you have enter ed the directory of Chat and `pip install .`, too.
