### ISSUE TITLE
[BUG]: about package in colab train_sft.py

### ISSUE THREAD

**Issue by GXKIM** [hpcaitech/ColossalAI#3469]
### 🐛 Describe the bug

Is it impossible to execute the code in the example on colab?
![image](https://user-images.githubusercontent.com/125621025/230322832-6d858a50-4a6f-42dd-9967-272031b39fe6.png)
When you import a package after installing the environment, an error occurs

### Environment

python 3.9
cuda 22.9

**Comment by GXKIM** [comment]
first commit

**Comment by JThh** [comment]
Can you locate which line of code caused the error?

**Comment by binmakeswell** [comment]
Hi @GXKIM Sorry, we are currently a very small team and have to focus on supporting and optimizing the most mainstream situation. https://github.com/hpcaitech/ColossalAI#installation We have not fully tested and optimized Colab.
