### ISSUE TITLE
[BUG]: chat optimizer.backward(loss) 

### ISSUE THREAD

**Issue by James6Chou** [hpcaitech/ColossalAI#3483]
### 🐛 Describe the bug

ColossalAI/applications/Chat/coati/trainer/strategies/colossalai.py file 150 line optimizer.backward(loss) should be a code error

**Comment by JThh** [comment]
Does it fail anyway?

**Comment by James6Chou** [comment]
> Does it fail anyway?

I'm not sure, but I didn't find the definition of the optimizer.backward(loss) function, and there is no such usage in the original pytorch

**Comment by JThh** [comment]
Hi, we have adapted the [optimizer AP](https://github.com/hpcaitech/ColossalAI/blob/f313babd11f8137c2496e7dc54c6b61604cd3672/colossalai/nn/optimizer/colossalai_optimizer.py#L36)I for this use!
