### ISSUE TITLE
[FEATURE]: Is hybrid parallelism supported in GPT demo?

### ISSUE THREAD

**Issue by nrailgun** [hpcaitech/ColossalAI#3484]
### Describe the feature

I found only DP and ZeRO strategy supports in `ColossalAI/applications/Chat/examples`, is hybrid parallelism (like PP / Megatron) supported?

**Comment by binmakeswell** [comment]
Hi @nrailgun DP+ZERO is a simple way and enough for most cases.
Examples of hybrid parallelism for large models will be provided soon.
Thanks.
