### ISSUE TITLE
No error reports, it just stops after showing "[extension] Compiling or loading the JIT-built cpu_adam kernel during runtime now". Any idea about why and where it stacks?[BUG]: 

### ISSUE THREAD

**Issue by Haoran1234567** [hpcaitech/ColossalAI#3496]
### 🐛 Describe the bug

No error reports, it just stops after showing "[extension] Compiling or loading the JIT-built cpu_adam kernel during run

### Environment

cuda:11.7
torch:'1.13.0+cu117'

**Comment by Taurids** [comment]
I want to load bloom occurs the same problem

**Comment by binmakeswell** [comment]
If it is stuck here for a long time, it should be the environment where not quite compatible.
How did you install colossalai?
What's your cuda and torch version?
Some user said it was solved with ‘upgrade gcc version from 4.8.5 to 9.5.0’

**Comment by rubbybbs** [comment]
> Hi @Taurids @Haoran1234567 If it is stuck here for a long time, it should be the environment where not quite compatible. How did you install colossalai? What's your cuda and torch version? Some user said it was solved with ‘upgrade gcc version from 4.8.5 to 9.5.0’

In my case, the problem can be solved by referring to the two questions above :-)

1. Update gcc & g++, e.g., for a conda environment:
`conda install -c conda-forge gcc=9.5.0 gxx=9.5.0`

2. Build the PyTorch extensions during `colossalai` installation
```
git clone https://github.com/hpcaitech/ColossalAI.git
cd ColossalAI
CUDA_EXT=1 pip install .
```

**Comment by Haoran1234567** [comment]
Thank you for your suggestions. My problem has been resolved. The solution is to change the ColossalAI installation method from the original 'CUDA_EXT=1 pip install colossalai 'Replace with Download From Source,' CUDA '_ EXT=1 pip install .’. I hope it can help everyone

**Comment by iceflame89** [comment]
```
rm -r  ~/.cache/colossalai/torch_extensions/
```
and try to run again
