### ISSUE TITLE
what is coati and how to install

### ISSUE THREAD

**Issue by Modas-Li** [hpcaitech/ColossalAI#3503]
### 🐛 Describe the bug

Traceback (most recent call last):
  File "train_sft.py", line 7, in <module>
    from coati.dataset import DataCollatorForSupervisedDataset, SFTDataset, SupervisedDataset
ModuleNotFoundError: No module named 'coati'
Traceback (most recent call last):
  File "train_sft.py", line 7, in <module>
    from coati.dataset import DataCollatorForSupervisedDataset, SFTDataset, SupervisedDataset
ModuleNotFoundError: No module named 'coati'
Traceback (most recent call last):
  File "train_sft.py", line 7, in <module>
    from coati.dataset import DataCollatorForSupervisedDataset, SFTDataset, SupervisedDataset
ModuleNotFoundError: No module named 'coati'
Traceback (most recent call last):
  File "train_sft.py", line 7, in <module>
    from coati.dataset import DataCollatorForSupervisedDataset, SFTDataset, SupervisedDataset
ModuleNotFoundError: No module named 'coati'

**Comment by TongLi3701** [comment]
Hi Modas,

You will need to install the package inside folder https://github.com/hpcaitech/ColossalAI/tree/main/applications/Chat using `pip install .`

Then you will have module `coati`

Thanks!

**Comment by Modas-Li** [comment]
Thank you for your email !您好，你的邮件我已收到，我会尽快给你回复。

**Comment by Modas-Li** [comment]
> 

Building wheels for collected packages: coati
  Building wheel for coati (setup.py) ... done
  Created wheel for coati: filename=coati-1.0.0-py3-none-any.whl size=63582 sha256=56804daa3dd2d332                                f65cc00fed52545329f89de893f2b2370c5fdca85290c8ba
  Stored in directory: /tmp/pip-ephem-wheel-cache-ze69xz9j/wheels/e8/71/7c/45575a5c76c31c334b963c6a                                660cb1b4f1881c79caeb57a45f
Successfully built coati


And still cannot find coati:
Traceback (most recent call last):
Traceback (most recent call last):
  File "examples/train_sft.py", line 7, in <module>
  File "examples/train_sft.py", line 7, in <module>
        from coati.dataset import DataCollatorForSupervisedDataset, SFTDataset, SupervisedDatasetfr                                om coati.dataset import DataCollatorForSupervisedDataset, SFTDataset, SupervisedDataset

ModuleNotFoundErrorModuleNotFoundError: : No module named 'coati'No module named 'coati'

Traceback (most recent call last):
  File "examples/train_sft.py", line 7, in <module>
    from coati.dataset import DataCollatorForSupervisedDataset, SFTDataset, SupervisedDataset
ModuleNotFoundError: No module named 'coati'
Traceback (most recent call last):
  File "examples/train_sft.py", line 7, in <module>
    from coati.dataset import DataCollatorForSupervisedDataset, SFTDataset, SupervisedDataset
ModuleNotFoundError: No module named 'coati'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 11448)                                 of binary: /data/anaconda3/bin/python

>

**Comment by TongLi3701** [comment]
Could you use `pip list` to check if you current env has `coati`?

**Comment by Modas-Li** [comment]
current env did not have coati, could you please advise me more,thx

**Comment by TongLi3701** [comment]
If you install successfully, you should be able to see `coati` installed in your environment. Please make sure you are in the right environment.

I suggest creating a new environment and installing all packages again.

Thanks.

**Comment by elven2016** [comment]
I also have this problem ,how do you solved?  pip show it have already installed, but the train script appears this error ModuleNotFoundError: No module named 'coati'

**Comment by binmakeswell** [comment]
> I also have this problem ,how do you solved? pip show it have already installed, but the train script appears this error ModuleNotFoundError: No module named 'coati'

This is strange. Did you follow the installation instructions? How can we reproduce your mistake?
https://github.com/hpcaitech/ColossalAI/tree/main/applications/Chat#install-the-environment

**Comment by Modas-Li** [comment]
Thank you for your email !您好，你的邮件我已收到，我会尽快给你回复。
