### ISSUE TITLE
[BUG]: problem about  examples/train_sft.sh

### ISSUE THREAD

**Issue by Tian14267** [hpcaitech/ColossalAI#3518]
### 🐛 Describe the bug

I run `examples/train_sft.sh` with 4GPU(**4 * V100**), and I get those choose:
![image](https://user-images.githubusercontent.com/27938135/230876635-3f0bc33d-c26b-491d-afb5-c1c14cde9566.png)

I have those problem:
1:  when I run `examples/train_sft.sh`，why I get those 3 choose ? I just run **Supervised instructs tuning**
2：I choose 1 or 2, and prompt me to need **Paste an API key**，I get key in and the length of key is certain 40. But it also said not len=40. I am confused.

**one other question:**
I use `nproc_per_node=4 `, Is that mean ,I cut one 7B model in 4  parts, and one part load to one GPU ?

**Comment by TongLi3701** [comment]
I would suggest registering a W&B account online (use their website) and choosing option 2.

You can copy the API key from your account and then proceed.

Thanks

**Comment by Tian14267** [comment]
> I would suggest registering a W&B account online (use their website) and choosing option 2.
> 
> You can copy the API key from your account and then proceed.
> 
> Thanks

Strangely enough, I'm just copying and pasting it, but it's not enough length.
（很奇怪的是，我是直接复制粘贴的key，但是还是会提示长度不对。我确定key的长度是40。）

**Comment by Tian14267** [comment]
Finally ,it's OK. add space before pasting

**Comment by TongLi3701** [comment]
I will close this issue.

If you have more questions, welcome to create a new issue.

Thanks.
