### ISSUE TITLE
[BUG]: ColossalAI/applications/Chat/coati/trainer/sft.py line 97 'Tensor' object has no attribute 'loss'

### ISSUE THREAD

**Issue by dingkun-ldk** [hpcaitech/ColossalAI#3521]
### 🐛 Describe the bug

ColossalAI/applications/Chat/coati/trainer/sft.py:9 7 in fit                                                                                       

![image](https://user-images.githubusercontent.com/101613683/230900224-94ec739d-8747-407f-b4d0-cbc49358ba43.png)

AttributeError: 'Tensor' object has no attribute 'loss'

**Comment by Camille7777** [comment]
Hi, @dingkun-ldk can you provide more information for us to reproduce the error?
