### ISSUE TITLE
[BUG]: TypeError: __init__() got an unexpected keyword argument 'ckpt'

### ISSUE THREAD

**Issue by lcaikk1314** [hpcaitech/ColossalAI#3526]
### 🐛 Describe the bug

When run "python scripts/txt2img.py --prompt "a photograph of an astronaut riding a horse" --plms --outdir ./output --ckpt /tmp/2023-04-11T14-51-15_train_colossalai_teyvat/diff_tb/version_0/checkpoints/epoch\=1-step\=60.ckpt --config /tmp/2023-04-11T14-51-15_train_colossalai_teyvat/configs/2023-04-11T14-51-15-project.yaml --n_samples 4",
Error occur:
Traceback (most recent call last):
  File "scripts/txt2img.py", line 306, in <module>
    main(opt)
  File "scripts/txt2img.py", line 200, in main
    model = load_model_from_config(config, f"{opt.ckpt}")
  File "scripts/txt2img.py", line 38, in load_model_from_config
    model = instantiate_from_config(config.model)
  File "/workspace/ColossalAI/examples/images/diffusion/ldm/util.py", line 79, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "/workspace/ColossalAI/examples/images/diffusion/ldm/models/diffusion/ddpm.py", line 594, in __init__
    super().__init__(conditioning_key=conditioning_key, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'ckpt'

### Environment

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Mon_May__3_19:15:13_PDT_2021
Cuda compilation tools, release 11.3, V11.3.109
Build cuda_11.3.r11.3/compiler.29920130_0

**Comment by JThh** [comment]
This [commit](https://github.com/hpcaitech/ColossalAI/commit/cad1f505125ab3d74f0390a3e3dc5796e5cd790f#diff-d7a36f944bcf9ccc4ca037db7edc7b41f9a1a9e53c514d0a708e012e228ca3f0) made the change. Can you install the latest package?

**Comment by lcaikk1314** [comment]
> This [commit](https://github.com/hpcaitech/ColossalAI/commit/cad1f505125ab3d74f0390a3e3dc5796e5cd790f#diff-d7a36f944bcf9ccc4ca037db7edc7b41f9a1a9e53c514d0a708e012e228ca3f0) made the change. Can you install the latest package?

I've used the latest code and installed the latest packages, but it still doesn't work

**Comment by NatalieC323** [comment]
Based on the provided instantiate_from_config function, it doesn't seem like the function directly handles the 'ckpt' argument, which may cause the error. We will look further into this and fix the error as soon as possible.

**Comment by NatalieC323** [comment]
Here is a piece of code commented which is functioned to detect the 'ckpt' parameter. Try uncommenting the code to see if it works.
![img_v2_64033c6e-0a79-4064-a855-7e152ecc133g](https://user-images.githubusercontent.com/127177614/232689325-23e20d9a-fae5-45be-916c-ef93065f3e98.jpg)

**Comment by lcaikk1314** [comment]
> Here is a piece of code commented which is functioned to detect the 'ckpt' parameter. Try uncommenting the code to see if it works.

According to your instructions, the problem has been solved.Thank you very much.
