### ISSUE TITLE
The results of PPO training are not so good

### ISSUE THREAD

**Issue by guijuzhejiang** [hpcaitech/ColossalAI#3543]
PPO training is difficult to converge. It feels related to the hyperparameters num_episodes, max_epochs, max_timesteps, update_timesteps. How do you recommend setting these parameters?

**Comment by binmakeswell** [comment]
Hi @guijuzhejiang There are many possible factors and parameters, and it's hard to give a best/good recommendation about them. We are also trying it with different models/datasets/etc. Welcome to share your results and insights. Thanks.
