### ISSUE TITLE
[BUG]: train_sft.py set lora_rank > 0, meet RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cpu! (when checking argument for argument mat2 in method wrapper_mm)

### ISSUE THREAD

**Issue by Desperado-Jia** [hpcaitech/ColossalAI#3554]
### 🐛 Describe the bug

lora_rank = 16, meet:
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cpu! (when checking argument for argument mat2 in method wrapper_mm)

**Comment by JThh** [comment]
May I see your `colossalai check -i`?
