### ISSUE TITLE
[BUG]: Error when using the cmd "docker pull hpcaitech/colossalai"

### ISSUE THREAD

**Issue by elfarouk** [hpcaitech/ColossalAI#3560]
### 🐛 Describe the bug

when using the default cmd "docker pull hpcaitech/colossalai" there is an error returned because not "latest" tag is created. If the tag is specified, the work around works but still not 100% proper solution for users.

### Environment

any

**Comment by binmakeswell** [comment]
Thank you for your feedback, we will fix it later.
