### ISSUE TITLE
[BUG]: An train_dataloader error is raised in the "Training reward model"  phase: TypeError: __init__() got an unexpected keyword argument 'train_dataloader'

### ISSUE THREAD

**Issue by Liuhailong2016** [hpcaitech/ColossalAI#3614]
### 🐛 Describe the bug

During the phase of traning reward model, the RewardModelTrainer could not be loaded.

 torchrun --standalone --nproc_per_node=1 examples/train_reward_model.py --pretrain "/data/rrtx/train/ColossalAI/Coati-7B/bloom-560m/" --model 'bloom' --strategy colossalai_zero2 --loss_fn 'log_exp' --save_path "/data/rrtx/train/ColossalAI/Coati-7B/bloom-560m/rmstatic.pt"
[04/20/23 19:32:48] INFO     colossalai - colossalai - INFO:
                             /root/anaconda3/lib/python3.9/site-packages/colossalai/context/parallel_context.py:522 set_device
                    INFO     colossalai - colossalai - INFO: process rank 0 is bound to device 0
[04/20/23 19:32:49] INFO     colossalai - colossalai - INFO:
                             /root/anaconda3/lib/python3.9/site-packages/colossalai/context/parallel_context.py:558 set_seed
                    INFO     colossalai - colossalai - INFO: initialized seed on rank 0, numpy: 42, python random: 42, ParallelMode.DATA: 42,
                             ParallelMode.TENSOR: 42,the default parallel seed is ParallelMode.DATA.
                    INFO     colossalai - colossalai - INFO: /root/anaconda3/lib/python3.9/site-packages/colossalai/initialize.py:115 launch
                    INFO     colossalai - colossalai - INFO: Distributed environment is initialized, data parallel size: 1, pipeline parallel
                             size: 1, tensor parallel size: 1
Some weights of the model checkpoint at /data/rrtx/train/ColossalAI/Coati-7B/bloom-560m/ were not used when initializing BloomModel: ['lm_head.weight']
- This IS expected if you are initializing BloomModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BloomModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
True
/root/anaconda3/lib/python3.9/site-packages/colossalai/kernel/op_builder/utils.py:95: UserWarning: [extension] The CUDA version on the system (11.4) does not match with the version (11.3) torch was compiled with. The mismatch is found in the minor version. As the APIs are compatible, we will allow compilation to proceed. If you encounter any issue when using the built kernel, please try to build it again with fully matched CUDA versions
  warnings.warn(
[extension] Compiling or loading the JIT-built cpu_adam kernel during runtime now
Emitting ninja build file /root/.cache/colossalai/torch_extensions/torch1.12_cu11.3/build.ninja...
Building extension module cpu_adam...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module cpu_adam...
[extension] Time to compile or load cpu_adam op: 0.2494218349456787 seconds
True
/root/anaconda3/lib/python3.9/site-packages/colossalai/kernel/op_builder/utils.py:95: UserWarning: [extension] The CUDA version on the system (11.4) does not match with the version (11.3) torch was compiled with. The mismatch is found in the minor version. As the APIs are compatible, we will allow compilation to proceed. If you encounter any issue when using the built kernel, please try to build it again with fully matched CUDA versions
  warnings.warn(
[extension] Compiling or loading the JIT-built fused_optim kernel during runtime now
Detected CUDA files, patching ldflags
Emitting ninja build file /root/.cache/colossalai/torch_extensions/torch1.12_cu11.3/build.ninja...
Building extension module fused_optim...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module fused_optim...
[extension] Time to compile or load fused_optim op: 0.21448278427124023 seconds
Found cached dataset parquet (/root/.cache/huggingface/datasets/Dahoas___parquet/default-b9d2c4937d617106/0.0.0/2a3b91fbd88a2c90d1dbbb32b460cf621d31bd5b05b934492fdef7d8d6f236ec)
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 586.04it/s]
Parameter 'indices'=<generator object train.<locals>.<genexpr> at 0x7f580416db30> of the transform datasets.arrow_dataset.Dataset.select couldn't be hashed properly, a random hash was used instead. Make sure your transforms and parameters are serializable with pickle or dill for the dataset fingerprinting and caching to work. If you reuse this transform, the caching mechanism will consider it to be different from the previous calls and recompute everything. This warning is only showed once. Subsequent hashing failures won't be showed.
100%|███████████████████████████████████████████████████████████████████████████████████████████████████| 76256/76256 [01:49<00:00, 698.37it/s]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 1020/1020 [00:01<00:00, 644.10it/s]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 5103/5103 [00:08<00:00, 613.22it/s]
Traceback (most recent call last):
  File "/root/ColossalAI/applications/Chat/examples/train_reward_model.py", line 193, in <module>
    train(args)
  File "/root/ColossalAI/applications/Chat/examples/train_reward_model.py", line 151, in train
    trainer = RewardModelTrainer(model=model,
TypeError: __init__() got an unexpected keyword argument 'train_dataloader'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 9089) of binary: /root/anaconda3/bin/python
Traceback (most recent call last):
  File "/root/anaconda3/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/root/anaconda3/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/root/anaconda3/lib/python3.9/site-packages/torch/distributed/run.py", line 761, in main
    run(args)
  File "/root/anaconda3/lib/python3.9/site-packages/torch/distributed/run.py", line 752, in run
    elastic_launch(
  File "/root/anaconda3/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/root/anaconda3/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
examples/train_reward_model.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-04-20_19:35:00
  host      : localhost.vm
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 9089)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html

**Comment by JThh** [comment]
Can we pull the latest changes from our repo and install coati again?

**Comment by Liuhailong2016** [comment]
This issue had been solved.

The initial RewardModelTrainer in training_reward_ model.py should remove the parameter define, change the trainer definition from

    trainer = RewardModelTrainer(model=model,
                                 strategy=strategy,
                                 optim=optim,
                                 loss_fn=loss_fn,
                                 train_dataloader=train_dataloader,
                                 valid_dataloader=valid_dataloader,
                                 eval_dataloader=eval_dataloader,
                                 batch_size=args.batch_size,
                                 max_epochs=args.max_epochs)

to 
    trainer = RewardModelTrainer(model,
                                 strategy,
                                 optim,
                                 loss_fn,
                                 train_dataloader,
                                 valid_dataloader,
                                 eval_dataloader,
                                 args.batch_size,
                                 args.max_epochs)
