### ISSUE TITLE
[BUG]: the result after fine-tuning sft model always generated same answer

### ISSUE THREAD

**Issue by jialesmu** [hpcaitech/ColossalAI#3644]
### 🐛 Describe the bug

the output has always show like this pic, how should I solve this problem? the sft model generated answer not end until it achieve max_length 

### Environment

![image](https://user-images.githubusercontent.com/40394061/234495238-092da8ec-5354-4bac-a73a-eace747530e3.png)

**Comment by binmakeswell** [comment]
Hi @jialesmu You can try to adjust [these parameters](https://huggingface.co/docs/transformers/main_classes/text_generation).
![img_v2_ea8b9958-5ad7-4aba-8440-07eb4636821g](https://github.com/hpcaitech/ColossalAI/assets/61670638/97700551-90e4-4967-8e75-28097447feae)
![img_v2_722e68ed-c61a-4d98-a093-1cee58142c4g](https://github.com/hpcaitech/ColossalAI/assets/61670638/9b099a71-3c30-4aa6-be35-5501741a1258)
