### ISSUE TITLE
加载pretrain model报错

### ISSUE THREAD

**Issue by wangsenhao1** [hpcaitech/ColossalAI#3670]
### 📚 The doc issue

cuda 10.2
torch 1.12.1
gpu V100*2
colossalai 0.2.8

加载pretrain model代码如下：
config = GPT2Config.from_pretrained('gpt2-medium')
tp_degree = 2
default_pg = ProcessGroup(tp_degree=tp_degree)
default_dist_spec = ShardSpec([-1], [tp_degree])
with ColoInitContext(device='cpu', default_dist_spec=default_dist_spec, default_pg=default_pg):
        model = GPT2Model.from_pretrained('gpt2-medium', config=config)
        numel = sum([p.numel() for p in model.parameters()])
        logger.info(f"model params before gemini: {str_of_num(numel)}")
加载完毕后报错
![image](https://user-images.githubusercontent.com/46346381/235124487-0037b4c3-1791-4928-9393-064f8c84704b.png)
这是为什么？搞了好久了，求各位大佬解答

**Comment by JThh** [comment]
Can you try imitating what was done in [this example](https://github.com/hpcaitech/ColossalAI/blob/1a60dc07a8a6ef6980ffb913b8cbed795de92bff/examples/language/gpt/gemini/commons/model_zoo.py#L32) to load gpt2-medium? 

And refer to the steps of loading the model from [this line](https://github.com/hpcaitech/ColossalAI/blob/1a60dc07a8a6ef6980ffb913b8cbed795de92bff/examples/language/gpt/gemini/train_gpt_demo.py#L219).

**Comment by wangsenhao1** [comment]
那样加载model是一个只有架子的空模型吧，我想要transformers已经预训练好的模型，不用我再从头开始训练

**Comment by JThh** [comment]
是的，加载的就是transformers预训练好的模型。

**Comment by wangsenhao1** [comment]
> 

![image](https://user-images.githubusercontent.com/46346381/236096889-b6d1f16b-2bf7-4db9-878c-d3037d09475e.png)
这行代码不是从头开始搭建一个gpt模型么？没有预训练好的参数吧

**Comment by zhangyuanscall** [comment]
同样，我发现在加载huggingface初始化好的模型时候报错

**Comment by binmakeswell** [comment]
Hi @wangsenhao1 @zhangyuanscall You can refer to the solution of #2770  Thanks.
