### ISSUE TITLE
[Inference] How to generate answers after stage 3 PPO?

### ISSUE THREAD

**Issue by JinghongZeng** [hpcaitech/ColossalAI#3673]
Hi, I am doing stage 3 PPO in the `Chat` folder, and the result is a .pt model. I trained this model with GPT2 all the way. I am wondering if this model can be used to generate answers and how? I used the `generate_answers.py` in the `evaluate` folder to generate answers from this model with `do_sample = False`, but the answers are weird: each answer is identically a sequence of punctuations like "((((((". 

Some answers in json format:
`
[
    {
        "category": "coding",
        "instruction": "Write a program to find the nth Fibonacci number using dynamic programming.",
        "input": "",
        "output": "((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((\"",
        "id": 64
    },
    {
        "category": "common-sense",
        "instruction": "In a world where automation is becoming increasingly prevalent, is it more important to prioritize job creation or technological progress?",
        "input": "",
        "output": "((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((\"",
        "id": 40
    },
`

If I choose `do_sample = True`, there would be an error saying `RuntimeError: probability tensor contains either inf, nan or element < 0` and `ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 20420) of binary: /usr/bin/python3`.

I am using Ubuntu on WSL. Colossalai and other packages versions are up to date.

**Comment by binmakeswell** [comment]
Hi @JinghongZeng You can refer to the solution of #3644  Thanks.
