### ISSUE TITLE
train on a multi-gpu server

### ISSUE THREAD

**Issue by DevinCheung** [hpcaitech/ColossalAI#37]
For the case that I have only a multi-GPU server, no distributed system is available, how could I use all GPUs to train a model? Thanks!

**Comment by FrankLeeeee** [comment]
Hi Devin, you can start multi-GPU training via the following command
```
python -m torch.distributed.launch --nproc_per_node <num_of_gpus> main.py --world_size <num_of_gpus> --config <path to your config file>
```
We will add this into our documentation in the future as well.
