### ISSUE TITLE
[BUG]: CUDA out of memory when I training on stage3

### ISSUE THREAD

**Issue by leonselina** [hpcaitech/ColossalAI#3723]
### 🐛 Describe the bug

CUDA out of memory when I training on stage3. 
I got rm model  trained on stage2 with colossalai_zero2_cpu and A6000 48GB * 2 , but it's still OOM error on stage3
whatever with colossalai_zero2_cpu or colossalai_gemini.
should I need Lora?

**Comment by Mandy0016** [comment]
Do you have a solution for the 'out of memory' issue?

**Comment by JThh** [comment]
Yes, you may try using smaller LoRA rank values in the first two stages to fine-tune the pretrained models.
