### ISSUE TITLE
如何训练对话系统并生成数据集？/ How to train the dialogue system and generate a dataset?

### ISSUE THREAD

**Issue by gg22mm** [hpcaitech/ColossalAI#3726]
### 📚 The doc issue

如何训练对话系统并生成数据集？/ How to train the dialogue system and generate a dataset?

看了文档 / Read the document： https://github.com/hpcaitech/ColossalAI/tree/main/applications/Chat
看了数据 / Read the document： https://github.com/XueFuzhao/InstructionWild/blob/main/data/seed_prompts_ch.jsonl

![图片](https://github.com/hpcaitech/ColossalAI/assets/6648329/39193b86-3f16-4833-be23-e952d0edefd6)

这些都测试数据，没有训练数据格式，更没有多轮对话数据格式？  / Are these all test data without training data format, let alone multi round conversation data format?

问怎么训练多轮对话系统呢？/ How to train a multi round dialogue system?

**Comment by JThh** [comment]
Hi, @gg22mm, you should use datasets described in this [file](https://github.com/XueFuzhao/InstructionWild/blob/main/data/README.md) for actual training; it contains formatted training data.

**Comment by JThh** [comment]
In reward model training, there are normally multiple utterances like [here](https://huggingface.co/datasets/Anthropic/hh-rlhf/viewer/Anthropic--hh-rlhf/train?row=1).

**Comment by gg22mm** [comment]
Thank you.
