### ISSUE TITLE
[BUG]: code in ppo.py always read same datas from prompt_dataloader

### ISSUE THREAD

**Issue by lizongzhi** [hpcaitech/ColossalAI#3746]
### 🐛 Describe the bug

![1684209059995](https://github.com/hpcaitech/ColossalAI/assets/1809205/08ce4ca7-e1af-416a-8ca9-a63fcc419f0e)
“ prompts = next(iter(self.prompt_dataloader))”   always read same data from prompt_dataloader. Is it correct?

And what is meaning of "num_episodes" and "max_timesteps"? How to set these two param?

thank you

**Comment by lizongzhi** [comment]
@chengeharrison

**Comment by binmakeswell** [comment]
Hi @lizongzhi Thanks for your feedback, we will fix it later.

**Comment by haley05-cloud** [comment]
This will raise a StopIteration exception. How to set num_episodes and max_timesteps ?

**Comment by chengeharrison** [comment]
The error lies in  the `__len__` fuction in `coati/dataset/prompt_dataset.py`, a quick fix can be:

```python
    def __len__(self):
        return len(self.keyed_prompt["input_ids"])
```

We will soon fix this in the main branch.

**Comment by haley05-cloud** [comment]
> The error lies in the `__len__` fuction in `coati/dataset/prompt_dataset.py` in line 47, a quick fix can be:
> 
> ```python
>     def __len__(self):
>         return len(self.keyed_prompt["input_ids"])
> ```
> 
> Don't forget to run `pip install .` when you make changes to `coati`.
> 
> We will soon fix this in the main branch.

it work now. Thank you

**Comment by chengeharrison** [comment]
> ### 🐛 Describe the bug
> ![1684209059995](https://user-images.githubusercontent.com/1809205/238528496-08ce4ca7-e1af-416a-8ca9-a63fcc419f0e.png) “ prompts = next(iter(self.prompt_dataloader))” always read same data from prompt_dataloader. Is it correct?
> 
> And what is meaning of "num_episodes" and "max_timesteps"? How to set these two param?
> 
> thank you
> 
> ### Environment
> _No response_

Hi, @lizongzhi, here are some explanations. 
1. During one `timestep`, experience will be made.
2. When `timestep % update_timesteps == 0`, the model will learn once. 
3. When `timestep` reaches `max_timesteps`, one episode is over.

This training process is similar with that of other RL applications such as training an agent to play games. 
1. In one episode, the agent will have one life. 
2. In each step the agent will choose one action such as attack or something and the system will return a reward (this is "make experience"). 
3. When `timestep % update_timesteps == 0`, the agent will learn to play the game accoding to its experience buffer. 
4. One episode will end if the agent loses its life or it reaches the max timestep.

To set these parameters, I think you should at least let `num_episodes * max_timesteps * experience_batch_size` >> `prompt dataset size` and make sure the model is updated at an appropriate frequency (number of updating: `num_episodes * max_timesteps / update_timesteps`).
