### ISSUE TITLE
Program is stuck in this step when I'm running train_sft.sh

### ISSUE THREAD

**Issue by TTYee** [hpcaitech/ColossalAI#3818]
when I'm running train_sft.sh, I find the program is always stuck in this step.
![image](https://github.com/hpcaitech/ColossalAI/assets/100339350/230b2446-6965-4837-9c12-8a4dd7990a8c)
and the GPU usage is always stuck at 1889MB.
![image](https://github.com/hpcaitech/ColossalAI/assets/100339350/3cf708b5-1ada-4628-879c-950190b0bb4b)
And here is the content in train_sft.sh( I set the arguments according to the tutorial video)
![image](https://github.com/hpcaitech/ColossalAI/assets/100339350/86ffc649-cb04-471d-ae86-e55075dfce05)
Does anyone have the same problem? What can I do?

**Comment by gehuageyan** [comment]
me too, still fail now
