### ISSUE TITLE
[BUG]: CUDA Version: 12.1   requirements-test.txt error

### ISSUE THREAD

**Issue by okwow123** [hpcaitech/ColossalAI#3875]
### 🐛 Describe the bug

1)fbgemm-gpu==0.2.0   not found library -> fbgemm-gpu==0.3.0 upgrade fixed.

2)  git+https://github.com/HazyResearch/flash-attention.git@c422fee3776eb3ea24e011ef641fd5fbeb212623#egg=flash_attn
I encountered below error

note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> flash_attn

### Environment

CUDA Version: 12.1 
ubuntu 22.04

**Comment by Fridge003** [comment]
I've met the same bug today. Later I found that my python version (3.10) was too high for  0.2.0 version of fbgemm-gpu to be downloaded. I downgraded my python to 3.7 and solved the bug for fbgemm-gpu package.

The requirement for flash_attn should be okay, I didn't encounter bug on this package.
