### ISSUE TITLE
[BUG]: code in /home/project/coati/trainer/ppo.py always read same datas from prompt_dataloader

### ISSUE THREAD

**Issue by l241025097** [hpcaitech/ColossalAI#3894]
### 🐛 Describe the bug

always read same data from prompt_dataloader:
<img width="536" alt="0165e57217cfa0ce8efd4b6f7813c73" src="https://github.com/hpcaitech/ColossalAI/assets/31737569/1800c1b6-34bb-4948-a031-8f3110103656">
should be changed to:
<img width="561" alt="83568ab9c36368527b32aea7fc8ec92" src="https://github.com/hpcaitech/ColossalAI/assets/31737569/45372d2d-d009-49e3-aebe-b0580a70da52">
Please check.

**Comment by jiangmingyan** [comment]
This is random because shuffle is True.

**Comment by l241025097** [comment]
> This is random because shuffle is True.

<img width="969" alt="git_change" src="https://github.com/hpcaitech/ColossalAI/assets/31737569/6f1eff96-d16d-4979-a7c9-82132d295dd7">
<img width="968" alt="git_no_change" src="https://github.com/hpcaitech/ColossalAI/assets/31737569/a3995e9b-fd5f-4d36-a1eb-a5dfed63e844">

'shuffle'  is invalid while training with multiple gpus.

**Comment by CWHer** [comment]
Could you provide your launch command so that we can better reproduce this error? :)

**Comment by CWHer** [comment]
Actually, I can not reproduce this error in my environment.
Besides, this implementation is modified in b03d64d010cb6803b66230a0386bc62d989e6ef6 and I believe the bug is fixed.
Please reopen the issue if you find it still exists. :)
