### ISSUE TITLE
Chat的reward_model.py中-1有点疑惑

### ISSUE THREAD

**Issue by guojianwei** [hpcaitech/ColossalAI#3950]
https://github.com/hpcaitech/ColossalAI/blob/1aadeedeea4e5f2ee6304e10abe38ceb7beda33f/applications/Chat/coati/models/base/reward_model.py#LL39C13-L39C13 在Chat的reward_model.py里为什么这里要去掉最后一个呢？在第三阶段时是去掉一个batch中的最后一个</s>吗

**Comment by jiangmingyan** [comment]
The last token is predicted, so don't use it to calculate rewards.

**Comment by guojianwei** [comment]
Thank you for reply,&nbsp;
At reward_model.py forward method, assume that sequences.shape is (batch_size, seq_len)
so, last_hidden_states.shape will be (batch_size, seq_len, hidden_size) and&nbsp; self.value_head(last_hidden_states) will be (batch_size, seq_len, 1).

If values = self.value_head(last_hidden_states)[:, :-1] , the values.shape will be (batch_size, seq_len-1, 1).




My confusion is that when batch_size&gt;1, the last token of different sequences may be not in the same position after padding.&nbsp;
I think there may be a problem using [:,:-1] to remove last token's predicting value when batch_size&gt;1 and seq_len are different among sequences.
&nbsp;


剑诚
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年6月19日(星期一) 中午1:37
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [hpcaitech/ColossalAI] Chat的reward_model.py中-1有点疑惑 (Issue #3950)





 
The last token is predicted, so don't use it to calculate rewards.
