### ISSUE TITLE
[BUG]: Incompatibility for test requirements

### ISSUE THREAD

**Issue by Fridge003** [hpcaitech/ColossalAI#3952]
### 🐛 Describe the bug

As I am configuring test environment through 
```bash
pip install -r requirements/requirements-test.txt
```

An error pops up:
<img width="1769" alt="截屏2023-06-09 13 09 17" src="https://github.com/hpcaitech/ColossalAI/assets/56809903/fcb40078-71f1-4178-a676-10cc5289f1f8">

Maybe the requirement "fbgemm-gpu==0.2.0" should be modified to "fbgemm-gpu>=0.2.0" ?

**Comment by okwow123** [comment]
you have to let me know your system environments.

**Comment by Fridge003** [comment]
> you have to let me know your system environments.
OS: Linux
pip 23.0.1
torch 1.13.1+cu116

**Comment by Fridge003** [comment]
Environment:
OS: Linux
pip 23.0.1
torch 1.13.1+cu116
