### ISSUE TITLE
add ColossalAI org to Hugging Face

### ISSUE THREAD

**Issue by AK391** [hpcaitech/ColossalAI#396]
### Describe the feature

Hi, is there any interest in adding a ColossalAI organization to Huggingface? Organization can add models, datasets, and spaces(web demos)

some examples organizations
Keras: https://huggingface.co/keras-io
Facebook: https://huggingface.co/facebook
Microsoft: https://huggingface.co/microsoft
Pytorch: https://huggingface.co/pytorch

We can help with setting up the org and adding models/datasets/spaces thanks

a new organization can be added by going to https://huggingface.co/organizations/new

**Comment by FrankLeeeee** [comment]
Hi @AK391 , very glad to see your invitation! We will register our organization in Huggingface and let's keep in touch.

**Comment by AK391** [comment]
@FrankLeeeee Great, let me know if there are any issues, also a link can be added to the README with a Hugging Face badge so that users can find the organization and join

example:     <a href="https://huggingface.co/ColossalAI"><img src="https://img.shields.io/badge/%F0%9F%A4%97-Hugging%20Face-blue"></a>

**Comment by FrankLeeeee** [comment]
@AK391 Great, thanks!

**Comment by FrankLeeeee** [comment]
Hi @AK391 , may I know how to get the organization domain name verified?
<img width="1014" alt="Screenshot 2022-03-14 at 4 11 36 PM" src="https://user-images.githubusercontent.com/31818963/158131084-514d6ab1-2faf-4498-b67c-3838eef23225.png">

**Comment by AK391** [comment]
@FrankLeeeee Sure, looks like its verified now? Let me know if you still need assistance thanks

**Comment by AK391** [comment]
@FrankLeeeee Great, I can help with adding Gradio web demos to the organization for examples here: https://github.com/hpcaitech/ColossalAI-Examples for users to try out

**Comment by FrankLeeeee** [comment]
Thanks, @AK391 ! We will put up a demo in the next release :)

**Comment by binmakeswell** [comment]
Hi, @AK391 We plan to develop some features to provide better support to the huggingface community. Can we further communicate through email?
If you are interested, please send an email to ybl@hpcaitech.com, thanks.
