### ISSUE TITLE
[RFC] Collate testing functions into colossalai.testing module

### ISSUE THREAD

**Issue by FrankLeeeee** [hpcaitech/ColossalAI#405]
### Describe the feature

There are several testing functions which are commonly used in the `tests` folder, (e.g. all close). We can indeed make it a module in colossalai, like [`torch.testing`](https://github.com/pytorch/pytorch/tree/master/torch/testing). We can add our own customized `parameterize` function here as well so as not to initialize the distributed network for every single test case.

**Comment by FrankLeeeee** [comment]
@kurisusnowdeng @feifeibear

**Comment by feifeibear** [comment]
In every single unittest, we now init the network from scratch. Do you mean we can init a global network and reuse it for different tests? In this case, we only need to reset the network every time. However, do we have to init a number of networks in different MP and DP degrees?

**Comment by FrankLeeeee** [comment]
I mean we can reduce the number of network initialization by doing this:

```python
# current way
@pytest.mark.parametrize("world_size", [1, 2])
@pytest.mark.parametrize("cpu_offload", [True, False])
@pytest.mark.parametrize("shard_strategy", [TensorShardStrategy, BucketTensorShardStrategy])
def test_sharded_optim_v2(world_size, cpu_offload, shard_strategy):
    ...

# after collation
@colossalai.testing.parametrize("cpu_offload", [True, False])
@colossalai.testing.parametrize("shard_strategy", [TensorShardStrategy, BucketTensorShardStrategy])
def run_dist(cpu_offload, shard_strategy):
    ...

@pytest.mark.parametrize("world_size", [1, 2])
def test_sharded_optim_v2(world_size, cpu_offload, shard_strategy):
    ...
```

The first case will initialize 8 times but the latter only does it 2 times

**Comment by ver217** [comment]
> I mean we can reduce the number of network initialization by doing this:
> 
> ```python
> # current way
> @pytest.mark.parametrize("world_size", [1, 2])
> @pytest.mark.parametrize("cpu_offload", [True, False])
> @pytest.mark.parametrize("shard_strategy", [TensorShardStrategy, BucketTensorShardStrategy])
> def test_sharded_optim_v2(world_size, cpu_offload, shard_strategy):
>     ...
> 
> # after collation
> @colossalai.testing.parametrize("cpu_offload", [True, False])
> @colossalai.testing.parametrize("shard_strategy", [TensorShardStrategy, BucketTensorShardStrategy])
> def run_dist(cpu_offload, shard_strategy):
>     ...
> 
> @pytest.mark.parametrize("world_size", [1, 2])
> def test_sharded_optim_v2(world_size, cpu_offload, shard_strategy):
>     ...
> ```
> 
> The first case will initialize 8 times but the latter only does it 2 times

I just wrote a naive version FYI:
```python
class Parameterize:
    def __init__(self, **kwargs):
        self.keys = []
        self.values = []
        num_combs = 1
        for k, v in kwargs.items():
            self.keys.append(k)
            self.values.append(v)
            num_combs *= len(v)
        offset = [0] * len(self.keys)
        self.combs = []
        for n in range(num_combs):
            values = [val[offset[i]] for i, val in enumerate(self.values)]
            self.combs.append({k: values[i] for i, k in enumerate(self.keys)})
            if n < num_combs - 1:
                idx = 0
                while offset[idx] + 1 == len(self.values[idx]):
                    offset[idx] = 0
                    idx += 1
                offset[idx] += 1

    def __iter__(self):
        return iter(self.combs)

    def __len__(self):
        return len(self.combs)

    def __getitem__(self, idx):
        return self.combs[idx]


if __name__ == '__main__':
    parameters = Parameterize(world_size=[1, 2], checkpoint=[
        False, True], offload=[True])
    for kwargs in parameters:
        print(kwargs)
```

**Comment by FrankLeeeee** [comment]
> > I mean we can reduce the number of network initialization by doing this:
> > ```python
> > # current way
> > @pytest.mark.parametrize("world_size", [1, 2])
> > @pytest.mark.parametrize("cpu_offload", [True, False])
> > @pytest.mark.parametrize("shard_strategy", [TensorShardStrategy, BucketTensorShardStrategy])
> > def test_sharded_optim_v2(world_size, cpu_offload, shard_strategy):
> >     ...
> > 
> > # after collation
> > @colossalai.testing.parametrize("cpu_offload", [True, False])
> > @colossalai.testing.parametrize("shard_strategy", [TensorShardStrategy, BucketTensorShardStrategy])
> > def run_dist(cpu_offload, shard_strategy):
> >     ...
> > 
> > @pytest.mark.parametrize("world_size", [1, 2])
> > def test_sharded_optim_v2(world_size, cpu_offload, shard_strategy):
> >     ...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The first case will initialize 8 times but the latter only does it 2 times
> 
> I just wrote a naive version FYI:
> 
> ```python
> class Parameterize:
>     def __init__(self, **kwargs):
>         self.keys = []
>         self.values = []
>         num_combs = 1
>         for k, v in kwargs.items():
>             self.keys.append(k)
>             self.values.append(v)
>             num_combs *= len(v)
>         offset = [0] * len(self.keys)
>         self.combs = []
>         for n in range(num_combs):
>             values = [val[offset[i]] for i, val in enumerate(self.values)]
>             self.combs.append({k: values[i] for i, k in enumerate(self.keys)})
>             if n < num_combs - 1:
>                 idx = 0
>                 while offset[idx] + 1 == len(self.values[idx]):
>                     offset[idx] = 0
>                     idx += 1
>                 offset[idx] += 1
> 
>     def __iter__(self):
>         return iter(self.combs)
> 
>     def __len__(self):
>         return len(self.combs)
> 
>     def __getitem__(self, idx):
>         return self.combs[idx]
> 
> 
> if __name__ == '__main__':
>     parameters = Parameterize(world_size=[1, 2], checkpoint=[
>         False, True], offload=[True])
>     for kwargs in parameters:
>         print(kwargs)
> ```

Great, thanks!
