### ISSUE TITLE
[BUG]: Is there a better way to deal with data overflow?

### ISSUE THREAD

**Issue by densechen** [hpcaitech/ColossalAI#4057]
### 🐛 Describe the bug

I used colossalai to train a model on a large dataset. 
During training, we find a lot of steps will occur "INFO: Found overflow.".

By default, colossalai will skip this step's updating operation. But it is too expensive for us to skip a lot of steps.
Is there any better way to deal with this? 
Or how can we better avoid this warning?

**Comment by jiangmingyan** [comment]
> ### 🐛 Describe the bug
> I used colossalai to train a model on a large dataset. During training, we find a lot of steps will occur "INFO: Found overflow.".
> 
> By default, colossalai will skip this step's updating operation. But it is too expensive for us to skip a lot of steps. Is there any better way to deal with this? Or how can we better avoid this warning?
> 
> ### Environment
> _No response_
You can use the TorchDDPPlugin for training.
