### ISSUE TITLE
[BUG]: Bug problem for sft_dataset.py

### ISSUE THREAD

**Issue by Desperado-Jia** [hpcaitech/ColossalAI#4135]
### 🐛 Describe the bug

https://github.com/hpcaitech/ColossalAI/blob/09fe9dc704dd388f08e3b19dca65d3d0be64f106/applications/Chat/coati/dataset/sft_dataset.py#L97-L113

`label[:source_len] = IGNORE_INDEX` in `preprocess()` function may meet error when left padding.

![img_v2_133b5dca-f6a9-46e8-a7fe-1180163b001g](https://github.com/hpcaitech/ColossalAI/assets/31888981/77f2b3e0-79bc-4d4a-9db2-9577d9453eb9)

**Comment by CWHer** [comment]
![4b8a8b3c-a00b-4a6b-a1e6-29f872458f0f](https://github.com/hpcaitech/ColossalAI/assets/31888981/21e784ec-ab7c-4349-9df6-c0966849c749)

FYI, the behavior of OPT tokenizer is a little weird. It adds an `eos` token to the beginning of the example.
