### ISSUE TITLE
[RFC] Add CLI to ColossalAI

### ISSUE THREAD

**Issue by FrankLeeeee** [hpcaitech/ColossalAI#415]
### Describe the feature

We can add a CLI to provide easy-to-use utilities for the users for various functions. I have thought about several features that this CLI can provide.

1. **Launch multiple processes**

We currently reply on three launchers, which are torchrun, slurm and openmpi, to launch multiple processes. I believe that torchrun is the most common one used by PyTorch users, but torchrun requires manually executing this command on different nodes. SLURM and OpenMPI are much less common, especially for AI beginners. Thus, it is important for us to provide a launch tool that can easily help the users launch multiple-processes training.

Usage:

```bash
colossalai launch <launch_args> python train.py <train_args>
```

The `launch_args` can include (but not limited to the following):
- `--hosts`: the list of node hostnames
- `--hostfile`: the file containing a list of hostnames
- `-np`: number of processes to launch, the number of processes on each node will be `np / number of nodes`. 
- `--style`: this argument can be `torch`, `slurm` or `openmpi`. This is because that we provide three launch helper functions in colossalai, i.e. `launch_from_<torch/slurm/openmpi>`. These launch helpers read rank and world from the environment varialbe. This argument is to set environment variables differently so that the user does not have to manually change the launch method in their training script.

---

2. **Check dependency**

This command is to check whether the current installation is correct. For example, this function can let you know that if colossalai is built with CUDA extension.

Usage:

```bash
colossalai check
```

This will return the a list of check items:
1. CUDA/NCCL/torch/python version compatibility
2. CUDA extension
3. Nvidia Apex
4. to be added... 

---

3. **System Benchmark**

*This function is still in consideration.*

As we would like to support auto-parallelism in the future, knowing the system performance is necessary to propose suitable parallelism strategy. It is also important to know the peak performance of the system for experiment purpose as well, e.g. we want to test the maximum bandwidth and measure the bandwidth utilization in our experiments.

Usage:

```bash
colossalai benchmark <benchmark_args>
```

`benchmark_args` can include (but not limited to):
1. `--type`: this argument can be `bandwidth`, `GPU FLOPs`, etc.

**Comment by feifeibear** [comment]
I love this feature. it's sure to be welcomed by users

**Comment by kurisusnowdeng** [comment]
Just some small points to clarify. 
1. If we can handle launch on multiple nodes, we then don't need any `slurm` or `torchrun` stuff at all. Or, if we handle launch only on each node, we better guarantee the args not to confuse users (maybe we can make usage as close to torchrun as possible).
2. `colossalai launch <launch_args> python train.py <train_args>` why we need `python` here?

**Comment by FrankLeeeee** [comment]
> Just some small points to clarify.
> 
> 1. If we can handle the launch on multiple nodes, we then don't need any `slurm` or `torchrun` stuff at all. Or, if we handle the launch only on each single node, we better guarantee the args not to confuse users (maybe we can make usage as close to torchrun as possible).
> 2. `colossalai launch <launch_args> python train.py <train_args>` why we need `python` here?

1. I think we can remove the support for openmpi and torchrun. However, I am considering keeping slurm because slurm is widely used on clusters and using `srun` can launch processes automatically without knowing the specific node list.
2. `python` can be surely removed. Adding `python` making it more like a general launcher. The general launcher is `launcher + executable`. We can remove `python` if assuming `python` is the executable.

**Comment by FrankLeeeee** [comment]
One more CLI we can add is to check the correctness of the configuration file. This feature can be integrated with the `check` above.

```bash
colossalai check `<args>`
```

`<args>` can be:
-  `-i` / `--installation`: same as the second feature above.
- `-c` / `--config`: check the configuration schema and typo
