### ISSUE TITLE
[BUG]: how to use the logger

### ISSUE THREAD

**Issue by zhangvia** [hpcaitech/ColossalAI#4156]
### 🐛 Describe the bug

![image](https://github.com/hpcaitech/ColossalAI/assets/38352569/ee7e905b-55a0-45e5-a89c-87ea70a18db8)
ervery log.info(message) will print the code path and message, how to disable the code path print, just print the message

**Comment by Gy-Lu** [comment]
The log format is:
```
INFO: file_path:line_number call_function
INFO: the message
```
the first line is used to remind users where the info message happens.
However, the too-long path introduces your problem, we will fix it soon.

**Comment by zhangvia** [comment]
> The log format is:
> 
> ```
> INFO: file_path:line_number call_function
> INFO: the message
> ```
> 
> the first line is used to remind users where the info message happens. However, the too-long path introduces your problem, we will fix it soon.

so, if someone want to print some log line by line, the result will be wierd. i think it would be better that user can choose whether to disable the code path print
