### ISSUE TITLE
[FEATURE]: which file should be used for prompt_dataset

### ISSUE THREAD

**Issue by SeekPoint** [hpcaitech/ColossalAI#4222]
### Describe the feature

torchrun --standalone --nproc_per_node=2 train_prompts.py \
    --pretrain_dataset "/home/amd01/hf_model/opt-350m" \
    --prompt_dataset *******************
    --strategy colossalai_zero2 \
    --num_episodes 1 --num_collect_steps 2 --num_update_steps 1 \
    --train_batch_size 2

i try the files from https://github.com/XueFuzhao/InstructionWild, all failed

**Comment by CWHer** [comment]
The format of `prompt_dataset` is as follows,

```json
[
    ...
    {
        "instruction": "Write a descriptive paragraph about a memorable vacation you went on",
        "id": 1
    },
    {
        "instruction": "Write a persuasive essay arguing why homework should be banned in schools",
        "id": 2
    },
]
```

And I believe https://github.com/XueFuzhao/InstructionWild contains it.
