### ISSUE TITLE
[BUG]: can not run batch2_seq2048_flash_attn for 65b llama

### ISSUE THREAD

**Issue by uygnef** [hpcaitech/ColossalAI#4326]
### 🐛 Describe the bug

hi, there

I am attempting to run the 65b benchmark  using /examples/language/llama/benchmark_65B/3d/batch2_seq2048_flash_attn.sh., but I have encountered an error. 

`RuntimeError: Failed to replace input_layernorm of type LlamaRMSNorm with 
FusedRMSNorm with the exception: No module named 'fused_layer_norm_cuda'. `

My environment has two nodes, each with 8*80g a100 with cuda11.7. Would anyone be able to assist me with this issue? Thank you in advance.

``

```│ /shardformer/shard/sharder.py:189 in _replace_sub_module                     │
│                                                                              │
│   186 │   │   │   │   │   │   │   │   │   │   │   │   │   │   │   │    self. │
│   187 │   │   │   │   │   │   │   │   │   │   │   │   │   │   │   │    **kwa │
│   188 │   │   │   except Exception as e:                                     │
│ ❱ 189 │   │   │   │   raise RuntimeError(                                    │
│   190 │   │   │   │   │   f"Failed to replace {suffix} of type {native_sub_m │
│   191 │   │   │   │   │   f" with {target_module.__qualname__} with the exce │
│   192 │   │   │   │   │   "Please check your model configuration or sharding │
╰──────────────────────────────────────────────────────────────────────────────╯
RuntimeError: Failed to replace input_layernorm of type LlamaRMSNorm with 
FusedRMSNorm with the exception: No module named 'fused_layer_norm_cuda'. Please
check your model configuration or sharding policy, you can set up an issue for 
us to help you as well.```


### Environment

Package                       Version
----------------------------- ------------------------
absl-py                       1.3.0
accelerate                    0.17.1
aiofiles                      23.1.0
aiohttp                       3.8.1
aiosignal                     1.2.0
alabaster                     0.7.12
altair                        5.0.1
anyio                         3.7.0
anykeystore                   0.2
apex                          0.1
appdirs                       1.4.4
async-timeout                 4.0.2
attrs                         22.1.0
Babel                         2.10.3
bcrypt                        3.2.2
beautifulsoup4                4.11.1
brotlipy                      0.7.0
cachetools                    5.2.0
certifi                       2021.10.8
cffi                          1.15.1
cfgv                          3.3.1
charset-normalizer            2.0.4
click                         8.1.3
cmake                         3.26.4
colorama                      0.4.4
colossalai                    0.3.0
commonmark                    0.9.1
conda                         4.12.0
conda-content-trust           0+unknown
conda-package-handling        1.8.1
contexttimer                  0.3.3
contourpy                     1.0.6
cpm-kernels                   1.0.11
cryptacular                   1.6.2
cryptography                  37.0.4
css-html-js-minify            2.5.5
cxxfilt                       0.3.0
cycler                        0.11.0
datasets                      2.3.2
decorator                     5.1.1
deepspeed                     0.9.1+61a8b3a
defusedxml                    0.7.1
diffusers                     0.14.0
dill                          0.3.5.1
distlib                       0.3.4
docker-pycreds                0.4.0
docutils                      0.19
easydict                      1.10
einops                        0.6.0
evaluate                      0.4.0
exceptiongroup                1.1.1
fabric                        2.7.0
fastapi                       0.97.0
ffmpy                         0.3.0
filelock                      3.12.2
flake8                        5.0.4
flash-attn                    1.0.7
fonttools                     4.38.0
frozenlist                    1.3.0
fschat                        0.2.15
fsspec                        2023.3.0
ghp-import                    2.1.0
gitdb                         4.0.10
GitPython                     3.1.31
google-auth                   2.21.0
google-auth-oauthlib          1.0.0
gradio                        3.23.0
greenlet                      1.1.2
grpcio                        1.50.0
h11                           0.14.0
hjson                         3.0.2
httpcore                      0.17.2
httpx                         0.24.1
huggingface-hub               0.15.1
hupper                        1.10.3
icetk                         0.0.7
identify                      2.5.1
idna                          3.3
imagesize                     1.4.1
importlib-metadata            5.0.0
iniconfig                     1.1.1
interrogate                   1.5.0
invoke                        1.7.1
jieba                         0.42.1
Jinja2                        3.1.2
joblib                        1.3.1
jsonschema                    4.17.3
kiwisolver                    1.4.4
LAMP                          0.3.0
latex2mathml                  3.73.1
linkify-it-py                 2.0.2
lit                           16.0.6
lxml                          4.9.1
Markdown                      3.3.7
markdown-it-py                2.2.0
markdown2                     2.4.8
MarkupSafe                    2.1.2
matplotlib                    3.6.1
mccabe                        0.7.0
mdit-py-plugins               0.3.3
mdtex2html                    1.2.0
mdurl                         0.1.2
mergedeep                     1.3.4
mkdocs                        1.4.1
mkdocs-material               8.5.7
mkdocs-material-extensions    1.1
mpmath                        1.2.1
mssapi                        1.1
multidict                     6.0.2
multiprocess                  0.70.13
mypy-extensions               1.0.0
netifaces                     0.11.0
networkx                      3.0rc1
nh3                           0.2.13
ninja                         1.10.2.3
nltk                          3.8.1
nodeenv                       1.7.0
numpy                         1.24.3
nvidia-cublas-cu11            11.10.3.66
nvidia-cuda-cupti-cu11        11.7.101
nvidia-cuda-nvrtc-cu11        11.7.99
nvidia-cuda-runtime-cu11      11.7.99
nvidia-cudnn-cu11             8.5.0.96
nvidia-cufft-cu11             10.9.0.58
nvidia-curand-cu11            10.2.10.91
nvidia-cusolver-cu11          11.4.0.1
nvidia-cusparse-cu11          11.7.4.91
nvidia-nccl-cu11              2.14.3
nvidia-nvtx-cu11              11.7.91
oauthlib                      3.2.2
orjson                        3.9.1
packaging                     23.1
pandas                        1.4.3
paramiko                      2.11.0
PasteDeploy                   2.1.1
pathlib2                      2.3.7.post1
pathtools                     0.1.2
pbkdf2                        1.3
Pillow                        9.3.0
pip                           23.2
plaster                       1.0
plaster-pastedeploy           0.7
platformdirs                  2.5.2
pluggy                        1.0.0
portalocker                   2.7.0
pre-commit                    2.19.0
prompt-toolkit                3.0.38
protobuf                      3.19.6
psutil                        5.9.1
PuLP                          2.7.0
py                            1.11.0
py-cpuinfo                    8.0.0
pyarrow                       11.0.0
pyasn1                        0.4.8
pyasn1-modules                0.2.8
pycodestyle                   2.9.1
pycosat                       0.6.3
pycparser                     2.21
pydantic                      1.10.2
pydub                         0.25.1
pyflakes                      2.5.0
Pygments                      2.12.0
pymdown-extensions            9.7
PyNaCl                        1.5.0
pyOpenSSL                     22.0.0
pyparsing                     3.0.9
pyramid                       2.0
pyramid-mailer                0.15.1
pyre-extensions               0.0.29
pyrsistent                    0.19.3
PySocks                       1.7.1
pytest                        7.1.2
python-dateutil               2.8.2
python-multipart              0.0.6
python-slugify                6.1.2
python3-openid                3.2.0
pytorch-triton                2.1.0+7d1a95b046
pytz                          2022.5
PyYAML                        6.0
pyyaml_env_tag                0.1
recommonmark                  0.7.1
regex                         2022.10.31
repoze.sendmail               4.4.1
requests                      2.27.1
requests-oauthlib             1.3.1
responses                     0.18.0
rich                          12.4.4
rouge-chinese                 1.0.3
rsa                           4.9
ruamel-yaml-conda             0.15.100
safetensors                   0.3.1
semantic-version              2.10.0
sentencepiece                 0.1.97
sentry-sdk                    1.25.1
setproctitle                  1.3.2
setuptools                    63.1.0
shortuuid                     1.0.11
six                           1.16.0
smmap                         5.0.0
sniffio                       1.3.0
snowballstemmer               2.2.0
some-package                  0.1
soupsieve                     2.3.2.post1
Sphinx                        5.3.0
sphinx-copybutton             0.5.0
sphinx-immaterial             0.10.0
sphinx-material               0.0.35
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-katex           0.9.0
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
SQLAlchemy                    1.4.39
starlette                     0.27.0
svgwrite                      1.4.3
sympy                         1.11.1
tabulate                      0.9.0
tensorboard                   2.13.0
tensorboard-data-server       0.7.1
tensorboard-plugin-wit        1.8.1
tensorboardX                  2.5.1
text-unidecode                1.3
tiktoken                      0.4.0
tokenizers                    0.13.3
toml                          0.10.2
tomli                         2.0.1
toolz                         0.12.0
torch                         1.13.1+cu117
torch-tb-profiler             0.4.1
torchaudio                    0.13.1+cu117
torchdata                     0.5.1
torchvision                   0.14.1+cu117
tqdm                          4.65.0
transaction                   3.0.1
transformers                  4.28.1
translationstring             1.4
triton                        2.0.0
typing_extensions             4.4.0
typing-inspect                0.9.0
uc-micro-py                   1.0.2
Unidecode                     1.3.6
urllib3                       1.26.16
uvicorn                       0.22.0
velruse                       1.1.1
venusian                      3.0.0
virtualenv                    20.15.1
wandb                         0.15.4
watchdog                      2.1.9
wavedrom                      2.0.3.post3
wcwidth                       0.2.6
WebOb                         1.8.7
websockets                    11.0.3
Werkzeug                      2.2.2
wheel                         0.37.1
WTForms                       3.0.1
wtforms-recaptcha             0.3.2
xformers                      0.0.21+c979299.d20230718
xxhash                        3.0.0
yarl                          1.7.2
zipp                          3.10.0
zope.deprecation              4.4.0
zope.interface                5.4.0
zope.sqlalchemy               1.6

**Comment by flybird1111** [comment]
> ### 🐛 Describe the bug
> hi, there
> 
> I am attempting to run the 65b benchmark using /examples/language/llama/benchmark_65B/3d/batch2_seq2048_flash_attn.sh., but I have encountered an error.
> 
> `RuntimeError: Failed to replace input_layernorm of type LlamaRMSNorm with FusedRMSNorm with the exception: No module named 'fused_layer_norm_cuda'. `
> 
> My environment has two nodes, each with 8*80g a100 with cuda11.7. Would anyone be able to assist me with this issue? Thank you in advance.
> 
> ``
> 
> ```
> │                                                                              │
> │   186 │   │   │   │   │   │   │   │   │   │   │   │   │   │   │   │    self. │
> │   187 │   │   │   │   │   │   │   │   │   │   │   │   │   │   │   │    **kwa │
> │   188 │   │   │   except Exception as e:                                     │
> │ ❱ 189 │   │   │   │   raise RuntimeError(                                    │
> │   190 │   │   │   │   │   f"Failed to replace {suffix} of type {native_sub_m │
> │   191 │   │   │   │   │   f" with {target_module.__qualname__} with the exce │
> │   192 │   │   │   │   │   "Please check your model configuration or sharding │
> ╰──────────────────────────────────────────────────────────────────────────────╯
> RuntimeError: Failed to replace input_layernorm of type LlamaRMSNorm with 
> FusedRMSNorm with the exception: No module named 'fused_layer_norm_cuda'. Please
> check your model configuration or sharding policy, you can set up an issue for 
> us to help you as well.```
> 
> 
> ### Environment
> 
> Package                       Version
> ----------------------------- ------------------------
> absl-py                       1.3.0
> accelerate                    0.17.1
> aiofiles                      23.1.0
> aiohttp                       3.8.1
> aiosignal                     1.2.0
> alabaster                     0.7.12
> altair                        5.0.1
> anyio                         3.7.0
> anykeystore                   0.2
> apex                          0.1
> appdirs                       1.4.4
> async-timeout                 4.0.2
> attrs                         22.1.0
> Babel                         2.10.3
> bcrypt                        3.2.2
> beautifulsoup4                4.11.1
> brotlipy                      0.7.0
> cachetools                    5.2.0
> certifi                       2021.10.8
> cffi                          1.15.1
> cfgv                          3.3.1
> charset-normalizer            2.0.4
> click                         8.1.3
> cmake                         3.26.4
> colorama                      0.4.4
> colossalai                    0.3.0
> commonmark                    0.9.1
> conda                         4.12.0
> conda-content-trust           0+unknown
> conda-package-handling        1.8.1
> contexttimer                  0.3.3
> contourpy                     1.0.6
> cpm-kernels                   1.0.11
> cryptacular                   1.6.2
> cryptography                  37.0.4
> css-html-js-minify            2.5.5
> cxxfilt                       0.3.0
> cycler                        0.11.0
> datasets                      2.3.2
> decorator                     5.1.1
> deepspeed                     0.9.1+61a8b3a
> defusedxml                    0.7.1
> diffusers                     0.14.0
> dill                          0.3.5.1
> distlib                       0.3.4
> docker-pycreds                0.4.0
> docutils                      0.19
> easydict                      1.10
> einops                        0.6.0
> evaluate                      0.4.0
> exceptiongroup                1.1.1
> fabric                        2.7.0
> fastapi                       0.97.0
> ffmpy                         0.3.0
> filelock                      3.12.2
> flake8                        5.0.4
> flash-attn                    1.0.7
> fonttools                     4.38.0
> frozenlist                    1.3.0
> fschat                        0.2.15
> fsspec                        2023.3.0
> ghp-import                    2.1.0
> gitdb                         4.0.10
> GitPython                     3.1.31
> google-auth                   2.21.0
> google-auth-oauthlib          1.0.0
> gradio                        3.23.0
> greenlet                      1.1.2
> grpcio                        1.50.0
> h11                           0.14.0
> hjson                         3.0.2
> httpcore                      0.17.2
> httpx                         0.24.1
> huggingface-hub               0.15.1
> hupper                        1.10.3
> icetk                         0.0.7
> identify                      2.5.1
> idna                          3.3
> imagesize                     1.4.1
> importlib-metadata            5.0.0
> iniconfig                     1.1.1
> interrogate                   1.5.0
> invoke                        1.7.1
> jieba                         0.42.1
> Jinja2                        3.1.2
> joblib                        1.3.1
> jsonschema                    4.17.3
> kiwisolver                    1.4.4
> LAMP                          0.3.0
> latex2mathml                  3.73.1
> linkify-it-py                 2.0.2
> lit                           16.0.6
> lxml                          4.9.1
> Markdown                      3.3.7
> markdown-it-py                2.2.0
> markdown2                     2.4.8
> MarkupSafe                    2.1.2
> matplotlib                    3.6.1
> mccabe                        0.7.0
> mdit-py-plugins               0.3.3
> mdtex2html                    1.2.0
> mdurl                         0.1.2
> mergedeep                     1.3.4
> mkdocs                        1.4.1
> mkdocs-material               8.5.7
> mkdocs-material-extensions    1.1
> mpmath                        1.2.1
> mssapi                        1.1
> multidict                     6.0.2
> multiprocess                  0.70.13
> mypy-extensions               1.0.0
> netifaces                     0.11.0
> networkx                      3.0rc1
> nh3                           0.2.13
> ninja                         1.10.2.3
> nltk                          3.8.1
> nodeenv                       1.7.0
> numpy                         1.24.3
> nvidia-cublas-cu11            11.10.3.66
> nvidia-cuda-cupti-cu11        11.7.101
> nvidia-cuda-nvrtc-cu11        11.7.99
> nvidia-cuda-runtime-cu11      11.7.99
> nvidia-cudnn-cu11             8.5.0.96
> nvidia-cufft-cu11             10.9.0.58
> nvidia-curand-cu11            10.2.10.91
> nvidia-cusolver-cu11          11.4.0.1
> nvidia-cusparse-cu11          11.7.4.91
> nvidia-nccl-cu11              2.14.3
> nvidia-nvtx-cu11              11.7.91
> oauthlib                      3.2.2
> orjson                        3.9.1
> packaging                     23.1
> pandas                        1.4.3
> paramiko                      2.11.0
> PasteDeploy                   2.1.1
> pathlib2                      2.3.7.post1
> pathtools                     0.1.2
> pbkdf2                        1.3
> Pillow                        9.3.0
> pip                           23.2
> plaster                       1.0
> plaster-pastedeploy           0.7
> platformdirs                  2.5.2
> pluggy                        1.0.0
> portalocker                   2.7.0
> pre-commit                    2.19.0
> prompt-toolkit                3.0.38
> protobuf                      3.19.6
> psutil                        5.9.1
> PuLP                          2.7.0
> py                            1.11.0
> py-cpuinfo                    8.0.0
> pyarrow                       11.0.0
> pyasn1                        0.4.8
> pyasn1-modules                0.2.8
> pycodestyle                   2.9.1
> pycosat                       0.6.3
> pycparser                     2.21
> pydantic                      1.10.2
> pydub                         0.25.1
> pyflakes                      2.5.0
> Pygments                      2.12.0
> pymdown-extensions            9.7
> PyNaCl                        1.5.0
> pyOpenSSL                     22.0.0
> pyparsing                     3.0.9
> pyramid                       2.0
> pyramid-mailer                0.15.1
> pyre-extensions               0.0.29
> pyrsistent                    0.19.3
> PySocks                       1.7.1
> pytest                        7.1.2
> python-dateutil               2.8.2
> python-multipart              0.0.6
> python-slugify                6.1.2
> python3-openid                3.2.0
> pytorch-triton                2.1.0+7d1a95b046
> pytz                          2022.5
> PyYAML                        6.0
> pyyaml_env_tag                0.1
> recommonmark                  0.7.1
> regex                         2022.10.31
> repoze.sendmail               4.4.1
> requests                      2.27.1
> requests-oauthlib             1.3.1
> responses                     0.18.0
> rich                          12.4.4
> rouge-chinese                 1.0.3
> rsa                           4.9
> ruamel-yaml-conda             0.15.100
> safetensors                   0.3.1
> semantic-version              2.10.0
> sentencepiece                 0.1.97
> sentry-sdk                    1.25.1
> setproctitle                  1.3.2
> setuptools                    63.1.0
> shortuuid                     1.0.11
> six                           1.16.0
> smmap                         5.0.0
> sniffio                       1.3.0
> snowballstemmer               2.2.0
> some-package                  0.1
> soupsieve                     2.3.2.post1
> Sphinx                        5.3.0
> sphinx-copybutton             0.5.0
> sphinx-immaterial             0.10.0
> sphinx-material               0.0.35
> sphinxcontrib-applehelp       1.0.2
> sphinxcontrib-devhelp         1.0.2
> sphinxcontrib-htmlhelp        2.0.0
> sphinxcontrib-jsmath          1.0.1
> sphinxcontrib-katex           0.9.0
> sphinxcontrib-qthelp          1.0.3
> sphinxcontrib-serializinghtml 1.1.5
> SQLAlchemy                    1.4.39
> starlette                     0.27.0
> svgwrite                      1.4.3
> sympy                         1.11.1
> tabulate                      0.9.0
> tensorboard                   2.13.0
> tensorboard-data-server       0.7.1
> tensorboard-plugin-wit        1.8.1
> tensorboardX                  2.5.1
> text-unidecode                1.3
> tiktoken                      0.4.0
> tokenizers                    0.13.3
> toml                          0.10.2
> tomli                         2.0.1
> toolz                         0.12.0
> torch                         1.13.1+cu117
> torch-tb-profiler             0.4.1
> torchaudio                    0.13.1+cu117
> torchdata                     0.5.1
> torchvision                   0.14.1+cu117
> tqdm                          4.65.0
> transaction                   3.0.1
> transformers                  4.28.1
> translationstring             1.4
> triton                        2.0.0
> typing_extensions             4.4.0
> typing-inspect                0.9.0
> uc-micro-py                   1.0.2
> Unidecode                     1.3.6
> urllib3                       1.26.16
> uvicorn                       0.22.0
> velruse                       1.1.1
> venusian                      3.0.0
> virtualenv                    20.15.1
> wandb                         0.15.4
> watchdog                      2.1.9
> wavedrom                      2.0.3.post3
> wcwidth                       0.2.6
> WebOb                         1.8.7
> websockets                    11.0.3
> Werkzeug                      2.2.2
> wheel                         0.37.1
> WTForms                       3.0.1
> wtforms-recaptcha             0.3.2
> xformers                      0.0.21+c979299.d20230718
> xxhash                        3.0.0
> yarl                          1.7.2
> zipp                          3.10.0
> zope.deprecation              4.4.0
> zope.interface                5.4.0
> zope.sqlalchemy               1.6
> ```

Have you installed Apex?

**Comment by uygnef** [comment]
@flybird1111 I have installed apex==0.1

**Comment by Edenzzzz** [comment]
> No module named 'fused_layer_norm_cuda'

Hi, 
This may be due to installing a python-only apex. You can resolve this by following the official instructions to install from source (https://github.com/NVIDIA/apex) or uninstalling apex.
