### ISSUE TITLE
Trying to adpat DLRM but encounter api incompatibility

### ISSUE THREAD

**Issue by henryqin1997** [hpcaitech/ColossalAI#437]
### Describe the feature

DLRM is taking multiple input of different shape as default dataloader design.  When trying to adapt it using engine api, I meet a 
<img width="829" alt="image" src="https://user-images.githubusercontent.com/37519855/158567836-544bf09f-dfe2-4011-91bc-db5c208a591a.png">
Can we allow tuple input for this case as it need less effort compared to turning it into dict?

**Comment by feifeibear** [comment]
Can you provide more information? A code snippet will be more helpful.

**Comment by FrankLeeeee** [comment]
Hi, I understand your question. This dict setting is designed for pipeline and we will support tuple in later versions.

**Comment by binmakeswell** [comment]
We have updated a lot. This issue was closed due to inactivity. Thanks.
