### ISSUE TITLE
[BUG]: log_interval not used in SFTrainer (examples) 

### ISSUE THREAD

**Issue by allzero-kwon** [hpcaitech/ColossalAI#4410]
### 🐛 Describe the bug

https://github.com/hpcaitech/ColossalAI/blob/6ccecc0c6984b2fe03d3b1718a79fa170d53a430/applications/Chat/examples/train_sft.py#L199

Hi. I was wondering how can i log training values in SFTrainer.
With above example, there is a log_interval as an argument, but not used actually.

How can I use this argument with SFTrainer.
Because i can't use wandb in my environments so i need to check my logs by tqdm or stdout.

**Comment by CWHer** [comment]
Thanks for reporting. Actually, we may fix it in an incoming PR.

For now, you may refer to [sft class](https://github.com/CWHer/ColossalAI/blob/giant-step-baby-step/applications/Chat/coati/trainer/sft.py) and [sft trainer](https://github.com/CWHer/ColossalAI/blob/giant-step-baby-step/applications/Chat/examples/train_sft.py) for some references about how to add `tensorboard` or `wandb` logger.
