### ISSUE TITLE
[BUG]: TypeError: Booster.boost() missing 1 required positional argument: 'optimizer'

### ISSUE THREAD

**Issue by lijieyuan** [hpcaitech/ColossalAI#4411]
### 🐛 Describe the bug

8.10  clone the code. I make a test;
torchrun --standalone --nproc_per_node=1 train_prompts.py   --pretrain "/opt-1.3b" --model 'opt'  --pretrain_dataset testdataset     --prompt_dataset prompt.json     --strategy colossalai_zero2     --num_episodes 1 --num_collect_steps 2 --num_update_steps 1 
the error ：
Traceback (most recent call last):
  File "/ColossalAI-main/applications/Chat/examples/train_prompts.py", line 222, in <module>
    main(args)
  File "/ColossalAI-main/applications/Chat/examples/train_prompts.py", line 155, in main
    strategy.prepare((actor, actor_optim), (critic, critic_optim), reward_model, initial_model)
  File "/opt/conda/lib/python3.10/site-packages/coati/trainer/strategies/base.py", line 75, in prepare
    model, *_ = self.booster.boost(arg)
TypeError: Booster.boost() missing 1 required positional argument: 'optimizer'

Thank you!

### Environment

cuda 11.7 
python 3.10.12
pytorch 1.13.1+cu117

**Comment by CWHer** [comment]
I think you may need to re-install `Colossalai`.

The latest version of Colossal Chat requires at least v0.3.1 of `Colossalai`, or you can just clone the whole repo and install it without `pip`.

**Comment by lijieyuan** [comment]
The error is solved.   Thank you!
