### ISSUE TITLE
Support ADAMW on CPU.

### ISSUE THREAD

**Issue by feifeibear** [hpcaitech/ColossalAI#444]
### Describe the feature

Support ADAMW on CPU.
https://pytorch.org/docs/stable/generated/torch.optim.AdamW.html?highlight=adamw#torch.optim.AdamW

**Comment by Gy-Lu** [comment]
Hi, we have already supported adamw. Using adam in `colossalai.nn.optimizer`, you can pass `adamw_mode=True` to use it. In fact, we are using adamw by default.
