### ISSUE TITLE
[BUG]: ThreeDimParallelPlugin doesn‘t finish the checkpointio

### ISSUE THREAD

**Issue by zryowen123** [hpcaitech/ColossalAI#4449]
### 🐛 Describe the bug

i use the example/llama branch, it provide a ThreeDimParallelPlugin ,but it doesn't provide the save model method， please fix it

**Comment by Fridge003** [comment]
We are working on this feature now, it will be fixed soon.

**Comment by flybird11111** [comment]
> ### 🐛 Describe the bug
> i use the example/llama branch, it provide a ThreeDimParallelPlugin ,but it doesn't provide the save model method， please fix it
> 
> ### Environment
> _No response_

finished. https://github.com/hpcaitech/ColossalAI/blob/c554b7f559b592c4d358db677c87658b11a6341c/colossalai/booster/plugin/hybrid_parallel_plugin.py#L463
