### ISSUE TITLE
[BUG]: HybridParallelPlugin的PP性能确认

### ISSUE THREAD

**Issue by wangbluo** [hpcaitech/ColossalAI#4573]
### 🐛 Describe the bug

您好，下午跑了一下脚本：https://github.com/hpcaitech/ColossalAI/blob/main/examples/language/llama2/scripts/benchmark_7B/gemini.sh

这是我跑的gemini.sh:
采用了HybridParallelPlugin，tp = 2， pp = 4，batch_size = 8，llama13b模型

`colossalai run --nproc_per_node 8 --hostfile $HOSTFILE benchmark.py -c 13b -p 3d -g -x -b 8 --shard_param_frac 1.0 --offload_optim_frac 0.0 --offload_param_frac 0.0 --tp 2 --pp 4`

打印出来的args参数如下：
`args: Namespace(config='13b', plugin='3d', batch_size=8, num_steps=5, ignore_steps=2, grad_checkpoint=True, max_length=4096, warmup_ratio=0.8, memory_limit=None, xformers=True, shard_param_frac=1.0, offload_optim_frac=0.0, offload_param_frac=0.0, tp=2, pp=4, mbs=1, zero=0)`

结果如下：

![a060d4388e49c2193e09816d80f34e992bb390f1](https://github.com/hpcaitech/ColossalAI/assets/32676639/f262de52-3596-4498-b6e9-7db615b40736)

感觉这个结果不是很理想，想确认一下HybridParallelPlugin的PP是正式发布了吗，
因为我看到llama65b这个模型的训练，用到了tp pp以及zero，这个性能就挺好的。https://github.com/hpcaitech/ColossalAI/tree/example/llama/examples/language/llama

**Comment by flybird11111** [comment]
> 

正式发布了，您可以看https://github.com/hpcaitech/ColossalAI/blob/main/colossalai/booster/plugin/hybrid_parallel_plugin.py 这个组件，该plugin的文档也会尽快发布

**Comment by wangbluo** [comment]
> > 
> 
> 正式发布了，您可以看https://github.com/hpcaitech/ColossalAI/blob/main/colossalai/booster/plugin/hybrid_parallel_plugin.py 这个组件，该plugin的文档也会尽快发布

好的非常感谢回复，辛苦了。
