### ISSUE TITLE
[DOC]: your code for training llama2 is missing

### ISSUE THREAD

**Issue by bliao-git** [hpcaitech/ColossalAI#4661]
### 📚 The doc issue

Your code for training llama2 is missing. Link directs to the llama code page.

**Comment by flybird11111** [comment]
https://github.com/hpcaitech/ColossalAI/blob/main/examples/language/llama2/pretrain.py hi，llama2 code is here,  Where is the incorrect link?

**Comment by binmakeswell** [comment]
Hi @bliao-git [llama1](https://github.com/hpcaitech/ColossalAI/tree/example/llama/examples/language/llama) and [llama2](https://github.com/hpcaitech/ColossalAI/tree/main/examples/language/llama2) code are placed in different branches.
