### ISSUE TITLE
[BUG]: pretrain llama Error

### ISSUE THREAD

**Issue by Maxhyl** [hpcaitech/ColossalAI#4677]
### 🐛 Describe the bug

模型训练正常，保存模型时报错：
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /home/edcuser/models/ColossalAI-main-llama2/ColossalAI-main/examples/languag │
│ e/llama2/pretrain.py:276 in <module>                                         │
│                                                                              │
│   273                                                                        │
│   274                                                                        │
│   275 if __name__ == '__main__':                                             │
│ ❱ 276 │   main()                                                             │
│   277                                                                        │
│                                                                              │
│ /home/edcuser/models/ColossalAI-main-llama2/ColossalAI-main/examples/languag │
│ e/llama2/pretrain.py:265 in main                                             │
│                                                                              │
│   262 │   │   │   │                                                          │
│   263 │   │   │   │   if args.save_interval > 0 and (step + 1) % args.save_i │
│   264 │   │   │   │   │   coordinator.print_on_master(f'Saving checkpoint')  │
│ ❱ 265 │   │   │   │   │   save(booster, model, optimizer, lr_scheduler, epoc │
│   266 │   │   │   │   │   │    args.save_dir)                                │
│   267 │   │   │   │   │   coordinator.print_on_master(f'Saved checkpoint at  │
│   268 │   │   # the continue epochs are not resumed, so we need to reset the │
│                                                                              │
│ /home/edcuser/models/ColossalAI-main-llama2/ColossalAI-main/examples/languag │
│ e/llama2/pretrain.py:87 in save                                              │
│                                                                              │
│    84 │   os.makedirs(os.path.join(save_dir, 'model'), exist_ok=True)        │
│    85 │                                                                      │
│    86 │   booster.save_model(model, os.path.join(save_dir, 'model'), shard=T │
│ ❱  87 │   booster.save_optimizer(optimizer, os.path.join(save_dir, 'optimize │
│    88 │   booster.save_lr_scheduler(lr_scheduler, os.path.join(save_dir, 'lr │
│    89 │   running_states = {                                                 │
│    90 │   │   'epoch': epoch,                                                │
│                                                                              │
│ /home/edcuser/.conda/envs/torch113/lib/python3.10/site-packages/colossalai/b │
│ ooster/booster.py:251 in save_optimizer                                      │
│                                                                              │
│   248 │   │   │   │   names to compose the keys in state_dict. Defaults to N │
│   249 │   │   │   size_per_shard (int, optional): Maximum size of checkpoint │
│   250 │   │   """                                                            │
│ ❱ 251 │   │   self.checkpoint_io.save_optimizer(optimizer, checkpoint, shard │
│   252 │                                                                      │
│   253 │   def save_lr_scheduler(self, lr_scheduler: LRScheduler, checkpoint: │
│   254 │   │   """Save lr scheduler to checkpoint.                            │
│                                                                              │
│ /home/edcuser/.conda/envs/torch113/lib/python3.10/site-packages/colossalai/c │
│ heckpoint_io/checkpoint_io_base.py:191 in save_optimizer                     │
│                                                                              │
│   188 │   │   │   size_per_shard (int): size per shard in MB. Default: 1024. │
│   189 │   │   """                                                            │
│   190 │   │   if shard:                                                      │
│ ❱ 191 │   │   │   self.save_sharded_optimizer(optimizer, checkpoint, gather_ │
│   192 │   │   else:                                                          │
│   193 │   │   │   self.save_unsharded_optimizer(optimizer, checkpoint, gathe │
│   194                                                                        │
│                                                                              │
│ /home/edcuser/.conda/envs/torch113/lib/python3.10/site-packages/colossalai/c │
│ heckpoint_io/general_checkpoint_io.py:120 in save_sharded_optimizer          │
│                                                                              │
│   117 │   │                                                                  │
│   118 │   │   # Save shards of optimizer states.                             │
│   119 │   │   total_size = 0                                                 │
│ ❱ 120 │   │   for idx, shard_pair in enumerate(sharded_state):               │
│   121 │   │   │   shard, current_size = shard_pair                           │
│   122 │   │   │   shard_file = get_shard_filename(states_name, idx)          │
│   123 │   │   │   total_size = total_size + current_size                     │
│                                                                              │
│ /home/edcuser/.conda/envs/torch113/lib/python3.10/site-packages/colossalai/c │
│ heckpoint_io/utils.py:152 in shard_optimizer_checkpoint                      │
│                                                                              │
│   149 │   │   │   # If the states are stored as DTensors, mark isDTensor as  │
│   150 │   │   │   if is_distributed_tensor(state_tensor):                    │
│   151 │   │   │   │   isDTensor = True                                       │
│ ❱ 152 │   │   │   state_size += calculate_tensor_size(state_tensor)          │
│   153 │   │                                                                  │
│   154 │   │   if not isDTensor:                                              │
│   155                                                                        │
│                                                                              │
│ /home/edcuser/.conda/envs/torch113/lib/python3.10/site-packages/colossalai/c │
│ heckpoint_io/utils.py:40 in calculate_tensor_size                            │
│                                                                              │
│    37 │   │   float: size of the tensor in MB.                               │
│    38 │   """                                                                │
│    39 │   print ("类型：", type(tensor))                                     │
│ ❱  40 │   return tensor.numel() * tensor.element_size() / 1024 / 1024        │
│    41                                                                        │
│    42                                                                        │
│    43 def is_safetensors_available() -> bool:                                │
╰──────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'int' object has no attribute 'numel'

**Comment by flybird11111** [comment]
这里应该是有问题修复了，看起来您没有获取到补丁代码，您更新一下colossalai试试呢？

**Comment by Maxhyl** [comment]
更新colossalai0.3.2后解决，谢谢
