### ISSUE TITLE
[PROPOSAL]: 请不要随意消耗用户的耐心，请注重开源项目的口碑，不要过大宣传

### ISSUE THREAD

**Issue by yoosan** [hpcaitech/ColossalAI#4679]
### Proposal

ColossalAI作为一个开源的训练框架，值得尊敬和佩服，respect
但是不得不指出，ColossalAI在各个公众号pr的内容，和实际用户体验大相径庭
既然你们花那么大力气去做pr，为什么连简单的训练例子的脚本都没有，一个实际可运行的例子也没有，比如说llama2-70b
用户去熟悉你们的框架，到配好环境去使用，也是有开发成本的，用户花了时间和精力进来，最后发现没法运行，对用户信任度伤害是很大的。
不知道ColossalAI开发者有多少，我觉得在社区构建，对用户的issue响应程度上，还不如一个学生维护的项目，比如https://github.com/hiyouga/LLaMA-Efficient-Tuning

请把精力花在解决用户的问题上，而不是去宣传。

### Self-service

- [ ] I'd be willing to do some initial work on this proposal myself.

**Comment by flybird11111** [comment]
> ### Proposal
> ColossalAI作为一个开源的训练框架，值得尊敬和佩服，respect 但是不得不指出，ColossalAI在各个公众号pr的内容，和实际用户体验大相径庭 既然你们花那么大力气去做pr，为什么连简单的训练例子的脚本都没有，一个实际可运行的例子也没有，比如说llama2-70b 用户去熟悉你们的框架，到配好环境去使用，也是有开发成本的，用户花了时间和精力进来，最后发现没法运行，对用户信任度伤害是很大的。 不知道ColossalAI开发者有多少，我觉得在社区构建，对用户的issue响应程度上，还不如一个学生维护的项目，比如https://github.com/hiyouga/LLaMA-Efficient-Tuning
> 
> 请把精力花在解决用户的问题上，而不是去宣传。
> 
> ### Self-service
> * [ ]  I'd be willing to do some initial work on this proposal myself.

好的，接收到反馈，给您造成困扰很抱歉，我们会加大力度处理issue，响应用户问题。

**Comment by flybird11111** [comment]
请问您llama2-70b训练是遇到什么问题了呢？

**Comment by flybird11111** [comment]
> ### Proposal
> ColossalAI作为一个开源的训练框架，值得尊敬和佩服，respect 但是不得不指出，ColossalAI在各个公众号pr的内容，和实际用户体验大相径庭 既然你们花那么大力气去做pr，为什么连简单的训练例子的脚本都没有，一个实际可运行的例子也没有，比如说llama2-70b 用户去熟悉你们的框架，到配好环境去使用，也是有开发成本的，用户花了时间和精力进来，最后发现没法运行，对用户信任度伤害是很大的。 不知道ColossalAI开发者有多少，我觉得在社区构建，对用户的issue响应程度上，还不如一个学生维护的项目，比如https://github.com/hiyouga/LLaMA-Efficient-Tuning
> 
> 请把精力花在解决用户的问题上，而不是去宣传。
> 
> ### Self-service
> * [ ]  I'd be willing to do some initial work on this proposal myself.

https://github.com/hpcaitech/ColossalAI/blob/main/examples/language/llama2/pretrain.py llama2-70b训练脚本在这里提供了, 您可以看看这个文件。

**Comment by alphanlp** [comment]
compatible is a big problem!!!!

**Comment by wangbluo** [comment]
您好，希望不会冒犯到你们，我也举两个例子：

第一个是我当时看到了你们关于ShardFormer的发布，在接入性、策略的组合这块非常方便，但是效果不是很好，跟你们确认了才知道PP还不能使用，而且我也不能复现benchmark，一样的配置，sequence length加到2048就oom了，1024的情况下tp，比原模型还要慢，我不清楚是什么原因，flash attention也不会这样吧，如果没做完，还是需要在Readme说一下，不用太心急说推出了什么功能，不然用户测的时候发现还没有做好，就尴尬了。

第二个例子是跑你们关于llama2，gpt的example，光是环境配置我就配了两天，首先按照你们的pip install xformer，会直接自动安装pytorch2.0，而现在colossalai也没支持pytorch2.0，用户在不知情的情况下升级了pytorch2.0然后一堆报错，（我看到有人也遇到了这个错误，metadata很典型的pytorch2.0报错），后来问了一下你们，通过构建源码的方式来安装解决了，然后又遇到了一个fbgemm_gpu_py.so not found的错误，但是都是按照你们requirement来装的，而且这个requirement我当时也是在一个分支里找到的，main分支的requirement.txt还没有跟着一起更新。

其实环境配置是一个蛮重要，但是容易被忽视的问题。

除此之外，之前测试shardformer跑GPT2模型有一个past_key_values问题，需要手动设置为none，跑llama2模型 7b 13b的时候会遇到没有同时均等切分num_key_value_heads和num_heads的问题。

用户按照要求，花时间来配置，结果跑不起来，就会觉得很挫败。

工程能力这块可以再加强一下，做框架，对工程能力我觉得比算法要求要更高一些，至少保证给出的benchmark没有问题。

但是我还是很看好的colossalai的，这样的框架是要革Megatron-LM和Deepspeed的命的，真心希望能越做越好，我相信很多用户也是这样希望的，祝好。

**Comment by binmakeswell** [comment]
Hi @yoosan @alphanlp @wangbluo 
Thank you for your sincere feedback. 
We will conduct more comprehensive maintenance and testing. 
We deeply apologize for the inconvenience caused.

**Comment by fastalgo** [comment]
您好，我们开发人员费了很大的精力，每次发布时都确保质量最高。
看到您的评论我比较惊讶，不知为何您想直接贴标签和带节奏

就事论事：
Llama2 gemini方案是完全提脚本和文档的，环境问题也在文档里说了。
当时就是为了避免弄太多配置用户配不清楚所以只放了性能最好的gemini的。
如果您仍然无法复现的话，请直接联系我。

谢谢您对Colossal-AI的关注！

**Comment by FrankLeeeee** [comment]
谢谢各位的建议，我们团队会做出相应调整，更好地打磨我们的文档、例子以及代码，近期会集中更新一下文档和例子，希望能让大家更简单地用上ColossalAI并复现出各个应用。

**Comment by wangbluo** [comment]
> 

对不起，我不是故意的，我不知道您说的带节奏有没有包含到我，但是我完全没有这个意思，只是路过看到这个issue就站在用户的角度上，把最近测得一些情况说了一下，也可能是我使用有问题，我的理解还不够到位。我也准备认真阅读一下你们的实现，提高一下自己的水平。您看我上个评论打字认真写了这么多，也是对您的框架抱有很高的期望的，就像我上个评论里说的那样，我认为colossalai未来会代替megatron-LM和Deepspeed的，真心祝越来越好。

可能这个issue标题有一些争论，但是本人完全没有这个意思，非常感谢colossalai所做的努力，也希望你们不要太往心里去，批评总是比建设简单的多，你们的付出毫无疑问是值得肯定的，而且成果也是大家有目共睹的。希望不会太影响你们的心情，我的评论太草率了，对不起对不起(╥_╥)

**Comment by flybird11111** [comment]
我查看到您的llama2训练问题issue，8卡A100训练llama2-70b oom的话，您可以考虑增加资源，我们在pr中提供的llama的测速数据是在 512 A100 40G的环境上进行的。
