### ISSUE TITLE
Unable to setup development environment

### ISSUE THREAD

**Issue by tanmaydevale** [hpcaitech/ColossalAI#468]
Hi!
I am unable to setup a development environment for contributing.
I ran the following commands,
pip uninstall colossalai
git clone https://github.com/hpcaitech/ColossalAI.git
cd ColossalAI
pip install -r requirements/requirements.txt
pip install --global-option="--no_cuda_ext" -e .

I got the following error message
![ColossalSetup](https://user-images.githubusercontent.com/87221911/159157014-45d817c6-92e9-46b2-9775-538c7b11a691.png)

So I switched to google colab with GPU support.
I ran the following commands
!git clone https://github.com/hpcaitech/ColossalAI.git
cd ColossalAI
!pip install -r requirements/requirements.txt
!pip install -e .

It successfully installed colossalai-0.1.0

So I ran pytest -m cpu tests/
But obtained the following output.
![image](https://user-images.githubusercontent.com/87221911/159157521-1ce7f7a2-a00d-4e5a-9d7f-e6c96b29e54d.png)

What should I do?

**Comment by FrankLeeeee** [comment]
Hi, for the first installation error, can you provide your environment, i.e. CUDA, cudnn, python versions? For the second one, can you try `export PYTHONPATH=</xxx/ColossalAI>` where you need to replace `xxx` with your own path.

**Comment by tanmaydevale** [comment]
I don't have CUDA on my PC. My python version is Python 3.8.5

**Comment by FrankLeeeee** [comment]
Hi, ColossalAI currently requires GPUs for installation.

**Comment by tanmaydevale** [comment]
Oh, okay
