### ISSUE TITLE
[BUG]: applications/Chat/coati/trainer/strategies /colossalai.py is not compatible with the gemini_plugin.py

### ISSUE THREAD

**Issue by alphanlp** [hpcaitech/ColossalAI#4681]
### 🐛 Describe the bug

```bash
  File "/data/llmodel/huap/ColossalAI/applications/Chat/train_sft.py", line 205, in <module>
    train(args)
  File "/data/llmodel/huap/ColossalAI/applications/Chat/train_sft.py", line 32, in train
    strategy = GeminiStrategy(placement_policy='cuda')
  File "/data/llmodel/huap/ColossalAI/applications/Chat/coati/trainer/strategies/colossalai.py", line 194, in __init__
    super().__init__(seed, plugin_initializer)
  File "/data/llmodel/huap/ColossalAI/applications/Chat/coati/trainer/strategies/ddp.py", line 42, in __init__
    super().__init__(plugin_initializer)
  File "/data/llmodel/huap/ColossalAI/applications/Chat/coati/trainer/strategies/base.py", line 29, in __init__
    self.plugin = plugin_initializer()
  File "/data/llmodel/huap/ColossalAI/applications/Chat/coati/trainer/strategies/colossalai.py", line 169, in <lambda>
    plugin_initializer = lambda: GeminiPlugin(
TypeError: __init__() got an unexpected keyword argument 'device'
```

Can somebody can give a correct Example？

**Comment by flybird11111** [comment]
> super().**init**(plugin_initializer)

HIHI, Can you please upgrade Coati？This will resolve your issue.

**Comment by CWHer** [comment]
Some recommended modifications are provided in #4685, yet it may still encounter some errors.

We are working on solving this issue, and @flybird11111 will be in charge.

**Comment by alphanlp** [comment]
> > ### 🐛 Describe the bug
> > ```shell
> >   File "/data/llmodel/huap/ColossalAI/applications/Chat/train_sft.py", line 205, in <module>
> >     train(args)
> >   File "/data/llmodel/huap/ColossalAI/applications/Chat/train_sft.py", line 32, in train
> >     strategy = GeminiStrategy(placement_policy='cuda')
> >   File "/data/llmodel/huap/ColossalAI/applications/Chat/coati/trainer/strategies/colossalai.py", line 194, in __init__
> >     super().__init__(seed, plugin_initializer)
> >   File "/data/llmodel/huap/ColossalAI/applications/Chat/coati/trainer/strategies/ddp.py", line 42, in __init__
> >     super().__init__(plugin_initializer)
> >   File "/data/llmodel/huap/ColossalAI/applications/Chat/coati/trainer/strategies/base.py", line 29, in __init__
> >     self.plugin = plugin_initializer()
> >   File "/data/llmodel/huap/ColossalAI/applications/Chat/coati/trainer/strategies/colossalai.py", line 169, in <lambda>
> >     plugin_initializer = lambda: GeminiPlugin(
> > TypeError: __init__() got an unexpected keyword argument 'device'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Can somebody can give a correct Example？
> > ### Environment
> > _No response_
> 
> how about trying 'pip install colossalai==0.3.2'

yes ,  i use colossalai==0.3.2

but the code in colossalai.py is : 
        plugin_initializer = lambda: GeminiPlugin(
            # gemini_config
            device=get_current_device(),
            placement_policy=placement_policy,
            precision='fp16',
            pin_memory=pin_memory,
            force_outputs_fp32=force_outputs_fp32,
            strict_ddp_mode=shard_init,
            search_range_m=search_range_m,
            hidden_dim=hidden_dim,
            min_chunk_size_m=min_chunk_size_m,
            # zero_optim_config
            gpu_margin_mem_ratio=gpu_margin_mem_ratio,
            # optim_config
            initial_scale=initial_scale,
            growth_factor=growth_factor,

**Comment by flybird11111** [comment]
hi，This issue is being fixed, please follow this pull request.https://github.com/hpcaitech/ColossalAI/pull/4698

**Comment by CWHer** [comment]
This issue is fixed now. You can pull the latest code from `main` branch to fix it.
**However**, there still exists some other compatibility issues with `Gemini` plugin. For instance, `Gemini` is not compatible with `model.from_pretrained` yet, and we are working on fixing it.
