### ISSUE TITLE
[DOC]: Model Zoo is mentioned, but it isn't available on pip install

### ISSUE THREAD

**Issue by RamyaNP** [hpcaitech/ColossalAI#4682]
### 📚 The doc issue

Cloning the repo also doesn't help
could you please direct me to where I can find your model-zoo?

**Comment by flybird11111** [comment]
Model zoo is our testing tool, and it is not installed as part of ColossalAI during installation. Its code is located here. https://github.com/hpcaitech/ColossalAI/tree/main/tests/kit/model_zoo

**Comment by RamyaNP** [comment]
really appreciate your speedy response. Thank you!
