### ISSUE TITLE
[FEATURE]: HybridPlugin是否支持LazyInit加载

### ISSUE THREAD

**Issue by xs1997zju** [hpcaitech/ColossalAI#4687]
### Describe the feature

 65b等较大模型加载内存较大， HybridPlugin是否支持LazyInit加载？

**Comment by flybird11111** [comment]
You can directly use lazy init. You can refer to this example. https://github.com/hpcaitech/ColossalAI/blob/main/examples/language/llama2/pretrain.py

**Comment by xs1997zju** [comment]
@flybird11111 Hey, in examples/language/llama2/pretrain.py,  it doesn't use HybridPlugin

**Comment by flybird11111** [comment]
> @flybird11111 Hey, in examples/language/llama2/pretrain.py, it doesn't use HybridPlugin

Yes, hybrid parallel plugin and lazyinit are decoupled. You can refer to the usage of lazyinit in this example.

**Comment by xs1997zju** [comment]
OK, Thanks
