### ISSUE TITLE
[BUG]: torch version check

### ISSUE THREAD

**Issue by littsk** [hpcaitech/ColossalAI#4714]
### 🐛 Describe the bug

When the Torch version is greater than 2.0, the colossal run generates a command that is suitable for versions below 1.9.

**Comment by flybird11111** [comment]
> ### 🐛 Describe the bug
> When the Torch version is greater than 2.0, the colossal run generates a command that is suitable for versions below 1.9.
> 
> ### Environment
> _No response_

Hi, lazy init does not support torch 2.0 now and we're working on. Can you try torch 1.13.1?

**Comment by CjhHa1** [comment]
Thx for your contribution, I've left a comment and you can check

**Comment by chuhac** [comment]
temporary fix in cli/run.py
``` python
torch_version = version.parse(torch.__version__)
assert torch_version.major >= 1
full_version = (torch_version.major - 1) * 10 + torch_version.minor
    if full_version < 9:
....
```
