### ISSUE TITLE
[BUG]: examples/language/llama2/pretrain.py与benchmark.py TFlops有差别

### ISSUE THREAD

**Issue by wangbluo** [hpcaitech/ColossalAI#4744]
### 🐛 Describe the bug

开发者们你们好，我分别测试了pretrain.py和benchmark.py两个脚本的性能，主要测试了step_time和Tflops
测试配置是gemini、llama2 13b、64 batch size、sequence length为2048
两个脚本的step_time都是从一个step的开始到backward结束

其中benchmark.py的steptime约为9.5s，Tflops打印显示175，通过计算这两个也是完全符合的。
但是pretrain.py steptime打印出来为13.5s，Tflops在125左右,而且两个脚本的最大显存占用也不一样，benchmark.py的最大显存只有39998MB，但是pretrain.py最大显存是47-52G

我理解这两个应当是一样的才对，想问一下一般会有什么原因呢，还是我测的有问题呢

这是pretrain.py:
![image](https://github.com/hpcaitech/ColossalAI/assets/32676639/60859355-87c4-4a94-aa10-6782440c4686)
![image](https://github.com/hpcaitech/ColossalAI/assets/32676639/a8376f68-e850-44f3-8546-704295d6e587)

这是benchmark.py:
![image](https://github.com/hpcaitech/ColossalAI/assets/32676639/3a0c1ff3-87a1-4eef-9893-7b2aef7b7c0d)
![image](https://github.com/hpcaitech/ColossalAI/assets/32676639/6260350f-1324-4c44-8ea3-a6ca7869b135)

**Comment by flybird11111** [comment]
查看到您benchmark中使用了flash attention，pretrain中没有使用，您可以也打开试试。

**Comment by wangbluo** [comment]
> 查看到您benchmark中使用了flash attention，pretrain中没有使用，您可以也打开试试。

非常感谢！现在完全一致了，非常牛掰
![image](https://github.com/hpcaitech/ColossalAI/assets/32676639/0400d078-eb07-48b5-b595-1a277417e265)

现在看起来有充分的理由说服老板用上你们的脚本了，是时候抛弃deepspeed了haha😄

**Comment by flybird11111** [comment]
> > 查看到您benchmark中使用了flash attention，pretrain中没有使用，您可以也打开试试。
> 
> 非常感谢！现在完全一致了，非常牛掰 ![image](https://user-images.githubusercontent.com/32676639/268503308-0400d078-eb07-48b5-b595-1a277417e265.png)
> 
> 现在看起来有充分的理由说服老板用上你们的脚本了，是时候抛弃deepspeed了haha😄
感谢您关注colossalai～

**Comment by 1099692150** [comment]
楼主，能说下pretrain.py中如何计算tflops吗？

**Comment by wangbluo** [comment]
> 楼主，能说下pretrain.py中如何计算tflops吗？

你好，可以在Colossalai中搜索tflops会有很多相关计算，总的来说是：

def get_tflops(model_numel, batch_size, seq_len, step_time):

      return model_numel * batch_size * seq_len * 8 / 1e12 / (step_time + 1e-12)
      
如果不开grad checkpoint应当是model_numel * batch_size * seq_len * 6 / 1e12 / (step_time + 1e-12)

也可以参考这个：
https://github.com/hpcaitech/ColossalAI/blob/7266f82d0358ae736a294e2613a00e57aaec9f89/examples/language/performance_evaluator.py#L141C9-L141C87
