### ISSUE TITLE
[BUG]: examples >llama2 >pretrain.py 使用colossalai run会报exception: [Errno 7] Argument list too long: '/bin/bash'

### ISSUE THREAD

**Issue by Krisort** [hpcaitech/ColossalAI#4797]
### 🐛 Describe the bug

使用colossalai run 调用pretrain.py会出现：
Error: failed to run torchrun --nproc_per_node=8 --nnodes=1 --node_rank=0 --master_addr=127.0.0.1 --master_port=29500 pretrain.py  -g -p hybrid_parallel -b 1 on 127.0.0.1, is localhost: True, exception: [Errno 7] Argument list too long: '/bin/bash'

将colossalai run 替换为 torchrun 可以运行。

### Environment

Ubuntu 18.04 python3.7 pytorch1.12.1 cuda11.3 colossalai 0.3.3 8*V100

**Comment by flybird11111** [comment]
可以看看你的脚本命令吗

**Comment by Krisort** [comment]
脚本如下，谢谢回复~
#!/bin/bash

################
#Load your environments and modules here
################

cd ../..

export OMP_NUM_THREADS=8
export HF_DATASETS_CACHE="/mnt/home/data"

colossalai run --nproc_per_node 8 pretrain.py -g -p hybrid_parallel -b 1

**Comment by Krisort** [comment]
也有可能是我们集群环境的问题（我换了不同版本的镜像都是这个问题，但是本地的一台机器上可以colossalai run启动），我多请教一下，我用torchrun启动和colossalai run启动有什么区别吗（除了torchrun需要去每个节点手动启动）？会影响hybrid_parallel吗？我torchrun启动，2个节点，16卡，tp，pp都为2，micro_batch_size为1，但是看日志打印出来的一个iter的batch_size是16，请问这是正常的吗？谢谢！

**Comment by Krisort** [comment]
抱歉，我没问题了。我理解错local batch size了，我以为local batch size是每个dp的batch size，实际是和卡的数量（world size）有关，global batch size = local batch size * world size。**p.s. 标题中的bug是我自己集群的问题（虽然还没解决），提了bug issue，再次抱歉**

**Comment by flybird11111** [comment]
哈哈，没事，感谢您关注colossalai

**Comment by fsq77** [comment]
所以这个问题是怎么解决的呀
