### ISSUE TITLE
[BUG]: Gemini failed for Lora  and ptuning while using Peft

### ISSUE THREAD

**Issue by luckyyangrun** [hpcaitech/ColossalAI#4818]
### 🐛 Describe the bug

Gemini failed for Lora  and p-tuning while using Peft

> plugin = GeminiPlugin(precision=args.mixed_precision,  placement_policy='auto')
> booster = Booster(plugin=plugin)

> init_ctx = nullcontext()
> with init_ctx:
>     model = AutoModelForCausalLM.from_pretrained(args.pretrain).to(torch.cuda.current_device())
>     lora_config = LoraConfig(
>                 task_type=TaskType.CAUSAL_LM, inference_mode=False, r=lora_rank, lora_alpha=32, lora_dropout=0.1
>             )
>     model = get_peft_model(model, lora_config)
> optimizer = HybridAdam(model.parameters(), lr=cfg.lr, weight_decay=cfg.weight_decay)
> model, optimizer, _, dataloader, lr_scheduler = booster.boost(model, optimizer, dataloader=dataloader, > lr_scheduler=lr_scheduler)
> begin train loop

![image](https://github.com/hpcaitech/ColossalAI/assets/67430592/aa17eb93-6690-4c89-b406-f4bf86838338)

### Environment

peft 0.3.0.dev0
torch-'1.13.1+cu117', transformers-4.33.2, colossalAI-release-v0.3.3

**Comment by luckyyangrun** [comment]
Thank you very much for your response. However, the ColossalAI  I am using already includes the updates made yesterday 9.26

**Comment by luckyyangrun** [comment]
And I found that in applications/Chat/examples/community/peft/train_peft_sft.py. The model and optimizer are not been boosted ( prepared) by the booster ( strategy).

**Comment by CWHer** [comment]
I'm sorry that `/community/peft` is provided and maintained by the community, as its design principle and implementation details may differ from ours. 
I have sent an email to the author, describing our updates on `colossalai`, but without any reply yet.
