### ISSUE TITLE
[BUG]: AssertionError: Accumulation steps are not supported in stage 3 of ColossalAI

### ISSUE THREAD

**Issue by sherlcok314159** [hpcaitech/ColossalAI#4847]
### 🐛 Describe the bug

When using gradient accumulation in colossal_gemini, it causes this error.

Example Script:

```bash
torchrun --standalone --nproc_per_node=4 train_sft.py \
    --pretrain "meta-llama/Llama-2-7b-hf" \
    --model 'llama' \
    --strategy colossalai_gemini \
    --save_path output/Coati-7B \
    --dataset yizhongw/self_instruct \
    --batch_size 8 \
    --accumulation_steps 8 \
    --lr 2e-5 \
    --max_datasets_size 512 \
    --max_epochs 1 \
    --grad_checkpoint
```

**Comment by 149189** [comment]
Hey! I would Love to Work on this Issue

**Comment by 149189** [comment]
@sherlcok314159

**Comment by Fridge003** [comment]
hi, we are developing gradient accumulation feature for gemini, please check the update in the following days~

**Comment by Fridge003** [comment]
Hi @sherlcok314159 , gradient accumulation for gemini has been implemented, usage can be referred to [this tutorial] (https://colossalai.org/docs/features/gradient_accumulation_with_booster). If there is any bug please contact me.
