### ISSUE TITLE
[BUG/Shardformer]: test_model scripts failing due to enable_flash_attention

### ISSUE THREAD

**Issue by ppt0011** [hpcaitech/ColossalAI#4848]
### 🐛 Describe the bug

currently, quite a few PRs (e.g. [4838](https://github.com/hpcaitech/ColossalAI/actions/runs/6337031093/job/17239225204?pr=4838) and [4825](https://github.com/hpcaitech/ColossalAI/actions/runs/6324411346/job/17173885641?pr=4825) ) cannot be merged due to failed CI. With some investigation, we realised that all test_shard_***.py scripts under test_model cannot run due to "free(): invalid pointer". The scripts are able to run if we turn off enable_flash_attention in https://github.com/hpcaitech/ColossalAI/blob/ed06731e00be6db982aa22dbe2c70bee88dbc05d/colossalai/shardformer/shard/shard_config.py#L70

**Comment by itstalmeez** [comment]
Can you allow me to open it?

**Comment by flybird11111** [comment]
> Can you allow me to open it?

Sure, it's ok to run with flash attention now.
