### ISSUE TITLE
[FEATURE]: Add Flash Attention 2

### ISSUE THREAD

**Issue by rajveer43** [hpcaitech/ColossalAI#4859]
### Describe the feature

Add Flash Attention 2 IF possible

**Comment by kurisusnowdeng** [comment]
@rajveer43 hi, we already have support for flash attention 2. If you are using huggingface models, please use `shardformer` to wrap your model, and set `enable_flash_attention=True` in [`ShardConfig`](https://colossalai.org/docs/features/shardformer/#shardformer-configuration). Or, if you are using your own model, you could also use [`ColoAttention`](https://github.com/hpcaitech/ColossalAI/blob/main/colossalai/kernel/cuda_native/mha/mha.py#L18), which is functionally equivalent to `torch`'s [`sdp`](https://pytorch.org/docs/stable/generated/torch.nn.functional.scaled_dot_product_attention.html#torch.nn.functional.scaled_dot_product_attention) but is supposed to be more efficient.
