### ISSUE TITLE
[BUG]: 微信二维码失效

### ISSUE THREAD

**Issue by shenzy08** [hpcaitech/ColossalAI#4880]
### 🐛 Describe the bug

微信二维码失效了

**Comment by binmakeswell** [comment]
Hi @shenzy08 感谢反馈，您可以先扫这个
![image](https://github.com/hpcaitech/ColossalAI/assets/61670638/bcdec085-4b33-457a-b06a-34af7a60bb51)

**Comment by binmakeswell** [comment]
微信群主页链接已修复
https://raw.githubusercontent.com/hpcaitech/public_assets/main/colossalai/img/WeChat.png
