### ISSUE TITLE
[BUG]: ModuleNotFoundError: No module named 'colossalai.global_variables'

### ISSUE THREAD

**Issue by hellangleZ** [hpcaitech/ColossalAI#4881]
### 🐛 Describe the bug

When I use titian to try train a GPT-2

/ColossalAI-main/examples/language/gpt/titans

There is a error message and the train node is stopped.

(clai) root@A100:/aml2/ColossalAI-main/examples/language/gpt/titans# colossalai run --nproc_per_node=2 train_gpt.py --config configs/gpt2_small_zero3_pp1d.py --from_torch --use_dummy_dataset
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
/root/miniconda3/envs/clai/lib/python3.8/site-packages/colossalai/kernel/cuda_native/mha/flash_attn_2.py:28: UserWarning: please install flash_attn from https://github.com/HazyResearch/flash-attention
  warnings.warn("please install flash_attn from https://github.com/HazyResearch/flash-attention")
/root/miniconda3/envs/clai/lib/python3.8/site-packages/colossalai/kernel/cuda_native/mha/mem_eff_attn.py:15: UserWarning: please install xformers from https://github.com/facebookresearch/xformers
  warnings.warn("please install xformers from https://github.com/facebookresearch/xformers")
/root/miniconda3/envs/clai/lib/python3.8/site-packages/colossalai/kernel/cuda_native/mha/flash_attn_2.py:28: UserWarning: please install flash_attn from https://github.com/HazyResearch/flash-attention
  warnings.warn("please install flash_attn from https://github.com/HazyResearch/flash-attention")
/root/miniconda3/envs/clai/lib/python3.8/site-packages/colossalai/kernel/cuda_native/mha/mem_eff_attn.py:15: UserWarning: please install xformers from https://github.com/facebookresearch/xformers
  warnings.warn("please install xformers from https://github.com/facebookresearch/xformers")
Traceback (most recent call last):
  File "train_gpt.py", line 8, in <module>
    from titans.model.gpt import GPTLMLoss
  File "/root/miniconda3/envs/clai/lib/python3.8/site-packages/titans/__init__.py", line 1, in <module>
    from . import layer
  File "/root/miniconda3/envs/clai/lib/python3.8/site-packages/titans/layer/__init__.py", line 1, in <module>
    from . import attention
  File "/root/miniconda3/envs/clai/lib/python3.8/site-packages/titans/layer/attention/__init__.py", line 1, in <module>
    from .gpt_attention import GPTSelfAttention
  File "/root/miniconda3/envs/clai/lib/python3.8/site-packages/titans/layer/attention/gpt_attention.py", line 9, in <module>
    from titans.decorator import no_support
  File "/root/miniconda3/envs/clai/lib/python3.8/site-packages/titans/decorator/__init__.py", line 1, in <module>
    from .no_support import no_support, support_moe_only, support_sp_pp_only, support_tp_pp_only, no_parallel_support
  File "/root/miniconda3/envs/clai/lib/python3.8/site-packages/titans/decorator/no_support.py", line 2, in <module>
    from colossalai.global_variables import tensor_parallel_env as tp_env
ModuleNotFoundError: No module named 'colossalai.global_variables'
Traceback (most recent call last):
  File "train_gpt.py", line 8, in <module>
    from titans.model.gpt import GPTLMLoss
  File "/root/miniconda3/envs/clai/lib/python3.8/site-packages/titans/__init__.py", line 1, in <module>
    from . import layer
  File "/root/miniconda3/envs/clai/lib/python3.8/site-packages/titans/layer/__init__.py", line 1, in <module>
    from . import attention
  File "/root/miniconda3/envs/clai/lib/python3.8/site-packages/titans/layer/attention/__init__.py", line 1, in <module>
    from .gpt_attention import GPTSelfAttention
  File "/root/miniconda3/envs/clai/lib/python3.8/site-packages/titans/layer/attention/gpt_attention.py", line 9, in <module>
    from titans.decorator import no_support
  File "/root/miniconda3/envs/clai/lib/python3.8/site-packages/titans/decorator/__init__.py", line 1, in <module>
    from .no_support import no_support, support_moe_only, support_sp_pp_only, support_tp_pp_only, no_parallel_support
  File "/root/miniconda3/envs/clai/lib/python3.8/site-packages/titans/decorator/no_support.py", line 2, in <module>
    from colossalai.global_variables import tensor_parallel_env as tp_env
ModuleNotFoundError: No module named 'colossalai.global_variables'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 15187) of binary: /root/miniconda3/envs/clai/bin/python
Traceback (most recent call last):
  File "/root/miniconda3/envs/clai/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==1.13.1', 'console_scripts', 'torchrun')())
  File "/root/miniconda3/envs/clai/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/root/miniconda3/envs/clai/lib/python3.8/site-packages/torch/distributed/run.py", line 762, in main
    run(args)
  File "/root/miniconda3/envs/clai/lib/python3.8/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/root/miniconda3/envs/clai/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/root/miniconda3/envs/clai/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train_gpt.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-10-10_16:20:01
  host      : a100.internal.chinacloudapp.cn
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 15188)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-10-10_16:20:01
  host      : a100.internal.chinacloudapp.cn
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 15187)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
Error: failed to run torchrun --nproc_per_node=2 --nnodes=1 --node_rank=0 --master_addr=127.0.0.1 --master_port=29500 train_gpt.py --config configs/gpt2_small_zero3_pp1d.py --from_torch --use_dummy_dataset on 127.0.0.1, is localhost: True, exception: Encountered a bad command exit code!

### Environment

Ubuntu:18.04
CUDA 11.7
2 A100
torch 1.13.1
python 3.8

**Comment by Orion-Zheng** [comment]
Thank you for your feedback.😃May I ask how do you configure the environment? I can try to reproduce the bug on our machine and help you.

**Comment by Fridge003** [comment]
Hi, `global_variables` module has been deprecated and moved to legacy. To import it correctly, please use `colossalai.legacy.global_variables`.

I also observe that this error is triggered in titan package. The codes in titans are outdated, so running it requires downgrading colossalai to earlier versions (lower than v0.3.2). Or please run other examples, such as gemini examples or hybrid parallel examples.

**Comment by hellangleZ** [comment]
> Thank you for your feedback.😃May I ask how do you configure the environment? I can try to reproduce the bug on our machine and help you.
Hardware A100*2
OS:Ubuntu:18.04
CUDA 11.7
torch 1.13.1
python 3.8
Colossal 0.3.3 0.3.2 0.3.1 0.2.5 any of them could not work

**Comment by hellangleZ** [comment]
> Hi, `global_variables` module has been deprecated and moved to legacy. To import it correctly, please use `colossalai.legacy.global_variables`.
> 
> I also observe that this error is triggered in titans package. The codes in titans are outdated, so running it requires downgrading colossalai to earlier versions (lower than v0.3.2). Or please run other examples, such as gemini examples or hybrid parallel examples.

Hi  I change to 0.3.1, it still error, and hyprid could not work, gemini, could work always

![image](https://github.com/hpcaitech/ColossalAI/assets/15274284/62d54d03-899f-4476-868f-6368cfb8c363)

![image](https://github.com/hpcaitech/ColossalAI/assets/15274284/bf15d733-dc45-452f-ba93-b930ee5b8b42)

![image](https://github.com/hpcaitech/ColossalAI/assets/15274284/dafe8fe1-07a6-49fb-98f0-e1bf3b857d33)

**Comment by Orion-Zheng** [comment]
please try the method described in the previous comment😃He has figure out the solution

**Comment by hellangleZ** [comment]
> > > Hi, `global_variables` module has been deprecated and moved to legacy. To import it correctly, please use `colossalai.legacy.global_variables`.
> > > I also observe that this error is triggered in titans package. The codes in titans are outdated, so running it requires downgrading colossalai to earlier versions (lower than v0.3.2). Or please run other examples, such as gemini examples or hybrid parallel examples.
> > 
> > 
> > Hi I change to 0.3.1, it still error, and hyprid could not work, gemini, could work always
> > ![image](https://user-images.githubusercontent.com/15274284/274176682-62d54d03-899f-4476-868f-6368cfb8c363.png)
> > ![image](https://user-images.githubusercontent.com/15274284/274176866-bf15d733-dc45-452f-ba93-b930ee5b8b42.png)
> > ![image](https://user-images.githubusercontent.com/15274284/274176971-dafe8fe1-07a6-49fb-98f0-e1bf3b857d33.png)
> 
> Hi, hybrid parallel is a new feature, so it should run under latest colossalai version.
> 
> For the bug in titans examples, it's caused since the newest codes moved deprecated functions to legacy folder, while the earlier colossalai doesn't have legacy folder. Would you please use scripts of earlier versions through `git checkout tags/v0.3.1`, or you can manually change all the `colossalai.legacy.xx` to `colossalai.xx`.

Hi @Fridge003  I just copy your suggestion, and use 0.3.1 verison code and colossal, but there is another issue....



![image](https://github.com/hpcaitech/ColossalAI/assets/15274284/e4557886-243a-4c36-83f6-f9f6448ba8dd)


By the way, would you please suggest of which demo is better with the lasted version, I really face too much problem on GPT2's demo,  what about llama2 or ?

Thanks very much

**Comment by Fridge003** [comment]
Both Gemini and hybrid parallel examples should work good for the latest version of colossalai. The titans examples are outdated thus not recommended. 

If there exists bugs in gemini/hybrid parallel demo after you shift back to latest colossalai, we will fix it.

**Comment by hellangleZ** [comment]
> Both Gemini and hybrid parallel examples should work well for the latest version of colossalai. The titans examples are outdated thus not recommended.
> 
> If there exists bugs in gemini/hybrid parallel demo after you shift back to latest colossalai, we will fix it.

I try two them, the two application are working good so far, @Fridge003
