### ISSUE TITLE
What's the minimal CPU memory and GPU memory to fine tune llama 2 70b?

### ISSUE THREAD

**Issue by fancyerii** [hpcaitech/ColossalAI#4931]
### Describe the feature

In https://huggingface.co/blog/ram-efficient-pytorch-fsdp, It's said llama 2 fsdp need 2TB+ cpu memory because every gpu need a copy of model in cpu which result in 280GB * 8(GPU/node) > 2TB CPU memory. So they use meta device to avoid this. I want to know what's the minimal hardware to pretrain/fine-tune llama 2 70b?

**Comment by Fridge003** [comment]
Hi, what kind of distributed training strategy(plugin) are you going to use? In ColossalAI, the FSDP Plugin is just a simple wrapping over PyTorch FSDP, so the requirement is the same as PyTorch.

**Comment by vaibhavnohria1** [comment]
@fancyerii i want to fix this issue!!

**Comment by fancyerii** [comment]
I don't know which one is best for me. I am now trying zero2. I have some 8 x a100 40GB nodes. And I have only a small mount of training data. So I want to know the minimal hardware requirements including cpu memory requirement.
