### ISSUE TITLE
[FEATURE]: Why PipelineP2PCommunication use broadcast_object but not send/recv API

### ISSUE THREAD

**Issue by lichenlu** [hpcaitech/ColossalAI#4939]
### Describe the feature

 Why PipelineP2PCommunication use broadcast_object but not send/recv API
![image](https://github.com/hpcaitech/ColossalAI/assets/26477886/8df89038-12e9-49d4-a101-a0a5d8180e19)
![image](https://github.com/hpcaitech/ColossalAI/assets/26477886/84c82cac-b07b-4650-8d03-b7237263e3ac)

**Comment by imgaojun** [comment]
我把P2P部分代码改成send/recv后，速度提升了20%。希望官方可以改回send/recv

**Comment by binmakeswell** [comment]
Hi @imgaojun and @lichenlu Thanks for the feedback, we are testing this. You are welcome to contribute by submitting a PR.
