### ISSUE TITLE
[checkpoint]: How to convert a booster checkpoint to a huggingface checkpoint?

### ISSUE THREAD

**Issue by tonydeep** [hpcaitech/ColossalAI#4969]
### Describe the feature

I want to test a checkpoint (from epoch-x_step_y) in another repo without using the booster plugin, just as standard using transformers from a local pretrained path.

**Comment by Fridge003** [comment]
Booster checkpoint is saved in a format compatible with of Huggingface, so it should work if you directly load it using `model_class.from_pretrained` method. If there is any bug please contact me.

**Comment by fsq77** [comment]
same question
