### ISSUE TITLE
Llama2 continual pretaining performance evaultion scripts

### ISSUE THREAD

**Issue by fancyerii** [hpcaitech/ColossalAI#5013]
### Describe the feature

I am following [Colossal-LLaMA-2](https://github.com/hpcaitech/ColossalAI/tree/main/applications/Colossal-LLaMA-2#performance-evaluation) to pretrain my domain llm. To measure it's performance, we need to use open datasets such as MMLU to evaluate. Is there any evaluation scripts available for them? thank you.

**Comment by Orion-Zheng** [comment]
Hello😃You can refer to the applications/ColossalEval to evaluate your model.

**Comment by fancyerii** [comment]
thanks.
