### ISSUE TITLE
What a pity !!! Compatibility Issue with PyTorch 2.x !

### ISSUE THREAD

**Issue by zhoumengbo** [hpcaitech/ColossalAI#5038]
### Describe the feature

I've recently encountered that Colossal-AI does not support PyTorch 2.x, which I find rather concerning given the substantial performance enhancements introduced in the latest PyTorch version. After setting up my environment, this limitation became apparent, and it prompts me to question the extent to which this affects the training or fine-tuning performance when using Colossal-AI.

Could you tell me some light on the performance discrepancies we might expect when not leveraging PyTorch 2.x with Colossal-AI? Any benchmarks or insights on this matter would be greatly appreciated, as it would inform the decision-making process for those of us considering whether to use Colossal-AI.

**Comment by Orion-Zheng** [comment]
Hello, we are currently adapting to the new PyTorch version. We will inform you immediately if there are any updates. Thank you for your attention.😃

**Comment by ericxsun** [comment]
You can use Pytorch 2.0.1 + ColossalAI 0.3.4. That's Okay

**Comment by CWHer** [comment]
Solved in #5050.
