### ISSUE TITLE
[BUG]: application LLAMA2 for data preparation , there is a bug

### ISSUE THREAD

**Issue by hellangleZ** [hpcaitech/ColossalAI#5045]
### 🐛 Describe the bug

(/aml2/colo) root@A100:/aml2/ColossalAI-0.3.4/applications/Colossal-LLaMA-2# python prepare_pretrain_dataset.py     --data_input_dirs "/aml/data/boyang/RedPajama-Data-1T-Sample/data"     --tokenizer_dir "/aml2/llam2/newtoken"     --data_cache_dir "jsonl_to_arrow_cache6"     --data_jsonl_output_dir "/aml/data/boyang/RedPajama-Data-1T-Sample/data_jsonl1"     --data_arrow_output_dir "/aml/data/boyang/RedPajama-Data-1T-Sample/data_arrow1"     --max_length 4096     --num_spliced_dataset_bins 10
You are using the legacy behaviour of the <class 'transformers.models.llama.tokenization_llama.LlamaTokenizer'>. This means that tokens that come after special tokens will not be properly handled. We recommend you to read the related pull request available at https://github.com/huggingface/transformers/pull/24565
Using pad_token, but it is not set yet.
Downloading and preparing dataset json/default to /aml2/ColossalAI-0.3.4/applications/Colossal-LLaMA-2/jsonl_to_arrow_cache6/raw/json/default-d7de43e9695cd3f8/0.0.0/e347ab1c932092252e717ff3f949105a4dd28b27e842dd53157d2f72e276c2e4...
Downloading data files: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 2428.66it/s]
Extracting data files: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 363.80it/s]
Setting num_proc from 96 back to 1 for the train split to disable multiprocessing as it only contains one shard.
Dataset json downloaded and prepared to /aml2/ColossalAI-0.3.4/applications/Colossal-LLaMA-2/jsonl_to_arrow_cache6/raw/json/default-d7de43e9695cd3f8/0.0.0/e347ab1c932092252e717ff3f949105a4dd28b27e842dd53157d2f72e276c2e4. Subsequent calls will reuse this data.
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:00<00:00, 1097.04it/s]
[11/14/23 02:23:53] INFO     colossalai - colossalai - INFO: /aml2/ColossalAI-0.3.4/applications/Colossal-LLaMA-2/prepare_pretrain_dataset.py:105 main             
                    INFO     colossalai - colossalai - INFO: Start to process part-0/10 of all original datasets.                                                  
Traceback (most recent call last):                                                                                                                                 
  File "/aml2/ColossalAI-0.3.4/applications/Colossal-LLaMA-2/prepare_pretrain_dataset.py", line 153, in <module>
    main()
  File "/aml2/ColossalAI-0.3.4/applications/Colossal-LLaMA-2/prepare_pretrain_dataset.py", line 113, in main
    dataset = dataset.sort(column_names=("seq_category", "seq_length"), reverse=False, keep_in_memory=False)
  File "/aml/conda/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 543, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/aml/conda/lib/python3.10/site-packages/datasets/fingerprint.py", line 511, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/aml/conda/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 4051, in sort
    raise ValueError(
**ValueError: Column '('seq_category', 'seq_length')' not found in the dataset. Please provide a column selected in: ['input_ids', 'labels', 'seq_length', 'seq_category']**

dataset , just follow the example. no change ,

![image](https://github.com/hpcaitech/ColossalAI/assets/15274284/0a8c2713-cc80-4eb0-be7a-c8c1fab5a3f9)

### Environment

A100*4*80G

Ubuntu 18.04

torch 1.13.1

cuda 11.7

**Comment by Orion-Zheng** [comment]
Thank you for your feed back. May I check your huggingface datasets version?
It's a weird error. In sorting code, we intended to sort data by two columns names, 'seq_category' and 'seq_length', separately. but your code treat the whole tuple as a column name '('seq_category', 'seq_length')' and raise column not found error.
I looked up the latest `arrow_dataset` in the huggingface dataset and didn't find the error info in line 4051. So i guess you may need to upgrade the datasets library to the latest version?😃
https://github.com/huggingface/datasets/blob/2.14.5/src/datasets/arrow_dataset.py#L3981
If the error persists, feel free to let me know

**Comment by hellangleZ** [comment]
> Thank you for your feed back. May I check your huggingface datasets version? It's a weird error. In sorting code, we intended to sort data by two columns names, 'seq_category' and 'seq_length', separately. but your code treat the whole tuple as a column name '('seq_category', 'seq_length')' and raise column not found error. I looked up the latest `arrow_dataset` in the huggingface dataset and didn't find the error info in line 4051. So i guess you may need to upgrade the datasets library to the latest version?😃 https://github.com/huggingface/datasets/blob/2.14.5/src/datasets/arrow_dataset.py#L3981 If the error persists, feel free to let me know


Hi  @Orion-Zheng 

My datasets version is the newest

![image](https://github.com/hpcaitech/ColossalAI/assets/15274284/83d1ffe2-c445-4dbc-88f0-bc8bc9fce7d2)

I have to mask the 3 lines code to avoid the error message, and could get the train process all pass, but it's not a reasonable solution for us 
![4314AD14](https://github.com/hpcaitech/ColossalAI/assets/15274284/9a5c8e8a-5c48-45ba-b617-db1947b5e61c)


![image](https://github.com/hpcaitech/ColossalAI/assets/15274284/e41f09e3-d9ca-4fe9-8636-cb0bb51544d3)

**Comment by Orion-Zheng** [comment]
Do you have multiple virtual environment? Can you run commands below to check if they point to the same path? 
```python
which python
which pip
```
According to your error info, the ValueError is raised by line 4051 of arrow_dataset.py. It should come from the datasets version 2.12. It seems like you install the latest version but didn't use it🤔I guess it is because the inconsistency of environment variables  
<img width="1448" alt="image" src="https://github.com/hpcaitech/ColossalAI/assets/62330719/9a67d32b-a16e-42cc-ba71-865088c66146">
https://github.com/huggingface/datasets/blob/2.12.0/src/datasets/arrow_dataset.py

**Comment by Orion-Zheng** [comment]
The error is because the version 2.12 has bad implementation to handle multiple columns names
<img width="773" alt="image" src="https://github.com/hpcaitech/ColossalAI/assets/62330719/d5986f49-5277-4d9f-89ce-4bc31c3bc219">
Now the condition is better.
<img width="651" alt="image" src="https://github.com/hpcaitech/ColossalAI/assets/62330719/e77a5672-035b-4d57-9a05-5a3aee3ffbed">
You can also change the column_names=("seq_category", "seq_length") to column_names=["seq_category", "seq_length"], this should be OK with all versions

**Comment by hellangleZ** [comment]
> The error is because the version 2.12 has bad implementation to handle multiple columns names <img alt="image" width="773" src="https://user-images.githubusercontent.com/62330719/282993652-d5986f49-5277-4d9f-89ce-4bc31c3bc219.png"> Now the condition is better. <img alt="image" width="651" src="https://user-images.githubusercontent.com/62330719/282993915-e77a5672-035b-4d57-9a05-5a3aee3ffbed.png"> You can also change the column_names=("seq_category", "seq_length") to column_names=["seq_category", "seq_length"], this should be OK with all versions

![image](https://github.com/hpcaitech/ColossalAI/assets/15274284/8e3b1af3-b005-457f-8087-bc467472fbae)


After change as your suggest， the code is working OK！！please close it， thank you
