### ISSUE TITLE
[FEATURE]: Torch 2.1 and cuda 12.1 support because I could not use colossal on H100....

### ISSUE THREAD

**Issue by hellangleZ** [hpcaitech/ColossalAI#5050]
### Describe the feature

NVIDIA H100 80GB HBM3 with CUDA capability sm_90 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_61 sm_70 sm_75 sm_80 sm_86 compute_37.
If you want to use the NVIDIA H100 80GB HBM3 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
/aml/colo/lib/python3.10/site-packages/colossalai/kernel/cuda_native/mha/flash_attn_2.py:28: UserWarning: please install flash_attn from https://github.com/HazyResearch/flash-attention
  warnings.warn("please install flash_attn from https://github.com/HazyResearch/flash-attention")
/aml/colo/lib/python3.10/site-packages/torch/cuda/__init__.py:155: UserWarning: 
NVIDIA H100 80GB HBM3 with CUDA capability sm_90 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_61 sm_70 sm_75 sm_80 sm_86 compute_37.
If you want to use the NVIDIA H100 80GB HBM3 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

And also the successful deployment which is on the A100, it could not be migrated to H100.....

**Comment by hellangleZ** [comment]
If there is any solid roadmap please also give me a info, any help is very appreciated

**Comment by Orion-Zheng** [comment]
Thank you for your feedback!😃We are working on the adaption to newer pytorch version, which may take some time. May I ask which pytorch version are you using? I will report it to my colleagues working on that.

**Comment by luckyyangrun** [comment]
Is there any updates? Really looking forward to the compatibility

**Comment by Orion-Zheng** [comment]
Yes.😃 Just talk to my colleague. The cuda 12.1 and Torch 2.1 support is ready in the main branch. You can try to build the repo from the main branch (we didn't formally release yet). If you met any problems, please feel free to ask

**Comment by luckyyangrun** [comment]
Thank you very much, really admire your efforts

**Comment by xs1997zju** [comment]
good job
