### ISSUE TITLE
[BUG]: Using HybridParallelPlugin/Gemini to train 70B llama-v2 on 32 A100 gpus get OOM error

### ISSUE THREAD

**Issue by yeegnauh** [hpcaitech/ColossalAI#5068]
### 🐛 Describe the bug

```
python benchmark.py \
    -c 70b -g -b 2 \
    --max_length 1024 -p 3d -x --tp 4 --pp 1 --zero 1 

```
I tried `tp 8 pp 2 ` ,zero 0/1, and plugin gemini, they all get a report of OOM .

Error shown as below:

dp_size=8, args.batch_size=2, args.num_steps=5, max_length=1024
Model params: 64.24 B

  File "/mnt/lustre/share_data//miniconda3/envs/llama2-env/lib/python3.10/site-packages/colossalai-0.3.4-py3.10-linux-x86_64.egg/colossalai/lazy/lazy_init.py", line 240, in _materialize_data
    target = self._materialize_data()
  File "/mnt/lustre/share_data//miniconda3/envs/llama2-env/lib/python3.10/site-packages/colossalai-0.3.4-py3.10-linux-x86_64.egg/colossalai/lazy/lazy_init.py", line 240, in _materialize_data
    init_val = func(
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 448.00 MiB (GPU 4; 79.32 GiB total capacity; 77.24 GiB already allocated; 443.56 MiB free; 77.32 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

How can I train llama v2 70B ?

### Environment

python 3.10
torch 1.13.1 
colossalai main branch till 2023/11/20
CUDA 11.7

**Comment by yeegnauh** [comment]
```
python benchmark.py \
    -c 70b -g -b 2 \
    --max_length 1024 -p 3d -x --tp 4 --pp 1 --zero 1
```

dp_size=8, args.batch_size=2, args.num_steps=5, max_length=1024
Model params: 64.24 B

got error ：

  File "/mnt/lustre/share_data/huangye/miniconda3/envs/llama2-env/lib/python3.10/site-packages/colossalai-0.3.4-py3.10-linux-x86_64.egg/colossalai/shardformer/shard/sharder.py", line 201, in _replace_sub_module
    raise RuntimeError(
RuntimeError: Failed to replace mlp.down_proj of type Linear with Linear1D_Row with the exception: CUDA out of memory. Tried to allocate 448.00 MiB (GPU 5; 79.32 GiB total capacity; 77.24 GiB already allocated; 299.56 MiB free; 77.32 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF. Please check your model configuration or sharding policy, you can set up an issue for us to help you as well.

**Comment by yeegnauh** [comment]
Can anybody run llama2 70B pre-train or benchmark with HybridParallel plugin normally ?
It is really weird.

**Comment by luckyyangrun** [comment]
I suggest using the following config --tp 8 --pp 1 --zero 2

**Comment by yeegnauh** [comment]
> 🐛 Describe the bug

Thank you very much!  It works. And I get a high performance.

And further more, when zero=3 ,tp=4/8, pp=1 , it can be trained normally with a high performance.
