### ISSUE TITLE
[BUG]: NaN loss while using Gemini + tensor_parallel

### ISSUE THREAD

**Issue by ericxsun** [hpcaitech/ColossalAI#5110]
### 🐛 Describe the bug

Using llama2 [benchmark.py](https://github.com/hpcaitech/ColossalAI/blob/main/examples/language/llama2/benchmark.py) with the change:
```
if args.plugin == "gemini":
        plugin = GeminiPlugin(
            precision="bf16",
            shard_param_frac=args.shard_param_frac,
            offload_optim_frac=args.offload_optim_frac,
            offload_param_frac=args.offload_param_frac,
            tp_size=args.tp,
        )
....
```

1. plugin = '3d' + tp=2
loss is normal

```
torchrun --nnodes=1 --nproc_per_node=4 --rdzv_id=1 --rdzv_backend=c10d --rdzv_endpoint=localhost:12345 \
  ColossalAI/examples/language/llama2/benchmark.py \
  -c 7b -g -b 1 --max_length 4096 -p 3d --tp 2 --pp 1 --zero 2 -s 100
```
![image](https://github.com/hpcaitech/ColossalAI/assets/1772912/9a8c4e79-d6d7-4eb6-9cd2-9e7936e8a056)

2. plugin = 'gemini'
loss is normal

```
torchrun --nnodes=1 --nproc_per_node=4 --rdzv_id=1 --rdzv_backend=c10d --rdzv_endpoint=localhost:12345 \
  ColossalAI/examples/language/llama2/benchmark.py \
  -c 7b -g -b 1 --max_length 4096 -p gemini --tp 1 --pp 1 --zero 2 -s 100
```
![image](https://github.com/hpcaitech/ColossalAI/assets/1772912/0dffbda6-206f-4036-9f1a-5599231ba304)

3. plugin = 'gemini' + tp=2
loss is normal at the beginning, and changes to NaN later
```
torchrun --nnodes=1 --nproc_per_node=4 --rdzv_id=1 --rdzv_backend=c10d --rdzv_endpoint=localhost:12345 \
  ColossalAI/examples/language/llama2/benchmark.py \
  -c 7b -g -b 1 --max_length 4096 -p gemini --tp 2 --pp 1 --zero 2 -s 100
```
![image](https://github.com/hpcaitech/ColossalAI/assets/1772912/43e8617e-2e00-410b-b519-ed400f1e4951)

Why loss goes to NaN when using 'gemini' + tensor parallel?  And how to fix it?

Thanks a lot.

### Environment

Pytorch: 2.0.1
ColossalAI: main branch (`CUDA_EXT=1 pip install .`)

**Comment by ericxsun** [comment]
Hello, @flybird11111 , do you have a moment to take a look? Thanks so much.

**Comment by ericxsun** [comment]
> > Hello, @flybird11111 , do you have a moment to take a look? Thanks so much.
> 
> Sure, I will take a look at it.

Thanks very much. May I ask `have you figure out why` ?

**Comment by flybird11111** [comment]
> > > Hello, @flybird11111 , do you have a moment to take a look? Thanks so much.
> > 
> > 
> > Sure, I will take a look at it.
> 
> Thanks very much. May I ask "have you figure it out"?

The issue is still under investigation.

**Comment by flybird11111** [comment]
Hi, this issue has been resolved.

**Comment by ericxsun** [comment]
> Hi, this issue has been resolved.

Thanks a lot @flybird11111, it works fine for randomly generated data

However, when using real data such as ThePile. I observe numerous zero values in [input_embeds](https://github.com/huggingface/transformers/blob/e660424717daf47d4e511a78b9dda230a2f2a602/src/transformers/models/llama/modeling_llama.py#L1011) 

```
        if inputs_embeds is None:
            inputs_embeds = self.embed_tokens(input_ids)
```
. It appears like the following: Zero values consistently appear at either the beginning or the end.
<img width="1335" alt="image" src="https://github.com/hpcaitech/ColossalAI/assets/1772912/831cdf74-2aa1-44a7-9c28-cd9661aad25e">
<img width="1111" alt="image" src="https://github.com/hpcaitech/ColossalAI/assets/1772912/820ec3b5-6bc3-4c4a-9e64-fef03fab3264">

If I comment [VocabParallelEmbedding1D replacement](https://github.com/hpcaitech/ColossalAI/blob/cefdc3261534408c83d338749fef183bf0f3fde7/colossalai/shardformer/policies/llama.py#L91), thing looks like well

```
            self.append_or_create_submodule_replacement(
                description=SubModuleReplacementDescription(
                    suffix="embed_tokens",
                    target_module=VocabParallelEmbedding1D,
                ),
                policy=policy,
                target_key=LlamaModel,
            )
```

**Comment by flybird11111** [comment]
Thanks, I'll look into it.

**Comment by ericxsun** [comment]
The loss becomes irregular when VocabParallelEmbedding1D is not utilized in gemini + tp=8 v.s. hybrid + tp=8 v.s. gemini +no-tp

![image](https://github.com/hpcaitech/ColossalAI/assets/1772912/f73ce66f-fb1b-4810-a513-68b47ae90f4f)

**Comment by ericxsun** [comment]
@flybird11111  May I ask have you figure it out? Thanks so much.

**Comment by ericxsun** [comment]
when using Gemini + tp_size=2 (4gpus), I found VocabParallelEmbedding1D.forward gave me a weird output after `reduce_forward` https://github.com/hpcaitech/ColossalAI/blob/af952673f758c71126b27de8b32bdf5df8f74b69/colossalai/shardformer/layer/embedding.py#L315

numerous Nan value of embedding output in step 11

```
[pretrain.py:main] - step: 10, loss: 11.12129
tensor([[[ 0.0101,  0.0159,  0.0010,  ..., -0.0123,  0.0070, -0.0052],
         [-0.0068, -0.0219, -0.0227,  ...,  0.0179,  0.0201,  0.0330],
         [ 0.0131, -0.0005, -0.0194,  ..., -0.0024,  0.0483,  0.0092],
         ...,
         [ 0.0011,  0.0023,  0.0153,  ...,  0.0184, -0.0029, -0.0283],
         [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
         [-0.0481,  0.0070,  0.0270,  ...,  0.0008, -0.0233, -0.0151]]],
       device='cuda:3', grad_fn=<_ReduceForwardBackward>)
tensor([[[ 0.0101,  0.0159,  0.0010,  ..., -0.0123,  0.0070, -0.0052],
         [-0.0068, -0.0219, -0.0227,  ...,  0.0179,  0.0201,  0.0330],
         [ 0.0131, -0.0005, -0.0194,  ..., -0.0024,  0.0483,  0.0092],
         ...,
         [ 0.0011,  0.0023,  0.0153,  ...,  0.0184, -0.0029, -0.0283],
         [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
         [-0.0481,  0.0070,  0.0270,  ...,  0.0008, -0.0233, -0.0151]]],
       device='cuda:2', grad_fn=<_ReduceForwardBackward>)
tensor([[[    nan,     nan,     nan,  ...,     nan,     nan,     nan],
         [ 0.0054, -0.0106, -0.0187,  ...,  0.0071,  0.0410,  0.0117],
         [    nan,     nan,     nan,  ...,     nan,     nan,     nan],
         ...,
         [ 0.0070, -0.0264,  0.0535,  ..., -0.0254, -0.0137,  0.0337],
         [ 0.0327,  0.0383, -0.0133,  ...,  0.0101,  0.0110,  0.0547],
         [    nan,     nan,     nan,  ...,     nan,     nan,     nan]]],
       device='cuda:1', grad_fn=<_ReduceForwardBackward>)
tensor([[[    nan,     nan,     nan,  ...,     nan,     nan,     nan],
         [ 0.0054, -0.0106, -0.0187,  ...,  0.0071,  0.0410,  0.0117],
         [    nan,     nan,     nan,  ...,     nan,     nan,     nan],
         ...,
         [ 0.0070, -0.0264,  0.0535,  ..., -0.0254, -0.0137,  0.0337],
         [ 0.0327,  0.0383, -0.0133,  ...,  0.0101,  0.0110,  0.0547],
         [    nan,     nan,     nan,  ...,     nan,     nan,     nan]]],
       device='cuda:0', grad_fn=<_ReduceForwardBackward>)
[pretrain.py:main] - step: 11, loss: nan
```

**Comment by flybird11111** [comment]
> when using Gemini + tp_size=2 (4gpus), I found VocabParallelEmbedding1D.forward gave me a weird output after `reduce_forward`
> 
> https://github.com/hpcaitech/ColossalAI/blob/af952673f758c71126b27de8b32bdf5df8f74b69/colossalai/shardformer/layer/embedding.py#L315
> 
> numerous Nan value of embedding output in step 11
> 
> ```
> [pretrain.py:main] - step: 10, loss: 11.12129
> tensor([[[ 0.0101,  0.0159,  0.0010,  ..., -0.0123,  0.0070, -0.0052],
>          [-0.0068, -0.0219, -0.0227,  ...,  0.0179,  0.0201,  0.0330],
>          [ 0.0131, -0.0005, -0.0194,  ..., -0.0024,  0.0483,  0.0092],
>          ...,
>          [ 0.0011,  0.0023,  0.0153,  ...,  0.0184, -0.0029, -0.0283],
>          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
>          [-0.0481,  0.0070,  0.0270,  ...,  0.0008, -0.0233, -0.0151]]],
>        device='cuda:3', grad_fn=<_ReduceForwardBackward>)
> tensor([[[ 0.0101,  0.0159,  0.0010,  ..., -0.0123,  0.0070, -0.0052],
>          [-0.0068, -0.0219, -0.0227,  ...,  0.0179,  0.0201,  0.0330],
>          [ 0.0131, -0.0005, -0.0194,  ..., -0.0024,  0.0483,  0.0092],
>          ...,
>          [ 0.0011,  0.0023,  0.0153,  ...,  0.0184, -0.0029, -0.0283],
>          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
>          [-0.0481,  0.0070,  0.0270,  ...,  0.0008, -0.0233, -0.0151]]],
>        device='cuda:2', grad_fn=<_ReduceForwardBackward>)
> tensor([[[    nan,     nan,     nan,  ...,     nan,     nan,     nan],
>          [ 0.0054, -0.0106, -0.0187,  ...,  0.0071,  0.0410,  0.0117],
>          [    nan,     nan,     nan,  ...,     nan,     nan,     nan],
>          ...,
>          [ 0.0070, -0.0264,  0.0535,  ..., -0.0254, -0.0137,  0.0337],
>          [ 0.0327,  0.0383, -0.0133,  ...,  0.0101,  0.0110,  0.0547],
>          [    nan,     nan,     nan,  ...,     nan,     nan,     nan]]],
>        device='cuda:1', grad_fn=<_ReduceForwardBackward>)
> tensor([[[    nan,     nan,     nan,  ...,     nan,     nan,     nan],
>          [ 0.0054, -0.0106, -0.0187,  ...,  0.0071,  0.0410,  0.0117],
>          [    nan,     nan,     nan,  ...,     nan,     nan,     nan],
>          ...,
>          [ 0.0070, -0.0264,  0.0535,  ..., -0.0254, -0.0137,  0.0337],
>          [ 0.0327,  0.0383, -0.0133,  ...,  0.0101,  0.0110,  0.0547],
>          [    nan,     nan,     nan,  ...,     nan,     nan,     nan]]],
>        device='cuda:0', grad_fn=<_ReduceForwardBackward>)
> [pretrain.py:main] - step: 11, loss: nan
> ```
Hi, I ran this command.
torchrun --nnodes=1 --nproc_per_node=4 --rdzv_id=1 --rdzv_backend=c10d --rdzv_endpoint=localhost:12345 benchmark.py -c 7b -g -b 1 --max_length 4096 -p gemini --tp 2
<img width="730" alt="image" src="https://github.com/hpcaitech/ColossalAI/assets/37931082/b3ba405e-ec13-47eb-b1f1-6ba35e1cc469">
<img width="1039" alt="image" src="https://github.com/hpcaitech/ColossalAI/assets/37931082/243ec78a-1be2-4f01-9a90-a72fbaea78a6">
The loss looks normal.

**Comment by flybird11111** [comment]
Can you pull the latest code and try again?

**Comment by ericxsun** [comment]
> Can you pull the latest code and try again?

Okay, Thank you very much.

**Comment by ericxsun** [comment]
I may have a partial understanding of it. We rewrite dataset(mixed multi data) using prefetching, and the data is being split across GPUs. Here is a snippet of the code:
```
process_group = _get_default_group()
world_size, rank = process_group.size(), process_group.rank()

data_range = whole_range.sub_range(split=rank, n_splits=world_size)
...
```

This code seems to work correctly when Tensor-Parallel is not in use, but it may lead to issues with Tensor-Parallel. Would it be advisable to replace `_get_default_group` with `plugin.tp_group`?

Thanks a lot. @flybird11111

**Comment by flybird11111** [comment]
> I may have a partial understanding of it. We rewrite dataset(mixed multi data) using prefetching, and the data is being split across GPUs. Here is a snippet of the code:
> 
> ```
> process_group = _get_default_group()
> world_size, rank = process_group.size(), process_group.rank()
> 
> data_range = whole_range.sub_range(split=rank, n_splits=world_size)
> ...
> ```
> 
> This code seems to work correctly when Tensor-Parallel is not in use, but it may lead to issues with Tensor-Parallel. Would it be advisable to replace `_get_default_group` with `plugin.tp_group`?
> 
> And I'm little confused by diff prepare_dataloader between GeminiPlugin and HybridParallelPlugin:
> 
> GeminiPlugin
> 
> ```
> sampler = DistributedSampler(
>             dataset, num_replicas=zero_world_size * extra_dp_world_size, rank=zero_rank * extra_dp_world_size + extra_dp_rank, shuffle=shuffle
>         )
> ```
> 
> v.s. HybridParallelPlugin
> 
> ```
> sampler = DistributedSampler(
>             dataset, num_replicas=self.pg_mesh.size(DP_AXIS), rank=self.pg_mesh.coordinate(DP_AXIS), shuffle=shuffle
>         )
> ```
> 
> Thanks a lot. @flybird11111

The Gemini plugin and the hybrid parallel plugin will manage the allocation of data on each rank. It suggests replacing _get_default_group with dp_group

**Comment by ericxsun** [comment]
Okay, Thanks again, I'll try it.

**Comment by ericxsun** [comment]
I have tested it and successfully resolved the problem with 4 GPUs and tp_size=2. Thank you very much. @flybird11111 

There is a small issue: why is the variable named `extra_dp_group` in Gemini and `dp_group` in Hybrid?

**Comment by flybird11111** [comment]
In geminiplugin, extra_dp_group and zero_group are both dp group.

**Comment by ericxsun** [comment]
> In geminiplugin, extra_dp_group and zero_group are both dp group.

Therefore, if `extra_dp_group<=`, `zero_group` should be utilized as `dp_group`, is it right?. What should be done if `extra_dp_group>1` in my particular scenario? (I'm little messed up)

**Comment by flybird11111** [comment]
`rank=zero_rank * extra_dp_world_size + extra_dp_rank`, just allocate data in both the dp group and the zero group.

**Comment by ericxsun** [comment]
> `rank=zero_rank * extra_dp_world_size + extra_dp_rank`, just allocate data in both the dp group and the zero group.

Thank you for valuable explanation.

Thanks again.
