### ISSUE TITLE
[BUG]: how to disable FlashAttention  

### ISSUE THREAD

**Issue by SeekPoint** [hpcaitech/ColossalAI#5174]
### 🐛 Describe the bug

RuntimeError: FlashAttention only supports Ampere GPUs or newer.

### Environment

colossal 0.3.4

ColossalAI/examples/language/opt# bash run_demo.sh
+ pip install -r requirements.txt

**Comment by flybird11111** [comment]
You can set enable_all_optimization to false. And configure other optimizations as needed.
