### ISSUE TITLE
Implement triton kernels for inference

### ISSUE THREAD

**Issue by yuanheng-zhao** [hpcaitech/ColossalAI#5193]
Tracking for implementation of triton kernels compatible with relevant submodules and KVCache for inference.

- Context-stage Attention https://github.com/hpcaitech/ColossalAI/pull/5192
- Decoding-stage Attention https://github.com/hpcaitech/ColossalAI/pull/5249
- Pos Embedding 
  - https://github.com/hpcaitech/ColossalAI/pull/5252 
- KVCache Copy
  - context: fused in context attention
  - decoding: https://github.com/hpcaitech/ColossalAI/pull/5261 
- Layer norm  https://github.com/hpcaitech/ColossalAI/pull/5262

**Comment by CjhHa1** [comment]
First stage kernel implementation is done
