### ISSUE TITLE
[BUG]: The placement policies between Bert example and the stable ColAI are not compatible

### ISSUE THREAD

**Issue by nkfyz** [hpcaitech/ColossalAI#5200]
### 🐛 Describe the bug

The placement policy of Gemini plugin in Bert example is "cuda", which is as follows:

<img width="692" alt="image" src="https://github.com/hpcaitech/ColossalAI/assets/62918515/1441b971-7914-46b4-9f85-374c6dd20090">

However, this policy is not supported by the ColAI (main branch). Existing policy includes "auto" and "static".

<img width="372" alt="image" src="https://github.com/hpcaitech/ColossalAI/assets/62918515/9b5d3695-a330-45a1-9221-e91af2631dd0">

Therefore, the error is: 

<img width="937" alt="image" src="https://github.com/hpcaitech/ColossalAI/assets/62918515/209673c9-0a11-468b-89cf-e5996c4615bd">

Correct the policy from "cuda" to "auto" can solve this problem and successfully testing:

<img width="1079" alt="image" src="https://github.com/hpcaitech/ColossalAI/assets/62918515/aefacc24-305c-4e39-80f7-50f898568dca">

Thanks.

**Comment by flybird11111** [comment]
Thank you, we will fix this issue as soon as possible.
