### ISSUE TITLE
[BUG]:  failed with 'not a valid RSA private key file' when run colossal with 2 nodes

### ISSUE THREAD

**Issue by SeekPoint** [hpcaitech/ColossalAI#5213]
### 🐛 Describe the bug

root@MZ32-00:/ColossalAI/examples/language/llama2# colossalai run --nproc_per_node 2 --host 192.168.1.11,192.168.1.12 --master_addr 192.168.1.11 --master_port 29508 pretrain.py

Error: failed to run torchrun --nproc_per_node=2 --nnodes=2 --node_rank=1 --master_addr=192.168.1.11 --master_port=29508 pretrain.py on 192.168.1.12, is localhost: False, exception: not a valid RSA private key file
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************
===and it was hangs on here

I am sure it worksbwell with 
  colossalai run --nproc_per_node 2 pretrain.py
on both single node

**Comment by flybird11111** [comment]
Hi, have you configured passwordless login between your nodes?

**Comment by SeekPoint** [comment]
do you mean 'ssh hostname' without password? I done

**Comment by zhangvia** [comment]
> do you mean 'ssh hostname' or 'ssh 192.168.xxx.xxx' without password?Yes, I done

you can set NCCL_DEBUG=INFO to see more log
