### ISSUE TITLE
[BUG]: Different behaviors when setting param for colossalai.nn.Linear and torch.nn.Linear

### ISSUE THREAD

**Issue by Wesley-Jzy** [hpcaitech/ColossalAI#523]
### 🐛 Describe the bug

scripts:
```
import torch
from colossalai import nn as col_nn
bias = nn.Parameter(torch.zeros(1000))
col_layer = col_nn.Linear(1000,1000, bias=False)
torch_layer = torch.nn.Linear(1000,1000,bias=False)
```

Then run col_layer.bias = bias and torch_layer.bias = bias
torch_layer.bias = bias is ok but col_layer.bias = bias reports the following error:
KeyError: "attribute 'bias' already exists"

**Comment by feifeibear** [comment]
You can add a setter in class Linear. Make sure your setting is valid in terms if the tensor shape.

colossalai/nn/layer/colossalai_layer/linear.py
```
@property
    def bias(self, value):
        self.layer.bias = value
```

**Comment by kurisusnowdeng** [comment]
We do not recommend this way to set parameters for parallel layers because the parameter objects no longer have our custom parallel processings (e.g. various forward & backward hooks).

If you do want to set a parameter by yourself, you could try the following way
```python
    layer = col_nn.Linear(1000, 1000, bias=True)
    new_bias = torch.zeros((1000,))
    layer.bias.data.copy_(new_bias)
```

**Comment by feifeibear** [comment]
The bias shape is different. Users do not know how did you split the bias?

**Comment by Wesley-Jzy** [comment]
@kurisusnowdeng I've dodged the difficulies I faced by passing a hand-cutting copy but it was very confusing when I first time converted pytorch Bert into Colossalai. I know maybe it's difficult to provide an all-purpose setter to users like the shape problem @feifeibear referred to. At lease we can make the error report more friendly.

**Comment by binmakeswell** [comment]
We have updated a lot. This issue was closed due to inactivity. Thanks.
