### ISSUE TITLE
how can I use my IB 100g card to training with multi node?

### ISSUE THREAD

**Issue by SeekPoint** [hpcaitech/ColossalAI#5266]
### Describe the feature

root@MZ32-00:/ColossalAI/examples/language/llama2# ifconfig

eno1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.11  netmask 255.255.255.0  broadcast 192.168.1.255
        inet6 2409:8a50:3020:5d70:e29b:8cc1:fa33:cbd8  prefixlen 64  scopeid 0x0<global>
        inet6 fe80::5259:de5e:e208:a742  prefixlen 64  scopeid 0x20<link>
        inet6 2409:8a50:3020:5d70:bb44:a058:849b:d594  prefixlen 64  scopeid 0x0<global>
        ether 18:c0:4d:80:51:56  txqueuelen 1000  (Ethernet)
        RX packets 2701416  bytes 543187328 (543.1 MB)
        RX errors 1  dropped 4880  overruns 0  frame 1
        TX packets 20864211  bytes 30107024017 (30.1 GB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device memory 0x94420000-9443ffff

ibp65s0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 4092
        inet 11.4.3.177  netmask 255.255.0.0  broadcast 11.4.255.255
        unspec 00-00-00-68-FE-80-00-00-00-00-00-00-00-00-00-00  txqueuelen 256  (UNSPEC)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

++++++++++++++++++++++++++++++++++

amd01@MZ32-01:~$ ifconfig

eno2: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.12  netmask 255.255.255.0  broadcast 192.168.1.255
        inet6 fe80::97d6:6dda:5bee:7a41  prefixlen 64  scopeid 0x20<link>
        inet6 2409:8a50:3020:5d70:33a8:55ce:93da:d5a9  prefixlen 64  scopeid 0x0<global>
        inet6 2409:8a50:3020:5d70:bcb5:c325:76ac:ac60  prefixlen 64  scopeid 0x0<global>
        ether d8:5e:d3:12:29:ea  txqueuelen 1000  (Ethernet)
        RX packets 95709  bytes 109708513 (109.7 MB)
        RX errors 0  dropped 1485  overruns 0  frame 0
        TX packets 173482  bytes 134568240 (134.5 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device memory 0x94400000-9441ffff

ibp65s0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 4092
        inet 11.4.3.175  netmask 255.255.0.0  broadcast 11.4.255.255
        unspec 00-00-00-68-FE-80-00-00-00-00-00-00-00-00-00-00  txqueuelen 256  (UNSPEC)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
++++++++++++++++++++++++++++++

now, I can run 

root@MZ32-00:/ColossalAI/examples/language/llama2# colossalai run --nproc_per_node 2 --host 192.168.1.11,192.168.1.12 --master_port=29507 --master_addr 192.168.1.11 pretrain.py

well, but failed on:
root@MZ32-00:/ColossalAI/examples/language/llama2# colossalai run --nproc_per_node 2 --host 11.4.3.177,11.4.3.175 --master_port=29590 --master_addr 11.4.3.177 pretrain.py
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************
Error: failed to run torchrun --nproc_per_node=2 --nnodes=2 --node_rank=1 --master_addr=11.4.3.177 --master_port=29590 pretrain.py on 11.4.3.175, is localhost: False, exception: [Errno None] Unable to connect to port 22 on 11.4.3.175

**Comment by lllsy12138** [comment]
Hi, have you solve this problem, I got a similar problem.

**Comment by SeekPoint** [comment]
Yes, I did

But I am not sure which step I take.

The problemn is the config of ubuntu, not ColossalAI
