### ISSUE TITLE
Can your openmoe project train mixtral 8x7b model ?[FEATURE]: 

### ISSUE THREAD

**Issue by ZhangEnmao** [hpcaitech/ColossalAI#5319]
### Describe the feature

I want to know if your openmoe project can train other moe_models like mixtral ? And in your openmoe.md , I cannot find this checkpoint in nvidia-apex "git checkout 741bdf50825a97664db08574981962d66436d16a"

**Comment by flybird11111** [comment]
> other
Yes, you can pay attention to this code. https://github.com/hpcaitech/ColossalAI/blob/feat/moe/applications/ColossalMoE/train.sh

**Comment by flybird11111** [comment]
Hi, you can follow the latest code in the main branch.
