### ISSUE TITLE
Get error when want to use Colossal-LLaMA-2

### ISSUE THREAD

**Issue by zhpacer** [hpcaitech/ColossalAI#5394]
### Discussed in https://github.com/hpcaitech/ColossalAI/discussions/5393

<div type='discussions-op-text'>

<sup>Originally posted by **zhpacer** February 20, 2024</sup>
CUDA: Build cuda_11.8.r11.8/compiler.31833905_0
following: https://github.com/hpcaitech/ColossalAI/tree/main/applications/Colossal-LLaMA-2 
Error:
utils/flash_attention_patch.py", line 22, in <module>
    from colossalai.accelerator import get_accelerator
ModuleNotFoundError: No module named 'colossalai.accelerator'
</div>

**Comment by TongLi3701** [comment]
Could u please try the latest main branch of ColossalAI, it might because of the upgrade of ColossalAI itself.

**Comment by zhpacer** [comment]
My environment
   CUDA: 11.8
   pyTorch: 1.13

1. Update to the newest ColossalAI through git using the command: "BUILD_EXT=1 pip install .".  Then get the following error:

>     Traceback (most recent call last):
>   File "/opt/conda/lib/python3.8/site-packages/transformers/modeling_utils.py", line 530, in load_state_dict
>     return torch.load(
>   File "/opt/conda/lib/python3.8/site-packages/torch/serialization.py", line 734, in load
>     return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
>   File "/opt/conda/lib/python3.8/site-packages/torch/serialization.py", line 1069, in _load
>     unpickler = UnpicklerWrapper(data_file, **pickle_load_args)
> TypeError: 'weights_only' is an invalid keyword argument for Unpickler()

2. Can't load the llama2 model. After searching on google, someone said using transformers==4.36.0 can fix this problem. So I use transformers==4.36.0, can load the model but get another error:

>   File "train.py", line 422, in <module>
>     main()
>   File "train.py", line 346, in main
>     batch_output = model(**batch)
>   File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1185, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/opt/conda/lib/python3.8/site-packages/colossalai/booster/plugin/low_level_zero_plugin.py", line 65, in forward
>     return super().forward(*args, **kwargs)
>   File "/opt/conda/lib/python3.8/site-packages/colossalai/interface/model.py", line 25, in forward
>     return self.module(*args, **kwargs)
>   File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1185, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/opt/conda/lib/python3.8/site-packages/transformers/models/llama/modeling_llama.py", line 1174, in forward
>     outputs = self.model(
>   File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1185, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/opt/conda/lib/python3.8/site-packages/transformers/models/llama/modeling_llama.py", line 1061, in forward
>     layer_outputs = decoder_layer(
>   File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1185, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/opt/conda/lib/python3.8/site-packages/transformers/models/llama/modeling_llama.py", line 789, in forward
>     hidden_states, self_attn_weights, present_key_value = self.self_attn(
>   File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1185, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/home/work/test_lm/Update_ColossalAI/ColossalAI/applications/Colossal-LLaMA-2/colossal_llama2/utils/flash_attention_patch.py", line 129, in attention_forward
>     past_kv_len = past_key_value[0].shape[-2]
>   File "/opt/conda/lib/python3.8/site-packages/transformers/cache_utils.py", line 78, in __getitem__
>     raise KeyError(f"Cache only has {len(self)} layers, attempted to access layer with index {layer_idx}")
> KeyError: 'Cache only has 0 layers, attempted to access layer with index 0'

3. Then after searching on google, that's due to the conflict with flash_atten. Then disable the flash_atten in the command, it at last can work. But can't use flash_atten

Do you have some ideas about how to fix that? thanks!

**Comment by zhpacer** [comment]
> Could u please try the latest main branch of ColossalAI, it might because of the upgrade of ColossalAI itself.

if this is the case, the "requirements.txt" under "applications/Colossal-LLaMA-2/" is outdated now
