### ISSUE TITLE
[BUG]: bugs surfaced while training MoE(Mixtral)

### ISSUE THREAD

**Issue by ericxsun** [hpcaitech/ColossalAI#5426]
### 🐛 Describe the bug

With the main branch `applications/ColossalMoE`, I got such error:
```
grad = grad.to(master_moe_param.dtype).to(master_moe_param.device)
AttributeError: 'NoneType' object has no attribute 'to'
```

start script:
```
NUM_GPU=2
MODEL="mistralai/Mixtral-8x7B-v0.1"
SEQ_LENGTH=128
BATCH_SIZE=1
LR=0.00001

# hybrid
python -m torch.distributed.run --nnodes=1 --nproc_per_node $NUM_GPU --rdzv_id=1 --rdzv_backend=c10d --rdzv_endpoint=localhost:12346 \
    train.py \
    --num_epoch 1 \
    --model_name $MODEL \
    --plugin "hybrid" \
    --batch_size $BATCH_SIZE \
    --lr $LR \
    --zero_stage 2 \
    --pp_size 1 \
    --dp_size 1 \
    --ep_size 2
```

the full trace
```
Traceback (most recent call last):
  File "debug_moe.py", line 86, in <module>
    debug_main()
  File "debug_moe.py", line 82, in debug_main
    main(args, cfg)
  File "pretrain.py", line 308, in main
    raise e
  File "pretrain.py", line 286, in main
    optimizer.step()
  File ".local/lib/python3.10/site-packages/colossalai/zero/low_level/low_level_optim.py", line 616, in step

    grad = grad.to(master_moe_param.dtype).to(master_moe_param.device)
AttributeError: 'NoneType' object has no attribute 'to'
```

without `EPMixtralSparseMoeBlock` in mixtral_policy,  I met another problem: 

hangs at the following point:
![image](https://github.com/hpcaitech/ColossalAI/assets/1772912/af59c6fb-31a5-4de0-b348-72adbb32a31b)

### Environment

- transformers 4.38.2
- colossalai main, feat/moe branch
- pytorch 2.1.2cu118

**Comment by ericxsun** [comment]
The [feat/moe](https://github.com/hpcaitech/ColossalAI/blob/feat/moe/applications/ColossalMoE/train_moe.py)  branch runs successfully.  I believe that the `replace_moe_layer` https://github.com/hpcaitech/ColossalAI/blob/1d96a562bb73d33424a8f91ac7463fa4e3b7dada/applications/ColossalMoE/train_moe.py#L219  might be the crucial distinction.

cc @flybird11111

**Comment by ericxsun** [comment]
However, upon implementing the checkpoint in the feat/moe branch, I encountered an issue with restoring from the previously saved checkpoint not occurring correctly.

![image](https://github.com/hpcaitech/ColossalAI/assets/1772912/f36ba639-715b-44d1-8566-5b926b28ae11)

**Comment by ericxsun** [comment]
with replace_moe_layer implemeted in `feat/moe`, and save_shard_model in main branch, I can save and restore it correctly, 

![image](https://github.com/hpcaitech/ColossalAI/assets/1772912/125d89c8-ace4-41a0-bb31-649ca8e59109)

However, it cannot be loaded with `AutoModelForCausalLM`
```
from transformers import AutoModelForCausalLM
from transformers import AutoTokenizer

 model = AutoModelForCausalLM.from_pretrained(checkpoint)
```

error:
```
were not used when initializing MixtralForCausalLM: [
'model.layers.0.block_sparse_moe.experts.wi_gate', 
'model.layers.0.block_sparse_moe.experts.wi_up',
'model.layers.0.block_sparse_moe.experts.wo',
'model.layers.0.block_sparse_moe.gate_weight',
....
```

**Comment by flybird11111** [comment]
hi，What version of transformers have you installed?

**Comment by ericxsun** [comment]
> hi，What version of transformers have you installed?

transformers                  4.38.2

**Comment by ericxsun** [comment]
with some fix, I can save & restore correctly, and load from transformers

```
In [3]: from transformers import AutoModelForCausalLM
   ...: from transformers import AutoTokenizer
In [4]: model = AutoModelForCausalLM.from_pretrained(checkpoint)
Loading checkpoint shards:   0%|                                                                                        | 0/2 [00:00<?, ?it/s]
Loading checkpoint shards:  50%|████████████████████████████████████████                                        | 1/2 [00:25<00:25, 25.15s/it]
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████| 2/2 [00:33<00:00, 16.75s/it]

```

and restore it correctly
![image](https://github.com/hpcaitech/ColossalAI/assets/1772912/161a5a97-a624-49d8-9d91-bb25047a1a94)

**Comment by ericxsun** [comment]
However, when attempting to load Mixtral-8x7B-v0.1, executing replace_moe_layer is excessively slow and results in Out of Memory (OOM) errors.

```
File "models/mixtral_layer.py", line 63, in replace_moe_layer

replace_moe_layer(

File "models/mixtral_layer.py", line 63, in replace_moe_layer

replace_moe_layer(

File "models/mixtral_layer.py", line 63, in replace_moe_layer

replace_moe_layer(

File "models/mixtral_layer.py", line 55, in replace_moe_layer

model.block_sparse_moe = MixtralSparseMLP.from_native_module(

File "models/mixtral_layer.py", line 46, in from_native_module

sparse_mlp = SparseMLP(**moe_kwargs).to(dtype).to(device)

File ".local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1160, in to

return self._apply(convert)

File ".local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 810, in _apply

module._apply(fn)

File ".local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 833, in _apply

param_applied = fn(param)

File ".local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1158, in convert

return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)

torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 224.00 MiB. GPU 3 has a total capacty of 79.32 GiB of which 41.56 MiB is free. Process 3898623 has 79.28 GiB memory in use
```

Env:
- A800 80G, 8x10 gpus
- zero_state 2

| ep_size | OOM Tried to allocate |
| -------- | ----------------------|
| 2 | 448M |
| 4 | 224M |

**Comment by ericxsun** [comment]
Regarding the main branch, would it be advisable to include the following code snippet within the `def step(self, closure=None)` function of `colossalai/zero/low_level/low_level_optim.py`  

```
grad = working_moe_param.grad
if grad is None:
    continue
```

to avoid such error: 

```
    grad = grad.to(master_moe_param.dtype).to(master_moe_param.device)
AttributeError: 'NoneType' object has no attribute 'to'
```

Thanks a lot. @flybird11111

**Comment by ericxsun** [comment]
More exp:  The restoration appears to be correct when compared to 5x8 GPUs.

Env:
- gpus = 1 x 8
- ep_size = 2
- zero_state = 2 

<img width="628" alt="image" src="https://github.com/hpcaitech/ColossalAI/assets/1772912/1ad07be4-323b-4800-9a39-2d42e46ef535">

Env:
- gpus = 5 x 8
- ep_size = 2
- zero_state = 2 

<img width="637" alt="image" src="https://github.com/hpcaitech/ColossalAI/assets/1772912/c3f67fcb-be9d-48cb-8d62-513b96f24802">
