### ISSUE TITLE
[FEATURE]: Integrate GaLore into Colossalai Optimizer(Gemini/Hybrid)

### ISSUE THREAD

**Issue by ericxsun** [hpcaitech/ColossalAI#5443]
### Describe the feature

A recent paper titled "GaLore: Memory-Efficient LLM Training by Gradient Low-Rank Projection" (https://arxiv.org/pdf/2403.03507.pdf) demonstrates a remarkable memory-efficient approach during the training of large language models (LLMs). 

Can we integrate this memory-efficient technique into the Colossalai framework?

FYI
- GaLore Adamw: https://github.com/jiaweizzhao/GaLore/blob/master/galore_torch/adamw.py
- 8bit-GaLore Adamw: https://github.com/jiaweizzhao/GaLore/blob/master/galore_torch/adamw8bit.py

**Comment by ericxsun** [comment]
Any ColossalAI-er could take a look?

**Comment by ver217** [comment]
Thanks! We will take a look.

**Comment by Edenzzzz** [comment]
I will take multiple looks

**Comment by ericxsun** [comment]
I see the MR, that's awesome, when can we use it?

**Comment by Edenzzzz** [comment]
I plan to release it next week
