### ISSUE TITLE
[BUG]: No module named 'colossalai.kernel.extensions'

### ISSUE THREAD

**Issue by MountainGG** [hpcaitech/ColossalAI#5458]
### 🐛 Describe the bug

I encountered this problem while running llama pre-training scripts in the application folder, using colossalai0.3.6 installed from source. 'cd ./ColossalAI-0.3.6; BUILD_EXT=1 python -m pip install -e .' .

![1710387027565](https://github.com/hpcaitech/ColossalAI/assets/22727498/0f5e5bbc-9498-4d50-95ce-c914d7232f3f)
![1710387048821](https://github.com/hpcaitech/ColossalAI/assets/22727498/3dd7bcac-cef0-4ef3-9772-e957c705e536)
![1710386660604](https://github.com/hpcaitech/ColossalAI/assets/22727498/c97d5275-068d-4d91-a4d1-c03033c11473)

### Environment

colossalai0.3.6
torch2.1.2+cu118
python3.10
gcc10

**Comment by MountainGG** [comment]
Correction: I used 'cd ./ColossalAI-0.3.6; BUILD_EXT=1 python -m pip install -e .' ，and encountered the same problem.

**Comment by MountainGG** [comment]
![1710397315052](https://github.com/hpcaitech/ColossalAI/assets/22727498/f9b904e0-f125-47a8-bb0d-138891f0d416)

**Comment by polo-0831** [comment]
Same problem I met. I use Open-Sora to train, stuck on this step.
I notice there exsist a file called 'extensions' in folder ''colossalai/kerner', maybe that's a way to located extensions.py

**Comment by MountainGG** [comment]
> Same problem I met. I use Open-Sora to train, stuck on this step. I notice there exsist a file called 'extensions' in folder ''colossalai/kerner', maybe that's a way to located extensions.py

This file seems to be a path connected to the outermost “extensions” folder. But pip or python does not seem to recognize it. If you use pip to uninstall colossalai, you may see that it is installed at the same level as colossalai.

**Comment by Edenzzzz** [comment]
> > Same problem I met. I use Open-Sora to train, stuck on this step. I notice there exsist a file called 'extensions' in folder ''colossalai/kerner', maybe that's a way to located extensions.py
> 
> This file seems to be a path connected to the outermost “extensions” folder. But pip or python does not seem to recognize it. If you use pip to uninstall colossalai, you may see that it is installed at the same level as colossalai.

This (https://github.com/hpcaitech/ColossalAI/blob/main/colossalai/kernel/extensions) is a soft link to the parent extension folder. If you pull the main branch you shouldn't encounter this error. Alternatively, you can try `ln -s ../../extensions .'
inside the colossalai.kernel folder.
