### ISSUE TITLE
[FEATURE]: Upgrade the transformers version from 4.33.0 to 4.36.0 for Shardformer.

### ISSUE THREAD

**Issue by wangbluo** [hpcaitech/ColossalAI#5505]
### Describe the feature

Shardformer was originally developed based on transformers==4.33.0. In response to our users' needs, it needs to be upgraded to version 4.36.0.
The main changes involve the models in the colossalai/shardformer/modeling directory.
@ver217 @KKZ20 Please take a look, thanks! :)

**Comment by insujang** [comment]
Hi! Thanks for this work. I am not a part of hpcaitech, but just wondering: are you planning to keep bumping the version up? Since HF transformers version is now 4.39.3, and I found that at least llama2 model many internal implementations have been changed, and it did not work.

**Comment by wangbluo** [comment]
> Hi! Thanks for this work. I am not a part of hpcaitech, but just wondering: are you planning to keep bumping the version up? Since HF transformers version is now 4.39.3, and I found that at least llama2 model many internal implementations have been changed, and it did not work.

Hi, we have already upload all the shardformer model to 4.39.3 version of transformers, so I guess this issue can be closed.
