### ISSUE TITLE
[BUG]: Cannot find module 'colossalai.kernel.cuda_native' when run sequence_parallel example

### ISSUE THREAD

**Issue by ztorchan** [hpcaitech/ColossalAI#5553]
### 🐛 Describe the bug

I noticed that after v0.3.5 of ColossalAI, the `colossalai.kernel.cuda_native` module seems to have been removed. 

https://github.com/hpcaitech/ColossalAI/tree/8e412a548e5366d1c42bcf386bd185091bd0c280/colossalai/kernel

However, the statement `from colossalai.kernel.cuda_native import LayerNorm` still exists in `examples/tutorial/sequence_parallel/model/layers/bert_layer.py`, 

https://github.com/hpcaitech/ColossalAI/blob/8e412a548e5366d1c42bcf386bd185091bd0c280/examples/tutorial/sequence_parallel/model/layers/bert_layer.py#L4

which leads to errors.

`ModuleNotFoundError: No module named 'colossalai.kernel.cuda_native'`

 Is it normal?

### Environment

python 3.10.10 
cuda 11.6.1
torch 1.12.1

**Comment by Edenzzzz** [comment]
This is deprecated and yes we should remove it. @Courtesy-Xs could you point to where this kernel is located now?

**Comment by ztorchan** [comment]
I have changed some code to fix the bug. It can run in my machine now. Please check the PR.

**Comment by Edenzzzz** [comment]
Thanks for your attention. Though tutorials are part of the legacy API that we are deprecating, and I've added a similar fix for other tutorials to make them runnable.

**Comment by ztorchan** [comment]
Thanks. I will close the #5556
