### ISSUE TITLE
how to wrapped multiple models with booster

### ISSUE THREAD

**Issue by feixiang7701** [hpcaitech/ColossalAI#5641]
### Discussed in https://github.com/hpcaitech/ColossalAI/discussions/5595

If two models need to be trained, and they use different optimizers.  One model is a large model, which can't be loaded with single card, and the other is a small model to assist the training of the large model, but it also needs parameter update, how to warp each model through booster.
The original boost api only support warp wtih single nn.Module, so how to solve trained multi model with boost?

![Uploading 1.png…]()

**Comment by Edenzzzz** [comment]
Hi,
Thanks for the issue.
I think you can just boost two models using the same booster, as long as you want to apply the same parallel plan. Otherwise  you can create two boosters with your desired plans.

**Comment by feixiang7701** [comment]
Thanks

**Comment by wangqiang9** [comment]
I have the same promblem...
