### ISSUE TITLE
[BUG]: Slack link is invalid

### ISSUE THREAD

**Issue by vsmelov** [hpcaitech/ColossalAI#5671]
### 🐛 Describe the bug

When I try to follow the link on GitHub to join Slack it shows that the link is expired
![image](https://github.com/hpcaitech/ColossalAI/assets/9407507/44f3c664-771f-4241-8867-5ab9bb6d3127)

### Environment

Used link - https://join.slack.com/t/colossalaiworkspace/shared_invite/zt-z7b26eeb-CBp7jouvu~r0~lcFzX832w

**Comment by binmakeswell** [comment]
Hi @vsmelov 
I'm not sure where you got the above link.
The correct link is
https://join.slack.com/t/colossalaiworkspace/shared_invite/zt-2404o93sy-Y3~br1qkIeEcMOVSfJ8YYg
