### ISSUE TITLE
Adding Loki-Promtail configurations for log monitoring

### ISSUE THREAD

**Issue by SMesForoush** [hpcaitech/ColossalAI#587]
### Describe the feature

Loki is a horizontally scalable log aggregation system inspired by Prometheus. It can be easily connected to a cluster and scrape logs. This system can help monitor log files of the project using Grafana. 
With a README and docker-compose file, we can establish a simple guide for users to connect ColossalAI and Loki in Grafana.

**Comment by feifeibear** [comment]
Hello, @SMesForoush ,
Thanks for your suggestion. I am looking for your PR to the main branch.

**Comment by binmakeswell** [comment]
This issue was closed due to inactivity. Thanks.
