### ISSUE TITLE
[DOC]: Is there an example of Lora training for Llama3?

### ISSUE THREAD

**Issue by zhurunhua** [hpcaitech/ColossalAI#5964]
### 📚 The doc issue

 I couldn't find any Lora related parameters in the script：

<img width="1132" alt="image" src="https://github.com/user-attachments/assets/4885e331-5a50-445f-b23a-06819c41ece1">

**Comment by TongLi3701** [comment]
Hi, 

The project of Colossal-LLaMA is mainly designed for full parameter fine-tuning using Colossal-AI.

If you want to use lora, please have a look at ColossalChat: https://github.com/hpcaitech/ColossalAI/blob/main/applications/ColossalChat/examples/README.md#parameter-efficient-finetuning-peft 

where we have detailed implementation of using Lora.
