### ISSUE TITLE
[DOC]: Is there documentation on how to create hostfiles

### ISSUE THREAD

**Issue by zhenbuxianggaimingzi** [hpcaitech/ColossalAI#5965]
### 📚 The doc issue

According to the distributed training startup instructions on the documentation, 
```
colossalai run --nproc_per_node 4 --hostfile ./hostfile --master_addr host1  test.py
```
I need to create a hostfile file where each row is the parameter configuration for a node, 
```
host1
host2
```
but is there any documentation or example that explains what parameters are for each row and column of hostfile? I don't saw any instructions for that,  such as ip, port, gpu id, etc

**Comment by zhenbuxianggaimingzi** [comment]
thank you for your reply. what I also want to ask is how to write hosts.txt? for example, each line in hosts.txt contains the following information:
```
ip gpu_ids port
xx.xxx.xx.22 0,1,2,3 9999
xx.xxx.xx.23 0,1,2,3 8888
```
but I'm not sure what the canonical way is, it doesn't seem to be documented

**Comment by Edenzzzz** [comment]
You should only put in the IPs. I may update the docs when available, or you can submit a PR
