### ISSUE TITLE
[BUG]: Hang on startup

### ISSUE THREAD

**Issue by rob-hen** [hpcaitech/ColossalAI#5969]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### 🐛 Describe the bug

When  trying to train OpenSora1.2 via

`colossalai run --nproc_per_node 8 --hostfile hostfile scripts/train.py configs/opensora-v1-2/train/train_config.py`
it hangs at the startup:

`[2024-08-06 04:53:37] Beginning epoch 0...
Epoch 0:   0%|          | 0/1234 [00:00<?, ?it/s]`
By checking all nodes via `nvidia-smi`, all GPUs are at 100% load and x MB memory, execpt for one GPU, which is at  0% load and 0.95 x MB memory.

This has happend to me multiple times (each time another GPU is not prepared). Any idea how to solve this issue? 

When I start training, I get the message:

`Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. `

Not sure if that is relevant?

### Environment

CUDA 11.8
colossalai==0.4.0

**Comment by rob-hen** [comment]
Even more, when I close the colossalai call, it is not closing the jobs on the nodes. Some processes are frozen and cannot be killed by htop, resulting in a `soft lockup`  messages when calling `nvidia-smi`.

**Comment by Edenzzzz** [comment]
If you're using multi-node training, you might want to ensure that all nodes can ssh into one another using the same ssh port. See https://github.com/hpcaitech/ColossalAI/commit/9179d4088e378c437178432168dea9f32fbf739f

**Comment by Edenzzzz** [comment]
Feel free to reopen if it persists.

**Comment by rob-hen** [comment]
@Edenzzzz All setups seem to be fine. After x tries, at some point, it is able to load all GPUs and start the training.
