### ISSUE TITLE
2D transformer implementation of QKV

### ISSUE THREAD

**Issue by binmakeswell** [hpcaitech/ColossalAI#602]
### 🐛 Describe the bug

Currently, the QKV implementation in the 2D transformer is calculated on each GPU and obtains a local softmax, but the real transformer calculates the whole large matrix. The current scheme has better communication and scalability, and it's reasonable for image cases. However, for models such as MAE, since they follow the classical transformer, when using the current 2D, the results are not aligned.
In addition, the test code of this part is not being used.

**Comment by kurisusnowdeng** [comment]
The current implementation is supposed to be correct. Issue is already solved yesterday. I think you can close this issue if there is no other problem.

**Comment by fastalgo** [comment]
We thank friends from Ant Group for valuable discussions. @kurisusnowdeng did a very good job and friends from Ant Group are satisfied with the current implementation. @binmakeswell
