### ISSUE TITLE
[FEATURE]: Customize DDP arguments

### ISSUE THREAD

**Issue by ExtremeViscent** [hpcaitech/ColossalAI#670]
### Describe the feature

In the case when users need to specify DDP launching parameters (e.g.` find_unused_parameters`), keyword arguments should be passed to `torch.nn.parallel.DistributedDataParallel` at initialization.

**Comment by FrankLeeeee** [comment]
Thanks for the feedback, will add this soon.

**Comment by binmakeswell** [comment]
We have updated a lot. This issue was closed due to inactivity. Thanks.

**Comment by shyoulala** [comment]
If I use zero2, and there are some parameters that should not be trained, how should I set them?  If there are untrained parameters, you may encounter the following error: "AssertionError: fp32 param and grad have different shape".
