### ISSUE TITLE
[BUG]: Hybrid kernel went wrong when there were both fp16  and fp32 gradients

### ISSUE THREAD

**Issue by 1SAA** [hpcaitech/ColossalAI#675]
### 🐛 Describe the bug

When model has both fp16 gradient and fp32 gradient, hybrid adam may unable to update parameters correctly.
Since we put all parameters to a list in colossalai/nn/optimizer/hybrid_adam.py. Here it is.
![image](https://user-images.githubusercontent.com/72907851/161894415-11517bbe-950c-4caa-9a42-90d0806e8959.png)
But in our CUDA kernel, writes like this.
![image](https://user-images.githubusercontent.com/72907851/161895082-35147eff-5e81-4d32-baa0-8d6600adb3cc.png)
We only check the dtype of the first element in the list. This may cause wrong dtype.

**Comment by binmakeswell** [comment]
We have updated a lot. This issue was closed due to inactivity. Thanks.
