### ISSUE TITLE
Facing error in using CNN on MNIST

### ISSUE THREAD

**Issue by Ambrish001** [hpcaitech/ColossalAI#68]
I was using colossalAI for applying CNN on the MNIST dataset but the following error occurs which I am not able to remove:

[Epoch 0 train]:   0%|          | 0/6000 [00:00<?, ?it/s]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-48-ffc43def4367> in <module>()
      6     max_epochs = num_epochs,
      7     display_progress = True,
----> 8     test_interval = test_interval
      9 )

4 frames
/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
   1100         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1101                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1102             return forward_call(*input, **kwargs)
   1103         # Do not call functions when jit is used
   1104         full_backward_hooks, non_full_backward_hooks = [], []

TypeError: forward() takes 2 positional arguments but 11 were given

I have attached the link to the jupyter notebook. 
[https://colab.research.google.com/drive/15Yiv7EBAc6eWV14aGEl0GP3-AMZLSr06?usp=sharing](url)

**Comment by FrankLeeeee** [comment]
Hi @Ambrish001 , we would like recommend you to git clone and pip install from source. As these are early versions, functionality can be a bit unstable but the main branch of the repository is always update to date. Indeed, we have updated the API to be more user-friendly. The documentation https://colossalai.org/ is also in line with the main branch. We provided an example of resnet on cifar10 in the examples folder, which is similar to your case. Perhaps you can take it a s a reference. Feel free to reach me if any issue persists. 😃

**Comment by Ambrish001** [comment]
When I used git clone and pip installed it from source, the following error arises :

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-4-91866cbfd0a7> in <module>()
----> 1 import colossalai
      2 from colossalai.engine import Engine, NoPipelineSchedule
      3 from colossalai.trainer import Trainer
      4 from colossalai.context import Config
      5 import torch

3 frames
/usr/local/lib/python3.7/dist-packages/colossalai/amp/apex_amp/__init__.py in <module>()
      2 import torch.nn as nn
      3 from torch.optim import Optimizer
----> 4 import apex.amp as apex_amp
      5 
      6 

ModuleNotFoundError: No module named 'apex'

**Comment by FrankLeeeee** [comment]
Hi Ambrish, you can solve this problem by installing apex

```shell
git clone https://github.com/NVIDIA/apex
cd apex
pip install -v --disable-pip-version-check --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./
```

but we will have another pull request to handle this error as apex can be an optional dependency for colossalai. Thanks for finding this!

**Comment by Ambrish001** [comment]
The problem is still not solved. A similar issue arises when I install apex

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-5-91866cbfd0a7> in <module>()
----> 1 import colossalai
      2 from colossalai.engine import Engine, NoPipelineSchedule
      3 from colossalai.trainer import Trainer
      4 from colossalai.context import Config
      5 import torch

3 frames
/usr/local/lib/python3.7/dist-packages/colossalai/amp/apex_amp/__init__.py in <module>()
      2 import torch.nn as nn
      3 from torch.optim import Optimizer
----> 4 import apex.amp as apex_amp
      5 
      6 

ModuleNotFoundError: No module named 'apex.amp'

---------------------------------------------------------------------------
Link - https://colab.research.google.com/drive/1n6RZGjkjoq408bu92D41v3QL7cF5HCNq?usp=sharing

Also, when I use !pip install ColossalAI deepspeed , then this error occurs at last step:

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-33-aaa8f3b2fd02> in <module>()
      6     max_epochs = num_epochs,
      7     display_progress = True,
----> 8     test_interval = test_interval
      9 )

6 frames
/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py in cross_entropy(input, target, weight, size_average, ignore_index, reduce, reduction, label_smoothing)
   2844     if size_average is not None or reduce is not None:
   2845         reduction = _Reduction.legacy_get_string(size_average, reduce)
-> 2846     return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
   2847 
   2848 

ValueError: Expected input batch_size (1) to match target batch_size (0).

**Comment by FrankLeeeee** [comment]
Hi, there is an error occurred when installing apex. Let me clone your notebook and reproduce the error.

**Comment by FrankLeeeee** [comment]
Hi @Ambrish001 , I have cloned your google colab and fixed some bugs for you. You can refer to our [documentation](https://colossalai.org/index.html) for the latest api and examples. Meanwhile, this colab is not using any advanced feature, but that's definitely fine. If you wish to explore more advanced tools, you can refer to [this page](https://colossalai.org/config.html) to specify some configuration. 

Colab shared at:
https://colab.research.google.com/drive/1Qbo_mBCHXgUMl2GKTYAWo73sHtV9uqlC?usp=sharing

The colab will expire in 1 day so do copy it to your own google drive.

Feel free to get back to me if you still encounter bugs or have any question. More than willing to help :)

**Comment by FrankLeeeee** [comment]
Hi, @Ambrish001 . Hope that you are able to run now. I will close this issue.
