### ISSUE TITLE
[FEATURE]: CPU/Hybrid Adafactor Supports

### ISSUE THREAD

**Issue by feifeibear** [hpcaitech/ColossalAI#697]
### Describe the feature

I suggest adding CPU/Hybrid Adafactor supports for heterogeneous training.

Adafactor has less memory consumption than Adam, proposed in paper
`Adafactor: Adaptive Learning Rates with Sublinear Memory Cost`.

https://github.com/huggingface/transformers/blob/v4.17.0/src/transformers/optimization.py#L385

https://github.com/pytorch/fairseq/blob/main/fairseq/optim/adafactor.py

**Comment by binmakeswell** [comment]
We have updated a lot. This issue was closed due to inactivity. Thanks.
