### ISSUE TITLE
[DOC]: Need a simple Colab sample to show CUDA and Torch versions

### ISSUE THREAD

**Issue by ver217** [hpcaitech/ColossalAI#713]
### 📚 The doc issue

Mentioned in #709 .  Colossal requires torch>=1.8, minimal version of CUDA for this torch version is cu111. Maybe we can add a simple Colab sample showcasing CUDA and Torch version. Meanwhile, a CUDA version check is also nice to have.

**Comment by binmakeswell** [comment]
Perhaps improvements are needed in the reqiuments and error message as well. 
Many features cannot be displayed in colab with one GPU, and ZeRO's compatibility with colab needs to be verified.

**Comment by binmakeswell** [comment]
We have updated a lot. Colab is not suitable for large-scale parallelism.
This issue was closed due to inactivity. Thanks.
