### ISSUE TITLE
[FEATURE]: Get how many process share a CPU.

### ISSUE THREAD

**Issue by feifeibear** [hpcaitech/ColossalAI#714]
### Describe the feature

Can I know how many processes share a CPU in ParallelContext?
In the context of multi-node, each node has 1 CPU-8 GPU. 
When using hybrid parallelism, how can I know in this case 8 processes are using 1 CPU?

**Comment by FrankLeeeee** [comment]
Can you define what "share a CPU" means?

**Comment by FrankLeeeee** [comment]
Do you mean CPU affinity?

**Comment by feifeibear** [comment]
I updated the questions.

**Comment by FrankLeeeee** [comment]
I see. Generally, this is obtained by `torch.cuda.device_count`. If we want to store the information in the parallel context (i.e. which ranks are using the same CPU on the same node), we can do this when initializing the global process group.

**Comment by feifeibear** [comment]
OK, I will use `torch.cuda.device_count`, that is enough.

**Comment by FrankLeeeee** [comment]
Not sure if you need to consider complicated cases, e.g. using SLURM. SLURM binds one process to one GPU so that device count will always return 1 even if you have 8 GPUs on one node.
