### ISSUE TITLE
[BUG]: The problem about CUDA extension 

### ISSUE THREAD

**Issue by LaoNaH** [hpcaitech/ColossalAI#774]
### 🐛 Describe the bug

When i pip the colossalai, no matter use the command 'pip install colossalai' or 'pip install colossalai --global_option="no_cuda_ext"', it's all tips "if you want to activate cuda mode for moe, please install with cuda_ext"

**Comment by FrankLeeeee** [comment]
Hi, can you run `pip install` with `-v` flag. The log will tell more about why cuda extension is not installed.

**Comment by FrankLeeeee** [comment]
Colossal-AI pre-built with CUDA extension is provided at https://www.colossalai.org/download now.
