### ISSUE TITLE
[FEATURE]: Parallel layernorm optimization

### ISSUE THREAD

**Issue by kurisusnowdeng** [hpcaitech/ColossalAI#782]
### Describe the feature

We can compute the variance as ![var](https://latex.codecogs.com/svg.image?E[x^2]-(E[x])^2). Thus, for tensor parallelism, we only need to communicate once to aggregate ![ex](https://latex.codecogs.com/svg.image?\sum[x]) and ![ex2](https://latex.codecogs.com/svg.image?\sum[x^2]) at the same time.

**Comment by feifeibear** [comment]
A similar method has been proposed in [TurboTransformer Paper](https://dl.acm.org/doi/10.1145/3437801.3441578) to reduce sync times in cuda programming...

**Comment by binmakeswell** [comment]
We have updated a lot. This issue was closed due to inactivity. Thanks.
