### ISSUE TITLE
[BUG]: Miscalculation of q, k, and v when applying TP with self-attention

### ISSUE THREAD

**Issue by MaruyamaAya** [hpcaitech/ColossalAI#817]
### 🐛 Describe the bug

In the Self-attention layer Colossal is using a fused (seq_length, 3*embedding size) matrix in Linear_Col as the weight for calculating q, k, and v. This works if we keep the same TP size during the whole training and inference process. But if we change the TP size, the weight will be cut in the wrong way by Linear_Col and can not be distributed correctly to the workers. The weight for q, k, and v should be cut separately instead of being cut as a whole.

**Comment by kurisusnowdeng** [comment]
We now support saving & loading checkpoint to shift between different parallelism configurations. Please try `colossalai.utils.save_checkpoint` and `colossalai.utils.load_checkpoint`. They should work even you reload a model with a completely different parallelism. We will also update a tutorial about this ASAP.

**Comment by FrankLeeeee** [comment]
@kurisusnowdeng ku, he means that the qky linear layer will have arithmetically incorrect matrix splitting when the TP size changes.

**Comment by kurisusnowdeng** [comment]
> @kurisusnowdeng ku, he means that the qky linear layer will have arithmetically incorrect matrix splitting when the TP size changes.

@MaruyamaAya Could you please present an example to show what would be wrong?
