### ISSUE TITLE
[BUG]: Acc decreases when training with PP and TP

### ISSUE THREAD

**Issue by Gy-Lu** [hpcaitech/ColossalAI#851]
### 🐛 Describe the bug

When I ran ViT with cifar-10, I found that if using a hybrid of PP and TP, the test ACC decreased with the process of training.
However, things went fine if using PP or TP alone.

+ non_interleaved PP and 1d TP
`CONFIG = dict(NUM_MICRO_BATCHES=2, parallel=dict(pipeline=2, tensor=dict(size=2, mode='1d')))`

<img width="1425" alt="image" src="https://user-images.githubusercontent.com/74758262/164965370-bd7e7724-0d2c-4b55-ac77-3b01ddbcc0e2.png">

+ interleaved PP(num_chunk=1) and 1d TP
```python
NUM_CHUNKS = 1
CONFIG = dict(NUM_MICRO_BATCHES=2, parallel=dict(pipeline=2, tensor=dict(size=2, mode='1d')), model=dict(num_chunks=NUM_CHUNKS))
```
<img width="1425" alt="image" src="https://user-images.githubusercontent.com/74758262/164965513-79787ce6-ba56-49d5-a6c6-a0447cb293ac.png">

+ interleaved PP(num_chunks=2) and 2d TP
```python
NUM_CHUNKS = 2
CONFIG = dict(NUM_MICRO_BATCHES=2, parallel=dict(pipeline=2, tensor=dict(size=2, mode='1d')), model=dict(num_chunks=NUM_CHUNKS))
```
<img width="1429" alt="image" src="https://user-images.githubusercontent.com/74758262/164965681-52e18220-2101-4cb1-a6e6-d586de3eaa34.png">

**Comment by Gy-Lu** [comment]
Oh, I found that this model was defined with `torch.nn`.
:x

**Comment by binmakeswell** [comment]
We have updated a lot. This issue was closed due to inactivity. Thanks.
