### ISSUE TITLE
Unable to import get_dataloader from colossalai.utils

### ISSUE THREAD

**Issue by rahulgupta9202** [hpcaitech/ColossalAI#89]
While making an example for application of colossalAI with the new API, I wanted to use the get_dataloader method to create a dataloader but after running the line
`from colossalai.utils import get_dataloader`
 and ran into the error:
ImportError: cannot import name 'get_dataloader' from 'colossalai.utils' (/usr/local/lib/python3.7/dist-packages/colossalai/utils/__init__.py)

**Comment by FrankLeeeee** [comment]
Hi @rahulgupta9202 , did you install from pypi?

**Comment by rahulgupta9202** [comment]
> 

Hi @FrankLeeeee 
yeah, I installed the colossalAI library using PyPI

**Comment by FrankLeeeee** [comment]
Sorry for the confusion. The PyPI library is not updated yet, we recommend installing from source as stated in our readme. We will update on pypi once we have a stable version.

**Comment by rahulgupta9202** [comment]
Alright, thanks!
