### ISSUE TITLE
[FEATURE]: Is there a plan to support OPT?

### ISSUE THREAD

**Issue by binmakeswell** [hpcaitech/ColossalAI#908]
### Describe the feature

Meta released a model called OPT, and OPT-175B is comparable to GPT-3, requiring 1/7 the carbon footprint to develop. 
For Colossal-AI, it seems necessary to support it and demonstrate unique superiority.

https://arxiv.org/abs/2205.01068
https://github.com/facebookresearch/metaseq/tree/main/projects/OPT

https://mp.weixin.qq.com/s/qaik2nZtmptLv-51M-dmag
https://mp.weixin.qq.com/s/zCgXWGUlkIQaGDE14wAATw

**Comment by 480284856** [comment]
+1

**Comment by tao-oO** [comment]
+1

**Comment by feifeibear** [comment]
OPT has been implemented in the Example Repo.
see it here @tao-oO @480284856 
https://github.com/hpcaitech/ColossalAI-Examples/blob/main/language/opt/README.md
