### ISSUE TITLE
[FEATURE]: set ComputePattern for op rather than parameter

### ISSUE THREAD

**Issue by ver217** [hpcaitech/ColossalAI#926]
### Describe the feature

We set spec on parameter now, which means each paramter has its own unchanged compute_pattern. However, some models, like GPT-2, share parameter among different layers. GPT-2 shares token embedding weight among embedding layer and classifier layer, and it calls `torch.nn.functional.embedding` in embedding layer and calls `torch.nn.functional.linear` in classifier layer. One parameter may have two different compute pattern during training. Therefore, we should set compute pattern for operations rather than parameters.

**Comment by binmakeswell** [comment]
We have updated a lot. This issue was closed due to inactivity. Thanks.
