### ISSUE TITLE
[DOC]: pip uninstallable

### ISSUE THREAD

**Issue by Loydian** [hpcaitech/ColossalAI#988]
### 📚 The doc issue

With the guide from https://www.colossalai.org/download, I used the following command to install ColossalAI
```
pip install colossalai==0.1.4+torch1.11cu11.3 -f https://release.colossalai.org
```
But I got
```
ERROR: Could not find a version that satisfies the requirement colossalai==0.1.4+torch1.11cu11.3 (from versions: 0.0.1b0, 0.0.2, 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.4)
ERROR: No matching distribution found for colossalai==0.1.4+torch1.11cu11.3
```
Is that mean I must download it from source?

**Comment by ver217** [comment]
Hi, could you tell me your Python's version? For colossalai==0.1.4+torch1.11cu11.3, we only support Python 3.7-3.10 now.

**Comment by Loydian** [comment]
I use Python3.8

**Comment by ver217** [comment]
Oh, maybe unstable network leads to this problem. Could you try it again or use a proxy?

**Comment by Loydian** [comment]
I use the following command to create it
```
conda create -n colossal python=3.8
```
Since it is a brand new environment, I don't think there is any corruption with other installations.

**Comment by Loydian** [comment]
I have already try it with/without proxy, and still get the same ERROR

**Comment by ver217** [comment]
OK, I'm trying to reproduce your problem using conda.

**Comment by ver217** [comment]
Hi, I can install using your command.

![image](https://user-images.githubusercontent.com/23111350/168718989-5bc03005-fd25-43c3-b089-9457585e6440.png)

**Comment by ver217** [comment]
Are you using Linux x86_64? We only support this arch now. Windows and MacOS versions are not provided currently.

**Comment by FrankLeeeee** [comment]
> Are you using Linux x86_64? We only support this arch now. Windows and MacOS versions are not provided currently.

For Windows, we recommend using WSL.

**Comment by Loydian** [comment]
Oh, I try to install it on my own PC for some simple experiments.
I have WSL installed on my computer, but I haven't used it for python before. I will give it a try. Thanks for your patience.
